### ISSUE TITLE
Adding additional bindings for widget.Input

### ISSUE THREAD

**Issue by JoshPaulie** [Textualize/textual#1001]
Opening up dialog to discuss possible `widget.Input` bindings. I'd be happy to implement them, and already have a few on my local fork

### Proposed action and accompanying shortcut
* Clear line ✅ 
	* Shift+Delete (up for debate)
* Backspace (Word at a time)
	* Ctrl+Backspace
* Delete forward (Word at a time)
	* Ctrl+Delete
* Move Cursor (Word at a time) ✅
	* Ctrl+Left
	* Ctrl+Right

Besides the clear line action, "these are universal shortcuts."

There's a discussion to be had here regarding what we consider _universal_ to be. Are we treating `widget.Input` like we might an html input box? If so, the proposed shortcuts would qualify.

**Comment by JoshPaulie** [comment]
While trying to implement ctrl+backspace, I noticed an interesting interaction with `widget.Input`
- Any unbound bindings (key combinations) have no effect on `Input`
    - For example, `ctrl+left` does nothing bc it doesn't have a binding action.
- This is not the case with backspace though. `ctrl+backspace` and `shift+backspace` are functionally the same as `backspace`

**Comment by davep** [comment]
(Just checking some older issues) [Many more actions and bindings were added to `Input`](https://github.com/Textualize/textual/pull/1676) in [0.11.0](https://github.com/Textualize/textual/blob/main/CHANGELOG.md#0110---2023-02-15).
