### ISSUE TITLE
When saving screenshot on Windows get an encoding error 

### ISSUE THREAD

**Issue by nzsmith1** [Textualize/textual#1003]
After working around https://github.com/Textualize/textual/issues/993 I have another issue saving screenshots on Windows.

**Error output**

`(textualplayground-tYbP6BcW-py3.8) PS C:\Users\nzsmi\repo\textualplayground> & C:/Users/nzsmi/AppData/Local/pypoetry/Cache/virtualenvs/textualplayground-tYbP6BcW-py3.8/Scripts/python.exe c:/Users/nzsmi/repo/textualplayground/main.py
╭───────────────────────────── Traceback (most recent call last) ──────────────────────────────╮
│ c:/Users/nzsmi/repo/textualplayground/main.py:114 in action_screenshot                       │
│                                                                                              │
│   111 │   │   │   path (str, optional): Path to directory. Defaults to "./".                 │
│   112 │   │   """                                                                            │
│   113 │   │   self.bell()                                                                    │
│ ❱ 114 │   │   path = self.save_screenshot(filename, path)                                    │
│   115 │   │   message = Text.assemble("Screenshot saved to ", (f"'{path}'", "bold green"))   │
│   116 │   │   self.add_note(message)                                                         │
│   117 │   │   self.screen.mount(Notification(message))                                       │
│                                                                                              │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮      │
│ │ filename = None                                                                     │      │
│ │     path = ''                                                                       │      │
│ │     self = HardwareTestingApp(title='Hardware Testing App', classes={'-dark-mode'}) │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯      │
│                                                                                              │
│ C:\Users\nzsmi\AppData\Local\pypoetry\Cache\virtualenvs\textualplayground-tYbP6BcW-py3.8\lib │
│ \site-packages\textual\app.py:545 in save_screenshot                                         │
│                                                                                              │
│    542 │   │   svg_path = os.path.expanduser(os.path.join(path, svg_filename))               │
│    543 │   │   screenshot_svg = self.export_screenshot()                                     │
│    544 │   │   with open(svg_path, "w") as svg_file:                                         │
│ ❱  545 │   │   │   svg_file.write(screenshot_svg)                                            │
│    546 │   │   return svg_path                                                               │
│    547 │                                                                                     │
│    548 │   def bind(                                                                         │
│                                                                                              │
│ ╭───────────────────────────────────────── locals ─────────────────────────────────────────╮ │
│ │       filename = None                                                                    │ │
│ │           path = ''                                                                      │ │
│ │ screenshot_svg = '<svg class="rich-terminal" viewBox="0 0 1190 513.5999999999999"        │ │
│ │                  xmlns="http://ww'+12556                                                 │ │
│ │           self = HardwareTestingApp(                                                     │ │
│ │                  │   title='Hardware Testing App',                                       │ │
│ │                  │   classes={'-dark-mode'}                                              │ │
│ │                  )                                                                       │ │
│ │       svg_file = <_io.TextIOWrapper name='hardware testing app 2022-10-24 14_28_00       │ │
│ │                  515524.svg' mode='w' encoding='cp1252'>                                 │ │
│ │   svg_filename = 'hardware testing app 2022-10-24 14_28_00 515524.svg'                   │ │
│ │       svg_path = 'hardware testing app 2022-10-24 14_28_00 515524.svg'                   │ │
│ │    time_format = '%Y-%m-%d %X %f'                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                              │
│ C:\Users\nzsmi\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py:19 in encode   │
│                                                                                              │
│    16                                                                                        │
│    17 class IncrementalEncoder(codecs.IncrementalEncoder):                                   │
│    18 │   def encode(self, input, final=False):                                              │
│ ❱  19 │   │   return codecs.charmap_encode(input,self.errors,encoding_table)[0]              │
│    20                                                                                        │
│    21 class IncrementalDecoder(codecs.IncrementalDecoder):                                   │
│    22 │   def decode(self, input, final=False):                                              │
│                                                                                              │
│ ╭───────────────────────────────────────── locals ─────────────────────────────────────────╮ │
│ │ final = False                                                                            │ │
│ │ input = '<svg class="rich-terminal" viewBox="0 0 1190 513.5999999999999"                 │ │
│ │         xmlns="http://ww'+12692                                                          │ │
│ │  self = <encodings.cp1252.IncrementalEncoder object at 0x0000023B0C3167C0>               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'charmap' codec can't encode character '\u2b58' in position 8637: character 
maps to <undefined>`

**Solution**
Issue was resolved by setting encoding='utf-8' on on ln 544 app.py

---         with open(svg_path, "w") as svg_file:
+++      with open(svg_path, "w", encoding="utf-8") as svg_file:

**Shell**
Powershell (in VSCODE)

**Windows 11**
Version	10.0.22000 Build 22000

**Python**
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32

**Packages**
commonmark         0.9.1  Python parser for the CommonMark Markdown spec
importlib-metadata 4.13.0 Read metadata from Python packages
nanoid             2.0.0  A tiny, secure, URL-friendly, unique string ID generator for Python   
pygments           2.13.0 Pygments is a syntax highlighting package written in Python.
rich               12.6.0 Render rich text, tables, progress bars, syntax highlighting, mar...  
textual            0.2.1  Modern Text User Interface framework
typing-extensions  4.4.0  Backported and Experimental Type Hints for Python 3.7+
zipp               3.10.0 Backport of pathlib-compatible object wrapper for zip files

**Comment by davep** [comment]
Just to update, this will be in the next release. Thanks again for reporting.
