### ISSUE TITLE
SSH TUI server à la charmbracelet/wish

### ISSUE THREAD

**Issue by lucasea777** [Textualize/textual#1006]
I am not sure if this proposal belongs here, but I think it could definitely promote textual adoption.

[charmbracelet/bubbletea](https://github.com/charmbracelet/bubbletea) is like textual but for the go language.
They also implemented [charmbracelet/wish](https://github.com/charmbracelet/wish) which allows bubbletea applications to work as ssh public servers, this allows anyone to access the app simply by typing `$ ssh ssh.chat` (for example) on the terminal.

Having something similar would be really cool, of course it would have to be implemented on a different repo...

**Comment by jacopofar** [comment]
Sounds like the use case of [containerSSH](https://containerssh.io/), it requires the app to be dockerized but not to use any specific language or library. I haven't tried it with Textual yet

**Comment by ricott1** [comment]
[Urwid](https://github.com/urwid/urwid) does something similar using Twisted: https://github.com/urwid/urwid/blob/master/examples/twisted_serve_ssh.py .

We could probably do something similar for textual.

**Comment by torshepherd** [comment]
Adding onto this, I was able to make a quick and dirty Textual ssh server using `asyncssh` by just copying https://asyncssh.readthedocs.io/en/latest/#id15 and using a textual demo app as the script to run, but this is all sorts of funky on my pc:

![image](https://user-images.githubusercontent.com/49597791/210447511-9bb22921-807e-4fcc-ae72-08e10109b331.png)

Seems like it prints out my mouse movements?

Simply running `ssh localhost` and then running a textual app works everything except for styling, so there is hope!

Normally:

![image](https://user-images.githubusercontent.com/49597791/210447859-4d4968a9-af25-4f55-b40a-06c60965e985.png)


Over ssh:

![image](https://user-images.githubusercontent.com/49597791/210447792-2624aad1-a9ac-48a5-918e-b5a9759d05c2.png)


Should also be noted that results were significantly worse on Alacritty than built-in Ubuntu terminal.

**Comment by torshepherd** [comment]
Alacritty same example:
![image](https://user-images.githubusercontent.com/49597791/210448051-5ceeb044-cf2c-441c-8d09-3bedba212184.png)

**Comment by torshepherd** [comment]
Update: This completely goes away if I just set

```bash
export COLORTERM=truecolor
```

!! Now to make `asyncssh` do this for me

**Comment by lucasea777** [comment]
> Update: This completely goes away if I just set
> 
> ```shell
> export COLORTERM=truecolor
> ```
> 
> !! Now to make `asyncssh` do this for me

Great! Do you know if you can run asyncssh with authentication disabled, i.e. so that anyone can access it without an key/certificate?

**Comment by torshepherd** [comment]
The simple server example is exactly that:

https://asyncssh.readthedocs.io/en/latest/#simple-server
