### ISSUE TITLE
CSS_PATH should accept a list

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1010]
CSS_PATH should accept a list of paths, which will cause the app to load all the css files.

This can allow for CSS libraries in addition to custom CSS.

We should also document the order in which rules are applied, in addition to the order that `CSS` and `CSS_PATH` are applied.

**Comment by davep** [comment]
(as boosted by you on Twitter...) Now we have a pressing reason to allow this: https://koaning.github.io/tuilwindcss/
