### ISSUE TITLE
Document design system

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1011]
We need docs in the guide for the design system.

Would also be a good time to review colors choices. I'm broadly happy with the current choices, but supect there is room for improvement. Find a UI designer to check.

**Comment by phiarchitect** [comment]
Do you have anything started on this?

**Comment by willmcgugan** [comment]
Not yet, however you can run the following command for a preview:

```
textual colors
```

**Comment by phiarchitect** [comment]
In addition to the colors, what topics have you considered for the Design Guide?

I see the potential for a CssZenGarden demonstration. One app, multiple style sheets - showing the real power of your platform.

**Comment by phiarchitect** [comment]
BTW - `textual colors` is beautiful on the screen.

**Comment by willmcgugan** [comment]
Thanks. CssZenGarden is a good idea.

I suspect we should document how to achieve certain common layouts with CSS. And how to tackle common issues.

**Comment by phiarchitect** [comment]
I am at the point right now, as I consider how to adopt Textual for my projects. 

I am recognizing that the design considerations need include to strategies for:

- component functionality and hierarchy
- interactivity and bindings
- layout and navigation
- thematic styling

The whole of it is a composition. Essentially a template for a use case.

Right now, I am considering how to compose the functionality and workflow from a vast array of bash scripts I have developed over the last few years into a new foundation based on Textual. I've been studying the new docs and examples all week. They are really well done. This project is an enlightenment for the command line.

**Comment by darrenburns** [comment]
This is now documented at https://textual.textualize.io/guide/design/
