### ISSUE TITLE
Question: Why my textual does not look as it is in examples ?

### ISSUE THREAD

**Issue by RRadziejewski** [Textualize/textual#1022]
Hello i'm impressed by project and really want to start doing some magic with it, however examples does not look so good for me.
It is kinda dark and it does not look good, any idea why ?

![8B9LM1hwxE](https://user-images.githubusercontent.com/32438378/197957748-5f8214fe-c53c-4b9b-95bd-abc06a4d792a.png)

**Comment by davep** [comment]
Could you give us a bit more information about your environment please? The operating system, what sort of environment you're running under, what terminal, etc.

**Comment by RRadziejewski** [comment]
OS: Debian 11 bullseye

No GUI connection over vmware workstation console.

**Comment by willmcgugan** [comment]
Looks like it is default to 16 colors.

Do you know what your TERM env var is set to?

If you can set it, try `TERM=xterm-256color` and `COLORTERM=truecolor`

**Comment by RRadziejewski** [comment]
TERM is set to **linux**, adjusting env variables to above mentioned does not help.

**Comment by willmcgugan** [comment]
Are you setting those env vars where the app is running?

I am unfamiliar with the vmware workstation console, but it may be it doesn't have support for extended color.

**Comment by RRadziejewski** [comment]
OFC i'm setting those there.

Well i will leave it like it is since i need it out of the box anyway.

Thank's for the attention
