### ISSUE TITLE
Add explicit Unmount event

### ISSUE THREAD

**Issue by Tinche** [Textualize/textual#1025]
Not sure if this is intended or not. I was handling app cleanup in my `App.on_remove` so I was surprised it was being triggered when a child screen gets popped off. I can provide a snippet if need be.

**Comment by willmcgugan** [comment]
The remove message is something different. It asks the App to remove something from the DOM. Should really be private.

We don't have a convenient place to clean things up. What we probably need is an `UnMount` event.

**Comment by Tinche** [comment]
I see, alright. Can close this or keep it open to track a place for cleanup, your choice. Thanks.

**Comment by willmcgugan** [comment]
We have an `UnMount` event now.
