### ISSUE TITLE
Button.watch_variant does not remove old_variant class

### ISSUE THREAD

**Issue by n-doerrer** [Textualize/textual#1048]
When changing the variant of a Button widget, the new variant gets added to the classes, but the old one is not removed.
Minimal example:
```python
from textual.app import App, ComposeResult
from textual.widgets import Button


class MyApp(App):
	def __init__(self):
		super().__init__()
		self.button = Button()
		self.button.variant = "warning"
		self.button.variant = "default"

	def compose(self) -> ComposeResult:
		yield self.button

MyApp().run()
```
This still displays the button in "warning" style as it has both classes.
I believe the problem is the underscore instead of a dash in the watch_variant method.
https://github.com/Textualize/textual/blob/main/src/textual/widgets/_button.py#L218

textual version 0.2.1
terminal: xterm-256color on linux ubuntu 22.04 (Regolith)

**Comment by davep** [comment]
Good catch. Slightly more interactive display of this, allowing watching the classes develop:

```python
from textual.app import App, ComposeResult
from textual.widgets import Button, Static


class MyApp( App[None] ):

    def compose( self ) -> ComposeResult:
        yield Button( "Push Me" )
        yield Static( "Push the above!", id="classes" )

    def on_button_pressed( self, event: Button.Pressed ) -> None:
        event.button.variant = (
            "warning" if event.button.variant == "default" else "default"
        )
        self.query_one( "#classes", Static ).update(
            ", ".join( event.button.classes )
        )

if __name__ == "__main__":
    MyApp().run()
```

**Comment by davep** [comment]
Now fixed for the next release: https://github.com/Textualize/textual/pull/1051

Thanks @n-doerrer!
