### ISSUE TITLE
SCREENS should contain types or callables

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1054]
The SCREENS class var contains a mapping of Screen instances.

Rather than Screen instances, SCREENS should contain Screen types or callables that return a new screen.

**Comment by tsingwang** [comment]
@willmcgugan Hello, I used Screen instance in SCREENS utill 0.70.0 version, but it encounter this error after upgrade to latest version.

But how do you reuse the Screen class? Can you see my comment about this usecase https://github.com/Textualize/textual/discussions/4480#discussioncomment-11420598
