### ISSUE TITLE
Arguments are not working with 'textual run'

### ISSUE THREAD

**Issue by jspv** [Textualize/textual#1064]
Per `textual run --help`:
```
  If you are running a file and want to pass command line arguments, wrap the
  filename and arguments in quotes:

      textual run "foo.py arg --option"
```

This is not working.   Using the following sample.py:

```
from textual.app import App, ComposeResult
from textual.widgets import Static
from sys import argv

class MyApp(App):
    def __init__(self, greeting: str="default") -> None:
        self.greeting = greeting
        super().__init__()

    def compose(self) -> ComposeResult:
        yield Static(f"{self.greeting}")

if __name__ == "__main__":
    if len(argv) > 1:
        app = MyApp(argv[1])
    else:
        app = MyApp()
    app.run()
```

When run via:
`python ./sample.py foo`
it returns a textual window with `foo`

When run via:
`textual run "./sample.py foo"`
it returns a textual window with `default`

**Comment by davep** [comment]
The issue here is the bit of code towards the end:

```python
if __name__ == "__main__":
    if len(argv) > 1:
        app = MyApp(argv[1])
    else:
        app = MyApp()
    app.run()
```

The `textual run` command isn't running that code. When presented with your code, `textual run`, not seeing a variable called `app` at the top level (which is fine), goes looking for a class in your module that inherits from `App`; it then creates an instance of that and `.run()`s it.

However, even if you were to do that, I suspect it won't have the effect you're hoping for. As you may imagine, if you're going to `textual run` your application `argv` will end up looking quite different; at the moment anyway. I'm going to dig into this a little more and see if there might be a better way of doing things.

But there is a different approach you can take. Rather than using `textual run` to run your app, you can run it just as normal, with `python`, but have `TEXTUAL=devtools` in your environment. That gives all the benefits of a `textual run` without needing to use `textual run`.

So, for example, in one terminal you can do:

```sh
$ textual console
```

to get the developer console up and running, and then in another do something like (depending on shell):

```sh
$ export TEXTUAL=devtools python ./sample.py. foo
```

and everything should work as you were hoping.

Let me know how you get on and if this solves the issue for you.

**Comment by willmcgugan** [comment]
There's a fix for this in master.

**Comment by davep** [comment]
@jspv Yup, as Will mentions, about 90 minutes before you mentioned it, we did https://github.com/Textualize/textual/pull/1070 which should address this. :-)

**Comment by jspv** [comment]
Thanks for the quick response.  This is still not solving my concern on what is the right way to get arguments in to the app from `textual run`.  From issue [1030](https://github.com/Textualize/textual/issues/1030), it looked like it was better to pass arguments in was via `__init__`, but this clearly breaks `textual run` which only passes them via sys.argv and will break the `__init__` call unless logic is added for that particular situation.  

What I would expect would be for both `python ./sample.py foobar` and `textual run "./sample.py foobar"` to have the exact same result.  For me to get this, I need to use logic like below which has to evaluate both methods which seems overly complex.   Would it be better that when `textual run` is called using the explicit python script like `textual run "./filename.py argument"` to have runpy.run_path execute __main__ just like python does instead of searching for the object?

```
from textual.app import App, ComposeResult
from textual.widgets import Static
from sys import argv

class MyApp(App):
    def __init__(self, args=None) -> None:
        if args is None:
            if argv is not None:
                self.args = argv
            else:
                self.args = "nothing passed"
        else:
            self.args = args
        super().__init__()

    def compose(self) -> ComposeResult:
        yield Static(f"{self.args}")

if __name__ == "__main__":
    MyApp(argv).run()
```

**Comment by jspv** [comment]
Thanks, I truly appreciate the discussion.  It would be **really good** to add TEXTUAL=devtools to the documentation, I agree that is probably the best way to debug if the code has any logic outside of the App instance.

I think the other thing that I found confusing is the output of `textual run --help` which implies strongly (at least to me) that `textual run` will pass the arguments via command line to foo.py **file** itself. 

```  
If you are running a file and want to pass command line arguments, wrap the filename and arguments in quotes:

      textual run "foo.py arg --option"
```
_"If you are running a file and want to pass command line arguments"_ - I think could be easily interpreted that it would call the code the same way as it does when running the file from the command line (e.g. the fairly typical model when running a file that execution starts with __main__).   Perhaps being explicit that ``textual run`` will only run the app instance and not any surrounding code and that any command line arguments will be available to the app instance via sys.argv" in the help would be clearer.  (or maybe I'm just a bit dense :-)

Again, the TEXTUAL=devtools does seem to be the most flexible, any reason to not do this all the time?  Is there any particular benefit from running textual console?

**Comment by davep** [comment]
I would imagine that most people will find out about `textual run` from the docs, [where it does give details on how the app is run](https://textual.textualize.io/guide/devtools/#run) -- but I take your point that perhaps the help output might give the wrong impression. I suspect there may be some assumption going on in the docs too that folk will appreciate the implications of having the conventional `__main__` guard in there.

I'll make a note about ensuring that the environment variable gets clearly mention in the docs.

**Comment by babucarr32** [comment]
Make sure to install dev tools
`pip install textual-dev`
See: https://textual.textualize.io/getting_started/#installation
