### ISSUE TITLE
textual[dev] Click dependcy is pinned to version 8.1.2 which breaks other CLIs

### ISSUE THREAD

**Issue by RhetTbull** [Textualize/textual#1065]
textual[dev] dependencies are pinned to a specific version of Click (8.1.2): `click = {version = "8.1.2", optional = true}`.  If there's not some specific reason the textual CLI  won't work with newer versions of Click, it would be better to use a caret requirement: `click = {version = "^8.1.2", optional = true}`

https://github.com/Textualize/textual/blob/39dced58e0e1d701056c23f65a540a9e1cf291b5/pyproject.toml#L35-L37

Rationale:  the developers using textual to create TUIs are almost certainly also using CLI frameworks like Click.  Requiring a very specific version of Click will likely break dependencies for existing CLIs trying to adopt a Textual TUI because developers will likely install the textual dev tools alongside their projects.  That's what happened to me as can be seen in the screenshot below:

<img width="842" alt="Screen Shot 2022-10-30 at 6 22 45 PM" src="https://user-images.githubusercontent.com/41546558/198916809-c22db8d2-0ece-4d29-a51c-16487b588d1e.png">

By the way, I *love* the developer support in textual 0.2.1.  The console and `textual run --dev` features are wonderful.  But they'd be much more useful if they were more permissive with the dependencies.

**Comment by willmcgugan** [comment]
We can definitely relax the dev requirements.
