### ISSUE TITLE
Implement a Textual snapshot testing framework

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1073]
We have the `run_test` context manager which can automate a Textual app. And we have snapshots, but the two systems don't yet work well together.

I think we can combine the two for a very powerful way of testing apps. Something along these lines.

```python
async with app.run_test() as pilot:
    await pilot.press("f", "o", "o")
    assert pilot.snapshot("after text input")
```

After discussion with @darrenburns it looks like we should build our own pytest plugin.

This should be available to use, and also third-party app developers.

**Comment by willmcgugan** [comment]
Note: I think we need the input queue in before this. Otherwise we have to insert arbitrary pauses.

**Comment by darrenburns** [comment]
Putting some thoughts down...

```python
# Plugin code
@pytest_asyncio.fixture
async def pilot():
    async with app.run_test() as pilot:
        yield pilot

# User code
async def test_example(pilot):
    await pilot.press(*"foo")
    assert pilot.snapshot()  # Optionally pass an ID, otherwise snapshot is associate with test?
```

**Comment by rodrigogiraoserrao** [comment]
Is this issue closable? The snapshot testing framework already exists but we do need arbitrary pauses in some places.

**Comment by willmcgugan** [comment]
I'm not certain. We can issue keys, but I'm not sure if we can issue keys, and take multiple snapshots for a single test. @darrenburns  ?

**Comment by willmcgugan** [comment]
Closing for now. Still the possibility of extending the snapshot tests, which are already objectively awesome.
