### ISSUE TITLE
width: auto seems to be calculated incorrectly sometimes - is it being measured before markup is rendered?

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#1091]
This red background widget has width: auto, and visually it appears 24 characters wider than it should be.

The widget contains 3 opening `[dim]` (15 chars total) and 3 closing markup tags `[/]` (9 chars total).

24 markup characters used in total, 24 characters wider than expected.

![Image](https://user-images.githubusercontent.com/5740731/199356700-779d49c8-032b-4b42-bf4b-26ba54eb9280.png)

If a return a `Text` object via `Text.from_markup` from my widget's `render` method (instead of a str), the width is as expected.

**Comment by willmcgugan** [comment]
@darrenburns Does your width auto PR address this?

**Comment by darrenburns** [comment]
I don't know, will check it soon

**Comment by willmcgugan** [comment]
There have been additional changes to the auto widget calculation since this issue. @darrenburns pretty sure this is solved, but would you mind confirming then closing the issue?

**Comment by darrenburns** [comment]
Confirmed fixed.
