### ISSUE TITLE
Drop-down menu widget assistance proposal

### ISSUE THREAD

**Issue by UriyaHarpeness** [Textualize/textual#1092]
Hello there! I see in the roadmap under "Widgets" - "Drop-down menus".

I would like to try and contribute by attempting to create this widget, is the image below similar to what you had in mind?
For the initial implementation at least I would do it without key bindings.

Please let me know if this might help and be added formally to textual.

CC: @shacham6.

![image](https://user-images.githubusercontent.com/53301931/199448508-d77f7035-e635-4247-9aa9-e255355b6e01.png)

**Comment by davep** [comment]
Hey @UriyaHarpeness -- I can see this being a popular widget library with quite a few people. If you build it as an add-on library for Textual that would be helpful in a few ways; it'd benefit folk who want to make use of it, it would help test out how easy it is for people to build additions *for* Textual rather than *within* Textual, and it helps to encourage the building of a widget ecosystem for the library.

**Comment by UriyaHarpeness** [comment]
I believe this indeed can be implemented outside of textual, but this has some downsides.
First, it is written in textual's roadmap, probably because it could be useful in common situation. Developing it outside means it's not "standard". Also, what differs between widgets that should sit in textual and outside?
Secondly, if trxtual is still subject to change and it is not inside it, this widget _might_ break, although not very likely.

@devap

**Comment by Pagajo** [comment]
@davep I think what @UriyaHarpeness means is that `Drop-down menus` is already listed among the [planned widgets in the roadmap](https://textual.textualize.io/roadmap/#widgets). Maybe I'm wrong in assuming this, but I inferred that the widget is planned to appear in the core, `textual` package.

**Comment by davep** [comment]
Aye, agreed, it is on the roadmap. But at the moment, at this very early stage in Textual's development, it would be super-useful if big handy widgets like this start out as suggested above; it's going to be extremely helpful in seeing how accommodating Textual is at having "third party" widgets developed around it. That's not to say that such widgets won't end up being "first party" of course, but doing it this way will really help us.

@Pagajo Yup, 100% how I read that too.
