### ISSUE TITLE
Add a method of getting a single widget by its ID alone

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1105]
While things like `query_one`, `first`, `last` and `only_one` exist as ways of getting a single node from the DOM, there can be a performance hit when there are a lot of widgets in the DOM. The most likely time this will be noticed is when you wan to pull a single widget out of the DOM via its ID.

Look at adding some form of `widget_by_id` method, which uses the ID alone to quickly index into the DOM.

**Comment by willmcgugan** [comment]
`get_widget_by_id` is a good idea.

We will also need to maintain an index of IDs for fast access.
