### ISSUE TITLE
[BUG] Odd animation behaviors (multiple) 

### ISSUE THREAD

**Issue by epi052** [Textualize/textual#1117]
> Please give a brief but clear explanation of what the issue is. Let us know what the behaviour you expect is, and what is actually happening. Let us know what operating system you are running on, and what terminal you are using.

I've been working on getting animated docks working and have run into a few things:
1. enhancement: it would be nice to have control over x/y planes when using `transition: offset ...`, i.e. `transition: offset|offset-x|offset-y`
    as shown below, when i use both an x/y offset to animate the bottom bar rising up, it appears to come in from the lower left hand corner. It would be nicer looking if it were only rising straight up at the correct x offset / size
2. also shown below, the first animation often doesn't animate, this happens with inline CSS as well as a css file. It also appears to be per-animation; i.e. the sidebar fails, then works, then the bottom bar fails, then works.
3. enhancement: when using a grid and a dock, the grid components all update their size, and that's awesome. However, what I'd like is to animate that the same way that the docks are animated. The goal would be that all the panes move smoothly together to their new configuration.
4. i needed to manually adjust width of the bottom bar when adjusting the offset; and had to adjust the offset to something that wasn't intuitive. 
    when the sidebar width is `33%` what looks i needed to do `offset-x: 47%;  width: 68%;` when, naively, i would think the x-offset would remain 33%. 

I understand this is a lot for one ticket, but it's all in the same family, and some of it may just be me :grin: 

> Feel free to add screenshots and/or videos. These can be very helpful!

first animation isn't animated
https://user-images.githubusercontent.com/43392618/200075228-33bf9c1a-9539-4f83-9665-628a85ecd72a.mp4

bottom bar coming in from the left and bottom
https://user-images.githubusercontent.com/43392618/200075288-dba77a71-66fb-4d44-8d63-26f4b8f51646.mp4

> If you can, include a complete working example that demonstrates the bug. Please check it can run without modifications.

```python
class Demo(App):
    TITLE = "Demonstration"
    BINDINGS = [
        ("s", "toggle_sidebar", "Sidebar"),
        ("b", "toggle_bottombar", "Bottombar"),
    ]
    CSS = """
    Screen {
        layout: grid;
        grid-size: 2 5;
    }

    .box {
        height: 100%;
        border: round white;
    }

    #left-main {
        row-span: 5;
    }
    
    #right-main {
        row-span: 5;
    }

    #sidebar {
        display: none;
        offset-x: -100%;
    }

    Demo.-show-sidebar #sidebar {
        display: block;
        dock: left;

        border: round yellow;

        height: 100%;
        max-width: 33%;
        margin-bottom: 1;

        transition: offset 500ms in_out_cubic;
        offset-x: 0;
    }

    #bottombar {
        display: none;
        offset-y: 100%;
    }

    Demo.-show-bottombar #bottombar {
        display: block;
        dock: bottom;

        border: round red;

        max-height: 33%;
        width: 100%;
        margin-bottom: 1;

        transition: offset 500ms in_out_cubic;
        offset-y: 0;
    }

    Demo.-show-sidebar.-show-bottombar #bottombar {
        offset-x: 47%;
        width: 68%;
    }

    """

    def compose(self) -> ComposeResult:
        # yield Header()
        yield Static(classes="box", id="left-main")
        yield Static(classes="box", id="right-main")
        yield Static(classes="box", id="sidebar")
        yield Static(classes="box", id="bottombar")
        yield Footer()

    def action_toggle_sidebar(self) -> None:
        if "-show-sidebar" in self.classes:
            self.remove_class("-show-sidebar")
        else:
            self.add_class("-show-sidebar")

    def action_toggle_bottombar(self) -> None:
        if "-show-bottombar" in self.classes:
            self.remove_class("-show-bottombar")
        else:
            self.add_class("-show-bottombar")


if __name__ == "__main__":
    Demo().run()
```

**Comment by willmcgugan** [comment]
Sorry, there's too much to parse in this issue. Would you mind breaking down in to individual issues.  On problem-per issue.

Be sure to include what your expectations are and what is actually happening. Videos are great.
