### ISSUE TITLE
After stopping a debugged app in VS Code it writes the coordinates of the mouse to the terminal

### ISSUE THREAD

**Issue by tonybaloney** [Textualize/textual#1171]
I had to record this one because it would be very hard to describe.

![screenshot 2022-11-14 at 14 17 58](https://user-images.githubusercontent.com/1532417/201568008-36b97858-3105-48a6-b81d-2d78c8c4a42c.gif)

I've made a basic app and started it in VS Code under the integrated terminal. It renders nicely. I stopped the app by clicking the 'stop' button in VS Code (instead of exiting the app nicely) and afterward anytime I move the mouse inside the VS Code terminal window it's writing the coordinates to the shell prompt!

**Comment by willmcgugan** [comment]
When you kill the processes, Textual doesn't have the opportunity to reset mouse input. Your only option is to type "reset" at the prompt.

Don't think there is much else we can do about that I'm afraid.

**Comment by tonybaloney** [comment]
Is there anything VS Code can do?

**Comment by willmcgugan** [comment]
Maybe. The debugger could write the escape codes to restore the terminal. No harm in doing that, and it would be transparent for the user.

**Comment by tonybaloney** [comment]
Related: https://github.com/microsoft/vscode-python/issues/20227
