### ISSUE TITLE
Changing data table cell values only displays new values on hover

### ISSUE THREAD

**Issue by tonybaloney** [Textualize/textual#1172]
I'm trying to add some behaviours to a DataTable that highlight related rows based on some custom logic. If you do something like stylise the text of a cell and call `.refresh_cell` it changes the value, but it only appears in the new style if you hover a mouse over it.

Here's a reproducible sample:

```python
from textual.app import App, ComposeResult 
from textual.widgets import Header, Footer, DataTable

from rich.text import Text

class InstructionView(DataTable):

    def watch_cursor_cell(self, old, value) -> None:
        if old:
            self.data[old.row][0] = Text(self.data[old.row][0].plain)
            self.refresh_cell(old.row, 0)
        self.data[value.row][0].stylize("bold magenta")
        self.refresh_cell(value.row, 0)
        # works when you uncomment this
        # self._clear_caches()
        return super().watch_cursor_cell(old, value)


class DissyApp(App):
    """An interactive TUI disassembler."""

    BINDINGS = [("q", "quit", "Quit")]
    TITLE = "Dissy"

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield InstructionView()
        yield Footer()

    def on_mount(self):
        table = self.query_one(InstructionView)
        table.show_header = False
        table.add_columns("Name", "Age")
        for name, age in [("Alice", 23), ("Bob", 32), ("Charlie", 28)]:
            table.add_row(Text(name), Text(str(age)))


if __name__ == "__main__":
    """Run the app."""
    DissyApp().run()
```

![screenshot 2022-11-14 at 16 30 54](https://user-images.githubusercontent.com/1532417/201583350-c2c97cfa-b4a4-46a2-b484-a20d10f63973.gif)

I found a workaround fix to call a private method to clear the caches, but it doesn't seem super efficient to have to do that.

![screenshot 2022-11-14 at 16 30 21](https://user-images.githubusercontent.com/1532417/201583384-2a3f88fa-2cda-4c9d-9c4c-eb819f4c2efa.gif)

**Comment by mrossinek** [comment]
I also just noticed this. Looking at the source code of the `DataTable` widget it would be interesting, too:
1. allow adding to a specific cell's style like it is done for example [here](https://github.com/Textualize/textual/blob/87329b6d077e27e644f43847b68052c03206b6eb/src/textual/widgets/_data_table.py#L465-L468)
2. enable cache resetting for a specific cell based on the [cache key](https://github.com/Textualize/textual/blob/87329b6d077e27e644f43847b68052c03206b6eb/src/textual/widgets/_data_table.py#L469)

This would provide a more efficient solution than clearing the entire cell cache as done by the OP.

The reason I am suggesting a public way of stylizing a cell directly would potentially allow the streamlining of the cache reset/screen update as part of the stylizing method

**Comment by TomJGooding** [comment]
Spotted this old issue was still open while looking for something else - I think this can probably now be closed given the changes since to the DataTable which includes methods to update cells?

**Comment by davep** [comment]
As Tom says above (some time back, only just noticed this), I'm pretty sure this is fixed now. Closing.
