### ISSUE TITLE
An exception when composing a child widget seems to stop the app but not error out

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1177]
Just noting this one here so I don't forget, as I noticed it while looking into something else and I want to come back and check what this is about (or anyone else can dive in, of course).

Given this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Static
from textual.containers import Container

class Question( Container ):

    def __init__( self, error_out: bool ) -> None:
        self.error_out = error_out
        super().__init__()

    def compose( self ) -> ComposeResult:
        wut = 1 / int( not self.error_out )
        yield Static( f"How did I get here? ({wut})" )

class Crashy( App ):

    def compose( self ) -> ComposeResult:
        yield Question( False )
        yield Question( True )

Crashy().run()
```

The app doesn't complete rendering, but at the same time it doesn't stop and indicate an error. The error is shown once the app is <kbd>Ctrl</kbd>+<kbd>C</kbd>d out.

**Comment by darrenburns** [comment]
This should be fixed by https://github.com/Textualize/textual/pull/1505
