### ISSUE TITLE
Button variant="disabled" gives type hinting error

### ISSUE THREAD

**Issue by learnbyexample** [Textualize/textual#1188]
Here's a sample program to reproduce the issue:

```python
from textual.app import App, ComposeResult
from textual.widgets import Button

class MinimalApp(App):

    def compose(self) -> ComposeResult:
        yield Button(variant="disabled")

if __name__ == "__main__":
    app = MinimalApp()
    app.run()
```

Here's the error I get:

```bash
$ mypy minimal.py 
minimal.py:7: error: Argument "variant" to "Button" has incompatible type "Literal['disabled']"; expected "Literal['default', 'primary', 'success', 'warning', 'error']"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

Looking through https://github.com/Textualize/textual/blob/main/src/textual/widgets/_button.py, seems like the `disabled` variant is missing here:

```python
ButtonVariant = Literal["default", "primary", "success", "warning", "error"]
_VALID_BUTTON_VARIANTS = {"default", "primary", "success", "warning", "error"}
```

**Comment by davep** [comment]
I'll check when i get to my desk, but I believe this is correct. Disabled isn't a variant, it's a property. For example, a "success" variant button can be enabled or disabled.

**Comment by learnbyexample** [comment]
Oh ok. I checked https://textual.textualize.io/widgets/button/ again, and seems like I wrongly assumed `disabled` was one of the variants.

Can you explain why the below code works even when I'm mistakenly using `variant="disabled"`?

```python
    def compose(self) -> ComposeResult:
        yield Button(variant="disabled")
        yield Button()
```

![image](https://user-images.githubusercontent.com/17766317/202119924-e07d3972-2dc1-44f2-9dc6-50e4c4162a21.png)

**Comment by davep** [comment]
You should be able to see why with this -- click on the active buttons to show the classes:

```disabled
from textual.app import App, ComposeResult
from textual.widgets import Button, Static

class ButtonApp( App[ None ] ):

    CSS = """
    Screen {
        align: center middle;
    }
    Static {
        width: auto;
    }
    """

    def compose(self) -> ComposeResult:
        yield Button( "This is a success button", variant="success" )
        yield Button( "This is a disabled success button", variant="success", disabled=True )
        yield Button( "This is a 'vanilla' button" )
        yield Button( "This is a invalid variant button", variant="launch" )
        yield Button( "This is a button with variant set to disabled", variant="disabled" )
        yield Static( id="css" )

    def on_button_pressed( self, event: Button.Pressed ) -> None:
        self.query_one( "#css", Static ).update( str( event.button.classes ) )

if __name__ == "__main__":
    ButtonApp().run()
```

From what I can tell (I'll double-check with Will when he gets in regarding intent), a variant adds a class prefixed with a `-`, no matter what you set the variant to. On top of that, styling a disabled button is done with the internal `-disabled` class. So by setting the variant to disabled, ignoring the type warning you saw, means you've accidentally applied the disabled style. You can see this in the code I post here because, despite the last button looking disabled, you can click on it. On the other hand you can't click on the second button because it is really disabled.

Or, put another way I guess; the type warning warned you bad things might happen and they happened. ;-)

**Comment by davep** [comment]
Side note: as you'll see in #1189 there seems to be code in `Button` to validate the variant, but it's never actually used. I suspect the real issue here is that variant validity is only done in type-checking right now and isn't done at runtiume.

**Comment by learnbyexample** [comment]
Thanks for the explanation and the sample code (in which I also learned that CSS can be assigned in the code itself).

I'll close this issue as my code now correctly uses `disabled=True`, thanks :)

**Comment by davep** [comment]
Just to update: as from the next release this will raise an exception at runtime.
