### ISSUE TITLE
Add a selector to focus_next and focus_previous

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1196]
`focus_next` and `focus_previous` should take a selector, so the focus moves to the next widget that matches the supplied selector.

**Comment by rodrigogiraoserrao** [comment]
Is the idea here that the selector be optional (or something like `"*"` by default) which is used to query the DOM to determine what the next/previous element to focus is?

**Comment by willmcgugan** [comment]
Yeah
