### ISSUE TITLE
Build a "Placeholder" widget

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1200]
We had a Placeholder widget which could be used to design a layout before you built a full widget. This use an older API.

We should refresh the placeholder idea, make it look nicer that the previous iteration, and add some features

- Pick harmonious alternating colors, by mixing brackground with ~30% from [this palette](https://iamkate.com/data/12-bit-rainbow/)
- Argument to select various modes: plain color, size and location, CSS, lorem ipsum text, etc
- Add click handler to cycle between modes

**Comment by rodrigogiraoserrao** [comment]
With the commit https://github.com/Textualize/textual/commit/83c8a9b55f4ad9a141f23ebe9b2348ba12b06d52 we have the scaffolding for the widget `Placeholder` which:

 - has 5 different variants that display different things; and
 - cycles through the different variants when you click the placeholder.

 1. The `"default"` variant shows a solid colour (from the palette linked) that was associated to the placeholder upon instantiation.
 2. The `"state"` variant shows whether the placeholder has focus (or not) and whether the mouse is over the placeholder or not.
 3. The `"size"` variant shows the size of the placeholder.
 4. The `"css"` variant shows the CSS of the placeholder.
 5. The `"text"` variant shows some Lorem Ipsum text.

**Comment by rodrigogiraoserrao** [comment]
Questions left unanswered:

 - Exactly _how_ should each variant be styled by default?
 - Should the background colour (from the palette linked) be customisable?
 - Should the placeholders scroll if the content is too large? (E.g., the css variant tends to have lots of content that won't fit small placeholders.)

**Comment by rodrigogiraoserrao** [comment]
After some discussion, the variants for state and CSS have been removed from consideration.
Thus, placeholders have 3 variants.
