### ISSUE TITLE
DataTable `clear` is missing

### ISSUE THREAD

**Issue by asyd** [Textualize/textual#1206]
[DataTable doc](https://textual.textualize.io/api/data_table/#textual.widgets._data_table.DataTable.clear) refers to a `clear()` method, but doesn't exists:

```
>>> from textual.widgets import DataTable
>>> test = DataTable()
>>> test.clear()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DataTable' object has no attribute 'clear'
>>> test.add_row('test')
```

**Comment by darrenburns** [comment]
The docs were updated a little prematurely - this'll be part of the next release (which I think will be this weekend, but @willmcgugan can confirm)

**Comment by rodrigogiraoserrao** [comment]
[0.5.0](https://github.com/Textualize/textual/releases/tag/v0.5.0) added the method `DataTable.clear` 😃
