### ISSUE TITLE
Add key lookup data structure

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#1208]
We have a few different mappings inside `keys.py` which map between keys/characters/unicode symbol names/aliases/key_display.

We need a data-structure that allows us to convert quickly between these different concepts.

We should formalise these concepts and try to come up with a naming system that makes sense - there's too many use-cases that require mapping between them at the moment, and it's difficult to follow.

**Comment by jayaddison** [comment]
This is potentially where I should have added some thoughts documented in #1323 (I didn't discover this issue until a few days after opening that one..).

**Comment by jayaddison** [comment]
May also relate to #1342.

**Comment by willmcgugan** [comment]
I think we have solved the various key issues with various mappings.

There likely is still room for a refactor, to abstract the various helper methods. That may happen, but closing this ticket for now.
