### ISSUE TITLE
Improve error message for textual run command with incorrect path to package.

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1217]
In some situations, the command `textual run package.path.to.app` returns a cryptic error when the `package.path.to.app` is not an actual package path.

 > Unable to find '' in <module 'package.path.to.app' from
'C:\\Users\\rodri\\Documents\\Textualize\\Textual\\package\\to\\app.py'>

To reproduce this issue, go to the root of the repro:

```shell
λ textual run docs.examples.widgets.button
Unable to find '' in <module 'docs.examples.widgets.button' from
'C:\\Users\\rodri\\Documents\\Textualize\\Textual\\docs\\examples\\widgets\\button.py'>

λ textual run docs.examples.widgets.button.ButtonApp
No module named 'docs.examples.widgets.button.ButtonApp'; 'docs.examples.widgets.button' is not a package
```

However, both commands will work if the file defines an `app`:

If you remove the typical guard `if __name__ == "__main__"` and change the end of the file to the code shown below, then both commands work.

```py
# if __name__ == "__main__":
app = ButtonsApp()
print(app.run())
```

However, the user probably meant to use the command `textual run` with a path file, e.g. with `textual run docs/examples/widgets/button.py` in this case.

**Comment by willmcgugan** [comment]
Now it says:

```
Unable to find 'app' in <module 'docs.examples.widgets.button' from '/Users/willmcgugan/projects/textual/docs/examples/widgets/button.py'>
```

Which is fairly clear, but at some point we will had some more detailed help in the errors.
