### ISSUE TITLE
Render button inside table rows

### ISSUE THREAD

**Issue by fraybabak** [Textualize/textual#1242]
To be added by @willmcgugan

**Comment by rodrigogiraoserrao** [comment]
Hey there!
Sorry for letting this issue unanswered for so long.

I'm guessing you wanted to suggest we allow adding `Button` instances to the `DataTable`?

_For now_, the `DataTable` widget only displays static content.
If you need to display some buttons in a tabular fashion, consider using the `Grid`[ layout](https://textual.textualize.io/guide/layout/#grid).
(If you need help, join us [in our Discord server](https://discord.gg/Enf6Z3qhVr).)

So, I'll close this issue for now but we might revisit this in the future!
Thanks for your suggestion.
