### ISSUE TITLE
App size is locked to the initial terminal window size

### ISSUE THREAD

**Issue by voxofox** [Textualize/textual#1245]
Instead of the App expanding to fill the width / height of the terminal emulator window, it remembers the _first_ time a terminal app (e.g. kitty, foot, terminator) runs Textual, and then uses those window dimension on each subsequent run.

![image](https://user-images.githubusercontent.com/92116921/203297698-3142aca5-04a4-46e0-9b0e-b7e251ecb36d.png)

The app also doesn't resize when the window is resized. 

The above shows `kitty` (left) with the same app running in `foot` (right), however, the left window is "stuck" to the dimensions I initially used for kitty. 

The same issue exists for a blank app with no CSS and only a Placeholder Widget:

![image](https://user-images.githubusercontent.com/92116921/203298848-a228c2f9-4672-4f37-98d1-206294ccf0f1.png)

based off of 

```python
class BlankApp(App):
    def compose(self) -> ComposeResult:
        yield Placeholder()

app = BlankApp()
````

I use `fish` but running it from `bash` has the same result.

Packages :
- `Python 3.10.7`
- `textual                  0.5.0     Modern Text User Interface framework`

System:

![image](https://user-images.githubusercontent.com/92116921/203298350-fc757412-86b7-4677-8f45-3ed24a9c8e64.png)

and in case it's useful, the devtool output on launching the above `BlankApp()` invoked with ` textual run --dev main.py`

![image](https://user-images.githubusercontent.com/92116921/203299174-97941eff-cd67-4df5-b335-3c318122bd54.png)

**Comment by darrenburns** [comment]
Your shell has `$COLUMNS` and `$LINES` variables which should get updated whenever you resize your terminal window. We've seen issues in the past where these variables weren't being updated for some reason (in my case, it wasn't being updated inside `poetry shell` on v1.2.0 of poetry).

If you run `echo $COLUMNS`, resize your terminal windows, then run `echo $COLUMNS` again, does the value printed change to reflect the new width of your terminal window? It's possible it's getting stuck.

**Comment by voxofox** [comment]
![image](https://user-images.githubusercontent.com/92116921/203303007-d5786bb1-76df-4595-8b2d-0aca569efacc.png)

You are right! Could reproduce that behaviour here on the same version of Poetry

![image](https://user-images.githubusercontent.com/92116921/203303106-2be8a371-f3a7-48b9-9e7f-95b5051d6721.png)

So the issue is with `poetry` and is [known](https://github.com/python-poetry/poetry/issues/6351). Apparently it's fixed in `1.2.1`... will test.

**Comment by darrenburns** [comment]
Great - I'm on `1.2.2` now and it works fine. Let me know how it goes :)

**Comment by voxofox** [comment]
Yessss :))) That did the trick! Thanks @darrenburns <3

For anyone else : a restart of the terminal is needed too.
