### ISSUE TITLE
Live console widget

### ISSUE THREAD

**Issue by hajdbo** [Textualize/textual#125]
It would be nice to have a widget that behaves like a console.
At first, just able to print and auto-scroll, and scroll bar, with auto-refresh.
```console.print("another brick in the wall")```

Maybe reuse Rich's Live View / Console?

**Comment by Tinche** [comment]
I am looking into this too. Could we emulate this with an autoscrolling ScrollView?

**Comment by presedo93** [comment]
Did you get any further in this topic? I have a pytorch-lightning script that prints to console and I would like to encapsulate that printing inside a Panel (or a live console widget) so that the prints of the module won't be in top of the interface when it starts

**Comment by ncwhale** [comment]
When I try to using rich.console inside textual, BOOM! everything broken.

**Comment by DanielATucker** [comment]
@willmcgugan Please implement this feature. I have an application that is heavily dependant on Rich, Rich Handlers, Rich Logging, Rich Console and now Textual (can you tell I like your work lol), and the last piece of the puzzle is getting Rich Console to work as a widget in Textual. I've been driving myself mad for days thinking the bug was in my code until I stumbled upon this thread. 
Please allow for a creation of a widget in Textual that can display a Rich Console utilizing the ScrollView or something similar.

**Comment by DanielATucker** [comment]
@yamatteo, That's not exactly what I'm looking for. I have an application that uses console.input() and Rich logging to simulate a bash screen. When I try to add an input to the code you wrote, my terminal just hangs indefinitely with no response. Maybe if we could integrate https://github.com/sirfuzzalot/textual-inputs then have it displayed using your console_outputs. 

If not, I understand, but could you look at my code and point me in the right direction of integration? https://github.com/DanielATucker/Brain. The main console logic is in Brain.py under def switchboard

**Comment by yamatteo** [comment]
@DanielATucker is it a REPL you want?
```
from rich.text import Text

from textual import events
from textual.app import App
from textual.widgets import Header, ScrollView
from rich.console import Console
from textual_inputs import TextInput

console = Console()


class OutConsole(ScrollView):
    prev = Text("")

    async def eval(self, text_input):
        pre_y = self.y
        with console.capture() as capture:
            try:
                console.print(eval(text_input))
            except Exception:
                console.print_exception(show_locals=True)
        self.prev.append(Text.from_ansi(capture.get() + "\n"))
        await self.update(self.prev)
        self.y = pre_y
        self.animate("y", self.window.virtual_size.height, duration=1, easing="linear")


class InConsole(TextInput):
    def __init__(self, out):
        super(InConsole, self).__init__()
        self.out = out

    async def on_key(self, event: events.Key) -> None:
        if event.key == "enter":
            await self.out.eval(self.value)
            self.value = ""


class GridTest(App):
    async def on_mount(self) -> None:
        output = OutConsole()
        in_put = InConsole(out=output)

        grid = await self.view.dock_grid(edge="left", name="left")
        grid.add_column(fraction=1, name="u")
        grid.add_row(fraction=1, name="top", min_size=3)
        grid.add_row(fraction=20, name="middle")
        grid.add_row(fraction=1, name="bottom", min_size=3)
        grid.add_areas(area1="u,top", area2="u,middle", area3="u,bottom")
        grid.place(area1=Header(), area2=output, area3=in_put, )


GridTest.run(title="Something like REPL")
```

**Comment by DanielATucker** [comment]
@yamatteo yes, your fix is exactly what I needed. Thanks for your help!

**Comment by DanielATucker** [comment]
@yamatteo How would add to the console from outside of the OutConsole. For example in the on_mount I am trying to add  console.print("Hello") after both the InConsole and Outconsole, but when I run the code it never shows up, anything else I try ends with a series or errors. I have been trying for days to figure out how to print to the console from other parts of my program, eg. error messages and status updates and such.

**Comment by yamatteo** [comment]
@DanielATucker You can do as follow:
```
class GridTest(App):
    async def on_mount(self) -> None:
        output = OutConsole()
        in_put = InConsole(out=output)

        # ... same as before ...

        # You can use output.eval to add console output
        await output.eval(repr("Hello World!"))

        # You can change the value of output directly
        await output.update(output.prev[:-2] + "?")
```
Maybe I should point out that this is not the clean way to do it in textual. I'm sure the developer is cooking some proper widget that will work in harmony with the rest of the framework. This is just a dirty hack.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue

**Comment by erezsh** [comment]
Request to re-open this issue!

**Comment by cyberalt1** [comment]
Please reopen, this is a major use case for most terminal apps

**Comment by brandon-fryslie** [comment]
How is this not a thing?  It's cool that I can write a calculator and have metrics dashboards and browse databases in my terminal but I can also do that with GUI apps.  Writing a REPL is pretty terminal specific so you'd hope it would be a first class citizen of a TUI app.  sure it's not going to translate to web, but who cares?
