### ISSUE TITLE
Improve error message when file monitor cannot find CSS file

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1262]
If an app points to a CSS file that does not exist and the file monitor tries to monitor it, we get an unpleasant `FileNotFoundError`.

For example, the app below raises the error that follows under:

```py
from textual.app import App

class MyApp(App):
    CSS_PATH = "inexistent_file.css"

MyApp(watch_css=True).run()
```

```
Traceback (most recent call last):
  File "C:\Users\rodri\Documents\Textualize\Textual\myapp.py", line 6, in <module>
    MyApp(watch_css=True).run()
  File "C:\Users\rodri\Documents\Textualize\Textual\src\textual\app.py", line 353, in __init__
    FileMonitor(self.css_path, self._on_css_change)
  File "C:\Users\rodri\Documents\Textualize\Textual\src\textual\file_monitor.py", line 19, in __init__
    self._modified = self._get_last_modified_time()
  File "C:\Users\rodri\Documents\Textualize\Textual\src\textual\file_monitor.py", line 23, in _get_last_modified_time
    return max(os.stat(path).st_mtime for path in self.paths)
  File "C:\Users\rodri\Documents\Textualize\Textual\src\textual\file_monitor.py", line 23, in <genexpr>
    return max(os.stat(path).st_mtime for path in self.paths)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\rodri\\Documents\\Textualize\\Textual\\inexisting_file.css'
```

The error says what is wrong, but the traceback is very big and I think we could do better.
For example, we could raise a `StylesheetError` saying that the given stylesheet was not found.

An alternative would be to wrap the assignment to `self.css_monitor`:

https://github.com/Textualize/textual/blob/10a3fb1d1b68a6ef3a32e1cc380295993d01cd23/src/textual/app.py#L351-L355

With a `try: ... except: ...` block:

```py
        try:
            self.css_monitor = (
                FileMonitor(self.css_path, self._on_css_change)
                if ((watch_css or self.debug) and self.css_path)
                else None
            )
        except FileNotFoundError as ex:
            raise StylesheetError(f"unable to read CSS file {ex.filename!r}") from None
```

Another alternative would be to make sure all of the files exist after they are validated in [lines 308-327](https://github.com/Textualize/textual/blob/10a3fb1d1b68a6ef3a32e1cc380295993d01cd23/src/textual/app.py#L308-L327):

```py
        for path in css_paths:
            if not path.is_file():
                raise StylesheetError(f"unable to read CSS file {str(path)!r}")
```

**Comment by willmcgugan** [comment]
+1 for the better error message.

**Comment by willmcgugan** [comment]
I think the lack of a nice traceback was a general issue we since fixed.

Here's what happens now:

![Image](https://user-images.githubusercontent.com/554369/213195295-e0a74795-49fb-4ab5-9b8b-a4ee31ba3b5a.png)

Room for improvement maybe, but the error message is at least clear an unambiguous.
