### ISSUE TITLE
Small doc clarification

### ISSUE THREAD

**Issue by vitrioil** [Textualize/textual#1265]
https://github.com/Textualize/textual/blob/8c7bc0aca5bb5eee248afa0b3c921243350df7a3/docs/guide/reactivity.md?plain=1#L220

Shouldn't this be `The watch method is...`?

**Comment by darrenburns** [comment]
Yes, it should be. Feel free to open a PR, otherwise we'll get it updated soon :)

**Comment by vitrioil** [comment]
Cool, let me raise a PR.
