### ISSUE TITLE
Widgets mounted within a single mount call gradually drawing in their content

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1276]
Not logging this as a bug as such, more noting this here at the end of the day so I can come back to it and dig a little more. But while working on [an app to test out parts of Textual](https://github.com/davep/unbored), I've noticed a curious thing. I'm [making a call to `mount`, adding a collection of widgets all in one go.](https://github.com/davep/unbored/blob/524623a22216e622c87007c20719d2b733e423ba/unbored#L445-L453) As the app first draws there's a very noticeable building of the widgets, step-by-step. It can be seen in this video:

https://www.youtube.com/watch?v=Y91Z4eIxZsg

and here are the key frames of what's happening:

<img width="941" alt="Screenshot 2022-11-24 at 17 39 50" src="https://user-images.githubusercontent.com/28237/203842993-94c5d11e-4121-479e-a182-86e71e39cf68.png">

<img width="941" alt="Screenshot 2022-11-24 at 17 40 04" src="https://user-images.githubusercontent.com/28237/203843027-3d749f4c-1434-47b0-8ff7-3f23c9fb1edb.png">

<img width="941" alt="Screenshot 2022-11-24 at 17 40 20" src="https://user-images.githubusercontent.com/28237/203843146-d1a95953-8d87-4b97-add9-6a2d0ef8acc1.png">

The first frame is especially curious as the widget says "Activity", and to the best of my knowledge there's nothing in my code would emit that -- some default behaviour when inheriting directly from `Widget` perhaps?

**Comment by rustybrooks** [comment]
A Container is just a Widget with some custom CSS on it so that is pretty odd.
```
class Container(Widget):
    DEFAULT_CSS = """
    Container {
        layout: vertical;
        overflow: auto;
    }
    """
```

I looked at your code and noticed that you have a class named Activity and that's what you're mounting.  So I am guessing that until it actually calls the compose() function it just shows the name of the class as a place holder.

**Comment by willmcgugan** [comment]
Suspect this is fixed, or not a issue with Textual. Closing as stale. Feel free to reopen if required.
