### ISSUE TITLE
Cursor flying around in Windows console

### ISSUE THREAD

**Issue by fancidev** [Textualize/textual#1283]
System: Windows 10

Console: cmd.exe 10.0.19041.746

Python: 3.8

Reproduce: 

python -m textual

Then resize the console window. 

Then when I scroll through the page, I see a cursor flying around in the window, which I guess is when the UI is being redrawn.

Maybe forgot to hide the cursor after responding to console resize?

**Comment by davep** [comment]
Could you confirm what terminal you're using? The best experience with Textual under Windows will be with [the Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=gb). If you're not using that can I ask you try again with that?

**Comment by fancidev** [comment]
Thanks for the quick response. I am using the Windows Command Prompt. Let me try Windows Terminal and see how it goes.

**Comment by davep** [comment]
Let us know how you get on. I suspect you'll find it much nicer.

**Comment by davep** [comment]
@fancidev Have you had a chance to review this, along with how it may impact #1284 and #1285 too?

**Comment by davep** [comment]
Closing on the assumption it was down to known issues with the default Windows console. Please feel free to reopen if that wasn't the case.
