### ISSUE TITLE
Screen and cursor not restored when textual exits

### ISSUE THREAD

**Issue by fancidev** [Textualize/textual#1284]
System: Windows 10

Console: cmd.exe 10.0.19041.746

Python: 3.8

Reproduce:

python -m textual

Ctrl+Q

Then the app exits, but there are two problems:

1, the screen is not cleared. I have to do “cls”.

2, the cursor disappears. I don’t know how to get it back. “reset” is not a valid command under Windows.

**Comment by davep** [comment]
Could you confirm what terminal you're using? The best experience with Textual under Windows will be with [the Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=gb). If you're not using that can I ask you try again with that?

**Comment by davep** [comment]
Closing on the assumption it was down to known issues with the default Windows console. Please feel free to reopen if that wasn't the case. (see also #1283)
