### ISSUE TITLE
Invalid border character in demo under Windows

### ISSUE THREAD

**Issue by fancidev** [Textualize/textual#1285]
System: Windows 10

Console: cmd.exe 10.0.19041.746

Python: 3.8

Reproduce:

python -m textual

The border around the “Textual Demo” message (and other borders) are displayed as a glyph that indicates invalid characters.

I use the “consolas” font and have “chcp 65001”.

For info, “textual borders” show only the below border types properly: solid, double, ascii, none, hidden.

**Comment by davep** [comment]
Could you confirm what terminal you're using? The best experience with Textual under Windows will be with [the Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=gb). If you're not using that can I ask you try again with that?

**Comment by davep** [comment]
Closing on the assumption it was down to known issues with the default Windows console. Please feel free to reopen if that wasn't the case. (see also #1283)
