### ISSUE TITLE
Textual has no version dunder

### ISSUE THREAD

**Issue by jacobtomlinson** [Textualize/textual#1287]
I'm in the habit of looking for a [`__version__` dunder](https://peps.python.org/pep-0008/#module-level-dunder-names) when trying to figure out what versions of packages I have installed. I noticed today that textual doesn't have one.

```python
>>> import textual
>>> textual.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'textual' has no attribute '__version__'
```

It would be nice if textual followed this convention.

**Comment by davep** [comment]
While I say this as a long-time "fan" of supplying and using `__version__` (and related metadata dunders), it's my understanding that the preferred method these days (and one I started to lean into with a previous system I built) is going via [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html#overview):

```python
>>> from importlib.metadata import version
>>> version( "textual" )
'0.5.0'
```

**Comment by oleksis** [comment]
Use textual `--version` : `ModuleNotFoundError: No module named 'click'`

```bash
➜ python -V
Python 3.10.2

➜ python -m pip install --upgrade pip

➜ pip install textual

➜ textual --version
  File "C:\temp\venv\Scripts\textual.exe\__main__.py", line 4, in <module>
  File "C:\temp\venv\lib\site-packages\textual\cli\cli.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'

➜ pip install click

➜ textual --version
textual, version 0.5.0

```

[Tree widget import error](https://github.com/Textualize/textual/issues/1300#issuecomment-1329661167)

**Comment by davep** [comment]
@oleksis As mentioned elsewhere, that's related to #983

**Comment by jacobtomlinson** [comment]
Yeah I ran into #983 too but I'm not sure it is related to my issue here.

I totally agree that `from importlib.metadata import version; version( "textual" )` is current best practice. But `__version__` is still a pretty common expectation for Python libraries and it would take minimal effort to support (just use `importlib.version` to populate it).

**Comment by willmcgugan** [comment]
The problem was that there was no tool to do this automatically. So pretty much any tool that uses `poetry` won't have a `__version__`.

IIRC I tried  `importlib.version` in `__init__.py` with Rich, but backed out because it was very slow (it enumerates all the packages)!

I believe Sebastian Ramirez was working on a Poetry plugin to do this automatically...

**Comment by jacobtomlinson** [comment]
Ah interesting. Most projects I maintain use [versioneer](https://github.com/python-versioneer/python-versioneer) to set/generate the version from git. I've never used it in a poetry-specific project though.

**Comment by willmcgugan** [comment]
Not super happy with the options here, but I think I have a solution. A module level `getattr` which use either `importlib.metadata` or `pk_resources` to get the version.

So it will be slow on Python3.7, but at least its lazy. You won't pay the price unless you get `__version__`. 

I think I'm willing to do this in preference to adding a backport for 3.7. But it is a lesser evil.

Can anyone see any problems with this approach?

```python
def __getattr__(name: str) -> str:
    if name == "__version__":
        try:
            from importlib.metadata import version
        except ImportError:
            import pkg_resources

            return pkg_resources.get_distribution("textual").version
        else:
            return version("textual")
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
```
