### ISSUE TITLE
Design discussion about input validation

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1288]
The input validation mechanism has to be designed and a couple of things were mentioned when discussing this task:

 1. favouring composition over inheritance;
 2. the fact that 1. prevents CSS type selection;
 3. the fact that 2. could be solved by allowing the CSS type name to differ from the Python class name;
 4. default input validation mechanism using a regex and an overridable method;
 5. probably not building input validation on top of reactive attributes;

<details>
<summary>These bullet points extracted from this transcript of a conversation between @willmcgugan @davep @darrenburns and me (@rodrigogiraoserrao):</summary>

**Dave**: I’m trying to build a very simple `int` input field, that inherits from `Input`. Not intended to be *the* version of such a thing, just trying to get a feel for how you’d do it, and I can’t see an easy in to validating the input. My first approach to this is just to let the user type anything but indicate an error if they’re typing something that won’t `int()`. This suggests two approaches:

• Use some sort of `on_changed` handler in the subclass.
• Use some sort of `validate_value` handler

Thing is… I can’t see how to make either of these work. As best as I can tell an Input, or a child of an Input, can’t receive any sort of Changed message — it’s only ever sent to the parent. Meanwhile, if I implement validate_value in my child class all sorts of chaos happens, with exceptions about cursor position and the like.Am I reading this correctly? Something like an Input can’t observe itself, only its parent container can?

**Darren**: When you implement validate_value in your child class, are you calling super().validate_value(...)  inside it?
(...)
I don’t know that validate_value  is what you want though, those are more for taking the incoming value and correcting it
I think you want watch_value?

**Dave**: Possibly, although it **is** validation I want to do.
Moreover though, I’m thinking it’s kinda weird that my `IntInput` , which inherits from `Input`, can’t have an easy `on_changed` method to handle being changed. That feels like something people are going to want to do a lot.
Like, really simple `IntInput` would look like:

```py
class IntInput( Input ):
    """An input widget that only accepts integer values."""

    def on_input_changed( self, event: Input.Changed ) -> None:
        if event.input.value.strip():
            try:
                _ = int( event.input.value )
                self.set_class( False, "error" )
            except ValueError:
                self.set_class( True, "error" )
                self.app.bell()
```

**Darren**: Maybe. Right now the approach would be to use `watch_value` though. Problem is on submitted events, idk how you'd get hold of them in a subclass for example.

**Dave**: Ahh I know why `validate_value` got upset... I forgot to return the value.

(...)

**Will**: We could make `None` an illegal value in validators.

**Darren**: IDK about making `None` illegal. `None` can be a valid value for a reactive. Users assign their own semantics to it, and sometimes a validator could, quite deliberately, return `None` to “unset” a value for example.

**Will**: True. But then there is no way to catch that “forgot to return something” gotcha. Actually, it would be possible with some dark magic. Scan the AST to look for `return` statements. I was thinking we should have a “preflight check” mode which we could use for expensive checks like that.

(Darren + Dave suggest ↑ be solved with a linter, e.g. “`pylint-textual` much like `pylint-django`.)

**Dave**: so `watch_` has old and new values, but `validate_` only has the new value as parameters, correct? Is there something prohibiting `validate_` getting old and new too? I can see it being dead handy to validate as not-valid and return the old value.

**Will**: validate as an operation shouldn't need the previous value. Why do you need it?

**Dave**: I want to style an input with an error and not allow the dodgy change to persist. Think `IntInput`, someone types "11a", I want to sound the bell and only end up with "11" for example, because the "a" put it in an error state.

**Will**: That's not really the job of a validator. That kind of functionality probably belongs elsewhere.

**Rodrigo**: A "validate" method sounds like a "check if this new value is legal or not", I would expect it to return a bool, and if the return were `False` I'd expect the input to be left unchanged.

**Dave**: Okay. Justr tying to think like a user here and I can see a lot of folk heading down that route. I guess then the question is, why is it a `validate_` that returns a new value? What should it be used for?

**Will**: Think maximum value of 1-10. User puts in 11, and the validator restricts it to 10.

**Dave**: is that different from "user puts in 11a and validate restricts to 11"?

**Will**: No, but why would you need the previous value for that?

**Dave**: Because that'll have been the last valid value and having the code try and work out what it is, when it was there anywhere, seems like extra work for the user. I mean, okay, in that case I can just trim off the last character, but then there's a field that has "1111" in it and someone drops the "a" in the middle.

**Darren**: Right now you can look at `self.value` I think. In the input example

**Rodrigo**: If we have a float input and we try to validate `"1.2.3"` we don't know if we had `"1.23"` or `"12.3"`.

**Dave**: Oh! `self.value` hasn't actually been modified before `validate_` ends?

**Will**: That's right.

**Dave**: Ahh hah! Hadn't caught on to that. I'd read it is "thing got assigned a new value, would you like to check it?"

**Will**: But for the case of Input, there is nothing to restrict what the user types ATM. You Don't want `11a` to appear, then change to `11` later on.

**Rodrigo**: Folks, I am still not convinced that `validate_...` shouldn't just be a Boolean function that checks if the new change is legal or not...

**Dave**: Perfect.
```py
class IntInput( Input ):
    """An input widget that only accepts integer values."""

    def validate_value( self, value: str ) -> str:
        if value.strip():
            try:
                _ = int( value )
                self.set_class( False, "error" )
            except ValueError:
                self.set_class( True, "error" )
                self.app.bell()
                return self.value
        return value
```
Type non-int and terminal goes bong and no bad value. At least in the simple case.

**Will**: See the 1-10 example above.

**Rodrigo**: The 1-10 example makes sense but choosing a value to put there instead looks like a second layer that only happens after the validator fails.

**Dave**: (I'm sure there's a bunch of holes in the above but it was useful to properly get to know `validate_`.)

**Darren**: Pretend `validate_*` is called `sanitize_*`

**Will**: Maybe that is a better name.

**Rodrigo**: If it is called `sanitize_*` then I'm happy

**Darren**: There's also `clean_*`.

**Rodrigo**: `sanitize_*` could be called if `validate_*` returns `False`.

**Darren**: But I do agree that `validate_*` is a bit misleading, my first impressions were similar to what Rodrigo has mentioned.

**Will**: Neither "sanitize" nor "clean" are particularly apt either.

**Rodrigo**: What is being considered here? Simply renaming `validate_*` to smth else, or creating the two layers of verification? Because if there is a single layer of verification, this looks _very_ verbose:
```py
def validate_value(self, value: str) -> str:
    if condition(value):
        return value
    else:
        return self.value
```
And ↑ looks like a very common use case, simply validating and preserving the last legal value in case validation fails.

**Dave**: I do think it's important to keep in mind that my need here was reactive vs UI element. I want to be able to easily make a UI element that rejects bad input. That's common. And in this case, I was trying to do it off the back of a reactive. Kinda feel like there's two layers here.

**Will**: Validators are called when you set attribute i.e. `set.foo = 2`. You would not expect the assignment to simply not happen. At that point something is going to be set, or you get an exception, if we want to preserve the semantics of setting attributes.

**Rodrigo**: Ah, we are talking about validators for reactive attributes? That part when over my head! I thought we were talking about validators for input fields.

**Dave**: Yeah, in this particular case I'm leaning on the former because it's used to implement the latter with `Input`. Which is actually really nice, but it's worth keeping that in mind.

**Will**: We need a solution for Input validation. But it probably wouldn't be through reactive attributes.
I'm thinking a regex, plus a method to override on the Input class.

**Dave**: Aye, I can likely think of a few times where a regex isn't going to cut it, so as long as you can override that's good.

**Will**: Although, I am favouring "composition over inheritance" lately.

**Dave**: Example?

**Will**: Rather than a `check_input_value_before_updating` method, there could be a small `InputChecker` class that you associated with your `Input`. It avoids inheritance, which is often a "now you have 2 problems" type of solution.

**Rodrigo**: Hm, so an `IntInput` would actually be `Input` + `IntInputChecker`?

**Will**: Essentially, yeah.
Initialize via a classvar.

**Dave**: So you'd have to inherit anyway, right?

**Will**: Yeah, or the checkers could be on `__init__`. But you wouldn't need to add methods.

**Rodrigo**: Not necessarily. You could, but something like `IntInput = partial(Input, validator_class=IntInputChecker)` shows that the pattern here really is composition. Assuming `Input` has a parameter `validator_class`.

**Dave**: Wouldn't that result in `IntInput` still being type `Input` though? Not very friendly with CSS.

**Will**: Good point, Dave.

**Rodrigo**: Let the record show that using inheritance like
```py
class IntInput(Input):
    def __init__(self, validator_class, *args, **kwargs):
        super().__init__(*args, validator_class=validator_class, **kwargs)
```
distracts you from the fact that the main pattern is composition and not inheritance.
We get different classes so that CSS works nicely and we essentially split the validation to another class, thus favouring composition over inheritance. IMO

**Darren**: With composition you wouldn't _need_ to subclass. The idea being you can pull/compose the functionality you need (and only the functionality you need). You could instantiate an input like `Input(..., validator=NumberValidator())`. So the subclass `IntInput` wouldn't be necessary. FWIW I am thoroughly in the composition over inheritance camp.

**Dave**: If it doesn't result in circular references and results in smaller `.py` files (I'm looking at you `widget.py`) I'm all in.
But again Darren, you wouldn't be able to style `IntInput` different from `Input` with a type selector.

**Will**: This actually should be possible. Not sure if it is exposed, but you could set the CSS name differently from the class name.

**Darren**: My point is that IntInput wouldn't even be required.

**Will**: Yeah, but Dave was pointing out that if the validator was a parameter on Input, you couldn't currently single it out via the type name since everything would be an `Input`.
Which makes the ability to override the CSS type name more important.

**Darren**: But the validator wouldn't be a widget? So why would you query it?

**Dave**: Because, say, I want to query all the IntInputs to gather their values, or... something.
It wasn't that you should never do it, more that it's a downside of not "inherit class-based things all the way it's a tree of widgets people!"

**Darren**: Oh, so you mean if we use composition more then we lose some of the querying capabilities since you can't say give me all Inputs that use an `IntValidator` or whatever?
I think at that point though you should be using CSS classes.

**Dave**: So, when we do implement some of the other inputs mentioned on the roadmap, I think we **should** subclass, not just compose input variables, for that reason. Then users don't have to add a CSS class to every IntInput, for example.

**Darren**: I disagree because I think the example of needing to query all inputs with a certain validator isn't very realistic and isn't enough to justify using inheritance over composition.

**Will**: The CSS inheritance is independent of Python inheritance. So we could make it work that way.

**Dave**: Cool. I mean, I'm not wedded to how it's done internally, but it would be weird to have CSS type selection for some of the widget tree, but not all of it.
</details>

**Comment by ofek** [comment]
In case it's useful for the future design, I was having trouble with maintaining an invariant where validation only occurs for user input because validation (and changed events) also occurs for default values. To resolve this I am doing the following:

```python
class DefaultValue:
    def __init__(self, value: object):
        self.inner = value

class ValidatedInput(Input):
    def validate_value(self, value: object):
        if isinstance(value, DefaultValue):
            return value.inner

        self.validate_user_input(value)
        return value

    def validate_user_input(self, value):
        pass

class SomeInput(ValidatedInput):
    def on_mount(self):
        super().on_mount()

        self.value = DefaultValue(...)

    def validate_user_input(self, value):
        ...
```

**Comment by willmcgugan** [comment]
Input validation will land soon!
