### ISSUE TITLE
Add additional bindings to `Input` 

### ISSUE THREAD

**Issue by vsajip** [Textualize/textual#1310]
I'm thinking of these:
```python
Binding('ctrl+left', 'word_left', 'previous word', show=False),
Binding('ctrl+right', 'word_right', 'next word', show=False),
Binding('ctrl+u', 'delete_left_all', 'delete left all', show=False),
Binding('ctrl+w', 'delete_left_word', 'delete left word', show=False),
Binding('ctrl+f', 'delete_right_word', 'delete right word', show=False),
Binding('ctrl+k', 'delete_right_all', 'delete right all', show=False)
```
and have already implemented the above in a subclass in an app I'm working on, seem to work reasonably. I could work up a PR but I'm not sure how the unit and integration testing for this kind of thing would work.

**Comment by vsajip** [comment]
Just look at the contents inside the blue border - I snipped these from my app so the surrounding stuff can be ignored.

Navigate right/left by word:
![word-left-right](https://user-images.githubusercontent.com/130553/205379801-b29d2cb9-c72a-4c59-a238-e9e8befe1813.gif)
Delete leftwards by word:
![delete-left-word](https://user-images.githubusercontent.com/130553/205379968-768ee4f2-eb4c-437f-a468-7ddd923d19ef.gif)
Delete rightwards by word:
![delete-right-word](https://user-images.githubusercontent.com/130553/205380057-1242dcea-8bd1-4fde-a3ae-f3eb7dc0d16d.gif)
Delete all to left:
![delete-left-all](https://user-images.githubusercontent.com/130553/205380165-570ad712-bfc9-4729-9910-10b20b967f7e.gif)
Delete all to right:
![delete-right-all](https://user-images.githubusercontent.com/130553/205380200-6555417e-059c-4b4d-b641-27d077f25ea9.gif)

**Comment by learnbyexample** [comment]
Yeah, these would be very helpful. I had added Ctrl+u/k/w for my app recently too. Good idea for Ctrl+f.

Also, I wanted to know - why Ctrl+d is used instead of Delete? Some terminals don't support it or some other reason?

**Comment by vsajip** [comment]
> I feel like Home/End behavior should depend on whether or not the focus is within the Input widget.

But if the focus is in the Input, it'll see those keys, but if it's not. then presumably it won't see those keys? Why does anything special need to be done for Home/End?

**Comment by learnbyexample** [comment]
I'm not sure where the other functionality is implemented. Home/End are used to move the screen to top/bottom. What I'm asking is that when focus is in Input, it should not move the screen.

**Comment by willmcgugan** [comment]
I think that may be fixed in main. We were responding to key events for home and end, but these were replaced with bindings. So if the focused widget has a binding it will now prevent the parent from handling it.

**Comment by willmcgugan** [comment]
We should follow any standard conventions were possible for such things.
