### ISSUE TITLE
Fix mouse01 transparent background

### ISSUE THREAD

**Issue by davidfokkema** [Textualize/textual#1317]
In the `mouse01.css` example in the mouse input section of the Textual guide there is this section:
```
PlayArea { 
    background: transparent;
    layer: ball;
    
}
```
However, the PlayArea widget is _not_ rendered transparent in iTerm and in VS Code. Thus, no mouse events are logged on the screen. If you replace `background: transparent` with `opacity: 0%` it _does_ render the widget transparent. Searching through the repository it seems to me that `transparent` is in fact a valid color and should be rendered transparent.

**Comment by willmcgugan** [comment]
I think there was a change to transparent backgrounds, that probably impacted this.

`/examples/guide/input/mouse.01.py` used to show a textlog of events underneath the widget that sticks to the mouse cursor. We need to restore that behaviour.

It might be as simple as changing opacity to `0%` as @davidfokkema suggested. Or possibly `visibility: hidden`

**Comment by davep** [comment]
Fixed by https://github.com/Textualize/textual/pull/1504
