### ISSUE TITLE
Text Input Widget

### ISSUE THREAD

**Issue by CyberSmash** [Textualize/textual#132]
To be added by @willmcgugan

Sorry if this is already a thing, or goes against the general philosophy of the project.

I have a need for an input widget a user could type text into. My use case is to search through a long list of items such as a directory tree.

One of the bigger hurdles here would be keys that are already bound to action. There doesn't seem to be a way to "unbind" a key, or "unbind" all keys temporarally when the correct input panel is selected. 

Thoughts?

**Comment by tusharsadhwani** [comment]
Here's a currently going on discussion: https://github.com/willmcgugan/textual/discussions/105

**Comment by Danmou** [comment]
For anyone else looking for this, [textual-inputs](https://github.com/sirfuzzalot/textual-inputs) implements simple text and number input widgets. They seem to work quite well and the implementation looks very straightforward. Keys being bound outside the widget does not seem to cause any issues when the widget has focus. All credit to the author @sirfuzzalot for implementing it!

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
