### ISSUE TITLE
Possible bug: binding for non-alphanumeric characters could be simpler

### ISSUE THREAD

**Issue by jayaddison** [Textualize/textual#1323]
Hi folks!

While learning `textual` today, I began by adapting the [`code_browser.py` demo](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/examples/code_browser.py).

To experiment with the interactive options, I replaced the [`toggle_files` action binding key of `f`](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/examples/code_browser.py#L27) with the single character `.` (unicode name: `FULL STOP`).

## Expected Behaviour
* The `.` action will be listed in the footer
* Pressing `.` would call the `action_toggle_files` method

## Actual Behaviour
* :white_check_mark: The `.` action appears in the footer
* :negative_squared_cross_mark: The action is not called, and the file browser does not toggle
  * The input character `.` is parsed to unicode name `FULL STOP`, which then becomes `full_stop` after it is [remapped](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/src/textual/app.py#L704-L710) in the code.
  * This means that the [`Bindings.get_key` lookup](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/src/textual/binding.py#L131-L146) does not return a result 

## :construction: Workaround / solution (?)
Using a binding with the key field `full_stop` (as the first entry in the three-item tuple) will provide the expected behaviour to the user.

However: that seemed challenging to discover (I added some debugging code to emit the keypress key names to determine what the input was being parsed to).

## :warning: Caution
If this is a bug, then some care may need to be taken with a fix.

In particular, a [`str.split` operation](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/src/textual/binding.py#L52) is performed for each constructed binding.  If the key character itself is a comma -- or contains a comma -- then unexpected behaviour could result.

## Screenshot
![image](https://user-images.githubusercontent.com/55152140/205971322-d52cae8b-eca4-4922-a939-18bae13561ef.png)

**Comment by davep** [comment]
What you're seeing here is intended behaviour but, as you've identified, the names of some keys aren't easy to discover right now. In part this is because there's still a fair bit of work to do on the documentation and stuff like this still needs documenting. Meanwhile though, to help with discovery, I've written [`textual-keys`](https://github.com/davep/textual-keys). You can install it with `pip` or `pipx` and then run `textual-keys` and mash on the keyboard and see what things are called. Like this:

<img width="922" alt="Screenshot 2022-12-06 at 20 15 05" src="https://user-images.githubusercontent.com/28237/206013392-0460dd47-5f1a-40c7-b0bc-daec590e5109.png">

It's highly likely a variation on this will make its way into Textual itself, perhaps as a command for the `textual` command (think `textual keys`, following the pattern of `textual colors` or `textual easing` and so on).

**Comment by jayaddison** [comment]
That looks very useful, thank you (neat to see that it's a `textual` app itself!).

The developer experience I have in mind is based on my own behaviour of frequently not waiting to read the documentation or searching around before trying out a shiny new technology/product.

It was a useful learning experience to unpick the code to figure out why the binding key wasn't matched -- but it's also (at least to my memory so far) the only weird gotcha I've found.  In general: I really like the webiness and jQueryness of the library so far, even if that sounds odd or like an opinion from a decade ago.

And that's probably how I'd argue in support of #1324 (in brief: if a binding key isn't going to match: tell the user and provide a suggestion for one that should work instead, if discoverable) -- even though I only really figured out that reasoning after the pull request was opened.

**Comment by davep** [comment]
I've not reviewed the PR myself as it looks to be making a fairly fundamental change to binding so it's really best looked at by @willmcgugan. He's (technically) on holiday until next week so, if you don't hear anything on it for a wee while, don't worry, it's not been ignored. :-)

**Comment by jayaddison** [comment]
Hehe, okie doke - thank you :)

**Comment by jayaddison** [comment]
No longer a problem since [`v0.8.0` of `textual`, where non-alphanumeric character binding support was added](https://github.com/Textualize/textual/blob/f29da41e9af01ec47acb0d123d82cc3385152c6b/CHANGELOG.md#added) (7a46672d64d93b23b280b876202dc4ae01df6918) :tada:
