### ISSUE TITLE
Footer bindings should update when active screen changes

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1334]
I have a simple application with two screens. One screen binds `P` to push the other screen on top, and that other screen binds `P` to pop itself out of the stack.
It doesn't seem related to the fact that the two bindings share the same key because I tried binding the two actions to different keys and the same issue persists.

The video recording shows that the labels identifying the screens swap back and forth as I press `P` repeatedly, but the footer remains unchanged:

https://user-images.githubusercontent.com/5621605/206693182-5386a7f7-6112-46e3-83a2-aba9c7bc9a8c.mp4

<details>
<summary>Code for the repro</summary>

```py
from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Footer, Label


class Screen1(Screen):
    BINDINGS = [("p", "pop", "pop")]
    def compose(self) -> ComposeResult:
        yield Label("Screen 1")
        yield Footer()

    def action_pop(self) -> None:
        self.app.pop_screen()


class Screen2(Screen):
    BINDINGS = [("p", "push", "push")]
    def compose(self) -> ComposeResult:
        yield Label("Screen 2")
        yield Footer()

    def action_push(self) -> None:
        self.app.push_screen("screen1")


class MyApp(App):
    SCREENS = {
        "screen1": Screen1,
        "screen2": Screen2,
    }

    def on_compose(self) -> None:
        self.push_screen("screen2")
        self.push_screen("screen1")


MyApp().run()
```

</details>

**Comment by rodrigogiraoserrao** [comment]
I also found that if you focus the footer after changing screens once, it will update the key bindings and from then on the correct footer is always shown. Look at the footer in the video below.

 - I pressed `P` once and nothing _visible_ happened;
 - I moved the mouse over the footer and the footer updated;
 - I pressed `P` repeatedly and the footer updated each time.


https://user-images.githubusercontent.com/5621605/206728050-bf1332ea-2e01-40a2-b5f7-5798903d27ef.mp4

**Comment by davep** [comment]
Working through the issue, and writing a sandbox app to better understand the problem, and this seems to work just fine:

```python
from string import ascii_lowercase

from textual.app     import App, ComposeResult
from textual.screen  import Screen
from textual.widgets import Header, Footer, Label
from textual.binding import Binding

class Base( Screen ):

    DEFAULT_CSS = """
    Screen {
        align: center middle;
    }
    """

    def compose( self ) -> ComposeResult:
        """Compose the child widgets."""
        yield Header()
        yield Label( "[b]Press (almost) any key[/]" )
        yield Footer()

class This( Base ):

    BINDINGS = [
        Binding( key, f"any( '{key}' )", "This" ) for key in ascii_lowercase
    ]

    def action_any( self, _: str ) -> None:
        self.app.push_screen( "that" )

class That( Base ):

    BINDINGS = [
        Binding( key, f"any( '{key}' )", "That" ) for key in ascii_lowercase
    ]

    def action_any( self, _: str ) -> None:
        self.app.pop_screen()

class ScreenKeysApp( App[ None ] ):

    SCREENS = {
        "this": This,
        "that": That
    }

    def on_mount( self ) -> None:
        self.push_screen( "this" )

if __name__ == "__main__":
    ScreenKeysApp().run()
```

On the other hand the code in the issue description does still display the problem as of Textual 0.10.1.

On the third hand, modifying the original report code so that the `App.compose` is:

```python
    def on_compose(self) -> None:
        self.push_screen("screen2")
#        self.push_screen("screen1")
```

and it works fine. Time to remind myself how the screen stack works and looks in this situation.

**Comment by willmcgugan** [comment]
If I were to guess, its because the Footer doesn't know to update when the current screen changes.

I wonder if there is an existing message the footer could respond to, which would prompt it to update.

**Comment by davep** [comment]
I think I might be misunderstanding that, as in both cases each screen has its own footer, so that'll be very different instances of a footer wont' it? (in the examples above)

**Comment by willmcgugan** [comment]
Yes, but I'm guessing that the context changed while the screen wasn't active. Don't want to presume your investigation though.

**Comment by davep** [comment]
Taking the original code again, another "fix" to the code itself is this:

```python
    async def on_compose(self) -> None:
        await self.push_screen("screen2")
        await self.push_screen("screen1")
```

I feel there's a bug in the test code in that I can't quite see why you'd want to push each of the screens onto the stack like this, and then apparently go on to ignore the initial screen pushed onto the stack while pushing/popping further. But... it's not invalid code of course, it just looks like there's always an unused screen washing around the stack.

So... that aside... my first thought after working through the code and the problem, is that perhaps the `Footer` is (quite rightly) getting confused about what `app.screen` as as it gets created?

**Comment by davep** [comment]
Actually, scratch the part about the extra screen on the stack: confusing myself about the order of things here; but I think the part about how the pushed screens get spun up likely holds when it comes to the `Footer` -- I'll start there.

**Comment by davep** [comment]
As further evidence for what I'm thinking, this change (not the proposed change, just an elimination of options change), has the original test code working just fine:

```diff
diff --git a/src/textual/widgets/_footer.py b/src/textual/widgets/_footer.py
index 0b1c9a80..d7ce8720 100644
--- a/src/textual/widgets/_footer.py
+++ b/src/textual/widgets/_footer.py
@@ -138,6 +138,4 @@ class Footer(Widget):
         return renderable

     def render(self) -> RenderableType:
-        if self._key_text is None:
-            self._key_text = self.make_key_text()
-        return self._key_text
+        return self.make_key_text()
```

Given that `App.push_screen` is async, and two are happening in sequence, and given that `Footer` caches its display, it looks like the `Footer` of both screens is picking up the same collection of keys as as things get mounted async.

**Comment by davep** [comment]
Testing with both the test apps (my own and the one provided here), doing side-by-side comparisons of `main` (what will become 0.11.0) and 0.10.1, running the same code with different Textual, I'm confident that this has been fixed during recent work (my best guess being the work on #1636).

Closing as fixed.

**Comment by willmcgugan** [comment]
Best resolution you could hope for!
