### ISSUE TITLE
Review Styles Reference

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1340]
Some CSS rules have missing values documented. We should review all the CSS rules un the reference section of the docs, to add anything missing.

**Comment by rodrigogiraoserrao** [comment]
Pages in the reference and status tracker:

 - [ ] align
 - [ ] background
 - [ ] border
 - [ ] box-sizing
 - [ ] color
 - [ ] content-align
 - [ ] display
 - [ ] dock
 - [ ] grid
 - [ ] height
 - [ ] layer
 - [ ] layers
 - [ ] layout
 - [ ] links
 - [ ] margin
 - [ ] max-height
 - [ ] max-width
 - [ ] min-height
 - [ ] min-width
 - [ ] offset
 - [ ] opacity
 - [ ] outline
 - [ ] overflow
 - [ ] padding
 - [ ] scrollbar colors
 - [ ] scrollbar-gutter
 - [ ] scrollbar-size
 - [ ] text-align
 - [ ] text-style
 - [ ] text-opacity
 - [ ] tint
 - [ ] visibility
 - [ ] width
