### ISSUE TITLE
Inside a widget, self.query("*") seems to return the widget itself as well as descendants

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1341]
A call to `widget.query` should not return self by default. So that `self.query("*").remove()` won't attempt to remove self.

For consideration:

    - Should `query` grow a `with_self` boolean to optionally return self?

**Comment by davep** [comment]
Given this:

```html
<html>

  <head>
    <title>Query Test</title>
  </head>

  <body>

    <div id="test">
      <div id="this-is-a-child">
        This is the test paragraph.
      </div>
    </div>

  </body>

</html>
```

this is the request:

![Screenshot 2022-12-14 at 08 42 53](https://user-images.githubusercontent.com/28237/207548108-2284cbb9-4351-459d-8f20-cba5ce26e1ff.png)

I'd say that's a point very much in favour of "this needs to change in Textual".

**Comment by willmcgugan** [comment]
Stealing this

**Comment by willmcgugan** [comment]
You can have it back
