### ISSUE TITLE
A `Widget`-derived widget with `inherit_bindings=False`, but no `BINDINGS`, appears to still inherit bindings

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1351]
This is *very* much related to #1343, but I think merits an issue of its own to consider first. The reasons *why* this happens seem clear enough, but I feel the setup may cause confusion. With Textual as it is of 0.6.0 (with the bindings for movement keys being on `Widget`), consider this widget:

```python
class Odradek( Widget, inherit_bindings=False ):
    pass
````

vs this:

```python
class Odradek( Widget, inherit_bindings=False ):
    BINDINGS = []
````

In the former case the bindings of `Widget` are still inherited. In the latter they're not.

**Comment by rodrigogiraoserrao** [comment]
@davep I'll be happy to tackle this one.

**Comment by willmcgugan** [comment]
Yup. Suspect that will do it.

**Comment by davep** [comment]
> @davep I'll be happy to tackle this one.

If you do, likely best to *not* start building up tests for it as I've just popped one for this exactly situation into https://github.com/Textualize/textual/pull/1346 and there's going to be more to come, that aren't the same issue but potentially overlap.
