### ISSUE TITLE
Review what causes some classes to get linked in our docs, and not others

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1364]
As of the time of writing, something like [the docs for `App.mount_all`](https://textual.textualize.io/api/app/#textual.app.App.mount_all) have (auto-?)links to `Widget`, but not for `AwaitMount` or `MountError`. The issue is: why one but not the other two? What causes the links to happen, should we encourage linking to all public-facing and published types and classes, and if so how do we encourage the docs to do this?

First thought about in a comment in #1363.

**Comment by vitrioil** [comment]
Isn't this because of no reference to that class which is somewhat determined from [here](https://github.com/Textualize/textual/blob/main/docs/api/widget.md)?

Example if I change it to say:
```markdown
::: textual.widget
```
Then I do see dedicated sections to `/api/widget/#textual.widget.AwaitMount` (and `/api/widget/#textual.widget.MountError`).

Although what's still weird is that there is a hyperlink to `AwaitMount` but not to `MountError` from `mount_all`'s documentation.

![mount_all_doc](https://user-images.githubusercontent.com/41074533/210633268-ac6ffb1c-9242-4bfe-8766-3138b335b318.png)

**Comment by davep** [comment]
Nothing leapt out at me relating to this specific issue, although in fairness I wasn't concentrating on it. Now I've found the relevant docs I'll dip back in with this in mind at some point soon.

**Comment by willmcgugan** [comment]
I wonder if @rodrigogiraoserrao figured this out in his tour of the docs?

**Comment by rodrigogiraoserrao** [comment]
> I wonder if @rodrigogiraoserrao figured this out in his tour of the docs?

Not yet, didn't have this present in my mind. But you can assign this to me and I'll have a look during my next batch of dealing with documentation tickets.

**Comment by davep** [comment]
Looking into this some more this morning and @vitrioil was spot on. Changing `docs/api/widget.md` to read like this:

```markdown
::: textual.widget
```

ensures all the public interfaces get documented and linkable. Moreover, doing this I'm finding that in the `mount_all` example mentioned above, everything that should be linkable is:

<img width="852" alt="Screenshot 2023-02-28 at 11 40 21" src="https://user-images.githubusercontent.com/28237/221843438-1a0d98b5-a083-4c20-95b1-8fa54abd58d1.png">

This seems like the correct way to go, at least for the API documentation: don't pull in the specific widget class, instead pull in the module and let everything inside it get documented (and so become linkable).

I'll go ahead and make the changes and PR it and we can all have a review of the docs and see if we're still happy with them.

**Comment by willmcgugan** [comment]
Fantastic 👍

**Comment by davep** [comment]
Also, if it's not in our docspec already, I think one to add is this:

- Types we define that will end up in the documentation should themselves get a docstring.

As an example, the `timer` argument of the `Timer` class takes a timer whose type is `TimerCallback | None`, but `TimerCallback` doesn't appear in the docs and so can't be linked to. The reason it isn't in the docs is because it's in the code like this:

```python
TimerCallback = Union[Callable[[], Awaitable[None]], Callable[[], None]]
```

It should have a docstring explaining its type. Eg:

```python
TimerCallback = Union[Callable[[], Awaitable[None]], Callable[[], None]]
"""A callback function for a timer -- someone who knows better than I can actually document this"""
```

Tagging @rodrigogiraoserrao just in case (although I will go check the specs in a bit).

**Comment by rodrigogiraoserrao** [comment]
> Tagging @rodrigogiraoserrao just in case (although I will go check the specs in a bit).

It's not explicitly in the specs that we should document types.
I like the idea of adding it there.
Will you do it?

**Comment by davep** [comment]
> Will you do it?

Perhaps not that specific example, and likely none in the PR I'm about to do; but I think like with documenting actions and component classes and the like, we should have an ongoing effort to do document-when-idle-and/or-seen.

**Comment by davep** [comment]
Oh, wait, you meant add it to the spec?
