### ISSUE TITLE
DataTable.add_row() doesn't work as expected, though add_rows() does.

### ISSUE THREAD

**Issue by vsajip** [Textualize/textual#1368]
This script (`simple_table.py`)
```python
import sys

from textual.app import App, ComposeResult
from textual.widgets import DataTable

class TableApp(App):
    def compose(self) -> ComposeResult:
        yield DataTable()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.add_columns('Col 1', 'Col 2')
        rows = (
            ('v1', 'v2'),
            ('v3', 'v4')
        )
        if len(sys.argv) > 1:
            table.add_rows(rows)
        else:
            table.add_row(rows[0])
            table.add_row(rows[1])

if __name__ == "__main__":
    app = TableApp()
    app.run()
```

If invoked with no parameters it shows an empty table, even though two rows have been added using `add_row()`. The orange cursor in the image below shows that the rows have been added - they just don't display correctly.

![ss2](https://user-images.githubusercontent.com/130553/207842461-7a69603c-b6f1-4d20-8103-ce65218e7b8b.png)

However, if invoked with any argument (say `foo`), the `add_rows()` path is taken and the rows do display correctly in this case:

![ss3](https://user-images.githubusercontent.com/130553/207842740-1781a152-fe98-4e35-8e76-74df9e66c632.png)

Using repo version of `textual`, Linux Mint 64-bit (Cinnamon desktop).

**Comment by rodrigogiraoserrao** [comment]
Hey there, the issue you are encountering is that the method `table.add_row` takes a variable number of arguments, where each argument is a cell value.

So, changing your code to

```py
# ...
        else:
            table.add_row(*rows[0])
            table.add_row(*rows[1])
# ...
```

will have it work as expected.

**Comment by davep** [comment]
`add_row` takes the column values [as positional parameters](https://textual.textualize.io/api/data_table/#textual.widgets._data_table.DataTable.add_row). So rather than like this:

```python
row = [ 1,2,3 ]
table.add_row( row )
```

it would be more like this:

```python
row = [ 1,2,3 ]
table.add_row( row[0], row[1], row[2])
```

or even:

```python
row = [ 1,2,3 ]
table.add_row( *row )
```

**Comment by vsajip** [comment]
OK, sorry for the noise. I didn't read carefully enough 😞

**Comment by rodrigogiraoserrao** [comment]
> OK, sorry for the noise. I didn't read carefully enough 😞

No worries, I made the same mistake the first couple of times!
