### ISSUE TITLE
Button padding causes button text to disappear

### ISSUE THREAD

**Issue by learnbyexample** [Textualize/textual#1377]
I'm seeing a difference between Textual `0.5.0` and `0.6.0` versions. Not sure if I'm doing something wrong.

This works:

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import Button, Label
from textual.containers import Container

class TestApp(App):

    CSS = '''
    .cell {
    margin: 1;
    }
    '''

    def on_mount(self) -> None:
        self.dark = False

    def compose(self) -> ComposeResult:
        yield Button(label="⭕️", classes="cell")


if __name__ == "__main__":
    app = TestApp()
    app.run()
```

![image](https://user-images.githubusercontent.com/17766317/208033912-b21b7dfc-b264-4f20-b450-1e84d542752e.png)

---

Adding padding causes button text to disappear:

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import Button, Label
from textual.containers import Container

class TestApp(App):

    CSS = '''
    .cell {
    margin: 1;
    padding: 1;
    }
    '''

    def on_mount(self) -> None:
        self.dark = False

    def compose(self) -> ComposeResult:
        yield Button(label="⭕️", classes="cell")


if __name__ == "__main__":
    app = TestApp()
    app.run()
```

![image](https://user-images.githubusercontent.com/17766317/208033812-f29809f9-c862-433a-88f0-6de82147c9e1.png)

**Comment by davep** [comment]
The problem you seem to be running into here is that, by default, a button is set to `height: 3;`. Adding the extra padding while staying within the bounds of that height setting is going to mean that something doesn't really show. In your code, if you want the height of the button to grow to allow for the padding, you're going to want to set it to `height: 5` or perhaps even `height: auto` if that makes more sense for your use.

**Comment by learnbyexample** [comment]
Thanks. I tried using `min-height: 1;` and it worked (checked with `0.9.1` version as well).
