### ISSUE TITLE
Cosmetic: it would be nice if one of the DataTable columns could use up horizontal space in the container

### ISSUE THREAD

**Issue by vsajip** [Textualize/textual#1383]
When a `DataTable` doesn't occupy all the horizontal space in its container, things can look a little off cosmetically. It would be nice if one could nominate a column by index to use up any remaining horizontal space. If not specified, things would work as they do now. 

Not using up available space:

![ss24](https://user-images.githubusercontent.com/130553/208194796-f956d446-4b1f-4786-957e-6702a72c23cd.png)

Using up available space:

![ss23](https://user-images.githubusercontent.com/130553/208194852-1205dd70-d78e-4a5e-901d-bd5b3960aed3.png)

**Comment by WMRamadan** [comment]
@vsajip Is this something you are in the process of implementing ?

**Comment by vsajip** [comment]
Only as a bit of a kludge - you have to use internals and browse the source. Also, only for the last column as it suits my use case. But allowing a different column to be the one that takes up the slack is ideal.

**Comment by willmcgugan** [comment]
The header bar now extends the full width. Which I think improves the aesthetics somewhat.
