### ISSUE TITLE
result = App.run()

### ISSUE THREAD

**Issue by kamadorueda** [Textualize/textual#139]
To be added by @willmcgugan

1. Thanks for such a great library
2. We are using your library! See the result here: https://github.com/fluidattacks/makes/pull/725
3. This is not an outstanding feature that must be added
4. But It would be very useful in some cases

The `App` class is normally used as a whole application: `App.run()`

It would be useful if we could return data from it on exit so we can do `result = App.run()`.
This allows for having many 'scenes' (`App`s) in our application, for instance for asking user for a value and then do some work, then show other 'scene' (other App), etc

**Comment by styk-tv** [comment]
@willmcgugan is there any update on this? would be great to be able to switch between multiple screens

**Comment by willmcgugan** [comment]
We're working on a large feature branch ATM. The code in main is somewhat frozen in terms of features. If you need this I'd suggest forking it for now. Happy to consider a PR.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
