### ISSUE TITLE
Driver artefact appears and remains on screen (appears related to getting terminal sync mode support)

### ISSUE THREAD

**Issue by vsajip** [Textualize/textual#1390]
Environment: Linux Mint 64-bit with Cinnamon desktop, Python 3.7.15, Textual 0.7.0 (issue also occurs with 0.6.0)

This script (`table3.py`)
```python
from __future__ import annotations

from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal, Vertical
from textual.widgets import Label

class TestApp(App):

    CSS = '.hfr { height: 1fr; }'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.label = Label()
        self.list = Container(self.label, classes='hfr')
        self.upper = Label('', classes='hfr')
        self.vertpane = Vertical(self.upper, self.list)

    def compose(self) -> ComposeResult:
        yield Horizontal(self.vertpane)

TestApp().run()
```

shows an permanent artefact on the screen

![ss25](https://user-images.githubusercontent.com/130553/208291812-7257badd-24bd-4e72-8608-561eb5944ae2.png)

which is apparently from this code:

https://github.com/Textualize/textual/blob/8760c3cc5ea6af106ceaf56a24293eb131d0220d/src/textual/drivers/linux_driver.py#L149

If there is actual text (`'Hi'`) added to the upper `Label`, the artefact doesn't remain (hard to know if it appears momentarily):

![ss26](https://user-images.githubusercontent.com/130553/208291989-97ab3e48-295d-4f8c-927c-d54d82715b5c.png)

Notice how in the first case (empty string as the Label's renderable) the label doesn't have a black background - unlike in the second case.

**Comment by rodrigogiraoserrao** [comment]
Hey @vsajip, could you check if this is still a problem in the OS you mentioned?
Environment: Linux Mint 64-bit with Cinnamon desktop

The PR above fixed a similar thing and there's the possibility that this was fixed alongside that fix, or some other fix that we did in the meantime.

Thanks.

**Comment by vsajip** [comment]
The problem seems to no longer be there, so I'll close this issue. Thanks for the update!
