### ISSUE TITLE
Docs: Improve mkdocs Checkbox Styling

### ISSUE THREAD

**Issue by WMRamadan** [Textualize/textual#1392]
The current styling of mkdocs material theme uses a gray circle with a white check inside of it for an unchecked checkbox, this is confused with the checked checkbox that has a styling of a green circle with a white check inside of it.

Example:
![Screenshot from 2022-12-18 16-47-23](https://user-images.githubusercontent.com/1612303/208304827-ef9fcb53-9264-4ea0-952e-e542d4afe466.png)

According to the following discussion (https://github.com/Textualize/textual/discussions/1021#discussioncomment-4440632) it would be nice to implement a styling based on the following example (https://github.com/WMRamadan/mkdocs-styling) to better distinguish between an unchecked box and a checked box within the textual docs.

Before & After Example:
![mkdocs_task_list_styling_example](https://user-images.githubusercontent.com/1612303/208304931-da9a92c3-a097-47ef-9b11-ee37a848afcd.jpg)

**Comment by willmcgugan** [comment]
Personally I find it clear enough as it is.

**Comment by davep** [comment]
I think the problem is, and it's caught me out before too: when none of the items are ticked, they all look ticked.

**Comment by WMRamadan** [comment]
@willmcgugan I see the PR was closed and noted it was not required. Although I still argue that this can get confusing for some users at times!
