### ISSUE TITLE
[Tree] Make TreeNode an immutable Sequence to allow for walking the tree

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1398]
Especially to allow some initial "just so" setup of a `Tree`, but also to make it easy to write code to walk a `Tree`, it would be useful to have public access to the `children` of a `TreeNode`.

**Comment by nitzan-shaked** [comment]
👍 I just needed this for writing code that "focuses" the tree on a specific node, collapsing all nodes other than one specific node. In my use-case I get only the *names* of the nodes (labels), not the nodes themselves, along them path; so have to traverse children.

**Comment by willmcgugan** [comment]
Making the list public invites a few problems. A dev might expect to be able to extend, remove etc and the tree to update accordingly.

I think we should provide for the use-case of iterating children, and walking a sub-tree without exposing the list.

**Comment by willmcgugan** [comment]
I'm thinking perhaps we should make TreeNode a Sequence, to allow for iterating. This would allow for walking a tree while not exposing internals.
