### ISSUE TITLE
[Tree] Add `NodeHighlighted` message 

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1400]
Currently the `Tree` widget sends out a message when a node is selected (that is, when there's a mouse click on a node, or the user presses <kbd>Enter</kbd> on a nide), when a node is expanded, and when a node is collapsed. Something that seems to be missing though is a message when a node is highlighted. This would allow other widgets to react to the cursor (that is, the node highlight) moving though the tree without needing to watch something like `Tree.cursor_line`, giving this sort of effect without needing to click on a node or expand it, etc:

https://user-images.githubusercontent.com/28237/208420917-bd7f5789-4345-48dd-932b-298004895988.mov

**Comment by darrenburns** [comment]
Just a note to say that ListView has similar behaviour, so we should be mindful to keep naming and semantics consistent with that :)
