### ISSUE TITLE
[Tree] Review the type of some `TreeNode` parameters within `Tree`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1401]
One or two instances of a `TreeNode` parameter within `Tree` are typed `TreeNode` rather than `TreeNode[TreeDataType]`, resulting in some type warnings. Review and potentially update.

**Comment by nitzan-shaked** [comment]
True and quite annoying when working with strict typing. It happens in more than one place. Specifically for Tree (and a small number of other things), I just proposed #1456

**Comment by willmcgugan** [comment]
Check and merge @nitzan-shaked 's PR for this.

**Comment by davep** [comment]
Mostly rendered moot by #1456.
