### ISSUE TITLE
Allow Binding descriptions to change

### ISSUE THREAD

**Issue by antoniovazquezblanco** [Textualize/textual#1410]
I would love to have an interface to change binding descriptions. An example would be keybinding for a toggle featue such as dark mode. It would be nice to show a binding displaying "[t] Toggle to dark theme" and when pressed show "[t] Toggle to light theme".

I would love to implement the feature if some pointers are given. Currently learning how to use textualize.

My intuition would be to change the binding object to allow reactive objects in the binding object and change the Footer class to return a renderable instead of caching the text...

Im I on the right path?

Thank you!

**Comment by willmcgugan** [comment]
We had planned to do something like this.  Honestly not sure what the best API would be yet. Could you post some psuedo-code for your proposal?

**Comment by antoniovazquezblanco** [comment]
Added a work in progrees PR to look into this:

https://github.com/Textualize/textual/pull/1412

**Comment by willmcgugan** [comment]
This is planned for the near future.
