### ISSUE TITLE
Improve error message when value `none` is in a list of text styles

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1420]
When you provide an illegal value for the CSS rule `link-style`, you get a helpful message displaying all legal values, saying that `text-style` expects a space-separated list of those.

If you set `text-style: bold italic reverse` it works fine.

If you set `text-style: none bold italic reverse` you are being silly, but there is no real reason for this to fail (I think). Yet, the error we get is 

```py
StyleSyntaxError: unable to parse 'none' as color; 'none' is not a valid color
```

To repro:

```py
from textual.app import App

class MyApp(App):
    DEFAULT_CSS = "* { text-style: bold italic none }"
```

**Comment by willmcgugan** [comment]
This is because the parsing is handle by Rich with does expect a color. But you're right, we can do better. Text-style doesn't take a color so we shouldn't complain about it.

I think the solution is to validate that this attribute contains only the supported text styles.
