### ISSUE TITLE
Request: Text-wrap attribute for the Input widget

### ISSUE THREAD

**Issue by trentwirth** [Textualize/textual#1424]
Hi there!

I've been using textual the past week and built a timestamping notes app. Thanks so much for building this tool, it's awesome!

I was wondering if it would he possible to add a `text-wrap` attribute to the Input widget, such that as text was typed it would wrap down (start on another line below) as opposed to have text continue to flow to the right. I think this would be a nice feature for larger input boxes - like the one I'm thinking of using :) 

This might be a big feature request and I know you have a lot to do! My app will work without this feature, but I thought it would be a good question to put into the issue-ether.

If textual is already capable of this, please point me in the right direction! I totally could have missed it.

Cheers,
Trent

**Comment by davep** [comment]
A `TextArea` widget is [on our roadmap](https://textual.textualize.io/roadmap/#widgets).

**Comment by trentwirth** [comment]
Oh wow, totally missed that. Thank you!
