### ISSUE TITLE
[Tree] Provide some sort of `expand/collapse_all` facility for `TreeNode`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1430]
It's currently possible to [`expand`](https://textual.textualize.io/api/tree_node/#textual.widgets._tree.TreeNode.expand) a `TreeNode`, but that only expands the direct children. It would be useful if it had an optional parameter, or another method akin to `expand_all`, so that every expandable  descendent node is expanded.

**Comment by willmcgugan** [comment]
Also `collapse_all`
