### ISSUE TITLE
DataTable cursor_type changes have no effect

### ISSUE THREAD

**Issue by antoniovazquezblanco** [Textualize/textual#1431]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed

Yes

Please give a brief but clear explanation of the issue.

Changing datatable `cursor_type` does not change cursor behaviour in a datatable. In fact, the cursor type variable is not used inside the datatable class.

What Operating System are you running on?

Currently Linux but seems to affect all platforms.

Feel free to add screenshots and/or videos. These can be very helpful!

If you can, include a complete working example that demonstrates the bug. Check it can run without modifications.
This is a partial screenshot of the demo below:
![imagen](https://user-images.githubusercontent.com/304193/209221954-1b1ae3a6-5be2-444c-8ddd-37283eefb455.png)

An example can be found in the following link:
https://github.com/antoniovazquezblanco/textual/blob/bugfix/datatable_cursor/examples/datatable_cursor.py

**Comment by willmcgugan** [comment]
Cursor type is not implemented yet. It will be soon. Bear with us!

**Comment by antoniovazquezblanco** [comment]
Nice! Do you want me to create a PR with the datatable cursor example? :)

**Comment by willmcgugan** [comment]
Thanks, but not right now. We can’t merge until we’ve updated the widget.

**Comment by antoniovazquezblanco** [comment]
Will preserve the branch until then. If you want me to create a PR to another branch where your may perform some testing just ping me. Awesome work, thank you!

**Comment by antoniovazquezblanco** [comment]
Found https://github.com/Textualize/textual/pull/1387.
