### ISSUE TITLE
[Tree] It would be beneficial to separate Tree node selection from node toggling

### ISSUE THREAD

**Issue by vsajip** [Textualize/textual#1433]
Currently, clicking on a `Tree` node label both selects the node and toggles its expansion state. It would be useful if node expansion was restricted (or restrictable on a per-`Tree` basis) to clicks on the expansion handle (triangle), and node selection to the label only.

**Comment by willmcgugan** [comment]
Try `auto_expand=False`

**Comment by davep** [comment]
> Try `auto_expand=False`

Unfortunately that seems to stop the ability to expand a tree without the mouse (at least by default -- presumably it's possible for the developer to add their own binding). Is that by design or shall I raise an issue to this effect?

**Comment by willmcgugan** [comment]
If the dev doesn't want selecting the label to expand the node automatically, then they would need to expand it manually. Unless we have some "expand but don't select" binding.

**Comment by davep** [comment]
> Unless we have some "expand but don't select" binding.

Aye, I'm thinking it might be an idea to split `action_select_cursor` out a bit so the keyboard binding can always expand, but the `_on_click` call to `action` has the desired `auto_expand` effect? Upshot being that, with `auto_expand=False`, a mouse click won't expand, but a tap of <kbd>Enter</kbd> will, the latter being a bit more deliberate as it's the cursor keys that change selection when in keyboard mode.

At least: playing with the permutations there right now that *feels* right under my fingers.

**Comment by mathman1618** [comment]
> Upshot being that, with `auto_expand=False`, a mouse click won't expand, but a tap of Enter will, the latter being a bit more deliberate as it's the cursor keys that change selection when in keyboard mode.

I'm adapting some code to the new `Tree` widget at present; I find `auto_expand=False` to work well with an additional binding (`Space`) for toggling node expansion.  I think separating selection and expansion is preferable to having `Enter` both select and expand a node.

Example use case: I have a tree view tied to a hexdump.  Selecting a node (single click or `Enter`) highlights a corresponding region in the hexdump, while clicking the triangle next to the node label or hitting `Space` toggles the node.  In this scenario I want to be able to select a node without necessarily collapsing its portion of the tree.

(It's also possible to enable a double click to toggle a node by hacking the `Driver` class a bit.)

**Comment by willmcgugan** [comment]
Maybe fixed, or possible some other way. To investigate.
