### ISSUE TITLE
[Tree] Allow for the complete repopulation of a `Tree`.

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1437]
Slightly related to #1396 in that to do it now the ability to change a `TreeNode.label` would be required. At the moment it is possible to use [`Tree.clear`](https://textual.textualize.io/api/tree/#textual.widgets._tree.Tree.clear) to clear all the nodes *under the root node*, but there appears to be no public interface for totally clearing a `Tree` and repopulating it from scratch -- other that performing a `remove` on the widget itself and then a `mount` of a fresh instance.

A use case for this would be if the `Tree` is being used to view the content of a file in a structured way, and you want the user to be able to load in a new file.

**Comment by willmcgugan** [comment]
Maybe add a root label option to `clear()`
