### ISSUE TITLE
Allow datatables to be 100% width and columns to grow to that width

### ISSUE THREAD

**Issue by antoniovazquezblanco** [Textualize/textual#1442]
It would be nice to have a datatable be able to span to a 100% width.
If column width is manually specified, that should be the width, otherwise, remaining space is ocupied by expanded columns that take up the slack.

**Comment by AlexAltea** [comment]
The conversation here does not answer the original question by @antoniovazquezblanco. The bot mistakenly thought this  was about DataTable alignment, and now Google results are pointing here...

Anyway, I have the same issue as OP: I can't find a way to stretch tables to occupy 100% of the width.

**Comment by davep** [comment]
The `DataTable` is still being enhanced and updated and this issue is one thing still to be addressed.

**Comment by willmcgugan** [comment]
Flexible columns are planned.

**Comment by TomJGooding** [comment]
> Flexible columns are planned.

So "this issue is one thing still to be addressed"? It's your project, but I don't understand why this was closed.

**Comment by willmcgugan** [comment]
There are lots of features we plan to add to the Data Table, including flexible columns. The issue was closed because it’s easier for us to track the work offline.
