### ISSUE TITLE
Initial value of `Input` not rendered upon `.mount`

### ISSUE THREAD

**Issue by mrossinek** [Textualize/textual#1443]
### Have you checked closed issues?

Yes, I did not find anything similar.

### Please give a brief but clear explanation of the issue.

The value of `Input(value=value)` does not get rendered when an `Input` is added via `.mount`.
It only gets rendered after an additional character is entered.

### What Operating System are you running on?

Arch Linux; Kernel 6.0.12-arch1-1

### Feel free to add screenshots and/or videos. These can be very helpful!

Screenshot of the snippet below which yields `Input` as part of `.compose`:
![screenshot_1672054846](https://user-images.githubusercontent.com/21973473/209545060-c975d955-8fad-471d-8e4d-94ca4989b813.png)

Screenshot of the snippet below which tries to `.mount` an `Input` widget after pressing `p` to trigger the action:
![screenshot_1672054926](https://user-images.githubusercontent.com/21973473/209545134-e809f69f-0c74-4684-908d-e7cb94273b63.png)
After inserting an additional character the provided `value` gets rendered properly:
![screenshot_1672054933](https://user-images.githubusercontent.com/21973473/209545166-830f74ac-5dac-405d-a059-d13d67d7e7fb.png)

### If you can, include a complete working example that demonstrates the bug. Check it can run without modifications.

Here is a *working* example based on `.compose`:
```python
from textual.app import App, ComposeResult
from textual.widgets import Input


class Prompt(App):

    def compose(self) -> ComposeResult:
        prompt = Input(value=":")
        yield prompt
        prompt.focus()


if __name__ == "__main__":
    Prompt().run()
```

And here is the *broken* example trying to use `.mount`:
```python
from textual.app import App
from textual.widgets import Input


class Prompt(App):

    BINDINGS = [
        ("p", "prompt", "Prompt"),
    ]

    def action_prompt(self) -> None:
        prompt = Input(value=":")
        self.mount(prompt)
        prompt.focus()


if __name__ == "__main__":
    Prompt().run()
```

### Solution Ansatz

I am suspecting the problem to lie in the `Input` widget itself. Specifically this widget has a `view_position` attribute which I believe to be the source of the error. Upon mounting this attribute has value `2` and it gets reset to `0` once inserting a character.
You can verify this with the following patch:
```patch
diff --git a/src/textual/widgets/_input.py b/src/textual/widgets/_input.py
index c2bfa638..21d67772 100644
--- a/src/textual/widgets/_input.py
+++ b/src/textual/widgets/_input.py
@@ -41,6 +41,7 @@ class _InputRenderable:
             segments = Segment.adjust_line_length(segments, width)
             line_length = width

+        yield str(input.view_position)
         line = line_crop(
             list(segments),
             input.view_position,
```

**Comment by davep** [comment]
To narrow this down a little: it does get rendered on `mount`, but it doesn't get rendered if it is mounted and then focused.

It does work as expected if the action is made into an async action and then the mount is awaited before setting focus:

```python
    async def action_prompt(self) -> None:
        prompt = Input(value="This is a test")
        await self.mount(prompt)
        prompt.focus()
```

**Comment by mrossinek** [comment]
> To narrow this down a little: it does get rendered on `mount`, but it doesn't get rendered if it is mounted and then focused.
> 
> It does work as expected if the action is made into an async action and then the mount is awaited before setting focus:
> 
> ```python
>     async def action_prompt(self) -> None:
>         prompt = Input(value="This is a test")
>         await self.mount(prompt)
>         prompt.focus()
> ```

This is indeed the case, thank you very much! In fact, `.focus()` is not required meaning that the value gets rendered correctly as long as one `await`s the `.mount` :+1: 
I suspect this is the intended behavior? If so, then I think this can be closed (a documentation update may be needed somewhere though :thinking:)

**Comment by davep** [comment]
> I suspect this is the intended behavior? If so, then I think this can be closed

When we get a moment I'd like to double-check this behaviour with @willmcgugan and @darrenburns first. It feels like it's behaving correctly, but I'd like their final say.
