### ISSUE TITLE
TextLog's Clear Function Problem

### ISSUE THREAD

**Issue by regexbuster** [Textualize/textual#1447]
Have you checked closed issues? Yes

Please give a brief but clear explanation of the issue.

When I call the clear method on a Text Log it clears the Text Log. However, when I write to the text log it produces the old information on the Text Log not the new data I have written.

What Operating System are you running on?

Ubuntu Linux (20.04) (It's WSL so it might be slightly different but I doubt it)

Feel free to add screenshots and/or videos. These can be very helpful!
https://youtu.be/BvxS5zAvZ4o

If you can, include a complete working example that demonstrates the bug. Check it can run without modifications.

**Comment by willmcgugan** [comment]
Can I see your code?

**Comment by willmcgugan** [comment]
Please give v0.8.2 a try

**Comment by regexbuster** [comment]
Thanks! If it's still broken I can send my code over. I'm on holiday though so I won't be by my computer till later.
