### ISSUE TITLE
issue with focus float input crash widget 

### ISSUE THREAD

**Issue by xalteropsx** [Textualize/textual#1463]
![image](https://user-images.githubusercontent.com/103671642/210159318-ef7563c0-627f-489a-83e4-6247c7eb7d94.png)

**Comment by davep** [comment]
@xalteropsx Do you think you could give a little more context to this please? An explanation of what you're doing and how the above error was arrived at would be useful. Ideally with a small self-contained example of the problem that can be tested by others.

**Comment by xalteropsx** [comment]
it happen when i left input with float value it happen just 1 time i assume i create ticket again if i notice what causing it
