### ISSUE TITLE
Bindings shortcuts

### ISSUE THREAD

**Issue by xoolive** [Textualize/textual#1470]
It would be nice to allow synonyms in Bindings key combinations:
`"ctrl+c"`, `"ctrl-c"`, `"C-c"`, *maybe more?* would read the same for many developpers. 

To be added by @willmcgugan

**Comment by willmcgugan** [comment]
Not a bug. I don't think we should have multiple overlapping conventions for keys. "^d" would be "ctrl+d" in Textual.

Run `textual keys` if there is any doubt about what a key combo will produce.
