### ISSUE TITLE
[Tree] Consider adding a "node is selected but widget doesn't have focus" styling to `Tree`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1471]
Coming from https://github.com/Textualize/textual/discussions/1375 -- it would be helpful if there was a way to style a `Tree` such that a selected node retains some sort of highlight, even when the `Tree` itself doesn't have focus. It'll be common that a `Tree` will drive the population of some other widget, which might be capable of being focused, and when the user tabs into that widget it would make sense that the `Tree` is still capable of making it clear which node is the selected one.

**Comment by nitzan-shaked** [comment]
I do this today with:

```
#my-tree:focus > .tree--cursor {
    background: $secondary-lighten-1;
}
```

isn't that the intended way?

**Comment by davep** [comment]
In my use of `Tree`, at least with Textual v0.9.1, when the `Tree` loses focus the selected node isn't highlighted in any way. Consider this (deliberately) garish take on the above for my AST viewer widget:

```diff
diff --git a/textual_astview/widgets/astview.py b/textual_astview/widgets/astview.py
index 8389086..6007a6a 100644
--- a/textual_astview/widgets/astview.py
+++ b/textual_astview/widgets/astview.py
@@ -38,6 +38,14 @@ class ASTView( Tree[ Any ] ):
         width: 1fr;
     }

+    ASTView > .tree--cursor {
+        background: red;
+    }
+
+    ASTView:focus > .tree--cursor {
+        background: green;
+    }
+
     .astview--def-name {
         text-style: italic;
         color: #888;
```

Tree with focus:

![Screenshot 2023-01-03 at 12 10 35](https://user-images.githubusercontent.com/28237/210354871-0b85f9f9-6995-4064-9eba-e2c017843834.png)

Tree without focus:

![Screenshot 2023-01-03 at 12 10 40](https://user-images.githubusercontent.com/28237/210354905-fcf31a7d-a74a-48bf-ac79-219201a88580.png)

But even if that did work I feel there's a good case to be made for this to be built into the way that `Tree` works as it would be in keeping with other similar frameworks down (CHUI and GUI) down the years.

**Comment by mathman1618** [comment]
+1 for this.  If another widget causes a new `Tree` node to be selected (via firing an `Event`, say) and the `Tree` is not in focus then the selected node may (will?) scroll into view but it will not be highlighted or otherwise visually indicated.  I think the current behavior is not intuitive ("Why did my tree suddenly scroll when it isn't selected?").

(ASIDE: The current behavior of `Tree` seems geared toward a "tree as a control" point of view---doing stuff in the tree may affect other widgets, but other widgets don't affect the tree.  I'd like to use `Tree` as a widget with two-way communication, able to both send and receive events.  For example, another Widget should be able to request that a particular node be selected, expanded, collapsed, etc.)

**Comment by davep** [comment]
@mathman1618 Some of what you're asking for is already possible

> I'd like to use Tree as a widget with two-way communication, able to both send and receive events. For example, another widget should be able to request that a particular tree node be selected, expanded, collapsed, etc.

Selected would be to use `Tree.select_node`, expanded would be to use `TreeNode.expand` and collapsed would be to use `TreeNode.collapse`. Consider this little example:

```python
from textual.app     import App, ComposeResult
from textual.widgets import Header, Footer, Tree, TreeNode
from textual.binding import Binding

class Sandbox( Tree[ None ] ):
    pass

class TreeSandbox( App[ None ] ):

    CSS = """
    Tree {
        width: 1fr;
    }
    """

    BINDINGS = [
        *[ Binding( str( n ), f"select( {n} )", f"Select {n}" ) for n in range( 10 ) ],
        *[ Binding( f"f{n}", f"expand( {n} )", f"Expand {n}" ) for n in range( 10 ) ]
    ]


    def __init__( self ):
        super().__init__()
        self.nodes: list[ TreeNode[ None ] ] = []

    def compose( self ) -> ComposeResult:
        yield Header()
        self.sandbox = Sandbox( "Tree Sandbox" )
        yield self.sandbox
        yield Footer()

    def on_mount( self ) -> None:
        for node in range( 10 ):
            self.nodes.append(
                self.sandbox.root.add( f"This is parent node {node}" )
            )
            for child in range( 10 ):
                self.nodes[ -1 ].add_leaf(
                    f"Child node {child}"
                )
        self.sandbox.focus()

    def action_select( self, node: int ) -> None:
        self.sandbox.select_node( self.nodes[ node ] )

    def action_expand( self, node: int ) -> None:
        if self.nodes[ node ].is_expanded:
            self.nodes[ node ].collapse()
        else:
            self.nodes[ node ].expand()

if __name__ == "__main__":
    TreeSandbox().run()
```

BTW, this is getting a wee bit of topic for this particular issue, but I wanted to make sure you saw the reply. Do feel free to carry this on as a Q&A discussion if you wish.
