### ISSUE TITLE
Setting the `value` of an unfocused `Input` causes the first character to not display

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1477]
Consider this code:

```python
from textual.app     import App, ComposeResult
from textual.widgets import Header, Footer, Input

class InputPopulate( App[ None ] ):

    CSS = """
    Screen {
        align: center middle;
    }
    """

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Input( placeholder="Data will go here" )
        yield Footer()

    def on_mount( self ) -> None:
        self.query_one( Input ).value = "This is a test value"

if __name__ == "__main__":
    InputPopulate().run()
```

After being run up, the `Input` looks like this:

<img width="248" alt="Screenshot 2023-01-04 at 13 11 11" src="https://user-images.githubusercontent.com/28237/210562690-335d3be2-51d2-4b71-ae61-e3ccc43c206d.png">

once focus is moved to it, however, the full `value` is shown:

<img width="215" alt="Screenshot 2023-01-04 at 13 11 29" src="https://user-images.githubusercontent.com/28237/210562755-a7f2920d-3ec2-402f-a03c-e96ce8e8a251.png">

**Comment by davep** [comment]
Possibly has some overlap with #1443?

**Comment by mrossinek** [comment]
> Possibly has some overlap with #1443?

I had a quick look but that issue does not seem to be related. At least picking a placeholder for `Input` longer than one character still has the same behavior for the entire string as described in that issue (i.e. the first character does not get handled differently)
