### ISSUE TITLE
Clicking a scrollbar sometimes drags it

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1478]
If I click a scrollbar thumb, sometimes the thumb gets locked and I am able to scroll even though I am not actually dragging the scrollbar.

The video below shows this behaviour and the console on the right seems to hint at the fact that, possibly, when the scrollbar thumb is clicked, the release event happens too quickly and the target isn't there for some reason.

https://user-images.githubusercontent.com/5621605/210574337-ba7d2a9e-2eee-4980-b191-b243028ecbce.mp4

```py
from textual.app import App
from textual.widgets import Label

TEXT = """I must not fear.
Fear is the mind-killer.
Fear is the little-death that brings total obliteration.
I will face my fear.
I will permit it to pass over me and through me.
And when it has gone past, I will turn the inner eye to see its path.
Where the fear has gone there will be nothing. Only I will remain.
"""


class ScrollbarApp(App):
    def compose(self):
        yield Label(TEXT * 10)

app = ScrollbarApp()
```

**Comment by rodrigogiraoserrao** [comment]
Yeah, it's not an issue of moving the cursor outside of the window.

I don't think there's anything particular about what I'm doing. Does it matter that I'm "clicking very lightly"? I doubt it...

**Comment by willmcgugan** [comment]
Ah. Managed to reproduce it. A very click tap without haptic force feedback. We're wondering if it is an accessibility feature.

**Comment by willmcgugan** [comment]
Almost certain this is an accessibility feature to allow you to drag scrollbars without holding. A tap produces a mouse down, without a corresponding mouse up. A second tap produces a mouse up.
