### ISSUE TITLE
[DataTable] Row, Column, cursor

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1485]
At the moment we have a cell cursor where the mouse highlights the hovered cell, and you can move the selected cell with the mouse.

We also need an option to do this for rows and columns. And additionally disable any cursor.

We have a `cursor_type` attribute which should be expanded for this use case. This should accept a literal "cell", "row", "column" or "none" to change cursor type.

**Comment by nitzan-shaked** [comment]
I feel like it's a great opportunity to bring up #1387 which has been patiently waiting for almost 3 weeks now...
