### ISSUE TITLE
Consider making the `Focus` and `Blur` events bubble

### ISSUE THREAD

**Issue by nitzan-shaked** [Textualize/textual#1499]
I find myself often subclassing widgets just so I can emit (what I call) `Focused` and `Blurred`. It's needed when an app wants to coordinate between widgets. For example: only when a table is focused do I want to show a side-panel with explanations about the current table row.

**Comment by davep** [comment]
Actually, I just remembered, there is another way (and I've even used it in one of my apps!); see [`DescendantBlur`](https://textual.textualize.io/events/descendant_blur/) and [`DescendantFocus`](https://textual.textualize.io/events/descendant_focus/).

**Comment by willmcgugan** [comment]
I think it makes sense to keep Focus, Blur as not bubbling. There are generally two quite different use cases to know wether you are focused, or a descendant is focused.
