### ISSUE TITLE
[Question] Align Datatable's content and text

### ISSUE THREAD

**Issue by anzhi0708** [Textualize/textual#1520]
Hi, awesome library :3 

As a noob, I have a simple question: how can I put the table right in the middle of the screen?

![image](https://user-images.githubusercontent.com/57821133/211184982-c8a6e7d3-8389-47c6-91c7-d0c4dc5f495d.png)

As you can see above, I set the table's `width` to 100%, but the *content* is still in the left; and the text in each cell are not in the middle neither. Send help :3

**Comment by davep** [comment]
The internal layout of a DataTable still needs a wee bit more work, and should be getting that attention this month.

**Comment by davep** [comment]
I think (not in a position to confirm at the moment) styling the `datatable--cursor` class in CSS should do it.
