### ISSUE TITLE
[CLI] Rename `textual colors` to `textual design` and add `textual colors` for named colors

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1527]
Currently, `textual colors` opens an example app that shows all the design colors. This command could, instead, be called `textual design` and the command `textual colors` could show a list of all the named colours that Textual recognises.

**Comment by willmcgugan** [comment]
I think I'm going to leave it as `textual colors`, but it might grow a tab to show the named colors
