### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by ohle** [Textualize/textual#153]
Hi.

I'm trying to make a textual app that deals with data from stdin. However, if I pipe something to a textual app, it gets consumed as keystrokes. When I consume stdin first (via `sys.stdin.read()`, for example), the app does not process keystrokes (rather, the typed keys get superimposed onto it).

Is there a solution for this?

**Comment by AdrianoKF** [comment]
Sorry for resurrecting this old issue, but would you mind sharing your solution, @ohle? I'm running into a similar issue currently and am banging my head against a wall. Thanks!

**Comment by ohle** [comment]
Trying to reconstruct what I did back then (I don't really use textual anymore, sorry), it was something like

```
content = sys.stdin.read()
sys.stdin = open('/dev/tty', 'r')
```

Then you have the originally piped content in `content`, and re-opening makes it available for keystrokes to textual.

**Comment by AdrianoKF** [comment]
> ```
> content = sys.stdin.read()
> sys.stdin = open('/dev/tty', 'r')
> ```

That did the trick, thanks for the reply! 🙏🏻
