### ISSUE TITLE
Document compound widgets

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1532]
There is a placeholder section in the Widgets guide for "Compound widgets", i.e. widgets which contain widgets.

This section needs to be written,  with a decent example, and an explanation of setting data on child widgets, and responding to event.

We need to emphasize that the parent widget can set attributes, but child widgets should `emit` events.

**Comment by rodrigogiraoserrao** [comment]
This had been tentatively closed by #1818 (now https://mathspp.com/blog/textual-tutorial-build-a-todo-app-in-python) and has been closed by #1952.
