### ISSUE TITLE
Can't build docs without `mkdocs-material` Insiders plugins 

### ISSUE THREAD

**Issue by JoshKarpel** [Textualize/textual#1540]
Looks like the `blog` plugin is Insiders-only, so if I try to build the docs (without Insiders, since I'm not an Insider :) ) I get 
```
$ mkdocs serve
ERROR    -  Config value 'plugins': The "blog" plugin is not installed
Aborted with 1 Configuration Errors!
```

The `mkdocs-material` docs suggest using configuration inheritance to work around this: https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins

**Comment by rodrigogiraoserrao** [comment]
@davep I'm bitten by this too, from time to time. Did your recent incursions into the way the docs are built and configured give you any insight into this?
Is it the case that `docs-build-offline` already works around this (for building the docs) which means a similar `docs-serve-offline` would work here, too?

**Comment by davep** [comment]
@rodrigogiraoserrao `make docs-build-offline` should be the solution to this as it removes anything that needs the insiders' edition (in part this was the motivation behind it).

**Comment by rodrigogiraoserrao** [comment]
Right. So, do you think it makes sense to have a `docs-serve-offline` which would probably be something like

```
.PHONY: docs-serve-offline
docs-serve-offline: clean-screenshot-cache docs-offline-nav
    $(run) mkdocs serve --config-file mkdocs-nav-offline.yml
    rm -f mkdocs-nav-offline.yml
```
