### ISSUE TITLE
A Widget with focus that is hidden keeps focus if there are no other focusable Widgets

### ISSUE THREAD

**Issue by jspv** [Textualize/textual#1565]
If a widget has focus and the .visible property is set to False *and* there are no other focusable widgets, focus stays with the now removed Widget any bindings for the removed widget stay active even though it is removed.  

I believe the correct behavior should be that focus should be set to None if there are no longer any focusable widgets, this will appropriately cause the bindings for the removed widget to also be removed.

Note: If there is another widget that can receive focus when the in-focus Widget is removed, the focus will move to that widget and the bindings from the removed widget go away as expected.  This issue only appears when there are no other focusable widgets available.

**Comment by davep** [comment]
Script to help test/recreate this:

```python
from textual.app      import App, ComposeResult, RenderResult
from textual.widgets  import Header, Footer, Label
from textual.reactive import reactive

class MyLabel( Label, can_focus=True ):

    BINDINGS = [
        ( "up", "move(1)", "Up" ),
        ( "down", "move(-1)", "Down" )
    ]

    counter = reactive( 0 )

    def render( self ) -> RenderResult:
        """Render the content of the widget."""
        return f"{self.counter=}"

    def action_move( self, direction: int ) -> None:
        self.counter += direction

class Issue1565App( App[ None ] ):

    BINDINGS = [
        ( "s", "show", "Show" ),
        ( "h", "hide", "Hide" ),
    ]

    CSS = """
    Screen {
        align: center middle;
    }

    MyLabel {
        text-align: center;
    }

    MyLabel.hidden {
        display: none;
    }

    MyLabel:focus {
        border: round $primary;
    }
    """

    def compose( self ) -> ComposeResult:
        yield Header()
        yield MyLabel()
        yield Footer()

    def on_mount( self ) -> None:
        self.query_one( MyLabel ).focus()

    def action_show( self ) -> None:
        self.query_one( MyLabel ).set_class( False, "hidden" )

    def action_hide( self ) -> None:
        self.query_one( MyLabel ).set_class( True, "hidden" )

if __name__ == "__main__":
    Issue1565App().run()
```

As mentioned in the description above, hiding the widget leaves it focused and with the bindings still around. On the other hand, if you tweak this code to add another widget that can get focus, it all works as expected.

**Comment by davep** [comment]
Giving this a retest with textual v0.34.0 and I can't recreate the issue any longer.
