### ISSUE TITLE
Refactor widgets imports to allow importing of related objects

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1589]
We have a module `__getattr__` in `widgets` which allows us to have a nice namespace for widgets.

For instance:

```python
from textual.widgets import DataTable
```

The problem with this is that some widgets have related objects that are required if you wish to subclass the widgets. Currently the only way to import these objects is with something like the following:

```python
from textual.widgets._data_table import Row
```

Some highly-coupled objects, such as messages and events. can go inside the widget class itself. For instance we have `DirectoryTree.FileSelected` but there remains some objects and symbols for which that doesn't work.

The proposed solution is for the widget classes to drop their underscore prefix, so you could import a related object like this:

```python
from textual.widgets.data_table import Row
```

This inevitably means that the `DataTable` has two imports, which can be problematic. To solve this we can prefix the class name with an underscore, which we drop in the lazy import machinary. Which means that the following would work in tandem:

```python
from textual.widgets import DataTable
from textual.widgets.data_table import Row
```

But the following will *not* work.

```python
from textual.widgets.data_table import DataTable
```

**Comment by willmcgugan** [comment]
@darrenburns to comment

**Comment by darrenburns** [comment]
@willmcgugan This looks exactly like what I had in mind.

**Comment by davep** [comment]
Taking a look at this, I noticed that this would have a bit of a knock-on effect on type-hinting and the like within Textual itself, and would also longer-term result in a greater maintenance load when it comes to adding and updating widgets. In an "offline" chat with @willmcgugan and @darrenburns I've suggested and we've decided to go with a slightly different approach.

We'll keep everything as it is right now, and the "support classes" that are needed by developers using Textual will be imported and reexported from non-underscore-prefixed files that live parallel to their widget counterpart. So, to support this example:

```python
from textual.widgets import DataTable
from textual.widgets.data_table import Row
```

`widgets/_data_table.py` remains as it is, and a `data_table.py` is created which simply imports `Row` and makes it available. This should keep the current general widget lazy-loading approach while also making it easy and clear to declare "public support classes" for widgets.

**Comment by davep** [comment]
Testing this, an example of the above in action:

```python
>>> from textual.widgets.data_table import DataTable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DataTable' from 'textual.widgets.data_table' (/Users/davep/develop/python/textual/src/textual/widgets/data_table.py)
>>> from textual.widgets.data_table import Row
>>> from textual.widgets.data_table import Column
>>> Row
<class 'textual.widgets._data_table.Row'>
>>> Column
<class 'textual.widgets._data_table.Column'>
>>> from textual.widgets import DataTable
>>> DataTable
<class 'textual.widgets._data_table.DataTable'>
>>>
```

**Comment by davep** [comment]
It's worth noting, there's a version of this for `TreeNode` at the moment, and this does go via the lazy-loading mechanism. Given that `TreeNode` isn't a widget and what's happening there is akin to what we're doing here, it might be an idea to deprecate that form of importing of `TreeNode` and switch to this approach. Allowing:

```python
from textual.widgets.tree import TreeNode
```

or even, perhaps ideally:

```python
from textual.widgets.tree import Node
```
