### ISSUE TITLE
[DataTable] Component style `datatable--even-row` doesn't get applied

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#1593]
Applying a component style `datatable--even-row` has no effect.

It works for odd rows, so need to investigate why it doesn't work for even only.

**Comment by willmcgugan** [comment]
I suspect that the even rows show the style of the parent. Which is enough to create the zebra stripes.

I'm wondering if we need the even row at all, given you could modify the widget style to achieve the same effect.

Although it might be worth it for sake of completeness...

**Comment by darrenburns** [comment]
Yeah, I think you're right. I'm pretty sure that was the behaviour I was seeing. It's not really required, but yeah, I think it's a bit nicer to have it than to not have it.

**Comment by darrenburns** [comment]
Closing as I can't reproduce this now.
