### ISSUE TITLE
DataTable - scrollbar doesn't update when show_header is set to False

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#1594]
When you show_header=False (meaning >=1 additional cells are now "free" at the bottom of the widget), the scrollbar still goes into those cells, as if the header is there.

**Comment by willmcgugan** [comment]
It doesn't update at all? Wow. Guess we have never tested that.

**Comment by darrenburns** [comment]
@willmcgugan I've added more info now. The scrollbar still works, just seems like it doesn't account for the new "size" of the DataTable (the size minus the header size).

**Comment by willmcgugan** [comment]
Ah. Sounds like a miscalculation of the `virtual_size`
