### ISSUE TITLE
A container with `grid` layout can't be set to `height: auto`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1597]
Following on from [this discussion](https://github.com/Textualize/textual/discussions/1571), and from checking with @willmcgugan about the intended working, it looks like there's a bug where you can't make a `grid` container `height: auto`. As a test bit of code:

```python
from typing             import Type
from textual.app        import App, ComposeResult
from textual.containers import Container, Horizontal, Vertical, Grid
from textual.widgets    import Header, Footer, Label
from textual.binding    import Binding

class GridHeightAuto( App[ None ] ):

    CSS = """
    #test-area {
        height: auto;
        border: solid red;
        height: auto;
    }

    Grid {
        grid-size: 3;
    }
    """

    BINDINGS = [
        Binding( "g", "grid", "Grid" ),
        Binding( "v", "vertical", "Vertical" ),
        Binding( "h", "horizontal", "Horizontal" ),
        Binding( "c", "container", "Container" )
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Vertical( Label( "Select a container to test (see footer)" ), id="sandbox" )
        yield Footer()

    def build( self, out_of: Type[ Container | Grid | Horizontal | Vertical ] ) -> None:
        self.query( "#sandbox > *" ).remove()
        self.query_one( "#sandbox", Vertical ).mount(
            Label( "Here is some text before the grid" ),
            out_of( *[ Label( f"Cell #{n}" ) for n in range( 9 ) ], id="test-area" ),
            Label( "Here is some text after the grid" )
        )

    def action_grid( self ):
        self.build( Grid )

    def action_vertical( self ):
        self.build( Vertical )

    def action_horizontal( self ):
        self.build( Horizontal )

    def action_container( self ):
        self.build( Container )

if __name__ == "__main__":
    GridHeightAuto().run()
```

The results are, `Container`:

<img width="922" alt="Screenshot 2023-01-17 at 15 41 40" src="https://user-images.githubusercontent.com/28237/212943127-f3c6171a-2b86-4db7-b512-1313b8fb86bd.png">

`Vertical`:

<img width="922" alt="Screenshot 2023-01-17 at 15 42 21" src="https://user-images.githubusercontent.com/28237/212943281-3e9dfd20-d99b-46ef-aae8-71b12a4eeafc.png">

`Horizontal`:

<img width="922" alt="Screenshot 2023-01-17 at 15 42 56" src="https://user-images.githubusercontent.com/28237/212943385-1cc7193e-539c-49a4-93e9-33652bbf3652.png">

And `Grid`:

<img width="922" alt="Screenshot 2023-01-17 at 15 43 15" src="https://user-images.githubusercontent.com/28237/212943474-5ea4950d-64c1-4cb9-8bcd-61ede2f64487.png">

It would appear that all container layouts handle `height: auto` fine expect for `grid`.

**Comment by shuckc** [comment]
I've run into this issue where a grid layout with a dynamic number of rows is problematic to handle, as `height: auto` collapses it. In my case and with a hand from @davep I calculated a desired height dynamically and applied it to the grid in python code. https://gist.github.com/shuckc/5ec3c4fed5844252fb2f9bb91d63bf88
