### ISSUE TITLE
Extend `ListView`/`ListItem` so that `ListItem` can have typed data

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1603]
Much like with `Tree` and `TreeNode`, it would be useful it `ListView` and `ListItem` had a `data` property so that some sort of data can be associated with an item in the list, and that it can be fully-typed.

**Comment by kratsg** [comment]
This would be really helpful. Right now, I have something like this:

```python
class InstitutionItem(ListItem):
    """An Institution ListItem."""

    __slots__ = ("value",)

    def __init__(self, institution: dict[str, Any]):
        super().__init__(Label(institution["name"]))
        self.value = institution
```

which means that on an emitted thing, I can catch a message like so

```
    def on_list_view_selected(self, message: ListView.Selected) -> None:
        """When institution has been chosen."""
        self.institution_details.institution = message.item.value
```

which works fine practically speaking, but the issue is just figuring out how to get typing working correctly as you will have typing errors:

```
src/itkdb_browser/tui.py:91: error: "ListItem" has no attribute "value"  [attr-defined]
```

Probably something with contravariance needed here to make this work more flexibly.

**Comment by davep** [comment]
Looking into this this morning and, the more I experiment with it, the less it seems necessary (or generally workable). While it would be possible to "type" the `ListView` to say what sort of `ListItem` it's going to wrap, this isn't going to help in the event handlers anyway as the event handler is there for *all* `ListView`s that might be a child of the code that's defining the handler.

Given the code above, probably the easiest and best way to type it would be:

```python
def on_list_view_selected(self, message: ListView.Selected) -> None:
    """When institution has been chosen."""
    assert isinstance(message.item, InstitutionItem)
    self.institution_details.institution = message.item.value
```

or:

```python
def on_list_view_selected(self, message: ListView.Selected) -> None:
    """When institution has been chosen."""
    if isinstance(message.item, InstitutionItem)
        self.institution_details.institution = message.item.value
```

Of course, if the handler is going to handle more than one `ListView`, each potentially with a different type of `ListItem`, you'd want to do some if-handling of the sender's `id` first and then use `isinstance` on the `item` to make the type checker happy.

More generally, having look at this and realised there's little utility to this, closing as investigated.
