### ISSUE TITLE
Remove race conditions from integration tests

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1606]
Our tests sometimes fail because of the way Textual updates widgets concurrently in asyncio tasks.

We are currently unable to predict when input has been processed in order to test the state. To workaround this we introduce sleeps, but this is unsatisfactory and a bit brittle.

We need to consider a way of making the final state more predictable. Ideally without compromising the ability for widgets to update independently.

**Comment by ofek** [comment]
what is the mechanism? I'd like to use this in my own tests

**Comment by willmcgugan** [comment]
You'll get it in the next version if you are using `run_test`. Basically it wait until the CPU is idle before running tests, to make things more predictable. You can also explicitly call `wait_for_idle`

**Comment by ofek** [comment]
thanks!

**Comment by rodrigogiraoserrao** [comment]
Some tests still feel flaky, e.g., `tests/test_data_table.py::test_datatable_message_emission`
