### ISSUE TITLE
Ttextual should use system terminal colors for cyan, etc.

### ISSUE THREAD

**Issue by khughitt** [Textualize/textual#1609]
In [Rich](https://github.com/Textualize/rich), using a term color such as "cyan" or "red" uses user's terminal colors, making it consistent with a users theme, e.g.:

![2023-01-18-095152_1723x1410_scrot](https://user-images.githubusercontent.com/125001/213257987-62435458-7ac5-4dc8-a30c-ae975ccd14a8.png)

Textual, however, ignores the system settings and just prints the static colors, e.g.:

```py
from textual.app import App, ComposeResult
from textual.widgets import Static

class ColorTest(App):
    """A Textual app to manage stopwatches."""

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        self.a = Static("cyan")
        self.b = Static("magenta")

        yield self.a
        yield self.b

    def on_mount(self) -> None:
        self.a.styles.background = "cyan"
        self.b.styles.background = "magenta"

if __name__ == "__main__":
    app = ColorTest()
    app.run()

```

Results in:

![2023-01-18-100711_1690x64_scrot](https://user-images.githubusercontent.com/125001/213260350-b46f5ab2-bfe2-4d41-87e8-a648d801f9d7.png)

In order to create textual apps that are consistent with a user's theme and also to be consistent with rich, it would be great if it also followed this convention, or at the very least, provided a mechanism via variables, etc. to use those colors.

**System info**

- Arch Linux
- Python 3.10.9
- Textual 0.8.1
- Rich 12.6.0
- [kitty](https://github.com/kovidgoyal/kitty)

**Comment by khughitt** [comment]
Thanks! And apologies for missing that -- I spent checked the docs and github issues, but overlooked the FAQ.

> Asking users to simply pick a better theme is not a good solution, since not all users will know how.

This is fair, but one could also design apps in such a way that ANSI colors are not the default, but rather something the user can "opt-in" for.

> This means that in the future you will be able to modify the core colors to blend in with your chosen terminal theme.

Do you mean by manually overriding specifying theme colors / overrides? If so, that would probably be enough for one to create a [pywal](https://github.com/dylanaraps/pywal) template to help keep Textual in-step with other parts of the system.

--

Just to be clear and so it doesn't seem like I'm just complaining, I would also like to say that I am incredibly grateful for your & other's work on both Rich and Textual! I've been using Rich for a while now and love it, and Textual is the first modern-looking TUI framework I have seen in any language. So, thank you. :pray:

**Comment by davep** [comment]
> Thanks! And apologies for missing that -- I spent checked the docs and github issues, but overlooked the FAQ.

Don't worry, you didn't miss it. While it has been a FAQ it wasn't in the FAQ when you asked so your question [prompted Will to add it to the actual FAQ](https://github.com/Textualize/textual/commit/e0043f21e25d053145b397aa8372d257c6833580).

**Comment by khughitt** [comment]
Ha okay thanks. That makes me feel like a little bit less of a jerk :)
