### ISSUE TITLE
textual push_screen/pop_screen breaks app functionality (for example, with ListView)

### ISSUE THREAD

**Issue by kratsg** [Textualize/textual#1632]
code

```python
from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import Button, Footer, Header, Label, ListItem, ListView, Static

class LoginScreen(Screen):

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Event handler called when login button is pressed."""
        button_id = event.button.id
        if button_id == "login":
            self.app.login()
            event.stop()

    def compose(self) -> ComposeResult:
        yield Horizontal(
            Vertical(
                Button("Login", id="login", variant="primary")
            )
        )


class MyList(ListView):
    """A widget to display a list of items."""
    def load_items(self) -> None:
        self.clear()
        for item in range(10):
            print(f'{item}')
            self.append(ListItem(Label(f'test {item}')))


class Browser(App):
    """App"""

    BINDINGS = [("q", "exit", "Quit"), ("d", "toggle_dark", "Toggle dark mode")]

    DEFAULT_CSS = """
    Browser > Static {
        content-align: center middle;
        background: crimson;
        border: solid darkred;
        height: 1fr;
    }

    .column {
        width: 1fr;
    }
    """

    def __init__(self) -> None:
        super().__init__()
        self.my_list = MyList(classes="column")

    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.dark = not self.dark

    def action_exit(self) -> None:
        """An action to exit."""
        self.exit()

    def login(self) -> None:
        """Called when the LoginScreen has logged in."""
        self.pop_screen()
        self.my_list.load_items()

    def on_mount(self) -> None:
        """Call after entering application mode."""
        self.push_screen(LoginScreen())

    def compose(self) -> ComposeResult:
        """Call to compose the app"""
        yield Header()
        yield Footer()
        yield Horizontal(
            self.my_list, Vertical(Static("column 2"), classes="column")
        )
```

If you run this app, you'll see some behavior that breaks:
- bindings don't work (`d` for dark mode, `q` for quit)
- `ListView` isn't updating when `ListView.append` is called (but you can confirm via `textual console` and `textual run --dev script.py` that the `print` statements are executing, so the `load_items()` is being called)
- `ListView` behavior also seems broken (clicking, arrow keys, highlighting all do not work)
- CTRL+C doesn't quit the program and something is still hanging around

If you modify this code to drop the push/pop screen:

```python
    def login(self) -> None:
        """Called when the LoginScreen has logged in."""
        #self.pop_screen()
        self.my_list.load_items()

    def on_mount(self) -> None:
        """Call after entering application mode."""
        #self.push_screen(LoginScreen())
        self.login()
```

then things work as expected (bindings work, `ListView` works and gets populated, CTRL+C also works). This example was more or less adopted from the dialog portion of the [Screens guide](https://textual.textualize.io/guide/screens/).

<details>
<summary>Textual Diagnostics</summary>

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.10.1 |
| Rich    | 13.2.0 |

## Python

| Name           | Value                                                  |
|----------------|--------------------------------------------------------|
| Version        | 3.8.6                                                  |
| Implementation | CPython                                                |
| Compiler       | Clang 10.0.1 (clang-1001.0.46.4)                       |
| Executable     | /Users/kratsg/.pyenv/versions/itkdb-browser/bin/python |

## Operating System

| Name    | Value                                                                                           |
|---------|-------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                          |
| Release | 22.1.0                                                                                          |
| Version | Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.19) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=135, height=60 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 135                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 60                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

</details>

**Comment by davep** [comment]
I can confirm that something's adrift here. Tested this app with 0.9.1 and it worked as you seem to intend; with 0.10.1 I'm seeing the problems you mention.

**Comment by davep** [comment]
The issue here seems to be with pushing an instance of a screen. If I declare the screen in `SCREENS` everything works fine again:

```python
--- kratsg_orig.py	2023-01-21 10:26:58
+++ kratsg.py	2023-01-21 10:21:06
@@ -47,6 +47,10 @@
     }
     """

+    SCREENS = {
+        "login": LoginScreen
+    }
+
     def __init__(self) -> None:
         super().__init__()
         self.my_list = MyList(classes="column")
@@ -66,7 +70,7 @@

     def on_mount(self) -> None:
         """Call after entering application mode."""
-        self.push_screen(LoginScreen())
+        self.push_screen("login")

     def compose(self) -> ComposeResult:
```

**Comment by kratsg** [comment]
In the meantime, I think I can go with declaring the `login` as a screen for the lifetime of the app (that should be ok in this instance).

**Comment by kratsg** [comment]
Hold up, I've managed to get it working if I do

```diff
--- kratsg_orig.py	2023-01-21 10:26:58
+++ kratsg.py	2023-01-21 10:21:06
@@ -47,6 +47,10 @@
     }
     """

+    SCREENS = {
+        "login": LoginScreen()
+    }
+
     def __init__(self) -> None:
         super().__init__()
         self.my_list = MyList(classes="column")
@@ -66,7 +70,7 @@

     def on_mount(self) -> None:
         """Call after entering application mode."""
-        self.push_screen(LoginScreen())
+        self.push_screen("login")

     def compose(self) -> ComposeResult:
```

instead. So I think there's possibly something with the `self.push_screen(LoginScreen())` that seems to be breaking things?

**Comment by davep** [comment]
You should find that that's essentially the same as what I suggested above.

**Comment by kratsg** [comment]
Ahh, I misunderstood your comment. My bad. you're right :)
