### ISSUE TITLE
Rethink naming/logic behind `Scalar.percent_unit`

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1642]
In the wake of fixing #1406 it became apparent that the attribute `percent_unit` of `Scalar` could be reviewed.

Things to consider:

 - `percent_unit` is currently typed as `Unit`, but `percent_unit` seems to serve as an indication that says what a relative dimension is relative to, which means `percent_unit` can never take all of the values of the enum `Unit`, which suggests `percent_unit` should take a more restricted type;
 - for the same reason as above, `percent_unit` could maybe be renamed to `relative_to`;
 - `percent_unit` seems to indicate it is a reference for when `unit` is `Unit.PERCENT`, however when the unit is a fraction, `percent_unit` also keeps track of the dimension (width or height) that the fraction is related to. This may be superfluous, because fraction units are relative to each other; and
 - `percent_unit` is only relevant for some values of `unit`, so consider setting it to `None` when it is not needed (and making `None` the default value).

**Comment by willmcgugan** [comment]
I don't think this is much of an issue in practice.
