### ISSUE TITLE
Adding a caret (^) to the front of a binding breaks the binding instead of changing it to a ctrl binding. Bindings do not support multiple modifier keys. Common modifier key shortcuts do not seem to work.

### ISSUE THREAD

**Issue by jk1ng** [Textualize/textual#1645]
Hi! Textual looks really awesome, but I'm really new to it (literally just doing the tutorial).

Ran into what looks like some bugs:

# Issues:

1. Using the caret (`^`) in front of a binding key breaks that binding. (bug)
2. Using more than one modifier key breaks that binding. (bug)
3. Explicitly writing out 'shift+key' breaks that binding (bug)
4. Other shortcuts for writing out binding keys do not work as "expected" (possibly more enhancement than bug)
5. Documentation expanding on how bindings work is either not present or not easily discoverable; are the only possible keybinds present in `textual/keys.py:8`? (enhancement)

# Steps to reproduce:

Follow the tutorial at
https://textual.textualize.io/tutorial/#the-app-class - but for a binding, try using the caret `^` symbol in front of a binding.

For example:

```python
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer


class StopwatchApp(App):
    """A Textual app to manage stopwatches."""

    BINDINGS = [
        ("v", "toggle_dark", "Toggle dark mode"), # Works
        ("W", "toggle_dark", "Toggle dark mode"), # Works
        ("^x", "toggle_dark", "Toggle dark mode"), # Doesn't work
        ("ctrl+shift+y", "toggle_dark", "Toggle dark mode"), # Doesn't work
        ("ctrl+z", "toggle_dark", "Toggle dark mode") # Works
        ("shift+d", "toggle_dark", "Toggle dark mode"), # Doesn't work
    ]

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Footer()

    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.dark = not self.dark


if __name__ == "__main__":
    app = StopwatchApp()
    app.run()
```

# Expected behavior:

I didn't really find the right search phrases to locate documentation for common modifier key representations, but this seems to conform with my memory of what I've seen:

https://www.autohotkey.com/docs/v1/lib/Send.htm

Specifically:

- `^` for CTRL key
- `!` for ALT key
- `+` for SHIFT key (this can be problematic, but maybe this can be reserved for only unambiguous cases)
- `#` for OS key (Windows key, Command key - not sure if/how-well this would work)

# Diagnostics

### Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.10.1 |
| Rich    | 13.2.0 |

### Python

| Name           | Value               |
|----------------|---------------------|
| Version        | 3.11.0rc2           |
| Implementation | CPython             |
| Compiler       | GCC 12.2.0          |
| Executable     | /usr/bin/python3.11 |

### Operating System

| Name    | Value                                                      |
|---------|------------------------------------------------------------|
| System  | Linux                                                      |
| Release | 5.19.0-29-generic                                          |
| Version | #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:14:09 UTC 2023 |

### Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

### Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=204, height=55 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 204                  |
| is_terminal    | False                |
| encoding       | utf-8                |
| max_height     | 55                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
Textual probably should throw an error for an unrecognised binding, yes. We will Add that to a future version.

The key system is documented in the [Input section of the guide](https://textual.textualize.io/guide/input/).

Textual can only detect only the keys encoded by the terminal, which is a subset of the keys the OS can detect. And some keys and combinations are reserved by the OS. Textual's naming conventions reflect that.
