### ISSUE TITLE
DataTable - cell_selected needs to be clicked twice to get the correct event.value

### ISSUE THREAD

**Issue by machiiine** [Textualize/textual#1674]
Hello,

I've tested the feature "on_data_table_cell_selected" but I cannot get it work smootly.

```
from textual.app import App
from textual.widgets import DataTable, Static


class Test(App):

    def compose(self):
        """Create child widgets for the app."""
        yield DataTable(id='data_table')
        yield Static("Empty", id="selected_menu")

    def on_mount(self):
        table: DataTable = self.query_one('#data_table', DataTable)
        table.add_columns("Header 1", "Header 2")
        table.add_row("FOO 1", "FOO 2")
        table.add_row("BAR 1", "BAR 2")

        table.styles.height = 4

    def on_data_table_cell_selected(self, event):
        selected_menu: Static = self.query_one('#selected_menu', Static)
        selected_menu.update(event.value)


if __name__ == "__main__":
    app = Test()
    app.run()
```

The static label is not always updated with the click entry.

**2nd request:**
I'm new to Python and Textual. I would have expected that I could add a method "on_data_table_cell_selected" on a child class of DataTable as described in the doc of the class CellSelected. But I m not able to get the event trigger within a class "ChildDataTable(DataTable)" for example.
I'm able to get "on_click" on the other hand. Is it expected ?

ps: nice tool !

**Comment by rodrigogiraoserrao** [comment]
Hey there, thanks for opening this issue.

Sorry if we were unresponsive but we've been working hard on `DataTable`, among other things.
As for the issue you reported (similar to #1668), it has been fixed in the meantime.

As for your second request, that was because of an unrelated issue that was also fixed (in #1738, I believe).
