### ISSUE TITLE
Create documentation standards

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1678]
Come up with a set of standards for the documentation.

Things to tackle:

 - How are docstrings written for
   - modules
   - regular functions
   - classes
   - methods
   - properties
   - attributes
 - Can we find a way for vanilla attributes and `@property` attributes to be documented _and shown_ in the same way?
 - Can we distinguish read-only properties from read/write properties?
 - Do we need to tweak/fork/PR `mkdocstrings` because of some weird edge cases?
 - What language identifier do we use for CSS? (`sass`, the parser is more lenient and gives better results)
 - Are sentences in tables capitalised or not?
 - Are sentences in tables punctuated or not?
 - (to be updated as more things come to mind)

---

Do not add explicit type hints to docstrings in the sections `Args`, `Returns`, and `Attributes` (see [PR 1599](https://github.com/Textualize/textual/pull/1599))
The types for arguments and return values are taken from the type hints in the signature.
The types of attributes are inferred, either by the type hinting of properties, or by explicit type hints when assigning to the attribute in `__init__`.

Example:

```py
class MyClass:
    """This is my docstring:

    Attributes:
        my_attr: This is what my_attr does.
    """

    def __init__(self, *args, **kwargs):
        self.my_attr: float = ...
```

---

# Standard

### Textual CSS code blocks

Textual CSS code blocks are formatted with `sass` because its parser is more lenient than that of CSS and generally produces better results for Textual CSS.

## Documentation build process

Textual documentation is built by MkDocs, configured in the file `mkdocs.yml`, and its pages live in the folder `docs`.
Our source code documentation depends on the plugin `mkdocstrings` and its Python handler, which in turn depend on `griffe`.

**Comment by rodrigogiraoserrao** [comment]
See the wiki page https://github.com/Textualize/textual/wiki/documentation-standards

**Comment by darrenburns** [comment]
@rodrigogiraoserrao This is still in "For Review". Should we move it over to "Done" now?

**Comment by willmcgugan** [comment]
Yep. It's an ongoing thing, bit we have a good foundation.
