### ISSUE TITLE
When Command+V in Input widget it's pasting the information twice

### ISSUE THREAD

**Issue by fbrodrigorezino** [Textualize/textual#1687]
I'm using mac. 

https://user-images.githubusercontent.com/93132522/215340934-529fb76e-c1fd-4000-a8f9-c4612d93a903.mp4

**Comment by willmcgugan** [comment]
Please post the output of `textual diagnose`

**Comment by davep** [comment]
This would seem to be a duplicate of #1657 which [is fixed for the next release](https://github.com/Textualize/textual/pull/1660).
