### ISSUE TITLE
Extend the `Input` word-oriented movement/edit actions to take `password` into account

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1692]
Having added a collection of new actions to `Input` in #1676, look at likely modifying the way they work a little to take into account the `password` setting for `Input`. The thinking here being that when `password` is `True` it makes the input look like a single word, so perhaps also treat it as if it were a single word too. So, when `password` is `True`, moving word left/right will just go to home/end, and deleting left/right a word will just delete all left/right.

**Comment by willmcgugan** [comment]
Moving this ToDo. Feels like we should do this on one go.
