### ISSUE TITLE
[Docs] Review Events reference

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1702]
The Reference > Events pages don't look great at the moment.

**Comment by willmcgugan** [comment]
Guess this is stale. @rodrigogiraoserrao Any suggestions for more improvements? Feel free to close if not.

**Comment by rodrigogiraoserrao** [comment]
This isn't stale, I was waiting for this to end up in TODO.
The docs pages on events are too short to warrant a structure similar to the widgets reference.
My suggestion is that we drop the sections that are written by hand or pulled directly from the API and instead just show the API.

E.g., the `Key` event would go from what's on the left to what's on the right.

![Screenshot 2023-11-22 at 17 27 31](https://github.com/Textualize/textual/assets/5621605/e4214575-0ea2-4ec6-b57f-681189f9d852)

We could possibly leave _just_ the initial sentence that describes the event in English.
