### ISSUE TITLE
Cannot gracefully exit app before the screen is refreshed

### ISSUE THREAD

**Issue by ofek** [Textualize/textual#1707]
1. Attempting to exit with ctrl+c during `on_mount` does nothing
2. In the following snippet if you comment that out on the main app and begin yielding the Widget, then exiting will properly stop rendering the screen but the process will actually continue to run and requires another ctrl+c to actually exit

```python
import asyncio

from textual.app import App
from textual.widgets import Footer, Header, Static


class Widget(Static):
    async def on_mount(self):
        self.call_after_refresh(self.__on_mount)

    async def __on_mount(self):
        await asyncio.sleep(9000)


class BlockingApp(App):
    def compose(self):
        yield Header()
        # yield Widget('foo')
        yield Footer()

    async def on_mount(self):
        await asyncio.sleep(9000)


if __name__ == '__main__':
    app = BlockingApp()
    app.run()
```

## Textual Diagnostics

<details>

### Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.10.1 |
| Rich    | 13.2.0 |

### Python

| Name           | Value                                                            |
|----------------|------------------------------------------------------------------|
| Version        | 3.11.1                                                           |
| Implementation | CPython                                                          |
| Compiler       | MSC v.1934 64 bit (AMD64)                                        |
| Executable     | C:\Users\ofek\AppData\Local\Programs\Python\Python311\python.exe |

### Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19044 |

### Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

### Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=199, height=42 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 199                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 42                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |
</details>

**Comment by willmcgugan** [comment]
The ctrl+c key handler is processed in the App's [message queue](https://textual.textualize.io/guide/events/#message-queue). The call to sleep is preventing further messages from being processed, and hence the ctrl+c key is never handled.

If the call to sleep is a proxy for a long running method, you should consider running it in a Task or a thread.

**Comment by ofek** [comment]
Okay then I'm assuming we can't fix 1, but can we please fix 2 if possible? That is the one I'm actually encountering.

**Comment by willmcgugan** [comment]
On macOS I can't exit at all (with the widget) because the app is sleeping for 9000. Which is what I would expect. 

Have't tried on Windows, but if a second ctrl+C exits, that is likely done at the system level.

Perhaps explain what real-world problem you are solving?

**Comment by ofek** [comment]
I'm trying to populate a widget outside of the mounting phase. Specifically, I am adding a ListItem for every response we get from a service. The exact requests are known shortly after runtime but actually performing them takes a few minutes.

**Comment by willmcgugan** [comment]
For long running methods consider using `run_in_executor` which will run your request in a thread. But you can't await it, as you would still block the event queue.

This is really an async issue that can be solved with various techniques from the asyncio library. But it is a common enough requirements, that we plan to add some kind of wrapper or syntactical sugar to make it easier.

**Comment by ofek** [comment]
Is there a way maybe to increase the priority of key bindings i.e. they go first in the queue or an option to make it so?

**Comment by willmcgugan** [comment]
Bindings have a priority flag which allows the App the opportunity to process them first. But no "queue jumping" per se.

It wouldn't actually help to jump the queue if something in the app is stuck in a message handler. I'm afraid there is no way to avoid the need for having long running tasks in a thread or Task.

**Comment by ofek** [comment]
okay thanks! do you have an example?

**Comment by willmcgugan** [comment]
Afraid not. I'm sure there will be plenty on StackOverflow etc.

**Comment by ofek** [comment]
Oh I mean I'm familiar with this but was asking specifically in the context of Textual e.g. best practices for where to set this up (`on_mount`?), will exiting automatically stops the threads, etc.

**Comment by ofek** [comment]
For posterity, this is what I ended up doing and seems to be working fine:

```python
import asyncio

from textual.app import App
from textual.widgets import Footer, Header, Label, ListItem, ListView

class ListWidget(ListView):
    def on_mount(self):
        super().on_mount()

        self.call_after_refresh(self.populate)

    def populate(self):
        asyncio.create_task(self.__populate())

    async def __populate(self):
        for i in range(10):
            await self.append(ListItem(Label(str(i))))
            await asyncio.sleep(1)

class LazilyLoadedApp(App):
    def compose(self):
        yield Header()
        yield ListWidget()
        yield Footer()

if __name__ == '__main__':
    app = LazilyLoadedApp()
    app.run()
```

**Comment by willmcgugan** [comment]
> Oh I mean I'm familiar with this but was asking specifically in the context of Textual e.g. best practices for where to set this up (`on_mount`?), will exiting automatically stop the threads, etc.

Not currently. But starting a concurrent thread on on_mount, and shutting it down in unmount seems like a reasonable approach.
