### ISSUE TITLE
Checkbox and radio buttons

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1725]
We currently have a widget called "Checkbox" which has a nice animation. We need a "RadioButton", but I can't think of a way to render it which would look consistent with Checkbox. So I think we should do the following:

- Rename `Checkbox` to `Switch`. 
- Add a Checkbox and a RadioButton widget with very similar interface to Checkbox.

The checkbox / radio button can use a simpler way of rendering with unicode characters. Something like this:

`[✓]`
`(⦿)`

I'm thinking that there should be an ON state in green. and an OFF state in a faded monochrome to match the colors used in Checkbox.

## Considerations

Maybe there should be a combined check/radio widget and the difference is a switch? Conceptually they are very similar.

There doesn't need to be any single select logic for radio buttons just yet. We will have a radio button box at some point, which enforces only one being selected at a time.

**Comment by willmcgugan** [comment]
Yeah, nice solution!

**Comment by davep** [comment]
I like the convention of `[ ]` and `( )`; this is long-established. At least as far back as the days of TurboVision, and still common these days. For example from Midnight Commander:

<img width="487" alt="Screenshot 2023-02-06 at 16 16 36" src="https://user-images.githubusercontent.com/28237/217027858-2612e6a7-135d-4f13-9858-88f61608e0c0.png">

**Comment by davep** [comment]
I've raised #1746 to track the rename of `Checkbox` to `Switch` as an issue in its own right. I feel this should be done as and tracked as a two-parter.

**Comment by davep** [comment]
> The checkbox / radio button can use a simpler way of rendering with unicode characters. Something like this:
>
> [✓]
> (⦿)

In offline conversation today Will has indicated that we should go with a slightly different approach to what was initially suggested. While keeping the same dimensions as the above, the choice now is to make it appear that the char characters will be 2x2 in a 3x2 space using half blocks on the left and right and an appropriate character in the middle. Initial choices being something like:

## Checkbox

`▐X▌`

Where the character in the middle's background will be the foreground colour of the left/right frame, and the left frame will be `▐` (U+2590, right half block) and the right frame will be `▌` (U+258C, left half block). The central character still to be decided (*I'll update this comment when I've picked an appropriate choice*).

The decision has also been made that the central character should never change, instead using colour alone to indicate checked/unchecked.

## Radio button

`▐O▌`

Where the character in the middle's background will be the foreground colour of the left/right frame, and the left frame will be `▐` (U+2590, right half block) and the right frame will be `▌` (U+258C, left half block). The central character still to be decided (*I'll update this comment when I've picked an appropriate choice*).

The decision has also been made that the central character should never change, instead using colour alone to indicate pressed/unpressed.

All of the above is, of course, subject to change as we trial things and dial this in.

**Comment by rodrigogiraoserrao** [comment]
> The decision has also been made that the central character should never change, instead using colour alone to indicate [...]

Isn't this a bad accessibility feature?

**Comment by davep** [comment]
> Isn't this a bad accessibility feature?

That was my feeling about it too.

**Comment by willmcgugan** [comment]
Accessibility for whom?

If its for color blind there will be plenty of contrast between the off and on states.

**Comment by rodrigogiraoserrao** [comment]
I thought of colour-blind people, yes. Generally, people with bad eyesight might also have a harder time distinguishing between the two if the only difference between the two states is colour.

Maybe I'm missing what we get from this decision and that/those advantage(s) will offset my worries.

**Comment by willmcgugan** [comment]
Most colorblind folk can see some color. But as long as there is sufficient contrast, which we can insure there will be, it should be easy to see.
