### ISSUE TITLE
Popping screens with buttons appears to prevent keyboard input

### ISSUE THREAD

**Issue by oscarrobertson** [Textualize/textual#1733]
Hi, it seems like something to do with screen popping via button actions has been broken by the upgrade from 0.9.1 ->0.10.1.

I ran into this writing my own code, but it actually appears reproducible from the demo code on modal screens here: https://textual.textualize.io/guide/screens/#modal-screens

To reproduce on version 0.10.1 just press q to open the quit screen, then click the cancel button. When you return to the main screen keyboard input appears to be broken, you won't be able to press q to open the quit screen again.

If you do the exact same on version 0.9.1, you're able to reopen the quit screen as expected.

I've also found that if you pop the screen using key presses, (either using BINDINGS or defining your own `on_event` manually) it also seems to work fine, so something seems very specifically to be the problem with button presses.

I tried to have a dig myself with the console logging and `PYTHONASYNCIODEBUG=1` but nothing pops out!

**Comment by davep** [comment]
Just tested and confirmed with 0.10.1, however I can't recreate with `main`, so I suspect more recent changes have addressed whatever the cause of this was. The most likely candidate is [some work that @willmcgugan did to fix some issues around screens](https://github.com/Textualize/textual/pull/1636).
