### ISSUE TITLE
Make the source for the examples on the front page of the docs easily viewable/discoverable

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1755]
Tweak the [opening page of our documentation](https://textual.textualize.io/) so that the source code for the example applications is as discoverable as possible; either by following the pattern we have for other screenshots in the rest of the docs ([where the screen, source and CSS are available via tabs](https://textual.textualize.io/widgets/button/#example)), or by having a direct link to the source on the repo.

**Comment by TomJGooding** [comment]
Sorry to add to this, but might I also suggest including a short description for each example and the Textual functionalities that they are showcasing? (E.g. dictionary.py is an example app using async handlers to look up word definitions from an api as you type)

**Comment by willmcgugan** [comment]
The examples on the front page are going to change soon.
