### ISSUE TITLE
[FEAT] Add testability of Textual apps to documentation

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#1762]
### Is there an existing issue for this?

- [x] I have searched the open issues

### Description of the feature or enhancement

> Testing leads to failure, and failure leads to understanding
—Burt Rutan

I appreciate this might be outside the scope of this project, but it would be useful for newcomers to TUIs and Textual (like myself) to include a short section in the documentation about how best to approach testing/debugging apps.

Explaining the importance of testing here would be like [teaching grandmother to suck eggs](https://en.wikipedia.org/wiki/Teaching_grandmother_to_suck_eggs)!

This might also help reduce the number of issues/discussions.

**Comment by davep** [comment]
Our documentation is of course still a work in progress, and this along with many other things is on the list of things to be added. The testing framework is only just starting to settle down, so we want to get it working spot on before unleashing it as a fully-supported feature.

Meanwhile though you might be able to learn some handy things by [reading our own tests](https://github.com/Textualize/textual/tree/main/tests).

**Comment by TomJGooding** [comment]
I see the Textual docs now have a [Testing guide](https://textual.textualize.io/guide/testing/)! 🎉

Closed as completed via #3329
