### ISSUE TITLE
Flesh out Pilot

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1764]
The `run_test` and `Pilot` interface is objectively awesome. It needs a few more methods to take it to the next level.

- Simulate mouse movements with `pilot.move_mouse` which takes a destination offset (or selector), and simulates mouse movement over time. We can use this to check hover states.
- `pilot.click` which initiates a simulated click (with modified keys).

Anything else?

**Comment by darrenburns** [comment]
I was thinking a click which takes a selector and clicks relative to it?
If you had a single button on your app you could just do something like click(Button) and it'd click the top left cell of the button. 
It'd make tests more robust as the button can be anywhere and you don't need to worry about it moving e.g. if you add a header. Optionally you'd pass an offset to click a specific place inside the button.

**Comment by willmcgugan** [comment]
Yeah, click with a selector makes sense. Although I had imagined clicking the center of the widget by default rather than the top left.
