### ISSUE TITLE
Adding a View to a ScrollView

### ISSUE THREAD

**Issue by lorenzhawkes** [Textualize/textual#177]
```python
from textual.app import App
from rich.text import Text
from textual.widgets import ScrollView, Static
from textual.views import GridView

class MyApp(App):

    async def on_mount(self):

        grid_view = GridView()
        grid_view.grid.add_column('col1')
        grid_view.grid.add_column('col2')
        for i in range(0, 20):
            grid_view.grid.add_row(f'row{i}', max_size=1)
            grid_view.grid.place(Static(Text(text=f'r{i}-c1')), Static(Text(text=f'r{i}-c2')))

        scroll = ScrollView(grid_view, auto_width=False)

        await self.view.dock(scroll, edge="top")


app = MyApp()
app.run(log="textual.log")
```

It looks like nesting Views inside of other Views is not supported (based on the implementation of the [reflow](https://github.com/willmcgugan/textual/blob/f47b3e089c681275c48c0debc7a320b66a772a50/src/textual/layout.py#L113) in Layout). 

This leads to the GridView having a width and height always equal to 0 so nothing is ever rendered.

Docking `grid_view` in the above example instead of `scroll` works fine.

To be added by @willmcgugan

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
