### ISSUE TITLE
Look at adding explicit import details to the API documentation

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1773]
Consider [this question on Discord](https://discord.com/channels/1026214085173461072/1033754296224841768/1074465926709264434). In the API documentation it's not entirely clear where various functions and classes should be imported from. A hint can be gathered from the URL, but it should be a clear item of information in the API page itself.

**Comment by barisione** [comment]
I think there's another issue here. Most other widgets can be used via `from textual import widgets` and `widgets.SomeWidget`. The exceptions I found after having a very quick look are `Tabs`, `Tab` and `ScrollView`. What do you think?

**Comment by davep** [comment]
`Tabs` and `Tab` aren't supported widgets of Textual (they're a hangover from an older version and need some attention). `ScrollView` is more of a specialised container (so, if anything, would make more sense being imported from `textual.containers`).

But, no matter where these land (and that could be another question to ask or issue to raise at some point), I feel we should address the point of this issue so there's never any confusion about where a class in Textual should be imported from (see also events, bindings, screens, etc...).

**Comment by nmay231** [comment]
Link #2832

**Comment by willmcgugan** [comment]
Closing. I don't think this is relevant now.
