### ISSUE TITLE
`scroll_*` doesn't work immediately after loading a `Syntax` into a `Static`

### ISSUE THREAD

**Issue by barisione** [Textualize/textual#1774]
I'm trying to load a source file into a `Static` and then jump to a line but it looks like `scroll_*` methods are not reliable.

I tried using https://github.com/Textualize/textual/blob/main/examples/code_browser.py and changed `scroll_home` to other functions like `scroll_end` and `scroll_to_region`. If used immediately after creating the widgets and loading a `Syntax` they never seem to work.
After switching files they sometimes work and sometimes not.

This is a minimal reproducer:
```
import os
import tempfile

from rich.syntax import Syntax
from textual import events
from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.geometry import Region
from textual.widgets import Static


class ScrollBugApp(App):
    def compose(self) -> ComposeResult:
        yield Vertical(Static(id="code", expand=True), id="code-view")

    def on_mount(self, event: events.Mount) -> None:
        tmp = tempfile.NamedTemporaryFile("w", delete=False)
        try:
            for i in range(1, 500):
                print(f"Line {i}", file=tmp)
            tmp.close()

            self.query_one("#code", Static).update(
                Syntax.from_path(
                    tmp.name,
                    line_numbers=True,
                    word_wrap=False,
                    indent_guides=True,
                    theme="github-dark",
                )
            )
            self.query_one("#code-view").scroll_to_region(
                Region(y=250, height=20),
                animate=False,
            )
        finally:
            os.unlink(tmp.name)


if __name__ == "__main__":
    ScrollBugApp().run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.10.1 |
| Rich    | 13.3.1 |

## Python

| Name           | Value                                                                     |
|----------------|---------------------------------------------------------------------------|
| Version        | 3.10.1                                                                    |
| Implementation | CPython                                                                   |
| Compiler       | Clang 13.0.0 (clang-1300.0.29.30)                                         |
| Executable     | /Users/bari/.pyenv/versions/3.10.1/envs/undo-core-venv3.10/bin/python3.10 |

## Operating System

| Name    | Value                                                                                             |
|---------|---------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                            |
| Release | 21.6.0                                                                                            |
| Version | Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.18) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=178, height=45 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 178                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 45                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
Cut down to a bare minimum, the issue can be seen here:

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Header, Footer, Static
from textual.binding    import Binding

class ScrollEndApp( App[ None ] ):

    BINDINGS = [
        Binding( str( n ), f"stuff( {n * 20} )", f"Stuff {n * 20}" ) for n in range( 1, 10 )
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Vertical( Static( expand=True ) )
        yield Footer()

    def action_stuff( self, times: int ) -> None:
        self.query_one( Static ).update(
            "\n".join(
                f"This is test line #{n}" for n in range( times )
            )
        )
        self.query_one( Vertical ).scroll_end()

if __name__ == "__main__":
    ScrollEndApp().run()
```

I would imagine that the issue here is that the `update` hasn't had full effect yet, and so the `scroll_end` won't really know how tall the `Static` is. Changing the above code to this:

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Header, Footer, Static
from textual.binding    import Binding

class ScrollEndApp( App[ None ] ):

    BINDINGS = [
        Binding( str( n ), f"stuff( {n * 20} )", f"Stuff {n * 20}" ) for n in range( 1, 10 )
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Vertical( Static( expand=True ) )
        yield Footer()

    def action_stuff( self, times: int ) -> None:
        self.query_one( Static ).update(
            "\n".join(
                f"This is test line #{n}" for n in range( times )
            )
        )
        # NOTE: Save doing the scroll until after the DOM has finished refreshing.
        self.call_after_refresh( self.query_one( Vertical ).scroll_end )

if __name__ == "__main__":
    ScrollEndApp().run()
```

works fine every time.

**Comment by willmcgugan** [comment]
Reasonable enough fix, but  we should consider making this automatic. i.e. calling `scroll_end` does a call to `call_after_refresh`. Otherwise I can see this tripping folk up.

**Comment by willmcgugan** [comment]
Does anything use that bool? Maybe we can drop it.

**Comment by davep** [comment]
I'll do a scan and see.

**Comment by davep** [comment]
Places where the return value of a `scroll_*` method is used in some way (not guaranteed to be an exhaustive list but should be pretty close):

- Use of `scroll_right` [in `Widget._on_mouse_scroll_down`](https://github.com/Textualize/textual/blob/80ae6ce4d90191173697210679af4a3cce2b3b86/src/textual/widget.py#L2581)
- Use of `scroll_down` [in `Widget._on_mouse_scroll_down`](https://github.com/Textualize/textual/blob/80ae6ce4d90191173697210679af4a3cce2b3b86/src/textual/widget.py#L2585)
- Use of `scroll_left` [in `Widget._on_mouse_scroll_up`](https://github.com/Textualize/textual/blob/80ae6ce4d90191173697210679af4a3cce2b3b86/src/textual/widget.py#L2591)
- Use of `scroll_up` [in `Widget._on_mouse_scroll_up`](https://github.com/Textualize/textual/blob/80ae6ce4d90191173697210679af4a3cce2b3b86/src/textual/widget.py#L2595)

Also I misspoke when I said *all* of the `scroll_*` methods return a `bool`; `Widget.scroll_visible` has no return value (internally it already does a `call_after_refresh` on `Widget.scroll_to_widget`) and `Widget.scroll_to_region` returns an `Offset`.

**Comment by davep** [comment]
See also #1897 which actually intersects with this.
