### ISSUE TITLE
Make dock_grid() scrollable

### ISSUE THREAD

**Issue by roniemartinez** [Textualize/textual#178]
First, this is an awesome project. Kudos!

The example in https://github.com/willmcgugan/textual/blob/main/examples/grid_auto.py works when the screen is big and enough to cover the widgets. But when making the terminal smaller or adding more items, the other items are hidden.

![image](https://user-images.githubusercontent.com/2573537/144713911-795e95d8-1e63-4d21-b40c-705ee170d841.png)

![image](https://user-images.githubusercontent.com/2573537/144713971-3d3edbac-4a82-4372-8d5a-af201bd6a082.png)

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
