### ISSUE TITLE
Clearing a DataTable does not clear previously used keys for reuse

### ISSUE THREAD

**Issue by ofek** [Textualize/textual#1806]
I would expect this method https://github.com/Textualize/textual/blob/v0.11.0/src/textual/widgets/_data_table.py#L1007-L1022 to also clear `self._row_locations` always and `self._column_locations` when the `columns` argument is `True`.

Otherwise, one cannot re-create the table using a subset of the previous data.

**Comment by darrenburns** [comment]
Good catch! I'll fix this soon.
