### ISSUE TITLE
[Typing] Add type hint to `sender` in widget messages?

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1813]
The class `Message` defines the attribute `sender` as being of the type `MessageTarget`, which is a fairly generic protocol. Fine.

When writing custom messages, wouldn't it make sense to add an explicit type hint to mark the class variable `sender` as being of the type of the widget within which the message is being defined?

E.g., won't this make sense:

```py
class MyWidget(Widget):
   class MyMessage(Message):

        sender: MyWidget  # Isn't this something sensible to do?

        def __init__(self, sender: MyWidget, ...):
            ...
```

By adding `sender: MyWidget` in the body of the class, IDEs and static checkers will let me make use of `.sender` as of being the type I already _know_ it is.

**Comment by willmcgugan** [comment]
Great in principle. But I suspect that will break typing somewhere. Feels like a LSP violation.

**Comment by davep** [comment]
Perhaps the way to go here would be to make `Message` a generic, so the sub-class can be declared including the type expected for the sender?

**Comment by rodrigogiraoserrao** [comment]
Assuming LSP means Liskov's Substitution Principle, I can't see how that could be true.
A message is defined inside a widget namespace, implying that the sender will be an instance of that type of widget or a subclass of another. If `B` is a subclass of `A` and the sender is typed as `A`, it is fine if the message is sent from `B`.

**Comment by rodrigogiraoserrao** [comment]
Reading [this on the mypy docs](https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides) makes me wonder whether I'm getting things the other way around.
I'll wait for a eureka moment or for someone to enlighten me.

**Comment by rodrigogiraoserrao** [comment]
Work on #1831 seems to suggest there is no issue with LSP.
I request we change this into an enhancement task and add it to the backlog.

**Comment by willmcgugan** [comment]
Ok, feel free to add that.

**Comment by rodrigogiraoserrao** [comment]
This become irrelevant as of #1940.
