### ISSUE TITLE
Investigate an improvement to how the namespace of messages is calculated

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1814]
Consider the following code, where there is a base class for two widgets that share a *lot* in common but have slightly different uses/APIs/reasons-to-exist. They both have a `value` in common and so will have a `Changed` message (consider this almost pseudocode to save me trying out *all* of the details):

```python
class MyBaseWidget( Widget ):

    value: reactive[bool] = reactive( False )

    class Changed( Message ):
        pass

    def watch_value( self ) -> None:
        self.post_message_no_wait( self.Changed() )

class HelloWidget( MyBaseWidget ):
    ...

class GoodbyeWidget( MyBaseWidget ):
   ...
```

To allow for sharing the bulk of the `Changed` message code between the two child classes, it would be useful if they could be declared something like this:

```python
class HelloWidget( MyBaseWidget ):
    class Changed( MyBaseWidget.Changed ):
        pass

class GoodbyeWidget( MyBaseWidget ):
    class Changed( MyBaseWidget.Changed ):
        pass
```

This almost works perfectly, expect that the message handlers that are looked for end up always being called `on_my_base_widget_changed` when we would want them to be `on_hello_widget_changed` and `on_goodbye_widget_changed`. This can be achieved and works perfectly if you do the following:

```python
class HelloWidget( MyBaseWidget ):
    class Changed( MyBaseWidget.Changed ):
        namespace = "hello_widget"

class GoodbyeWidget( MyBaseWidget ):
    class Changed( MyBaseWidget.Changed ):
        namespace = "goodbye_widget"
```

With this setup the parent widget can be "internal" and do almost all of the work and the two child classes can just handle their own differences *and* the events end up with the right names.

So... so far so good, it works fine, there's no issue here.

However, in conversation about this with Will, we believe that the Textual internals that work out the namespace for a given message *should* get the above right without the need to declare the `namespace`.

So the purpose of this issue is, at some point, to dive into [this code or thereabouts](https://github.com/Textualize/textual/blob/ba6c8afac6ffb78dffeab9ebdc7c115fd28cd40b/src/textual/message_pump.py#L54-L61) and see if there's a reason why the `namespace` isn't worked out as we'd expect here.

**Comment by rodrigogiraoserrao** [comment]
Thanks for the thorough message and pseudocode! You made finding the issue and the fix a breeze! PR incoming. 🚀

**Comment by davep** [comment]
Reminder to ourselves that once this is sorted we can tweak the code [for `Checkbox`](https://github.com/Textualize/textual/blob/b0f5c357822c43e9827b05dd6b131cf87c2bb301/src/textual/widgets/_checkbox.py#L17-L18) and [for `RadioButton](https://github.com/Textualize/textual/blob/b0f5c357822c43e9827b05dd6b131cf87c2bb301/src/textual/widgets/_radio_button.py#L24-L25).

**Comment by rodrigogiraoserrao** [comment]
> Reminder to ourselves that once this is sorted we can tweak the code [for `Checkbox`](https://github.com/Textualize/textual/blob/b0f5c357822c43e9827b05dd6b131cf87c2bb301/src/textual/widgets/_checkbox.py#L17-L18) and [for `RadioButton`](https://github.com/Textualize/textual/blob/b0f5c357822c43e9827b05dd6b131cf87c2bb301/src/textual/widgets/_radio_button.py#L24-L25).

On it.
