### ISSUE TITLE
Pilot cannot press key minus

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1815]
The way `App._press_keys` is implemented is flawed in here:

https://github.com/Textualize/textual/blob/ba6c8afac6ffb78dffeab9ebdc7c115fd28cd40b/src/textual/app.py#L830-L842

There is a clear bug because the transformation done on `key` with two consecutive replacements cannot be undone in line 840 with a single replacement.
In particular, the keys HYPHEN-MINUS and REVERSE SOLIDUS show that the underscores that we get after the two consecutive replacements cannot be unambiguously reverted.

On top of that, I have to understand what is the issue with a key that has length 1 and is not "alnum".
For example, `"-"` has length 1, is not "alnum", and could very well be pressed as is. Maybe we want to check if `key.isprintable` instead?

**Comment by rodrigogiraoserrao** [comment]
#1830 reveals another instance of the problematic fake restoration of the original name:

https://github.com/Textualize/textual/blob/be850635c2d764dfa4d45707a0cb92bfd63f355d/src/textual/keys.py#L267

**Comment by ofek** [comment]
I wonder if that explains these intermittent flakes when entering a temporary directory into an Input:

```
>               assert app.config.data['repos'] == {'agent': {'path': path}}
E               AssertionError: assert {'agent': {'p...\tmp8rutnaj'}} == {'agent': {'p...tmp8rut_naj'}}
E                 Differing items:
E                 {'agent': {'path': 'C:\\Users\\ofek\\AppData\\Local\\Temp\\tmp8rutnaj'}} != {'agent': {'path': 'C:\\Users\\ofek\\AppData\\Local\\Temp\\tmp8rut_naj'}}
E                 Use -v to get more diff

C:\Users\ofek\Desktop\code\ddqa\tests\screens\test_configure.py:290: AssertionError
---------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------
press 'C' (char='C')
press 'colon' (char=':')
press 'reverse_solidus' (char='\\')
press 'U' (char='U')
press 's' (char='s')
press 'e' (char='e')
press 'r' (char='r')
press 's' (char='s')
press 'reverse_solidus' (char='\\')
press 'o' (char='o')
press 'f' (char='f')
press 'e' (char='e')
press 'k' (char='k')
press 'reverse_solidus' (char='\\')
press 'A' (char='A')
press 'p' (char='p')
press 'p' (char='p')
press 'D' (char='D')
press 'a' (char='a')
press 't' (char='t')
press 'a' (char='a')
press 'reverse_solidus' (char='\\')
press 'L' (char='L')
press 'o' (char='o')
press 'c' (char='c')
press 'a' (char='a')
press 'l' (char='l')
press 'reverse_solidus' (char='\\')
press 'T' (char='T')
press 'e' (char='e')
press 'm' (char='m')
press 'p' (char='p')
press 'reverse_solidus' (char='\\')
press 't' (char='t')
press 'm' (char='m')
press 'p' (char='p')
press '8' (char='8')
press 'r' (char='r')
press 'u' (char='u')
press 't' (char='t')
press 'n' (char='n')
press 'a' (char='a')
press 'j' (char='j')
```

**Comment by rodrigogiraoserrao** [comment]
It _could_ be related. Notice that there is a character missing from the logged presses and it corresponds to the underscore, for which `unicodedata.name` gives one of those weird names:

```pycon
>>> import unicodedata
>>> unicodedata.name("_")
'LOW LINE'
```

_However_, without further investigation I can't tell.
Can you give me a bit more context into the code block with a failing test that you shared?

**Comment by rodrigogiraoserrao** [comment]
There are contexts in which `_` is used to denote a pause, which is problematic if what you really want is the underscore character!
How do you specify those key presses into the `Input`? If you replace a `_` with `underscore`, does it work @ofek ?

**Comment by ofek** [comment]
That works, thank you!!!
