### ISSUE TITLE
Fix typing for MyPy

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1822]
With the API more stable, we should get Textual passing Mypy.

There are currently 148 errors, but many of them have the same root cause.

It may require a few passes to get all of them. Suggest spending a day on fixing typing, and we will review the situation after.

**Comment by rodrigogiraoserrao** [comment]
Follow-up: see if my suggestion in #1813 breaks typing.

**Comment by rodrigogiraoserrao** [comment]
_Edit_: By the time I picked this up, there were 85 errors.

@darrenburns two issues read:
```
src/textual/_two_way_dict.py:41: error: Incompatible return value type (got "Optional[Value]", expected "Value")  [return-value]
src/textual/_two_way_dict.py:52: error: Incompatible return value type (got "Optional[Key]", expected "Key")  [return-value]
```

To guide my fix, I need to know if the rationale here is that the methods `.get` and `.get_key` never fail?
Or are they supposed to be mirroring `dict.get`? In which case, we probably need to restore the `default: T | None = None` annotation and fix typing in the correct way.

**Comment by rodrigogiraoserrao** [comment]
These have been axed down to around 30 in Python 3.7.
Most of them come from the widget Data Table and interactions with the `TwoWayDict` implemented in `_two_way_dict`. The PR above contains a possible approach but this needs to be validated with @darrenburns.

**Comment by willmcgugan** [comment]
Typing is an ongoing thing. We will have another pass soon.
