### ISSUE TITLE
Bigger and fancier fonts

### ISSUE THREAD

**Issue by dumblob** [Textualize/textual#1842]
To be added by @willmcgugan 

(Is the above line to be preserved for notification purposes?)

### Motivation

Many times in design it is desirable to use different font sizes. There is thousands of ascii art and fancy fonts made out of terminal characters & symbols. Many such "fonts" do not support full Unicode but that is usually not an issue (or at least it is "easy" to create the few missing glyphs for a translated title).

### Envisioned solution

Perhaps change API so that the following fonts can be easily used:
1. FIGlet http://www.figlet.org/
2. https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
3. https://www.asciiart.eu/computers/fonts
4. https://texteditor.com/ascii-art/
5. https://fsymbols.com/generators/carty/
6. https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=Red%20Phoenix&text=Your%20text%20here%20
7. ...

**Comment by willmcgugan** [comment]
I don't think we are going to put this in the core library. But it would make a great extension. We may end up doing it, if the community doesn't get there first.

**Comment by dumblob** [comment]
> I don't think we are going to put this in the core library.

Sounds like a pity (IMHO it would be a killer feature for this lib) but let us see what the community has to say :wink:.

Will you make a preliminary poll on Discord/other_communication_channels?
