### ISSUE TITLE
Allow for empty CSS variable definitions

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1849]
Consider the following CSS snippets:

 1.
```sass
$x: 
* {
    background: red;
}
```

2.
```sass
$x:
* {
    background: $x;
}
```

3.
```sass
* {
    background: red;
}
$x:
```

All three should work with the following behaviour:
 - an empty variable definition is allowed; and
 - setting a style to an empty variable should unset that style.

For example, 2. should unset the background of all widgets.

As of now, 2. and 3. can't be parsed.
2. raises an error regarding an undefined variable and 3. raises an `AttributeError` inside `substitute_references` in `parse.py`.

**Comment by rodrigogiraoserrao** [comment]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

This isn't a trivial fix but it also isn't an impossible one.
If you like puzzles, this might be a good one for you!
Fixing this will likely require toying with the CSS parser in `src/textual/css/parser.py`.

Good luck and have fun!

**Comment by zormit** [comment]
We'll have a look (@eliasdorneles). We're sittting in RB116@EuroPython Sprints.

**Comment by rodrigogiraoserrao** [comment]
Sure thing. Feel free to join us at 103 if you want.

**Comment by eliasdorneles** [comment]
I've noticed that this also breaks:

```
* {
    background: $x;
}

$x: red;
```

@rodrigogiraoserrao is this expected? do the CSS variables need to be declared before they're used?

**Comment by rodrigogiraoserrao** [comment]
I'm not sure if we want to have the ability of using a variable before defining it, but it doesn't shock me that you have to define it before using it.
So, I'd say to worry about the other cases first and then this could come after.

What do you think?
