### ISSUE TITLE
Add a percentage to the border definition to apply an alpha

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1863]
It's often a requirement to set a border that is muted a little, but there is no easy way of applying an alpha to a border if it is not already set.

I think we should add an optional percentage to the border definition, to multiple the borders alpha. Something like the following:

```
border: solid $foreground 50%;
```

**Comment by rodrigogiraoserrao** [comment]
Just to make sure, you _can_ mute the border a little if you bake the alpha value into the colour itself, right?

**Comment by willmcgugan** [comment]
Yeah, you can set a color with alpha. But you apply new alpha to that color.
