### ISSUE TITLE
Add title to CSS borders

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1864]
We should add the ability to render a title (displayed in the top) and a subtitle (displayed in the bottom) to CSS borders. Something akin to Rich panels.

Widget should grow `border_title` and `border_subtitle` attributes, which should accept a str or Text in the setter, and return a Text in the getter.

Additionally, there should be new CSS declaration s:

`border-title-align: <left, center, right>`
`border-subtitle-align: <left, center, right>`

Note that it only makes sense to render a single line in the titles. So we need a little logic to get the first line.

If the line doesn't fit, it should be truncated with ellipsis. The Text object can do this (set no_wrap=True, and overflow="ellipsis")

See panel.py in Rich for inspiration.

**Comment by learnbyexample** [comment]
Yeah, this would be great. In one of my projects, I apply border to a container and use `Label` widget to display a title before the container. Having a `Panel` like experience would be better.

Will there be a subtitle option as well?

**Comment by willmcgugan** [comment]
@learnbyexample Yeah, don't see why not.

**Comment by rodrigogiraoserrao** [comment]
I have a couple of follow-up questions regarding the specs:

 - Suppose the border is blank, none, or hidden:
   - Do we display non-empty titles and subtitles?
   - What if the title or subtitle is empty?
   - What if the title or subtitle is `None`?
 - What is the text colour? The same as the corresponding border edge or the text colour of the widget?
