### ISSUE TITLE
[typing] Method `watch` to watch reactives on other objects isn't typed appropriately

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1865]
Work on #1822 led to a typing issue in `demo.py` in the implementation of the `DarkSwitch`:

https://github.com/Textualize/textual/blob/e3cbaa8dca5a267c4d8b82d016d53e2573b0b7e5/src/textual/demo.py#L205-L209

The method `DOMNode.watch` is typed as receiving a `CallbackType` for the third argument but that assumes the callable has _no_ arguments.
However, because we are setting a watcher, we know it can get up to two arguments, the old/new values.
Thus, typing should be fixed here.

`mypy` doesn't complain because this is a highly dynamic part of the code and it doesn't know enough about it.

Suggested quick fix: type the third argument of `DOMNode.watch` as general `Callable`.
Ideal fix: create a proper type alias for watch methods and use it in the codebase.

**Comment by willmcgugan** [comment]
It's now typed as WatchCallbackType which is more specific.
