### ISSUE TITLE
Button rendering fails for the general label case

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1870]
Consider the first line of the method `Button.render`: https://github.com/Textualize/textual/blob/dc4421e76a782f02f6de8e3fb20512b18c8965d1/src/textual/widgets/_button.py#L219

`self.label` is typed as `RenderableType == ConsoleRenderable | RichCast | str` and _none_ of the three types in the union have a method `copy`.

The tests we have pass because `label` is always a `Text` (which is what we get when we pass a string to the label) and `Text` objects have a method `copy`.

Do we want to restrict buttons to only have `str | Text` labels?

Or how do we fix `Button.render` to work with the general renderables that we say it handles?

**Comment by willmcgugan** [comment]
Yeah, I don't think there is much utility for an arbitrary button renderable. You can import `TextType` from `rich.text` which is a union of `Text` and `str`
