### ISSUE TITLE
Consider making `NodeList` a generic over the type of widgets it holds

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1871]
Right now, the implementation of `_node_list.py::NodeList` is a sequence of widgets.

If we make it a generic over the specific type of widgets it holds, we would get better type safety in `ListView`.

**Comment by willmcgugan** [comment]
The node list holds a widget’s children. Which means it can literally hold any widget type. I don’t think there is any room to make of generic.

**Comment by rodrigogiraoserrao** [comment]
> The node list holds a widget’s children. Which means it can literally hold any widget type. I don’t think there is any room to make of generic.

The built-in type `list` also has the potential to hold _any_ object and sometimes we have lists of ints or strings.
Similarly, `ListView` is always a container of `ListItem`s. It isn't farfetched to assume that some containers in a user's app will have just a bunch of buttons, checkboxes, or some other custom widget.

That's what prompted this question.

**Comment by davep** [comment]
> The built-in type list also has the potential to hold any object and sometimes we have lists of ints or strings.

But those lists are normally created in a very specific context.

Given that `NodeList` is used for `DOMNode._nodes`, and that it's created in `DOMNode.__init__`, how and where do you see `NodeList` been told of any type other than `Widget` in normal use? Like, if someone wants to use a `Vertical` to only ever hold `MyCoolWidget`, how would you see the code working? And how would you then see things like `mount` being typed to work along with that (I've not dived in to look but I'd imagine it would have those sorts of knock-on effects).

**Comment by davep** [comment]
See also RadioSet (earlier this week I was pondering the same issue as with ListView and ListItem). 

Did make me wonder if there is or should be a on_child_mounted sort of event, to allow some checks - or something along those lines.

**Comment by rodrigogiraoserrao** [comment]
> The commit you referenced is probably not the best way forward. It will make the error go away, but the `cast` is invalid because we can't guarantee at runtime that it really will be a `ListItem`. This would still be true if we make NodeList a generic.

Right, it doesn't ensure we have `ListItem`s at runtime.
Neither does any of the static typing our code base has!
My understanding is that our codebase is typed so we can have a pre-flight sanity check.
I don't think we want to validate all the data types all the time during runtime.

If the users use `ListView` properly, then at that point we will have `ListItem` instances and I use the `cast` only to make mypy happy.

As for typing `NodeList`, I see that maybe it won't make a lot of sense.

**Comment by willmcgugan** [comment]
> Right, it doesn't ensure we have ListItems at runtime. Neither does any of the static typing our code base has!

True, but the difference is that a developer can satisfy Mypy for this and it could still break. You can use the `mount` method to add anything to the ListView. In this case, Mypy is correct in complaining. An `assert` may be better, because we can catch the error early, rather than wait for it to blow up in unexpected ways.

A longer term solution may be to add some kind of mechanism to ensure only nodes of a given type may be added.

**Comment by rodrigogiraoserrao** [comment]
Ahhh I see what you mean.
A developer that writes a type-safe program could still break this at runtime if it uses `ListView.mount` to add a non-`ListItem` to the list view. Is that it?

I was pondering on overriding `mount` and specifying that the widget to mount should be a `ListItem` but that would break Liskov's Substitution Principle!

**Comment by rodrigogiraoserrao** [comment]
Closing this for now as I think the discussion has reached a conclusion.
