### ISSUE TITLE
Possible issue with component classes, perhaps mixed with pseudo-classes

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1879]
Coming from [a report on Discord](https://discord.com/channels/1026214085173461072/1033754296224841768/1078807523227881492), it looks like there may be an issue with mixing pseudo-classes and component classes. I've not dived too deeply into this yet, just managed to create an isolated example of misbehaviour, so I'm recording it here at least as a placeholder.

The following code aims to set up a grid of datatables, using CSS to have the focused table have a different cursor colour from an unfocused table:

```python
from textual.app        import App, ComposeResult
from textual.containers import Grid
from textual.widgets    import Header, Footer, DataTable

class Focustest( App[ None ] ):

    CSS = """
    Grid {
        grid-size: 4
    }

    DataTable .datatable--cursor {
        background: #333;
    }

    DataTable:focus .datatable--cursor {
        background: #c0c;
    }
    """

    @property
    def data_table(self) -> DataTable:
        data_table = DataTable[str]()
        data_table.add_columns("Column 1", "Column 2", "Column 3")
        data_table.add_rows(
            [(str(n), str(n * 10), str(n * 100)) for n in range(10)]
        )
        return data_table

    def compose( self ) -> ComposeResult:
        yield Header()
        with Grid():
            for _ in range( 16 ):
                yield self.data_table
        yield Footer()

if __name__ == "__main__":
    Focustest().run()
```

If you run it you'll notice that the cursor colour does change under some circumstances, but not in the way you'd expect.

Tested with 0.12.0 so far; when I get a moment I'll revert to 0.11.1 and see how it worked there.

**Comment by darrenburns** [comment]
Note to self: take a look at `notify_styles_updated`

**Comment by darrenburns** [comment]
Closing - this was fixed in 0.17.0 on March 29 2023.

**Comment by pkazmier** [comment]
Of course, now that I've said that, I can't seem to reproduce again for a screenshot to show you. Will keep trying later today.

**Comment by pkazmier** [comment]
Got some weird behavior happening where mousing over the header rows will leave Column 3 highlighted sometimes.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/747855/231483358-af807e16-671f-4a91-a695-5bd5944845ab.png">

**Comment by pkazmier** [comment]
Just got it to happen again, not sure how yet:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/747855/231485800-f127351c-a5dc-499a-81ec-1943edda62b6.png">

**Comment by pkazmier** [comment]
The Column 3 effect above is easily reproduced.

Position your mouse at left side of the screen hovering over Column 1 of a data table. Then simply move your mouse to the right edge of the screen. Each Column 3 your mouse passes over will remain highlighted.

**Comment by lucasmouilleron** [comment]
Dirty fix for the @davep issue with Cell 0,0 and focus issue:

    def _render_cell(self, row_index: int, column_index: int, style: Style, width: int, cursor: bool = False, hover: bool = False):
        self._row_render_cache.clear()  # dirty fix
        self._line_cache.clear()  # dirty fix
        return super()._render_cell(row_index, column_index, style, width, cursor, hover)

**Comment by darrenburns** [comment]
I believe this should be fixed with https://github.com/Textualize/textual/pull/2304
