### ISSUE TITLE
DataTable "view" of a larger data set

### ISSUE THREAD

**Issue by multimeric** [Textualize/textual#1892]
The `DataTable` seems to have performance issues with about a million cells. If we reduce the number of cells in memory at one time to a fraction of that, and then lazily load new rows as the user scrolls down, plus delete old rows, it seems like we might solve these performance issues. Not entirely sure though because I'm not sure how the implementation works.

The simplest implementation of this might be via a pagination mechanism where the user has to implement `get_chunk() -> Iterable[Row]` and the class handles the loading as the user approaches the end of the current chunk . This would also support viewing external data such as in a database or a remote API and avoid having to load everything into memory.

**Comment by multimeric** [comment]
I note that "Lazy loading API" for DataTable is listed in the Roadmap. I might be able to give implementation a go if one of the maintainers is interested.

**Comment by kdkavanagh** [comment]
Anyone come up with an implementation/workaround for this?  Very interested as well

**Comment by max-arnold** [comment]
Could this be used as an interim solution? https://github.com/tconbeer/textual-fastdatatable

**Comment by willmcgugan** [comment]
This may happen, but not in the short term. A community solution would be great, and we would be happy to help.
