### ISSUE TITLE
Quitting app with ctrl + C starts app again, but just once

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1894]
Exiting an app with ctrl + C will restart it again, but only one time. The second time, the app will exit for good.

MRE:

```py
from textual.app import App


class MyApp(App):
    ...


MyApp().run()
```

The screen flickers when you exit the app the first time. If you run the app with `textual run --dev ...` and open a console, you will see that the console disconnects and connects again.

**Comment by davep** [comment]
Assuming you're always running this with `textual run`? If so it's doing what you ask: it's running it on import and then running it again afterwards.

Perhaps you mean do do this? ;-)

```python
from textual.app import App

class MyApp( App[ None ] ):
    ...

if __name__ == "__main__":
    MyApp().run()
```

**Comment by rodrigogiraoserrao** [comment]
Can we create a "shameful" label and add it to this issue, please?

**Comment by davep** [comment]
/me adds a "Must be almost home time" label
