### ISSUE TITLE
Returning `self` instead of `None` for `Widget` "verb" methods

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1908]
### Discussed in https://github.com/Textualize/textual/discussions/1817

<div type='discussions-op-text'>

<sup>Originally posted by **liancheng** February 16, 2023</sup>
My app has a form-like interface, and bound one key to each widget to set focus and optionally adjust the input, e.g., toggle a switch, move the cursor to the next `ListItem` in a `ListView`, etc.

For `Switch`es, I wrote the following method to achieve this:

```python
def action_toggle_switch(self, selector: str) -> None:
    switch = self.query_one(selector, Switch)
    switch.focus()
    switch.toggle()
```

The fact that both `focus()` and `toggle()` return `None` prevented me from chaining the calls. If they returned `self` instead, the above method can be simplified to:

```python
def action_toggle_switch(self, selector: str) -> None:
    self.query_one(selector, Switch).focus().toggle()
```

I'm not quite sure whether this violates certain well-established Python best practices or conventions, though.</div>

Chatted with @willmcgugan about this and the general feeling is this would be a good thing to do (if done carefully).

**Comment by rodrigogiraoserrao** [comment]
This was implemented in #2102.
