### ISSUE TITLE
Horizontal scrollbar for Markdown Viewer table is overriding the last row

### ISSUE THREAD

**Issue by learnbyexample** [Textualize/textual#1911]
While using the Markdown Viewer, tables requiring horizontal scrollbar seems to be overriding the last row. I'd expect the scrollbar to be added as a new row instead. Used the https://textual.textualize.io/widgets/markdown_viewer/#example (with non-table sections removed) for the demo below:

https://user-images.githubusercontent.com/17766317/222116203-3e02c3f9-ee57-4eb9-b18e-4cc99523dc6a.mp4

**Comment by learnbyexample** [comment]
I just tried adding an empty row at the end, and that's a good enough workaround for me.

**Comment by willmcgugan** [comment]
There's some incoming changes which should fix this.
