### ISSUE TITLE
[Docs] Not all attributes of Tree are documented

### ISSUE THREAD

**Issue by jtyers** [Textualize/textual#1921]
We all know from the (excellent) guide docs that `Tree` has a `root` attribute, which returns the `TreeNode` at the top of the tree.

Yet, the 'cod docs' fail to include this attribute: https://textual.textualize.io/api/tree/#textual.widgets.Tree. Search for `root` and there is no root attribute specifically documented!

I swear I've seen this elsewhere with some other widgets, but this is the first I've caught and written an issue for.

**Comment by davep** [comment]
Documentation is an ongoing project and, coincidentally, that was worked on earlier today: https://github.com/Textualize/textual/pull/1909

**Comment by jtyers** [comment]
How fortuitous! I see you've included `Tree.root` in there so I'll close.
