### ISSUE TITLE
RadioButton.Change event should have a button attribute

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1932]
https://github.com/Textualize/textual/discussions/1931

**Comment by davep** [comment]
It already has a [pressed](https://textual.textualize.io/widgets/radioset/#textual.widgets._radio_set.RadioSet.Changed.pressed) property which is the button that was pressed. Ways to get the information include:

- `event.input` -- the `RadioSet` that sent the message (following the convention set in `Input` and `Switch`)
- `event.input.pressed_button` - the button that is not pressed
- `event.input.pressed_index` - the index of the button that is now pressed
- `event.pressed` - the button that was pressed to cause the event

**Comment by willmcgugan** [comment]
Should be solved by https://github.com/Textualize/textual/pull/1940

**Comment by rodrigogiraoserrao** [comment]
Indeed, it was.
