### ISSUE TITLE
Switcher Widget

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1945]
We need a widget to switch between child widgets. Not sure what we would call it yet.

Essentially a single child would be visible at one time. Setting a reactive attribute to an query selector would make a new pane visible and hide the others.

**Comment by rodrigogiraoserrao** [comment]
Carousel? Gallery?

**Comment by willmcgugan** [comment]
Kind of, but more fundamental than that. Think of it as the foundation of a tabbed widget.
