### ISSUE TITLE
Additional containers

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1957]
We need a few additions / modifications to containers.py

- `Center` to horizontally align contents (width 100%, height auto)
- `Middle` to vertically align contents.
- `Horizontal` should have scrollbars disabled by default
- `Vertical` should have scrollbars disabled by default
- `HorizontalScroll` should have horizontal layout and scrollbars auto
- `VerticalScroll` should have vertical layout and scrollbars auto

**Comment by darrenburns** [comment]
There's some text about whether `Horizontal` and `Vertical` have scrollbars enabled or not in the "Layout" page of the guide. We'll need to make sure we update that page if we change the behaviour.

**Comment by willmcgugan** [comment]
The problem is that people liberally add these containers, but they generally only want a single container to scroll. 

If they mess up the styling, and everyone will first attempt, it can be very confusing when you get a scrollbar you don't want. Because you don't know which container really is scrolling.

I think its easier to design a UI if you have to explicitly say which container(s) should scroll.

**Comment by rodrigogiraoserrao** [comment]
Then, should the default value of `overflow` be `overflow: hidden hidden`?

**Comment by rodrigogiraoserrao** [comment]
Also, do you literally mean for `Center` to align **contents**, or should it just align _children_?
(Ditto for `Middle`.)

**Comment by davep** [comment]
(not answering for Will, of course) I think it would only make sense for it to act on the immediate children What's being spoken about here is sort of a follow on from [this FAQ](https://github.com/Textualize/textual/blob/main/questions/align-center-middle.question.md).

**Comment by willmcgugan** [comment]
> @willmcgugan what non-overflowing version are you going for?
> 
> 1. don't overflow in either direction:
>    
>    * `Horizontal` and `Vertical` set `overflow: hidden hidden`.

This one.


`Center` should align children.

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan I think it is more intuitive if the default styling of `Center`/`Middle` is to have their relevant dimension be `1fr` instead of `100%` to fill all the space available instead of being forcefully 100% of the container.

Let me know your decision and then I am ready to PR this.

**Comment by rodrigogiraoserrao** [comment]
After a quick chat, we agreed we'd set the relevant dimension to `1fr` instead of `100%` or leaving it unset.
