### ISSUE TITLE
Pilot tests incorrectly pass when exception thrown in action method

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#1972]
They pass, but an exception traceback is printed. Textual appears to be catching the exception and printing it, but it doesn't bubble up to the test framework. The test framework therefore passes the test because nothing went wrong from its POV.

I added a `1/0` into a handler for a binding and used `pilot.press` to press the corresponding key. The test passed unexpectedly.

I think we need to make it so that when we’re using run_test, Textual will print the exceptions as normal, but also allow them to bubble up.

**Comment by willmcgugan** [comment]
I'm not sure they can bubble up here. Given that everything is running on independent tasks.

Perhaps what we need to do is reraise those errors from `run_test` when it exits.

Just a suggestion. This needs a bit of an investigation.
