### ISSUE TITLE
TreeNode demo breaks.

### ISSUE THREAD

**Issue by qiuxiafei** [Textualize/textual#199]
By running `python -m textual.widgets._tree_control`, a tree view is expect to expand child nodes on click. But the demo breaks. The following two problems are rout causes:
1. TreeNode._empty should default to `True`, but it's `False` and always `False` then. https://github.com/Textualize/textual/blob/4d94df81e44b27fff52f0e38f4f109212e9e8c8a/src/textual/widgets/_tree_control.py#L46
2. A two arguments are required by `add` but only a single is given at: https://github.com/Textualize/textual/blob/4d94df81e44b27fff52f0e38f4f109212e9e8c8a/src/textual/widgets/_tree_control.py#L324

**Comment by willmcgugan** [comment]
You've found some test code. Files begining with an _ may not run with `python -m`
