### ISSUE TITLE
Remove underscore from press keys

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1994]
The snapshot tests and screenshots used to accept an underscore to insert a pause. This isn't supported anymore. We should remove the underscores from all tests, and the condition in press_keys which catches the underscores.

**Comment by davep** [comment]
Do we want to just simply remove `_`, or do we want to replace most instances with an appropriate `wait:<n>`?

**Comment by willmcgugan** [comment]
The underscore is literally doing nothing now, so they can all go.
