### ISSUE TITLE
ImportError: cannot import name 'Any' from 'typing_extensions'

### ISSUE THREAD

**Issue by dcambie** [Textualize/textual#1995]
Since #1831 textual uses `typing_extensions.Any` (e.g. in [actions.py#L6](https://github.com/Textualize/textual/blame/8cb28b66683fbd186ae57d25582e14d1437fcde5/src/textual/actions.py#L6)).

`Any` was introduced in typing_extensions 4.4.0, (see [changelog](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md)) however, the minimum version of `typing_extensions` required by textual in the pyproject.toml [seems to be 4.0.0](https://github.com/Textualize/textual/blob/8cb28b66683fbd186ae57d25582e14d1437fcde5/pyproject.toml#L45).

This creates the following error when textual is installed in a venv where typing_extensions is already present with version higher than 4.0 but lower than 4.4.

Traceback:
```bash
C:\Users\cambie\PycharmProjects\flowchem\venv\Scripts\python.exe C:\Users\cambie\PycharmProjects\flowchem\docs\_static\tree_figure.py 
Traceback (most recent call last):
  File "C:\Users\cambie\PycharmProjects\flowchem\docs\_static\tree_figure.py", line 1, in <module>
    from textual.app import App, ComposeResult
  File "C:\Users\cambie\PycharmProjects\flowchem\venv\lib\site-packages\textual\app.py", line 50, in <module>
    from . import Logger, LogGroup, LogVerbosity, actions, events, log, messages
  File "C:\Users\cambie\PycharmProjects\flowchem\venv\lib\site-packages\textual\actions.py", line 6, in <module>
    from typing_extensions import Any, TypeAlias
ImportError: cannot import name 'Any' from 'typing_extensions' (C:\Users\cambie\PycharmProjects\flowchem\venv\lib\site-packages\typing_extensions.py)
```

Fixed locally by pip install -U but asking for the obvious fix of bumping the dep. Congrats on the great library btw ;)

**Comment by willmcgugan** [comment]
Thanks, will bump that in the next release.

**Comment by kbd** [comment]
FWIW:

`$ poetry update`

• Updating typing-extensions (4.3.0 -> 4.5.0)

`python -m textual` failed before but works after 👍
