### ISSUE TITLE
Commemorative 2000th issue.

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2000]
🥳  This is a busy repo!

**Comment by rodrigogiraoserrao** [comment]
Cake is on me when @willmcgugan @davep @darrenburns come to Portugal.

Feel free to close this issue after partying for a minute.

**Comment by davep** [comment]
I asked @willmcgugan to raise the next one but he said "Sorry Dave, I'm afraid I can't do that".
