### ISSUE TITLE
Allow command-line option to change development port

### ISSUE THREAD

**Issue by AaronDMarasco** [Textualize/textual#2014]
I couldn't use `textual run --dev` because the server I was on had AV software listening on port 8081.

Luckily a quick `git grep` was able to fix it, but it would be nice to have that as a command-line option.

**Comment by rodrigogiraoserrao** [comment]
Thanks for your suggestion! As soon as #2258 gets merged, you can use the option `--port` with the command `textual console` to specify the port to use.
