### ISSUE TITLE
A self-removed widget can leave the layout unfinished

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2016]
Using the following code, with 0.14.0, hit the <kbd>a</kbd> button a few times to add some buttons. Next, navigate to a button somewhere in the middle of the stack and press it. This will remove the button but not refresh the layout correctly. I'm finding that in some situations it'll leave a hole where the button was, and then refresh properly on the next full interaction; other times it'll leave a "ghost" version of the button in place under some interaction takes place.

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Header, Footer, Button

class SelfRemoveButton( Button ):

    DEFAULT_CSS = """
    SelfRemoveButton {
        width: 100%;
    }
    """

    def on_button_pressed( self ):
        self.remove()

class SelfRemoveApp( App[ None ] ):

    BINDINGS = [
        ( "a", "add", "Add a button" )
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Vertical()
        yield Footer()

    def action_add( self ) -> None:
        self.query_one( Vertical ).mount( SelfRemoveButton( "Press me to remove me" ) )

if __name__ == "__main__":
    SelfRemoveApp().run()
```

**Comment by davep** [comment]
Now I think about it, I suspect this is a duplicate of #2007 -- I'll test with `main` in a moment (was testing with 0.14)

**Comment by davep** [comment]
Nope, not a dupe. Still happens with `main`.

**Comment by Ayehavgunne** [comment]
I am seeing this as well when I add a class with `display: none;`

**Comment by willmcgugan** [comment]
Can't reproduce in current main. Assuming fixed.
