### ISSUE TITLE
A message posted from a widget, just before it self-removes, doesn't make it to the parent

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2017]
*[This is a followup from an initial conversation/check on Slack; I'm posting this here more as a "double-check later" thing than anything else]*

Consider the following code. A message can be sent from it when it is first added, and also when it is pressed. When it is pressed it sends a message to say that it is being removed, and then removes itself from the DOM. However, the message to say it was removed never makes it to the parent (it does if the `self.remove()` is removed).

I was unsure what should happen here, but checking with Will, he confirmed that the message *should* make it up to the parent.

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Header, Footer, Button, TextLog
from textual.message    import Message

class MessageButton( Button ):

    DEFAULT_CSS = """
    MessageButton {
        width: 100%;
    }
    """

    class StuffHappened( Message ):

        def __init__( self, what: str ) -> None:
            super().__init__()
            self.what = what

    def on_mount( self ) -> None:
        self.post_message( self.StuffHappened( "I got added!" ) )

    def on_button_pressed( self ) -> None:
        self.post_message( self.StuffHappened( "I got removed!" ) )
        self.remove()


class MessasgeOnRemoveApp( App[ None ] ):

    CSS = """
    #buttons {
        border: round green;
        height: 2fr;
    }

    TextLog {
        border: round red;
        height: 1fr;
    }
    """

    BINDINGS = [
        ( "a", "add", "Add a button" ),
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        with Vertical():
            yield Vertical( id="buttons" )
            yield TextLog()
        yield Footer()

    def action_add( self ) -> None:
        self.query_one( "#buttons" ).mount( MessageButton( "Press me to remove me") )

    def on_message_button_stuff_happened( self, event: MessageButton.StuffHappened ):
        self.query_one( TextLog ).write( event.what )

if __name__ == "__main__":
    MessasgeOnRemoveApp().run()
```

PS: Using the above can trigger #2016 also; that can be ignored for the purposes of this test.

**Comment by willmcgugan** [comment]
The call to remove is actioned immediately after the handler returns, so that the widget has no parent to bubble to.

There are some easy workarounds:

- post the message to the parent
- call `self.call_later(self.remove)`

Ultimately though widgets should avoid removing themselves. The parents should manage the children's state where possible.

Unless there is a straightforward way of making it "just work", I think this may have to remain "as designed".

**Comment by davep** [comment]
Works for me. In the code I was working on that raised this issue, to originally get it working, [I went with the second option](https://github.com/davep/oidia/commit/7d72809ae7b58f7b2dc04c680f227e3aef8b20dc), so I'm happy to consider that one of the "correct ways".

I'll close this as I'm happy that this makes sense. Fairly sure I've seen a couple of other folk caught out by this so this gives us a clear answer to that.
