### ISSUE TITLE
DataTable width does not account for vertical scrollbar

### ISSUE THREAD

**Issue by ofek** [Textualize/textual#2019]
When a table has too many entries it adds a scrollbar to go down, which is proper, but then horizontally the scrollbar takes up space and therefore a horizontal scrollbar is added just to account for the vertical one

![dt](https://user-images.githubusercontent.com/9677399/224383166-b0b66ba6-226b-4310-85df-79c273243535.PNG)

## Code

<details>

```python
from os import urandom
from random import randrange

from textual.app import App
from textual.containers import Container, Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import DataTable, Header, Label


class LabeledBox(Container):
    DEFAULT_CSS = """
    LabeledBox {
        layers: base_ top_;
        width: 100%;
        height: 100%;
    }

    LabeledBox > Container {
        layer: base_;
        border: round $primary;
        width: 100%;
        height: 100%;
        layout: vertical;
    }

    LabeledBox > Label {
        layer: top_;
        offset-x: 2;
    }
    """

    def __init__(self, title, *args, **kwargs):
        self.__label = Label(title)

        super().__init__(self.__label, Container(*args, **kwargs))

    @property
    def label(self):
        return self.__label


class StatusTable(DataTable):
    def __init__(self):
        super().__init__()

        self.cursor_type = 'row'
        self.show_cursor = False
        self.add_column('Foo')
        self.add_column('Bar')
        self.add_column('Baz')

        for _ in range(50):
            self.add_row(
                urandom(randrange(10, 15)).hex(),
                urandom(randrange(10, 15)).hex(),
                urandom(randrange(10, 15)).hex(),
            )


class Status(LabeledBox):
    DEFAULT_CSS = """
    Status {
        width: auto;
    }

    Status Container {
        width: auto;
    }

    Status StatusTable {
        width: auto;
        margin-top: 1;
    }
    """

    def __init__(self, name: str):
        self.__name = name
        self.__table = StatusTable()

        super().__init__(f' {self.__name} ', self.__table)

    @property
    def name(self) -> str:
        return self.__name

    @property
    def table(self) -> StatusTable:
        return self.__table


class Rendering(LabeledBox):
    DEFAULT_CSS = """
    #issue-info {
        height: auto;
        border-bottom: dashed #632CA6;
    }

    #statuses-box {
        height: 1fr;
        width: auto;
    }
    """

    def __init__(self):
        self.__info = Label('test')

        super().__init__(
            '',
            Container(
                Horizontal(self.__info, id='issue-info'),
                Horizontal(*[Status(str(i)) for i in range(4)], id='statuses-box'),
                id='issues-box',
            ),
        )

    @property
    def info(self) -> Label:
        return self.__info


class Sidebar(LabeledBox):
    DEFAULT_CSS = """
    #sidebar-status {
        height: auto;
        border-bottom: dashed #632CA6;
    }

    #sidebar-options {
        height: 1fr;
    }
    """

    def __init__(self):
        self.__status = Label('ok')
        self.__options = Vertical()

        super().__init__(
            '',
            Container(self.__status, id='sidebar-status'),
            Container(self.__options, id='sidebar-options'),
        )

    @property
    def status(self) -> Label:
        return self.__status

    @property
    def options(self) -> Vertical:
        return self.__options


class MyScreen(Screen):
    DEFAULT_CSS = """
    #main-content {
        layout: grid;
        grid-size: 2;
        grid-columns: 1fr 5fr;
        grid-rows: 1fr;
    }

    #main-content-sidebar {
        height: 100%;
    }

    #main-content-rendering {
        height: 100%;
    }
    """

    def compose(self):
        yield Header()
        yield Container(
            Container(Sidebar(), id='main-content-sidebar'),
            Container(Rendering(), id='main-content-rendering'),
            id='main-content',
        )


class MyApp(App):
    async def on_mount(self):
        self.install_screen(MyScreen(), 'myscreen')
        await self.push_screen('myscreen')


if __name__ == "__main__":
    app = MyApp()
    app.run()
```
</details>

## Textual Diagnostics

<details>

### Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.13.0 |
| Rich    | 13.2.0 |

### Python

| Name           | Value                                                            |
|----------------|------------------------------------------------------------------|
| Version        | 3.11.1                                                           |
| Implementation | CPython                                                          |
| Compiler       | MSC v.1934 64 bit (AMD64)                                        |
| Executable     | C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\PYTHON.EXE |

### Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19045 |

### Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

### Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=199, height=42 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 199                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 42                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |
</details>

**Comment by willmcgugan** [comment]
Hi @ofek 

Try adding the following to your tables:

```
scrollbar-gutter: stable;
overflow-x: hidden;
```

**Comment by ofek** [comment]
I just tried and that doesn't change anything

**Comment by willmcgugan** [comment]
Actually, its just the `scrollbar-gutter: stable;` you need. Here's what it looks like for me:

<img width="1417" alt="Screenshot 2023-03-11 at 20 49 43" src="https://user-images.githubusercontent.com/554369/224511008-800ecaec-6b3c-4791-9f46-903419142e44.png">

**Comment by ofek** [comment]
thanks! will that be necessary after #2024 is merged?

**Comment by willmcgugan** [comment]
Yes. #2024 was a tangental bug.

The scrollbar gutter reserves space for scrollbars, so adding a scrollbar doesn't shrink the content area.
