### ISSUE TITLE
Have we outgrown the containers `Container` and `Content`?

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2029]
Haven't we outgrown the containers `Container` and `Content`?

It seems to me one would/should use `VerticalScroll` instead of `Container` and `Static` instead of `Content`.

**Comment by willmcgugan** [comment]
I don't think so, because `Content` is a container (i.e. expected to have children), where the others aren't.

**Comment by rodrigogiraoserrao** [comment]
Right, but `Content` and `Container` are the same. I don't see the point of having two containers that do the same thing.

**Comment by davep** [comment]
> Right, but Content and Container are the same.

Not quite. `Content` can be focused by default, `Container` not. There's also a subtle difference in the overflow styling.

**Comment by rodrigogiraoserrao** [comment]
There was too much nuance for me, then!
