### ISSUE TITLE
Revisit `DirectoryTree`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2056]
The [`DirectoryTree` widget](https://textual.textualize.io/widget_gallery/#directorytree) could do with a wee revisit. The `Tree` itself has been enhanced somewhat since `DirectoryTree` was first developed, and so we should look over it to ensure there's parity with messages that are posted.

Also, from watching people work with it, some other improvements come to mind (feel free to add more if you've seen any):

- ~~Some method of forcing a refresh (either of a specific node and its children, or the whole tree)~~
- ~~Some way of being able to (optionally) navigate above the initial root (the idea here being that someone may use it as a file-open navigation widget, start the user in a specific directory, and want them to be able to navigate higher up).~~
- ~~Add an option to ignore hidden directory entries~~ - handled by #2215
    - ~~As an aside: the current method of deciding hidden is very Unix-oriented. Might be worth thinking about what it means to show or not show hidden filesystem entries on Windows.~~ Handled by #2215
 - Check the messages raised and what event handlers will catch then; I think some `DirectoryTree` events will "leak" into normal `Tree` handlers and that could get surprising for people.
 - ~~Populate the tree using a worker so that the application stays more responsive.~~

**Comment by willmcgugan** [comment]
I don't think we want to include a way of navigating beyond the root. I feel that should be provided by another widget that embeds DirectoryTree

We do need a refresh method, or a perhaps `reload` to avoid the clash with Widget.refresh

I can think of a variety of other additions like only showing folders, adding checkboxes, etc.

We will revisit this soon.

**Comment by bluematt** [comment]
> Some way of being able to (optionally) navigate above the initial root (the idea here being that someone may use it as a file-open navigation widget, start the user in a specific directory, and want them to be able to navigate higher up).

I've been looking for this too.  My immediate notion was that `path` might be `reactive`, but no such luck.

**Comment by davep** [comment]
`DirectoryTree` does need a wee bit more attention, and while Will's mention above about not wanting to allow in-widget above-initial-root navigation makes sense, I do think a "reload content, optionally with this new root" method may happen.

Meanwhile, for about the same cost, what I'm doing in an app I've been working on is simply remove the widget and mount a fresh one with a new root:

```python
    async def chdir(self, path: Path) -> None:
        """Change the filesystem view to the given directory."""
        await self.query_one(FilteredDirectoryTree).remove()
        await self.mount(FilteredDirectoryTree(path))
```

**Comment by bluematt** [comment]
> Meanwhile, for about the same cost, what I'm doing in an app I've been working on is simply remove the widget and mount a fresh one with a new root:

That's what I've done in the meantime, although nowhere near as cleanly as that!

**Comment by miguelfaf10** [comment]
Is it possible to have Message generated when a folder is selected, just as like for files. not sure if this already avaiable?

**Comment by lllama** [comment]
It would be really nice to have a way to select a node from a `pathlib.Path` or similar.

**Comment by bluematt** [comment]
> It would be really nice to have a way to select a node from a `pathlib.Path` or similar.

I am currently looking at a workaround for this *exact* issue.

**Comment by bluematt** [comment]
> Is it possible to have Message generated when a folder is selected, just as like for files. not sure if this already avaiable?

You're probably looking for the `on_tree_node_selected(self, event: Tree.NodeSelected)` hook.

**Comment by lllama** [comment]
Code that's currently working for me with this:

```py
    async def refresh_tree(self, path_to_select):
        tree = self.query_one(DirectoryTree)
        await tree.remove()
        await self.mount(DirectoryTree(self.root))
        tree = self.query_one(DirectoryTree)

        path_parts = path_to_select.relative_to(self.root).parts

        node = tree.root
        current_path = Path(self.root)
        for part in path_parts:
            node = [n for n in node.children if Path(n.data.path) == current_path / part][0]
            if node.data.is_dir:
                tree.load_directory(node)
            else:
                tree.select_node(node)
            current_path = current_path / part

        tree.select_node(node)
```

**Comment by davep** [comment]
Updated the "job list" for this to mark that filtering and handling of hidden files was taken care of with #2215 and also to add:

- Check all messages to ensure there's no surprising event leakage from `Tree`
- Move tree population into a worker

**Comment by davep** [comment]
I believe everything here has been satisfied, either long-since merged into `main`, or a PR is ready for review. Closing.

If anything is missing a new issue for that item should be raised.
