### ISSUE TITLE
Message '.sender' set to last composed widget

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2070]
The attribute `Message.sender` is incorrectly set to the last widget that was composed instead of pointing to the widget that actually posts the message.

Run the app below and click the screen or the text as you please.
The text log will log events coming from a scrollbar.

For a MMWE get rid of the custom widget altogether and preserve only the `on_click` handler, which will still show clicks coming from the scrollbar...

```py
from textual.app import App, ComposeResult
from textual.message import Message
from textual.widgets import Header, Footer, Static, TextLog


class CustomWidget(Static):
    class CustomMessage(Message):
        pass

    def trigger(self) -> None:
        self.post_message(self.CustomMessage())


class MyApp(App[None]):
    def compose(self) -> ComposeResult:
        yield Header()
        yield CustomWidget("Big text\nso you can target it.", id="custom")
        yield Footer()
        yield TextLog(id="tl")

    def on_click(self, event) -> None:
        self.query_one(TextLog).write(event.sender)
        self.query_one(CustomWidget).trigger()

    def on_custom_widget_custom_message(
        self, event: CustomWidget.CustomMessage
    ) -> None:
        self.query_one(TextLog).write(event.sender)


app = MyApp()

if __name__ == "__main__":
    app.run()
```

**Comment by willmcgugan** [comment]
```python
    def trigger(self) -> None:
        self.post_message(self.CustomMessage())
```

You might be thinking that the sender is always `self` in the call to `post_message`. A reasonable assumption, but consider `self` to be the *destination* of the message.

Consider this line:

```python
self.query_one(CustomWidget).post_message(MyEvent())
```

The sender is *not* CustomWidget. CustomWidget is the destination of the message. The sender is the active message pump at the time.

There is a bug though. Basically it wasn't storing the app as the sender.
