### ISSUE TITLE
`)` cannot appear as part of the parameter passed to an action

### ISSUE THREAD

**Issue by liancheng** [Textualize/textual#2088]
Reproduction:

```python
from textual.app import App


class ActionBugApp(App):
    BINDINGS = [("a", "test(')')", "Test")]

    def action_test(self, _: str) -> None:
        pass


if __name__ == '__main__':
    app = ActionBugApp()
    app.run()
```

Omitting the full stack trace (since it's fairly easy to reproduce), the key error message is:

```
ActionError: unable to parse "(')" in action "test(')')"
```

Seems that [this regex](https://github.com/Textualize/textual/blob/2a6368754a8b3a11f1772b52298b5d3b50ceebaa/src/textual/actions.py#L20) is not general enough.

**Comment by liancheng** [comment]
My real-world use case is a [NetHack price identification](https://nethackwiki.com/wiki/Price_identification) tool.

In [NetHack](https://nethackwiki.com/wiki/Main_Page), different categories of items are represented using different characters, and `)` represents weapons.

I built the following app for manual and auto price ID, and I bound those item-category characters to an action to select the corresponding `ListItem` in the "Item category" `ListView` (with a `layout: horizontal`).

Hitting `)` to identify a weapon triggers this issue.

![nethack_price_id_2023-03-19T00_10_05_075154](https://user-images.githubusercontent.com/230655/226159835-e06026ea-7a4e-490a-bea2-f261a7f8ce68.svg)

**Comment by davep** [comment]
Yup, at first glance I feel `r"([\w\.]+)(\(.*\))"` might be a better regexp here (greedy match of `)` rather than non-greedy), although I'd nee to check the unit tests and also with Will to see if it was non-greedy for a reason.
