### ISSUE TITLE
Screen example not working with python3.8 (

### ISSUE THREAD

**Issue by cknoll** [Textualize/textual#2090]
The example from https://textual.textualize.io/guide/screens/#__tabbed_1_1 does not work for me if I run it from python3.8.

Specifically the `escape` key does not have the desired effect (returning to the empty screen) if pressed while the `BSOD`-screen is active. (With python3.9 the app works as expected.)

If I run it with `textual run --dev bsod.py` the debug console gives the following output:

```
[10:02:53] WARNING                                                                                \widget.py:2594\
BSOD(pseudo_classes={'enabled'}) IS NOT RUNNING, Key(key='escape', character='\x1b', name='escape', 
is_printable=False, aliases=['escape', 'ctrl+left_square_brace']) not sent
```

I discovered this problem while debugging not-working `Screen`-dependent bindings in my app. I get a similar "IS NOT RUNNING" error there.

This is the output of `textual diagnose`:

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.15.1 |
| Rich    | 13.3.1 |

## Python

| Name           | Value                                          |
|----------------|------------------------------------------------|
| Version        | 3.8.6                                          |
| Implementation | CPython                                        |
| Compiler       | GCC 9.3.0                                      |
| Executable     | /home/ck2/miniconda3/envs/base38/bin/python3.8 |

## Operating System

| Name    | Value                                 |
|---------|---------------------------------------|
| System  | Linux                                 |
| Release | 4.19.0-23-amd64                       |
| Version | #1 SMP Debian 4.19.269-1 (2022-12-20) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=112, height=38 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 112                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 38                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
While I am on macOS, I've just tested `screen01.py` with Pythons 3.7, 3.8, 3.9, 3.10 and 3.11 and every one of them works.

With 3.8, I'm using 3.8.13, and I see that [3.8.16](https://www.python.org/downloads/release/python-3916/) is the most recent version. Perhaps it's worth trying with a more recent release?

**Comment by davep** [comment]
How are you getting on with this @cknoll?

**Comment by cknoll** [comment]
I can confirm that the problem is gone with python 3.8.16 :+1:. With 3.8.6 (in different conda environment) I can still reproduce it reliably. 🤷

Anyway, I consider this as good solution. Tanks! 🙏

**Comment by davep** [comment]
Thanks for the update, much appreciated. Glad that sorted it.
