### ISSUE TITLE
Hide "enabled" from pseudo classes

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2096]
The "enabled" pseudo class is the inverse of "disabled".

It's presence in the pseudo classes set makes logging the DOM rather noisy.

![Image](https://user-images.githubusercontent.com/554369/225641453-9318c7c2-6dee-4f23-97e9-bbd1d22bfaea.png)

I don't want to get rid of it, but I wonder if we can presume the "enabled" where it does the check, rather than adding it to the set. In essence, the "enabled" check becomes  `if not "disabled in pseudo_classes"`

**Comment by darrenburns** [comment]
As far as I can tell there is no "enabled" check. I can't see "enabled" being used anywhere.

**Comment by willmcgugan** [comment]
In retrospect I don't think this is a good idea.
