### ISSUE TITLE
logging with RichHandler

### ISSUE THREAD

**Issue by bphunter1972** [Textualize/textual#2099]
I'm pretty surprised this isn't functioning as expected when running `textual run --dev`.

The messages make it to the screen, but they are all garbled.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/5446342/226709487-4975c9a3-2f8a-4ca9-a1ba-40c3ff6afb53.png">

I know about textual.log, but as I am adding a TUI front-end to another tool (which itself uses rich logging), I cannot readily swap it out.

Textual diagnosis:

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.15.1 |
| Rich    | 13.3.2 |

## Python

| Name           | Value                                                                              |
|----------------|------------------------------------------------------------------------------------|
| Version        | 3.8.10                                                                             |
| Implementation | CPython                                                                            |
| Compiler       | Clang 6.0 (clang-600.0.57)                                                         |
| Executable     | /Users/bphunter/Library/Caches/pypoetry/virtualenvs/gviz-AtLwRJRq-py3.8/bin/python |

## Operating System

| Name    | Value                                                                                           |
|---------|-------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                          |
| Release | 22.3.0                                                                                          |
| Version | Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.19) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=164, height=89 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 164                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 89                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
You can't have both a TUI and RichHandler writing in the same terminal. One would make the other unreadable. And you can't expect a logging handler in your app to know anything about a console in a different process.

I can see there being a dedicated Textual logging handler eventually. But that would still require you to be able to configure logging. You almost certainly can configure your logging to go to a file or stdout using the logging API. Even if the logging was initialised by a library. See the docs on [logging config](https://docs.python.org/3/library/logging.config.html#module-logging.config), in particular *disable_existing_loggers*

**Comment by bphunter1972** [comment]
Yes, I've added a FileHandler instead. 

But I do not need the TUI and the RichHandler going to the same terminal. I was hoping it could go to the dev console.

**Comment by willmcgugan** [comment]
If you log to stdout with StreamHandler it will go to the dev console.

**Comment by bphunter1972** [comment]
I must have misunderstood, as that's **definitely** not what I'm seeing. When I set up logging with the StreamHandler to stdout, I'm seeing the log messages overwrite my App's display, and it's only re-drawn if I hover over the text.

This is after launching my app with `textual run --dev`, and having the console up in another terminal.

I have something along these lines:

```python
import logging
from sys import stdout
from textual import log
...
log = logging.getLogger(__name__)
log_handler = logging.StreamHandler(stdout)
logging.basicConfig(level=logging.INFO, format="%(message)s", datefmt="[%X]", handlers=[log_handler])
...
    def on_input_submitted(self, message):
        log.info(f"received {message.value}")
        message.input.value = "> "
```

Here's what the upper corner of the display then looks like:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/5446342/226970452-a78b5e7b-f450-4d0e-9985-de05a71d364d.png">

Note that this happens whether it's to stdout or stderr.

**Comment by willmcgugan** [comment]
I think the problem may be that StreamHandler holds a reference to stdout, which prevents Textual from capturing it.

You could try configuring the logging in App.on_mount

Next release should have a dedicated Textual logger.

**Comment by bphunter1972** [comment]
That'd be great! Thanks!
 Looks like you opened up #2130 on this.

**Comment by bphunter1972** [comment]
That'd be great! Thanks!
