### ISSUE TITLE
Inconsistent phrasing in Styles reference

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2107]
We have some horrible inconsistent phrasing in the Styles reference. Here are a few examples:

- The content-align style aligns content inside a widget.
- The dock property is used to fix a widget to the edge of a container.
-  The min-width rule sets a minimum width for a widget..

I think we should settle on referring to them as **styles**, in the general case.

i.e. 

> The dock **style** is used to fix a widget to the edge of a container.

If the context is referring to the CSS only then it should be the **rule**, if it is referring to the Python only then is should be the **property**.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao One for you?

**Comment by rodrigogiraoserrao** [comment]
> We have some horrible inconsistent phrasing in the Styles reference.

Not on my watch!
I'll handle it.
