### ISSUE TITLE
Apparent missing content in border title and subtitle docs

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2108]
Just noting this as I saw it in passing while looking for something else: in the border title and subtitle guide docs there seems to be some content missing after the headings `All title and subtitle combinations`. Looks like some other file is supposed to be included in but isn't happening?

Tagging @rodrigogiraoserrao for obvious reasons.

**Comment by rodrigogiraoserrao** [comment]
I don't know what's going on in my life.
Commits f9335c468437bfe037025b5fe3aa12e3028f2a7b, be228313bb0ca2cda980d18f082186e51ecb5ec0, and 91914a67a7dfa0849b6f1c3dd3cce151a260881e, all show me editing a file `docs/snippets/border_sub_title_align_all_example.md`...
Then, _somehow_, I managed to delete the whole file in 0862e384cc76b505e80e6f67c8e78fafea1604e2...

I don't know _how_...
But yeah, the docs pages are trying to include a file that I managed to clear completely... 🤦

**Comment by davep** [comment]
> I don't know what's going on in my life.

It was the dodgy wifi connection, of course!
