### ISSUE TITLE
Possibility to get rid of "cutout" in ToggleButton when button is off

### ISSUE THREAD

**Issue by mzebrak** [Textualize/textual#2121]
In general, I really like the fact that checkbox and radiobutton controls have recently been introduced. However, I have a feeling that the "cutout" can be a bit confusing for users because at first glance it looks like the checkbox is just checked. This requires the user to toggle it to find out that in toggled mode it is green.

I tried to get rid of it with a CSS override, but then I noticed that it's a hardcoded part in the `_button` property.

```python
        # If the button is off, we're going to do a bit of a switcharound to
        # make it look like it's a "cutout".
        if not self.value:
            button_style += Style.from_color(
                self.background_colors[1].rich_color, button_style.bgcolor
            )
```

Would it be possible to influence whether "coutout" is visible?  I would see an additional parameter in togglebutton subclasses like `cutout=False`.

**Comment by mzebrak** [comment]
> If you make the cutout invisible, how would the user even know there is something there?

I think it shouldn't be a problem - this is how the HTML checkbox works also. I'm talking about just the ability to get rid of the "X" cutout. The square shade should still remain of course. 
It's focusable and can be labeled like "Are you a robot?", so you can see that it is a checkbox, just a dark shade of "X" indicates at a glance that it is checked.

**Comment by willmcgugan** [comment]
Browsers have a bit more freedom when it comes to drawing. I personally don't think a plain square is enough to indicate that it would be an unchecked checkbox.

I'm open to changes to make it easy to extend or style, but not a `cutout=False` option. Accommodating everyone's stylistic preferences will inevitably lead to every control growing a dozen parameters, and we're trying to create a common look and feel.

**Comment by mzebrak** [comment]
> Browsers have a bit more freedom when it comes to drawing. I personally don't think a plain square is enough to indicate that it would be an unchecked checkbox.
> 
> I'm open to changes to make it easy to extend or style, but not a `cutout=False` option. Accommodating everyone's stylistic preferences will inevitably lead to every control growing a dozen parameters, and we're trying to create a common look and feel.

Yeah I agree, the `coutout=False` was a quick simplification, but I believe that it should be possible to control this possibility on the CSS side, and currently, there is no such option.

**Comment by willmcgugan** [comment]
No plans to change the toggle buttons, but would happily accept a PR.
