### ISSUE TITLE
Implement Textual logging handler

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2130]
Logging StreamHandler prevents intercepting logging to stdout.

We should implement a dedicated Textual logging handler. I suspect all it really needs to do is print to `sys.stdout`, which will allow the stdout redirection to display it in the dev console.

**Comment by liancheng** [comment]
It would be great if we can show logs in UI (a `TextLog` widget) can also be helpful for migrating existing CLI tools. The rationale is that INFO-level logs should be considered part of the UI of the original CLI tool. They should be communicated to users.

See: https://github.com/Textualize/textual/discussions/2072
