### ISSUE TITLE
[Reminder] Scrollbar can end up detached from container (exact cause unknown at the moment)

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2131]
This issue is more of a reminder to me to dig a bit deeper and find the exact cause, just recording it as I noticed in passing while doing something else. While seeing about upgrading [unbored](https://github.com/davep/unbored) to the latest Textual, I happened to fire it up in a shorter-than-usual terminal and noticed this interesting behaviour when pulling up the filter dialog (which is a `Vertical` on a layer of its own and with offsets used to show/hide it so that transitions can be used to make a fun slide-in effect):

https://user-images.githubusercontent.com/28237/227460717-77fde391-74f5-4905-9d38-eafe841677dd.mov

*[NOTE: As of the time of writing it's using Textual 0.14.0 so it will be using `Vertical` where I likely (as of 0.16.0) want to be using `VerticalScroll` now.]*

Once I get time to try and reproduce this in isolation (or update unbored to 0.16.0 and find that it's gone away anyway, which is possible) I'll update and/or close this issue.

**Comment by davep** [comment]
Confirmed as still being an issue using `VerticalScroll` in v0.16.0.

**Comment by willmcgugan** [comment]
Suspect this is fixed.

**Comment by davep** [comment]
I suspect so too, but will test (looks like I'll need to tweak the application a wee bit too because the last time I tested this was before the Vertical/VerticalScroll switch, etc).

**Comment by davep** [comment]
Updated `Unbored` to the latest Textual and tested and, as suspected, all is fixed.
