### ISSUE TITLE
Add CSS to Screens

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2137]
- Add CSS to Screen (in addition to default_css)
- Raise an error if CSS is defined on other widgets

**Comment by rodrigogiraoserrao** [comment]
Are you talking about the CSS class variable @willmcgugan ?

**Comment by willmcgugan** [comment]
Yeah, So we can have a CSS classvar for screens.

And also `CSS_PATH` come to think of it.

**Comment by rodrigogiraoserrao** [comment]
> Yeah, So we can have a CSS classvar for screens.
> 
> And also `CSS_PATH` come to think of it.

Ok.

And you say you want to explicitly error when setting CSS on other widgets.
The two alternatives I could think of
 - override `__setattr__` and check if we are attempting to set `CSS`; and
 - define `CSS/CSS_PATH` to be descriptors with no getters and with setters that error when setting.

I like the second approach better because it prevents us from doing some extra work every single time we set an attribute on a widget.

**Comment by willmcgugan** [comment]
I'd suggest adding a check in the constructor. If `CSS` or `CSS_PATH` is set on anything other than App or Screen, then error out.

I don't think we should check for *setting* `CSS`, since that is not something you would be expected to do. Just wether it has been defined in a classvar.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao I'm afraid I don't understand the issue you mentioned. You might have to talk me through. Going to move this back to ToDo. Let me know when you have time to discuss it.

**Comment by rodrigogiraoserrao** [comment]
Update: we suspect it may be the way the app is imported when we run it with `textual run` that may be breaking the introspection mechanism.
Work in #2288 should clear the path for simplifying how the App resolves relative CSS file paths and it should unblock the issues I found above.

**Comment by dhallas** [comment]
Just adding my two-cents here.
I think it is a great idea to be able to have per-screen CSS files. This will allow you to split out your CSS to screen specific CSS files instead of having it in one big application wide file.
