### ISSUE TITLE
Mac keyboard shortcuts not supported

### ISSUE THREAD

**Issue by koaning** [Textualize/textual#2153]
I've noticed that `ctrl+s` bindings work just fine, but that `cmd+s` bindings don't in textual. I then confirmed via `textual-keys` and it seems that <kbd>CMD</kbd>+<kbd>S</kbd> does not register. 

I'd imagine you'd be interested in supporting these keys as well but wasn't sure if you weren't aware of if there's something strange about my setup that is causing this.

**Comment by davep** [comment]
Textual can only process keys that get sent into the terminal. The <kbd>⌘</kbd> key combinations are generally going to be used by the terminal application itself. Take macOS' own terminal application for example:

<img width="265" alt="Screenshot 2023-03-28 at 13 06 39" src="https://user-images.githubusercontent.com/28237/228231297-95b6a5f8-6bae-4880-ac8e-49bb5d177dc8.png">

**Comment by willmcgugan** [comment]
It is unfortunate that terminals don't support cmd keys. At least they never make it to the app.

I wonder if this is worth adding to the faq.
