### ISSUE TITLE
file watch and refresh

### ISSUE THREAD

**Issue by dindom999** [Textualize/textual#216]
To be added by @willmcgugan
Is it possible to add an event like
`def on_file_change(self, file_name):`
so that we can watch a file , when it changed, textual placehoder can display the lastest content.

Or anyone can tell me how to integrate pyinotify with textual , and make the following code work with textual?
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pyinotify
import asyncore
import datetime

fn = "/tmp/run.log"

def show():
    with open(fn,'r') as f:
        txt = f.read()
        print(txt)

class EventHandler(pyinotify.ProcessEvent):
    def process_default(self, event):
        show()

if __name__ == '__main__':
    show()
    wm = pyinotify.WatchManager()
    hander = EventHandler()
    notifier = pyinotify.AsyncNotifier(wm, hander)
    wm.add_watch(fn, pyinotify.IN_MODIFY, rec=True)
    asyncore.loop()


```

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
