### ISSUE TITLE
Consider lifting `_option_list.py:DuplicateID` and reusing for other widgets

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2164]
The `OptionList` makes use of a `DuplicateID` exception when two options have the same ID.
We have other widgets (like tabs) that expect unique IDs as well.
It may be worth pulling `DuplicateID` out so that it can be used across these widgets (and potentially by other things as well).

**Comment by davep** [comment]
Thinking about this some more, without diving into the code (bus thinking and phone typing), tabs are widgets in a shared container so a duplicate ID will be a MountError already. 

Options in an OptionList aren't widgets so are a different class of content.

**Comment by rodrigogiraoserrao** [comment]
Alright, then maybe we close this.
