### ISSUE TITLE
Document custom types used and actually show their definition

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2168]
I think we should document, perhaps in the API page, the custom types we use for things that are already documented.

For example, `App.CSS_PATH` shows up in the docs and is typed as `CSSPathType`, and the type itself is pretty much all the documentation needed for `App.CSS_PATH`.
However, `CSSPathType` isn't documented.

In my opinion, we chould/should document these custom types in the module they are defined in, or they should all be collected in a “Types” API page, for example.

**Note**: I spent some time trying to do this for a single type (`CSSPathType`) and I managed to put it in a separate API page.
However, I wasn't getting two important things:
 1. The signature of `App.CSS_PATH` wasn't linking to `CSSPathType`.
 2. I didn't manage to have `CSSPathType` show its signature, which is what I really wanted to have documented.

**Comment by willmcgugan** [comment]
I think the most straightforward solution would be to cover it in the docstrings. We do seem to be missing docstrings for `CSS_PATH`.

**Comment by rodrigogiraoserrao** [comment]
So, to clarify, you are suggesting that the docstring for `CSS_PATH` mentions and links to `CSSPathType`, for example?

**Comment by willmcgugan** [comment]
Yeah, if we can't somehow expand the `CSSPathType` then we could just say it can be a string, list of strings, or None.

**Comment by rodrigogiraoserrao** [comment]
Ok. I'll see what I can do.

**Comment by rodrigogiraoserrao** [comment]
Ok, I can correctly export useful type aliases and I can have the docs cross-reference them automatically when they show up in signatures. (Thanks, Dave, for the work in #2287!)

However, if you show a type alias in the docs, it won't expand its definition, even if you set the option `show_source: true`.
Sadly, this is probably the most important step of all!

So, do I manually add this duplicated info to the docstrings of those type aliases?
Do we create a small mkdocs/mkdocstrings plugin that handles this?

**Comment by willmcgugan** [comment]
What happens if we use the type in the docstring? i.e. something like this?

```python
CSS_PATH = ""
"""str | list[str] | None: Path to css files, or a list of paths."""
```

**Comment by rodrigogiraoserrao** [comment]
I'll see what reply I get back from https://github.com/mkdocstrings/mkdocstrings/issues/559
