### ISSUE TITLE
MarkdownViewer doesn't show ToC inside VerticalScroll

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2173]
When creating a `MarkdownViewer` instance inside `VerticalScroll`, the table of contents doesn't display entirely.
I can only see a thin sliver which I can click to open the ToC.

The ToC will also come into view if I resize the terminal.

Video demo and MWE follow:

https://user-images.githubusercontent.com/5621605/228794442-6446b5c8-fe8f-42e3-b1ac-be8241fe1885.mov

```py
from textual.app import App, ComposeResult
from textual.containers import VerticalScroll
from textual.widgets import MarkdownViewer


MARKDOWN = """
# Introduction

This is an introductory paragraph.
Of course it doesn't say much.


## Preamble

Get ready for a lot of a lot of stuff.
"""


class MyApp(App):
    CSS = """
    MarkdownViewer {
        height: 100%;
    }
    """

    def compose(self) -> ComposeResult:
        with VerticalScroll():
            yield MarkdownViewer(MARKDOWN)
```

**Comment by willmcgugan** [comment]
This works as expected for me. Can you try with an update to date Textual?

**Comment by rodrigogiraoserrao** [comment]
Seems to work in 0.18.0.
