### ISSUE TITLE
`Markdown.update` is currently async and must be awaited

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2179]
First noticed this when helping someone on Discord get their code updating a `Markdown` with new content. At the moment if you want to update a `Markdown` widget using its `update` method you must `await` the result. Checking with @willmcgugan it seems that it's not intentional that it's such and that it shouldn't be necessary at all.

**Comment by lolbat** [comment]
What is funny is that I am having that exact same issue :-) Will wait for a fix

**Comment by rodrigogiraoserrao** [comment]
This was fixed in #2182
