### ISSUE TITLE
Document Widget attributes

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2180]
The class `widget.py:Widget` has many undocumented attributes and it would be nice if they had proper docstrings!
_At least_ the public ones.

Examples (not sure if these are the only ones missing docs):

https://github.com/Textualize/textual/blob/4fcf44c354b421db1e59e080ad0f15cb06c08979/src/textual/widget.py#L312-L322

**Comment by willmcgugan** [comment]
I added docstrings recently. I think all of these are covered.
