### ISSUE TITLE
Markdown TOC reports "visible" when it is not.

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2208]
The TOC of a `MarkdownViewer` can be hidden via `show_table_of_contents`.
When it's hidden in that way, querying its property `visible` reports `True` when it should report `False`.

MWE; press `p` to see the reported value as `True`:

```py
from textual.app import App, ComposeResult
from textual.widgets import MarkdownViewer
from textual.widgets.markdown import MarkdownTableOfContents


class app_name(App[None]):
    def compose(self) -> ComposeResult:
        yield MarkdownViewer("", show_table_of_contents=False)

    def key_p(self):
        print(self.query_one(MarkdownViewer).show_table_of_contents)
        print(self.query_one(MarkdownTableOfContents).visible)


app = app_name()

if __name__ == "__main__":
    app.run()

```

**Comment by willmcgugan** [comment]
The `visible` property has a very specific meaning. It is when the `visibility` style is "hidden".

It's not an indicator that the widget can't be seen. There are a variety of ways in which a widget may not be on screen: display can be None, it can be off the screen / container, or its size can be (0, 0) etc.

**Comment by rodrigogiraoserrao** [comment]
I thought `visible` supposedly took all of those into account.
Can I change this issue into a suggestion that we make the docstring for `visible` reflect what you just said?

**Comment by willmcgugan** [comment]
Sure. Or feel free to just go ahead and update the docstring.
