### ISSUE TITLE
Margin and `fr` don't mix well

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2220]
**Edit**: original MRE was wrong.
[See the real issue below](https://github.com/Textualize/textual/issues/2220#issuecomment-1497849880)

**Comment by willmcgugan** [comment]
This seems to work as I would expect. A blank line, followed by the lines with text.

What do you get?

**Comment by rodrigogiraoserrao** [comment]
Don't mind me, I got the MRE mixed up.

Real issue: setting margins in widgets inside a container doesn't mix well with also using `fr` in those widgets.

The labels in the MRE below have 3 lines each. Each sets a margin to 1.
We set the outer container to `height: 8`.
Instead of splitting the 8 lines 4-4, the `fr` gives 4 lines to each label and then we need two _extra_ lines for the margins.

What we get:

![gh](https://user-images.githubusercontent.com/5621605/230155062-8eb46416-30f3-4cf6-af41-dd674dcb6049.png)


Expected output:

![gh](https://user-images.githubusercontent.com/5621605/230154950-5526a261-a623-452b-b674-88d119670b9e.png)


 - `margin.css`:

```sass
Container {
    height: 8;
    background: pink;
}

#top {
    background: red;
    margin-top: 1;
    height: 1fr;
}

#bot {
    background: blue;
    margin-bottom: 1;
    height: 1fr;
}
```

 - `margin.py`:

```py
from textual.app import App, ComposeResult
from textual.containers import Container
from textual.widgets import Label


class MyApp(App[None]):
    CSS_PATH = "margin.css"

    def compose(self) -> ComposeResult:
        with Container():
            yield Label("one\ntwo\nthree", id="top")
            yield Label("four\nfive\nsix", id="bot")
```

**Comment by rodrigogiraoserrao** [comment]
I have had all sorts of weird interactions with `margin` in the past. May be related with the above.

**Comment by willmcgugan** [comment]
Awesome, looks like my branch fixes that.

<img width="899" alt="Screenshot 2023-04-05 at 18 38 33" src="https://user-images.githubusercontent.com/554369/230160002-93692840-2acb-4454-8df3-e00cdb5b1da4.png">
