### ISSUE TITLE
It's possible to somehow break the working of `TabbedContent`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2229]
This one isn't exactly easy to explain, but hopefully easy to see and recreate with the following code (which is a distilled version of what I'm doing in a bigger application, where I found it).

Worth noting: the motivation here is that (in the application I'm working on) the `TabbedContent` is acting as a sidebar, where each pane has content that can be focused, and I want folk to be people to switch tabs without needing to navigate to the tab bar and back into the pane again. As such there's some bindings in place that call into the `Tabs` and uses their prev/next tab actions.

```python
from textual.app        import App, ComposeResult
from textual.binding    import Binding
from textual.containers import Vertical
from textual.widgets    import Header, Footer, TabbedContent, TabPane, Tabs, DirectoryTree

class SelfFocusPane(TabPane):

    DEFAULT_CSS = """
    SelfFocusPane {
        height: 100% !important;
    }
    DirectoryTree {
        width: 100%;
        height: 100% !important;
    }
    """

    def compose( self ) -> ComposeResult:
        """Compose the child widgets."""
        yield DirectoryTree(".")

    def on_show( self ) -> None:
        self.query_one( DirectoryTree ).focus()

class TabbedContentIssueApp( App[ None ] ):

    CSS = """
    Screen {
        align: center middle;
    }

    Screen > Vertical {
        width: 42;
    }

    TabbedContent {
        border: round red;
        max-width: 40;
        height: 100%;
    }

    ContentSwitcher {
        height: 1fr !important;
    }
    """

    BINDINGS = [
        Binding( "shift+left", "previous", "Previous" ),
        Binding( "shift+right", "next", "Next" ),
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        with Vertical():
            with TabbedContent():
                for n in range( 6 ):
                    yield SelfFocusPane( f"Tab {n}")
        yield Footer()

    def on_mount(self) -> None:
        self.query_one(Tabs).focus()

    def action_previous(self) -> None:
        self.query_one(Tabs).action_previous_tab()

    def action_next(self) -> None:
        self.query_one(Tabs).action_next_tab()

if __name__ == "__main__":
    TabbedContentIssueApp().run()
```

In experimenting, it looks like the `SelfFocusPane.on_show` setting focus to the child of the pane is key here; remove that and I can't recreate the issue.

**Comment by davep** [comment]
Try just holding the bound keys down and let it go full speed, letting it wrap around plenty of times. Hopefully the issue should appear. 

If not I'll retest here with main.

**Comment by rodrigogiraoserrao** [comment]
I held down Shift + Right for a bit, then I let go.
When I do, the underline will stay pretty much frozen somewhere (not necessarily aligned with a tab) and clicking the bindings in the footer will only work occasionally.
Is this more or less the issue you find?

**Comment by willmcgugan** [comment]
Yeah, that's it.

**Comment by rodrigogiraoserrao** [comment]
I found a funnier way of triggering the issue:

Add this handler to your app:

```py
class TabbedContentIssueApp(App[None]):
    # ...
    def key_p(self) -> None:
        self.action_next()
        self.action_next()
```

If you press `P` just **once**, the underline bar is going to take AGES to move two tabs to the right.
I haven't figured out _exactly_ what funky interaction is happening, but I have a potential fix in the works.
