### ISSUE TITLE
Consider removing vw and vh units

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2246]
We barely use `vw` and `vh` units, and where we do use them, we could substitute `%`.

Consider removing support for `vw` and `vh` entirely.

**Comment by rodrigogiraoserrao** [comment]
Aren't `vh` and `vw` relative to the dimensions of the terminal window..? Sometimes, I find those units useful. 🤷 
When I'm nested deep within containers and want to use a specific portion of my terminal size.

**Comment by willmcgugan** [comment]
Why would you need that though?

**Comment by rodrigogiraoserrao** [comment]
Because I may want a specific widget to be prominent and I'll want to give it a relative size that depends directly on the terminal, and the containers that I'm in might have `auto` dimensions or the like.

**Comment by willmcgugan** [comment]
I'm going to need a more practical example. Can you knock me up a demo?

**Comment by rodrigogiraoserrao** [comment]
Yeah.

I have a suite of apps I want to style in the same style.
I have a file `common.css` that sets a common style for the "main container" that exists in all apps:

```
/* common.css */
#content {
    width: auto;
    height: auto;
    border: round $primary;
    padding: 4 8;
}
```

Most apps have just a couple of buttons and labels on the screen, so it makes sense to set `width` and `height` to `auto`.
However, one app has a markdown viewer and I want it to be "big" by default, so I want to set its dimensions to ~70%-80% of the terminal size with `80vw` and `80vh`.

So, I want `#content` to shrink as much as possible by default while also being able to set a couple of specific apps to "big" sizes that depend on the terminal size.

**Comment by willmcgugan** [comment]
I'm not convinced that is a reasonable thing to do. I think it would make more sense to use percentage units there, so it is relative to the container, not the screen.

However, I don't think there is much point in removing these units now. Going to close this one, but may revisit it in the future.
