### ISSUE TITLE
Tabs widget should use new scroll_to_center

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2256]

**Comment by rodrigogiraoserrao** [comment]
Maybe I got the _intended semantics_ of `scroll_to_center` wrong.

`widget.scroll_to_center` will scroll `widget` to the center of the screen.
Should it be `container.scroll_to_center(widget)` so that it scrolls `widget` to the center of `container`?

**Comment by willmcgugan** [comment]
Yes, we don't always want to scroll everything to the center.
