### ISSUE TITLE
Scroll to center problem

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2268]
There's an issue with `scroll_to_center` that can be seen in the `scroll_to_center.py` snapshot.

Essentially it doesn't seem to scroll the inner-most container the first time, but does on the second time.

I did some debugging, and it appears that `max_scroll_x` and `max_scroll_y` are erroneously reporting zero, until the container becomes visible for the first time, then they have the correct values. The root cause seems to be that the `virtual_size` is the same as `size`, which is incorrect.

When fixing this, be careful not to break `textual colors`. If you click the last button it should scroll to the end.

This issue likely does touch on the compositor. I suspect it is something related to the `_full_map` structure.

**Comment by willmcgugan** [comment]
Apologies to @rodrigogiraoserrao , who's math was impeccable as always.

**Comment by rodrigogiraoserrao** [comment]
> Apologies to @rodrigogiraoserrao , who's math was impeccable as always.

Give me enough time, and I'll eventually make a ridiculous math error 😆

**Comment by rodrigogiraoserrao** [comment]
For reference, likely related to #2254.

**Comment by rodrigogiraoserrao** [comment]
> Give me enough time, and I'll eventually make a ridiculous math error 😆

It just happened. 🤷

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Infrastructure error during execution: Command '['git', 'clone', '--local', '--no-hardlinks', '/home/morganbest/.repopilot/repos/Textualize-textual', '/tmp/repopilot-Textualize-textual-mptzoxia']' returned non-zero exit status 128.

Relevant files:
- src/textual/app.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=47.659; matched issue terms: scroll, center, problem, there, s, issue
- src/textual/widget.py: path components match issue terms, source file; bm25 rerank score=41.771; matched issue terms: scroll, center, problem, there, s, can
- src/textual/screen.py: path components match issue terms, source file; bm25 rerank score=35.251; matched issue terms: scroll, center, there, s, can, py
- src/textual/selection.py: path components match issue terms, source file; bm25 rerank score=13.068; matched issue terms: scroll, there, s, py, container, first
- src/textual/widgets/_tabs.py: path components match issue terms, source file; bm25 rerank score=12.672; matched issue terms: scroll, center, problem, there, s, can
- tests/snapshot_tests/snapshot_apps/scroll_to_center.py: filename appears in issue text, path components match issue terms, test file; bm25 rerank score=3.510; matched issue terms: scroll, center, s, py, snapshot, visible

Attempts:
Attempt 1: success=False
File: src/textual/widget.py
Result: execution_error
Error:
Command '['git', 'clone', '--local', '--no-hardlinks', '/home/morganbest/.repopilot/repos/Textualize-textual', '/tmp/repopilot-Textualize-textual-mptzoxia']' returned non-zero exit status 128.

Token usage: 11330/100000
