### ISSUE TITLE
Progress bar widget

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2316]
We need a progress bar widget.

I think it should broadly be similar to Rich's progress bar, but with theme colors.

Rich Progress supports a lot of options. I don't think we necessarily have to replicate all of them in Textual. But we do need a solid foundation. So it should calculate speed and time remaining etc.

Perhaps we start of with a simple rendering of percentage plus bar.

Open to suggestions.

**Comment by rodrigogiraoserrao** [comment]
Should've been closed with #2333
