### ISSUE TITLE
Make widget event handlers private

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2324]
We generally don't want widget event handlers to be in the docs, so we should prefix them with an underscore.

**Comment by davetapley** [comment]
@willmcgugan FYI this broke something downstream:
- https://github.com/mitosch/textual-select/issues/5

Any thoughts for the maintainer over there, calling the private seems 🤢 but not sure of other approach? 🤔

**Comment by willmcgugan** [comment]
Answered on the other repo. BTW we have a native [Select](https://textual.textualize.io/widget_gallery/#select) control now. Hats off to @mitosch for his awesome implementation.
