### ISSUE TITLE
Input auto-complete

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2330]
We need a way to suggest auto-complete for the Input widget.

The auto-complete I'm thinking of is when you start typing and a the rest of the word or phrase appears in front of the cursor. Something like this:

You hit `T` and the text `extualize` appears with a different style in front of the cursor:

T*extualize*

Hitting `e` adds *xtualize*

Te*xtualize*

Pressing escape cancels the auto complete, pressing return accept it.

## The tricky part

The obvious solution would be to have a callback that takes the text in the input, and returns a potential auto-complete. However, we want this to be asynchronous. i.e. the callback should be able to do non-blocking work without making typing slow.

The probably probably requires the use of workers. Please discuss with @willmcgugan re the proposed solution.

**Comment by willmcgugan** [comment]
@darrenburns I do find that annoying. But return to accept the auto-complete seems to be common. If you don't want to accept the auto-complete, you can press escape to dismiss it first.

**Comment by TomJGooding** [comment]
> The auto-complete I'm thinking of is when you start typing and a the rest of the word or phrase appears in front of the cursor

Hope you don't mind me sticking my nose in... might this also allow a way showing a list of possible completions? This can be  helpful when you might not know _exactly_ what you're looking for.

(I'm aware there's some crossover with darren's personal autocomplete project here, so don't want to step on any toes!)

**Comment by willmcgugan** [comment]
I think we will have a builtin version of Darren's autocomplete at some point. Which might extend this feature. But its also nice to have this in isolation.

**Comment by mistotebe** [comment]
Consider the quick typing (mindless) user looking elsewhere doing data entry.

If it's a closed set of options, it's fine to have `enter` to accept, if it's free text, what if they did try and write 'te'? There should be a canonical way for them to input exactly that, regardless of possible completions, I guess making sure to hit `escape` works for that... I think you mention insipration by vue etc. how do they handle this?

**Comment by rodrigogiraoserrao** [comment]
I think we kind of _have_ to accept auto-completion on <kbd>Enter</kbd>. (Independently of also allowing <kbd>right</kbd> to accept the suggestion or not.)

Suppose we _didn't_.
Someone opens an app with an input, starts typing, and sees an auto-completion suggestion.
The user presses <kbd>Enter</kbd> to accept the suggestion.
Instead of accepting it, the user unintentionally triggered the message `Input.Submitted` which may have consequences that are difficult to recover from just because the user used the wrong keybinding.

The other side of this story is "the user wanted to submit _exactly_ what was typed, even though there is a suggestion showing, and upon pressing <kbd>Enter</kbd> the suggestion is accepted instead of submitting the input".
This is much easier to recover from because the user only has to delete the unwanted characters.

**Comment by darrenburns** [comment]
@rodrigogiraoserrao That's user error. The auto-completion is dimmed out, so it doesn't appear to the user that pressing enter will submit the entire completion suggestion.

This is how it works in both `zsh` and `fish` and many other shells. `prompt-toolkit` also takes the exact same approach.

<img width="572" alt="image" src="https://github.com/Textualize/textual/assets/5740731/31a31fb5-7f60-449c-8c0e-d1f30a1bf70b">

If I press enter in the image above, it submits "env TEX". If I press right or tab it fills in the remainder of the command. Additionally if I press Option+right, it fills a single word.

To me, if we implement it this way it's just doing it the opposite of how these things generally work in terminals and is really counterintuitive. I've never seen the approach suggested in this thread anywhere before personally and it doesn't feel like it'd be intuitive for terminal users.

**Comment by willmcgugan** [comment]
That makes more sense to me. I've always hated return to auto-complete. Often leads me to entering things I didn't intend to.

**Comment by rodrigogiraoserrao** [comment]
After an initial attempt at implementing this in #2604 in commit 75606c8 we realised I was doing only half the work.
The main point is that I should think of an API that would allow users to hook up their ways of getting suggestions, instead of what I did, where I assumed people would provide a static list of suggestions when the input was created.

Will suggested I create a `Suggester` class that could be composed with `Input`. The `Suggester` class is what users need to implement to let them get suggestions in whatever way they want.

**Comment by mistotebe** [comment]
On many systems, when doing case-insensitive suggestions/completions, they are case-respecting (i.e. if there is a unique case-matching option, it is suggested first). I can see that's not how #2604 works, are you open to reconsidering this?

**Comment by TomJGooding** [comment]
I think this is what [mistotebe](https://github.com/mistotebe) means by case-respecting here (please correct me if I'm wrong!)

| Input Value | Current Suggestion | Desired Suggestion |
|:-----------:|:------------------:|:------------------:|
|     case    |     Case Proper    |     case lower     |
|     CASE    |     Case Proper    |     CASE UPPER     |
|     Case    |     Case Proper    |     Case Proper    |

```python
from textual.app import App, ComposeResult
from textual.suggester import SuggestFromList
from textual.widgets import Input

options = ["Case Proper", "case lower", "CASE UPPER"]


class MyApp(App[None]):
    def compose(self) -> ComposeResult:
        yield Input(suggester=SuggestFromList(options, case_sensitive=False))


if __name__ == "__main__":
    app = MyApp()
    app.run()
```

**Comment by rodrigogiraoserrao** [comment]
@mistotebe can you point me to some notable systems that do this?
I am not convinced yet that this is worth the trouble and the increased code complexity, but if I see a couple of real-world examples I might change my mind and see what we can do.

**Comment by mistotebe** [comment]
The wizard setting up your .zshrc on first use (zsh-newuser-install) suggests this as one of its default settings and that's the one I've been using daily, there were other systems that did the "check for a literal match and fallback to a case-insensitive match if not found", can't remember examples. I'll try and remember which ones they were.

My suggestion would be to change the Suggester implementation to pass the original string in and let get_suggestion handle it. As an optimisation, SuggestFromList could do this, sligthly simplifying get_suggestion's work:
```python
        self._suggestions = list(suggestions)
        self._for_comparison = self._suggestions
        if self.case_sensitive:
            self._for_comparison.extend(suggestion.casefold() for suggestion in self._suggestions)
```

**Comment by rodrigogiraoserrao** [comment]
The rationale for the way it works currently is that the developer has to worry as little as possible about getting the completion, but maybe getting the original text value and then worrying about case sensitivity inside `get_suggestion` makes sense.

**Comment by robderon** [comment]
Hello ,
not sure I'm in the right place but i'm trying to change the key used for accepting the auto-completion. on macbooks the right arrow key is small and far away. I'd like to be able to change this key to tab, is this possible ?

**Comment by TomJGooding** [comment]
I'd caution that <kbd>Tab</kbd> is a bit of a reserved key in Textual, as it is used to focus the next widget.

But you could create a custom `Input` widget and add your own binding copying the code from the [cursor right action](https://github.com/Textualize/textual/blob/244e42c6fcfd4989de08c57ffc10db1e5fc87add/src/textual/widgets/_input.py#L617-L623).
