### ISSUE TITLE
Setting `show_root` to `True` raises a `KeyError`

### ISSUE THREAD

**Issue by lllama** [Textualize/textual#2363]
```py
    def compose(self):
        dir_tree = DirectoryTree("./src/routes")
        dir_tree.show_root = True
        yield Header()
        with Horizontal():
            yield Logo()
            with TabbedContent("Config", "Routes", "Server"):
                yield Config(self.config)
                yield dir_tree
                yield Label("hello")
        yield Footer()
```
setting `show_root` to `True`. raises the following error:
`KeyError: "No 'directory-tree--folder' key in COMPONENT_CLASSES"`

Diagnose output:

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.20.1 |
| Rich    | 13.3.3 |

## Python

| Name           | Value                                                                                                    |
|----------------|----------------------------------------------------------------------------------------------------------|
| Version        | 3.11.0                                                                                                   |
| Implementation | CPython                                                                                                  |
| Compiler       | Clang 14.0.0 (clang-1400.0.29.202)                                                                       |
| Executable     | /Users/felixingram/Library/Application Support/hatch/env/virtual/sanic-kit/1YPPa8fF/sanic-kit/bin/python |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 22.4.0                                                                                                |
| Version | Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 |

## Terminal

| Name                 | Value                              |
|----------------------|------------------------------------|
| Terminal Application | WezTerm (20230326-111934-3666303c) |
| TERM                 | xterm-256color                     |
| COLORTERM            | truecolor                          |
| FORCE_COLOR          | *Not set*                          |
| NO_COLOR             | *Not set*                          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=203, height=46 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 203                  |
| is_terminal    | False                |
| encoding       | utf-8                |
| max_height     | 46                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
To narrow it down a wee but, this only happens if `show_root` is changed before the DOM is fully-loaded (for example, doing the same in `on_mount` is fine). Looks like `watch_show_root` is a bit too eager.
