### ISSUE TITLE
Remove ScrollableContainer

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2369]
I don't think we need a base class here (sorry dave).

The Vertical and Horizontal scrollable containers should have the key bindings, without inheritance.

**Comment by davep** [comment]
In a subsequent conversation, reviewing why we introduced this last week and the possible use cases for it, we've decided that it will remain. However, before closing this issue, I'm going to have one last wander over where it's used and how it's documented and be sure it's all fine.
