### ISSUE TITLE
Create a RadioSet-like interface for checkbox groups

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#2379]
When using checkboxes in forms, they often appear in groups. I want to be able to say, “given this CheckboxSet, which options are currently active?”

Right now, to find this out, we'd have to do some DOM querying and it doesn't feel very ergonomic to work with.

RadioSet has a nice interface, where I can basically query for the RadioSet widget and ask find out which one is selected without having to worry about how things are structured in the DOM.

I think they work well when standalone, treated as a boolean - but are a little unwieldy when you have groups of them.

**Comment by darrenburns** [comment]
On further discussion, it may not even be a CheckboxSet we need. The problem is: we need a way of selecting multiple items from a list. The solution: 🤷

**Comment by willmcgugan** [comment]
An extension to OptionList feels like it would cover that use case.

**Comment by davep** [comment]
See also #2518.
