### ISSUE TITLE
Superfluous vertical scrollbar for Tabs widget since 0.21.0

### ISSUE THREAD

**Issue by ankraft** [Textualize/textual#2385]
It seems that since 0.21.0 a "Tabs" widget always displays a vertical scrollbar, even when no content is present in one of the tabs.
The extra size of the scrolling area is 3 lines, the same as the size of the tab area (2 lines + 1 underline).

![screenshot tabs extra vertical scrollbar](https://user-images.githubusercontent.com/8394617/234603510-4051616b-32ad-4c84-bc9e-2cdfeb4f4863.png)

Running on MacOS 13.3 and iTerm 3.4.19.

Thanks for the continuous developments and support!

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan following up on my first comment in the PR, this is more evidence in favour of setting the default width and height of containers to `1fr`.

**Comment by davep** [comment]
Thanks, this looks like an expected while also unintended consequence of some of the changes we're making to the default styling of various containers. But... it feels unlikely that this would affect `Tabs`; could it be that you're actually using `TabbedContent`?

Either way, having more of a chat about it here now, expect a 0.21.1 fairly soon; we're likely going to roll this particular aspect of the change back.

**Comment by ankraft** [comment]
Thanks a lot for the quick feedback. Looking forward to 0.21.1 ;)

> could it be that you're actually using TabbedContent?

No, for the screenshot I removed all the actual containers (except the header, footer and the Tabs) from the app. The Tabs widget I added like this in `compose()`:

``` python
yield Tabs(Tab('Resources', id = ...),
           Tab('Requests', id = ...),
           Tab('Registrations', id = ...),
           Tab('Configurations', id = ...),
           Tab('Infos', id = ...),
           Tab('About', id = ...))
```

**Comment by davep** [comment]
> No, for the screenshot I removed all the actual containers (except the header, footer and the Tabs) from the app.

@ankraft Hmm, that's sort of unexpected. Do you have a stand-alone minimal example you could post that shows the problem you're seeing, just so we can be sure that the incoming fix will address this?

**Comment by ankraft** [comment]
@davep Ah, perhaps it is not the `Tab` widget, it seems to be the `ContentSwitcher`:

```python
from textual.app import App, ComposeResult
from textual.widgets import Tabs, Tab, ContentSwitcher

class TabsApp(App):

    def compose(self) -> ComposeResult:
        yield Tabs(Tab('1'), Tab('2'))
        yield ContentSwitcher()

if __name__ == "__main__":
    app = TabsApp()
    app.run()
```

**Comment by davep** [comment]
> it seems to be the ContentSwitcher

@ankraft Bingo, that's the sort of thing I was expecting to see; in effect you'd sort of made your own `TabbedContent`.

**Comment by ankraft** [comment]
@davep Yes, I did. At that time I needed some extra activate/deactive procedures. Now I will try to use `TabbedContent`. Thanks again!

**Comment by ankraft** [comment]
@davep I tried to convert the app structure to `TabbedContent` but have problems with presenting Containers in a `TabPane`(basically they are not showing content at all or only some content, depending whether I use version 0.20.1 or 0.21.0).

The example code:

```python
from textual.app import App, ComposeResult
from textual.widgets import TabbedContent, TabPane,Label
from textual.containers import Vertical

class ExampleApp(App):

    def compose(self) -> ComposeResult:
        with TabbedContent():
            # works fine
            with TabPane('a'):
                yield Label('1')
                yield Label('2')
                yield Label('3')
            
            # doesn't show
            with TabPane('b'):
                with Vertical():
                    yield Label('1')
                    yield Label('2')
                    yield Label('3')
            
            # shows "1" and "2", but not "3"
            with TabPane('c'):
                yield Label('1')
                with Vertical():
                    yield Label('2')
                yield Label('3')

if __name__ == '__main__':
    app = ExampleApp()
    app.run()
```

In the application I am working on I inherit from `Vertical` because it manages a more complex layout displaying a list and data in multiple views (using `Container`). This works fine with my "self-made" `TabbedContent` in 0.20.1 .

**Comment by rodrigogiraoserrao** [comment]
@ankraft let me suggest you move this to the discussions or to the Discord server, as this has evolved into something unrelated to the original issue.

@davep, if you disagree, feel free to override my comment and reply here.
