### ISSUE TITLE
Issues with in-demo CSS code display — pull request welcome?

### ISSUE THREAD

**Issue by hartwork** [Textualize/textual#2389]
Hi, thanks for making textual and sharing it as Open Source! :pray: :+1: 

When I played with `python -m textual` today, I noticed that the CSS section — after scrolling to the bottom — …

![textual_Screenshot_20230426_175034](https://user-images.githubusercontent.com/1577132/234631384-215978cf-c9b3-47f7-b6af-1641d264c5c7.png)

…makes it _appears_ as if `OptionGroup {` was the last of 50 lines of the [file `demo.css`](https://github.com/Textualize/textual/blob/4148b1d4501f405eac9c74485ff876ffc8201ca7/src/textual/demo.css#L50). From a user point of view it felt broken and unintended so I had a closer look to find that:
- commit e419a0821cda7c5860c171a20c09034daaf82dea added explicit `[:50]`
- the same commit resolves use of `EXAMPLE_CSS` and that variable is now unused.

I would like to make one or two pull requests dropping the `[:50]` and dropping unused variable `EXAMPLE_CSS`.
Would that be welcome, should it be one or two, or would you rather quickfix this yourself?

Thanks and best, Sebastian

**Comment by rodrigogiraoserrao** [comment]
Hey @hartwork, thanks for reaching out. I agree that that looks a bit misleading, although _technically_ the prose above says that it is just an excerpt of the CSS.

I guess you could make a PR dropping the slicing of the CSS to just display the whole app CSS, assuming it is not a ridiculously long CSS file.

If it looks like _too much_ CSS, I suggest you split on `"\n\n"`, pick a couple of sections, and then join them back together with `"\n\n"`.
A single PR should be fine.

**Comment by hartwork** [comment]
@rodrigogiraoserrao here you go: #2393
