### ISSUE TITLE
Is this the desired behavior?

### ISSUE THREAD

**Issue by ZeroIntensity** [Textualize/textual#242]
ive been experimenting with textual for a little bit, and i came across something a bit weird with view docking.

when you run the code below, everything works just fine. it places the header at the top, footer at the bottom, and the placeholder on the left.
```py
class MyApp(App):
    async def on_mount(self) -> None:
        await self.view.dock(Header(), edge = "top")
        await self.view.dock(Footer(), edge = "bottom")
        await self.view.dock(Placeholder(), edge = "left", size = 30)
```
but, when you switch out the header and footer for a different widget (such as placeholder), only one widget is displayed (and spans across the entire screen).

```py
await self.view.dock(Placeholder(), edge = "top") # this is the only widget on screen!!
await self.view.dock(Placeholder(), edge = "bottom")
await self.view.dock(Placeholder(), edge = "left", size = 30)
```

i was actually able to fix this by manually defining the size, but then textual seemed to start ignoring the size (unless the edge is right or left, then it resizes on the x axis)

```py
await self.view.dock(Placeholder(), edge = "top", size = 10)
await self.view.dock(Placeholder(), edge = "bottom", size = 10)
await self.view.dock(Placeholder(), size = 30) # now the size is ignored
```
it seems the size parameter has different effects on widgets as well.
for example, when you run the code below, the third placeholder isnt shown at all. 

```py
await self.view.dock(Placeholder(), edge = "top", size = 20) # now takes up about 60% of the screen
await self.view.dock(Placeholder(), edge = "bottom", size = 10)
await self.view.dock(Placeholder(), size = 30, edge = "left") # this isnt shown at all
```
why is it that when i change the third one, it resizes on the x axis and doesnt affect the others, but when i change the first one, it resizes on the y axis and overwrites the third one?

again, im not sure if this is a bug or not. if it isnt, could you please clarify whats happening here?
note that i am running python 3.8 on ubuntu 20.04 lts

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
