### ISSUE TITLE
The borders, buttons, scrollbar rendered with artifacts on macOS

### ISSUE THREAD

**Issue by certik** [Textualize/textual#2435]
I tested Frogmouth in the default terminal on macOS Monterey on Apple M1 Max, here is what I can see:

<img width="682" alt="Screen Shot 2023-04-30 at 9 57 43 PM" src="https://user-images.githubusercontent.com/20568/235404806-b4f0f624-4745-4b9b-b02f-4df91aa2217f.png">

As you can see, there are many imperfections in the rendering. So far I noticed the following issues:

* The blue border in the help screen is a "dashed line"
* The "Close" button has the border inside the button
* The light blue area with the text "Frogmouth v0.3.2 Help" has black lines into it; so does the gray area with the text "Navigation keys"
* The scrollbar has weird tiny blue lines and black lines in it

I assume these are caused by a combination of my terminal and the (default) fonts.

Is there some documentation what settings and fonts to select (and how) for each terminal, to get good rendering results?

**Comment by certik** [comment]
Indeed, the link https://github.com/textualize/textual/blob/main/FAQ.md#why-doesnt-textual-look-good-on-macos answers this.

I tried kitty and indeed the rendering is fixed there, none of the above issues appear there. However, scrolling does not work there: https://github.com/Textualize/textual/issues/2436.

**Comment by davep** [comment]
Closing as answered by FAQ.

**Comment by holdenweb** [comment]
> Indeed, the link https://github.com/textualize/textual/blob/main/FAQ.md#why-doesnt-textual-look-good-on-macos answers this.

Unfotunately that link is a 404.

**Comment by certik** [comment]
Yes, a reminder to always use hashes for github URLs. It got moved here: https://github.com/Textualize/textual/blob/e68e6e37b546c8c7d760bc2ffd7fa8cfa3064907/docs/FAQ.md#why-doesnt-textual-look-good-on-macos

**Comment by willmcgugan** [comment]
We moved the FAQ in to the docs. 

https://textual.textualize.io/FAQ/#why-doesnt-textual-look-good-on-macos
