### ISSUE TITLE
Add a way to load a new directory in DirectoryTree

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2448]
- We need a way to change the directory root (and refresh) a DirectoryTree. 
- Related: we need a way to refresh the current directory.
- We have a `load_directory` method, which I think should be private.

**Comment by davep** [comment]
This is pretty much a duplicate of #2056

**Comment by davep** [comment]
Making a note of part of a conversation yesterday: for the moment the "refresh" will be for the `DirectoryTree` as a whole. Ideally we'd like to add the ability to refresh an individual directory within the tree. To do that, however, `Tree` itself will need to be updated to allow for a node's children to be removed (and, indeed, it would be useful if `Tree` supported node removal).
