### ISSUE TITLE
Add the ability to remove `Tree` nodes

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2462]
In part motivated by #2448, although I think the request has popped up before: it would be useful if `Tree` had a `delete_node` method to go along with `add_node`.

**Comment by tscholak** [comment]
Is there a workaround? Afaik, children of a node are currently immutable. Is it therefore recommended that the tree is cleared and reconstructed whenever one needs to remove nodes?

**Comment by davep** [comment]
@tscholak Short of messing around in the internals of the `Tree` (as it stands until this issue is handled), that's probably the way to do it right now, I'd imagine.
