### ISSUE TITLE
Document the `Screen` result system

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2467]
In PR #2321 we introduced typed screens and the ability to "return" a result from a screen. This was added but not documented as we wanted to see how it panned out. Having now successfully moved Frogmouth over to using this approach for its input dialogs, I think we're happy with how this works.

It's now time to document this in the guide.

**Comment by willmcgugan** [comment]
Done https://textual.textualize.io/guide/screens/#returning-data-from-screens
