### ISSUE TITLE
Confirm the state of `has_focus` when `on_focus` and `on_blur` fire

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2476]
This is more an issue for us to consider and confirm the current behaviour of `on_focus` and `on_blur` in respect to the state of `has_focus` when those event handlers fire.

Right now, for reasons that seem fairly obvious, when `on_focus` fires `has_focus` will be `False`, and on the other side when `on_blur` fires `has_focus` will be `True`. This has some ramifications for any code that might not be *in* those handlers, but which is called form those handlers, and which makes decisions based on the state of `has_focus` (as an example: perhaps dealing with some values within a cache where the state of `has_focus` is part of the key).

I can see that it makes sense that it works this way at the moment, but I wonder if this is the effect we actually want.

Code to play with/confirm the current behaviour:

```python
from textual.app        import App, ComposeResult
from textual.containers import Grid, Vertical
from textual.widgets    import Header, Footer, Button, TextLog

class FocusLogButton( Button ):

    def log_focus( self, handler: str ) -> None:
        self.screen.query_one( TextLog ).write(
            f"{handler} - {self.id=} - {self.has_focus=}"
        )

    def on_focus( self ) -> None:
        self.log_focus( "on_focus" )

    def on_blur( self ) -> None:
        self.log_focus( "on_blur" )

class KnowingFocusApp( App[ None ] ):

    CSS = """
    Grid {
        grid-size: 5;
        align: center middle;
    }
    """

    def compose( self ) -> ComposeResult:
        yield Header()
        with Vertical():
            with Grid():
                for n in range(25):
                    yield FocusLogButton( str( n ), id=f"button-{n}" )
            yield TextLog()
        yield Footer()

if __name__ == "__main__":
    KnowingFocusApp().run()
```

**Comment by davep** [comment]
In conversation with @willmcgugan about this, the feeling is that when `on_focus` is called, `self.has_focus` should be `True` by that point, and when `on_blur` is called, `self.has_focus` should be `False`. This is likely best done by removing the setting of `has_focus` from `Widget._on_focus` and `Widget._on_blur` and moving the setting into `Screen.set_focus`, ensuring the correct value is set for each widget (the one getting focus, the one having focus removed) before the relevant message is posted to the widget.

**Comment by willmcgugan** [comment]
The current behavior is a little counter-intuitive. But it doesn't seem to cause any issues in practice.

I can see good reasons for changing it, but also valid reasons for leaving it.

I think we will leave this until somebody encounters an issue with current behavior.
