### ISSUE TITLE
Fix documentation for OptionList

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2486]
The documentation for `OptionList` looks odd, specifically the sub-subsection "Common message properties". [Here](https://textual.textualize.io/widgets/option_list/#common-message-properties).
Not only the TOC headers but also the contents of those H4 headers.

I think we're trying to use some `mkdocstrings` feature but we failed. It should be fairly straightforward to fix.

**Comment by davep** [comment]
For what it's worth, I regenerated the documentation as of when `OptionList` was added 0be094cf4ae7349ecd7d1b304d7cf5a2e86ad160 and this is how it looks:

![Screenshot 2023-05-05 at 08 52 34](https://user-images.githubusercontent.com/28237/236404413-ca2f7654-0a3f-4f80-b60a-4ebda9baa08e.png)

It would seem I used a mkdocsstrings feature that either did work but no longer works, did work but now doesn't in any subsequent changes relating the the widget guide, or still works but doesn't work well with any subsequent template changes (have there been any?).

**Comment by rodrigogiraoserrao** [comment]
I am not sure if there have been template changes that affect the output you are showing, but the fact that the whole `OptionList` API is shown later means that this you are showing + the reference interfere with each other and the TOC (on the right in a browser) has some issues.

Thus, my proposed solution (in #2490) is to just get rid of this intermediate bit.
No other widget lists their message's attributes in the "Messages" section either way, so this will homogenise the documentation.
