### ISSUE TITLE
Create base `TreeMessage` for tree messages?

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2487]
`OptionList` has a `OptionMessage` that is inherited by the two `OptionList` messages.
Is it worth doing the same for the tree messages? There are 4 messages whose code is exactly the same, the only thing that changes is the name of the class.

**Comment by rodrigogiraoserrao** [comment]
> IIRC I made that change once but it got reversed. Might be worth looking back through history.

You are right, and I was the one who removed the base class 😆  https://github.com/Textualize/textual/commit/f34685b18fac829cf562513ec98797ccdae878aa

> I think the objection was to do with impact on documentation, so perhaps we're in a better place now.

I see the point. It isn't _super_ obvious what attributes the `OptionList` messages have.
Maybe if we add a sentence in the docstrings for those messages to check the base class, then we can inherit from those messages and we can, once more, have a `TreeMessage` base class.

Thoughts, @willmcgugan?

![Untitled](https://user-images.githubusercontent.com/5621605/236292880-2fda7ba2-7440-4d9f-a9cc-043509fe9f78.png)

**Comment by willmcgugan** [comment]
I think with @davep 's change to the `@on` decorator it makes sense to have common base classes.

The docs issue is annoying.

**Comment by willmcgugan** [comment]
Exactly. The indirection means that some people will miss the attributes in the base class.

**Comment by willmcgugan** [comment]
It probably does make some sense to have a common base class. But it doesn't seem all that useful: I can't see a reason why you would want to respond to multiple tree events in a single handler.

Closing this, because it just doesn't seem worth changing, unless we have an identiable need for it.
