### ISSUE TITLE
Revise documentation of default values for (class/module) attributes

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2488]
Right now, and ever since PR #2329, class and module attributes show their default values in the documentation, which isn't always a great thing to do.

See if we can hide those by default, and only show the ones that we really care about? (E.g., the types exported in the "Types" API page, potentially `DEFAULT_CSS`, etc.)

cc @davep although I'm 99.9999% sure he'd see this either way.

**Comment by willmcgugan** [comment]
It's not a bad idea. Although I'd worry it may be "too much information" for some folks.

Closing for now, but it is still on the cards for a future update.
