### ISSUE TITLE
CTRL+C can't exit APP when stopwatch is running in stopwatch.py

### ISSUE THREAD

**Issue by zhajio1988** [Textualize/textual#2492]
I start stopwatch in example textual/docs/examples/tutorial/stopwatch.py, i want to exit the APP, but CTRL+C can't exit the APP.
Sometimes, when i execute the stopwatch.py, and next use CTRL+C exit the APP, it can't work, i don't know why?

**Comment by davep** [comment]
I'm testing here with the latest version of Textual, on macOS, and not seeing this effect at all. Could you please post the output of `textual diagnose`?

**Comment by zhajio1988** [comment]
@davep 
How to use textual diagnose？

**Comment by davep** [comment]
Assuming you have [the development version of Textual installed](https://textual.textualize.io/getting_started/#installation), in your environment run `textual diagnose`; it's one of the [devtools commands](https://textual.textualize.io/guide/devtools/).

**Comment by zhajio1988** [comment]
@davep 
OOPS， i don't have development version.

**Comment by TomJGooding** [comment]
> I use blow cmd to install development version `/ic/app/c7/miniconda/envs/python3.8/bin/pip install textual[dev] --target=/taishan/app/c7/miniconda/envs/python3.8/lib/python3.8/site-packages/`, but when i execute `textual diagnose` on my terminal, it reports `bash: textual: command not found`. I don't know why.

Sorry to [stick my oar in](https://dictionary.cambridge.org/dictionary/english/put-stick-oar-in), but you've obviously managed to install `textual` in the first place, so try retracing your steps and install `textual[dev]` in the exact same way?

This isn't an issue with Textual - you can't really expect help with the way you're managing your environments.

**Comment by zhajio1988** [comment]
@TomJGooding 
Sorry for this mistake. I will reinstall the package.

**Comment by zhajio1988** [comment]
@davep 
Hi Dave
Below is textual diagnose outputs:
```
<!-- This is valid Markdown, do not quote! -->
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.23.0 |
| Rich    | 13.3.5 |

## Python

| Name           | Value                                       |
|----------------|---------------------------------------------|
| Version        | 3.8.3                                       |
| Implementation | CPython                                     |
| Compiler       | GCC 7.3.0                                   |
| Executable     | /home/jiongz/python_vir_env/_env/bin/python |

## Operating System

| Name    | Value                              |
|---------|------------------------------------|
| System  | Linux                              |
| Release | 3.10.0-957.el7.x86_64              |
| Version | #1 SMP Thu Nov 8 23:39:32 UTC 2018 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | *Not set*      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=189, height=43 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 189                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 43                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

```

**Comment by zhajio1988** [comment]
@davep 
Another server output is:
```
<!-- This is valid Markdown, do not quote! -->
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.23.0 |
| Rich    | 13.3.3 |

## Python

| Name           | Value                                           |
|----------------|-------------------------------------------------|
| Version        | 3.8.3                                           |
| Implementation | CPython                                         |
| Compiler       | GCC 7.3.0                                       |
| Executable     | /ic/app/c7/miniconda/envs/python3.8/bin/python3 |

## Operating System

| Name    | Value                               |
|---------|-------------------------------------|
| System  | Linux                               |
| Release | 2.6.32-754.el6.x86_64               |
| Version | #1 SMP Thu May 24 18:18:25 EDT 2018 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | gnome-terminal |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=189, height=43 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 189                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 43                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

```

**Comment by davep** [comment]
@zhajio1988 Thanks, nothing looks unusual to me here. However, you say "server", which has me wondering: is there anything else in the mix here? Are you using something like `screen` or `tmux`?

Also, just so I'm 100% clear on the issue: when you say <kbd>Ctrl</kbd>+<kbd>C</kbd> sometimes doesn't work in the stopwatch application, does that mean:

- It sometimes doesn't work but other time does, but only in the stopwatch?
- It always works in other Textual apps?
- It sometimes doesn't work but other times does, in *any* Textual application (for example, what about the demo app, or any of the examples, or your own apps)?

I think if we're going to narrow this down we're going to need some more precision when it comes to recording exactly what you're doing and seeing.

**Comment by zhajio1988** [comment]
@davep 
Hi Dave
Thanks, after re-install Textual , App under textual/examples seems work well.
The problem I found at first with Ctrl+c not exiting was probably because I changed stopwatch.py.
At present, the App I wrote includes DataTable, ProgressBar and other widgets, and use set_interval to update DataTable dynamically. when the database data is not updated, only when on_mount at the beginning, the DataTable is loaded, you can use Ctrl+C to exit, but Once the dynamic addition of row to the end of the table, Ctrl + C can not exit, Tab key can not move the cursor

**Comment by davep** [comment]
@zhajio1988 So, just so I'm clear here: the initial report was that you could not use <kbd>Ctrl</kbd>+<kbd>C</kbd> to exit the the stopwatch example; but actually that isn't the case and, instead, you have a modified version of the stopwatch application and/or an application of your own that can get into a situation where it's unresponsive to any input at all?

Is that correct?

If so, that's really a very different thing altogether.

If this is the case, could I ask that you perhaps start this again, perhaps [over in discussions](https://github.com/Textualize/textual/discussions), and document what your application is doing and what problems you're seeing? It's going to be a *lot* easier to help if you give us all the information about what you're doing and how it isn't working.

**Comment by zhajio1988** [comment]
@davep 
Ok, Dave, i think we can close this ticket. I will open a discussion. Thanks.
