### ISSUE TITLE
Typing warning on `Widget.styles.dock`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2494]
According to the documentation I can set the dock of a widget [in code](https://textual.textualize.io/styles/dock/#python) like this:

```python
self.styles.dock = "right"
```

however, when I do this, I see a warning like this:

![Screenshot 2023-05-05 at 07 43 33](https://user-images.githubusercontent.com/28237/236392443-4d00aaff-83d0-4b9f-b628-b0f31cdd7404.png)

and `mypy` (in strict mode at least) complains:

```
Argument 1 to "__set__" of "DockProperty" has incompatible type "RenderStyles"; expected "Styles"  [arg-type]
```

Simple stand-line bit of code for testing:

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Label

class DockTypeApp( App[ None ] ):

    def compose( self ) -> ComposeResult:
        with Vertical():
            yield Label("Dock")

    def on_mount(self) -> None:
        dock = self.query_one(Vertical)
        dock.styles.dock = "right"
        dock.styles.width = "20%"
        dock.styles.border = ("solid", "red")

if __name__ == "__main__":
    DockTypeApp().run()
```

**Comment by willmcgugan** [comment]
Might be an easy typing fix.

I wouldn't spend too much time on this. If its more than an hour, its probably not worth it.

**Comment by davep** [comment]
`mypy` with the more explicit report saves the day:

```sh
$ poetry run mypy dock_style_type.py
dock_style_type.py:14: error: Argument 1 to "__set__" of "DockProperty" has incompatible type "RenderStyles"; expected "Styles"  [arg-type]
```
