### ISSUE TITLE
Tweak the `on` decorator docs to make it clear events are still available

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2499]
From a question on Discord about `@on`:

> How I can access the Button value if i declare this decorator on a Button.Pressed event?

As I understand it a decorated handler can still have an event argument typed of the correct type, but looking in the docs for `@on` there doesn't seem to be an example of this or anything that makes it explicit that this is supported. For the sake of clarity, we should make sure this is explicitly said and shown.

**Comment by rodrigogiraoserrao** [comment]
Given my current work on #2498 I will take care of this there. I have to change the docs either way.

**Comment by rodrigogiraoserrao** [comment]
And, in case it wasn't clear, _yes_ you still have access to the message if your handler signature accepts it.

E.g.,:

```py
class MyApp(App[None]):
    # ...

    @on(TabbedContent.TabActivated)
    def three(self, message: TabbedContent.TabActivated) -> None:
        print(message.tab.id)
```
