### ISSUE TITLE
Substitute CSS variables

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#251]
To fully implement CSS variables we need to do the substitution within the parser.

This should ideally be done in a way that is transparent for the styles builder.

We may want styles to be nested, i.e. css variables could contain other css variables. Have a look at the implementation, and decide if it is worth doing now.

**Comment by encukou** [comment]
Pardon me for butting in, but... substitution in the parser seems off.
CSS variables ([custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)) allow things like:

```html
<style>
.a {
    --shout-color: red;
}
.b {
    --shout-color: blue;
}
em {
    color: var(--shout-color);
}
</style>

<div class="a">
   Shout in <em>Red</em>!
</div>
<div class="b">
   Shout in <em>Blue</em>!
</div>
```

**Comment by willmcgugan** [comment]
We're not copying browser CSS exactly.  Our implementation is a little more like sass, and we're keeping it simple for now.

**Comment by encukou** [comment]
I see. Sorry for the noise!

**Comment by willmcgugan** [comment]
No problemo!
