### ISSUE TITLE
Add Webhooks for Discord

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2511]
We can get GitHub notifications going to channels for Textual / Rich  / Frogmouth

https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

Suggsted on Dicsord https://discord.com/channels/1026214085173461072/1033752510848053399/1104886087349968987

**Comment by willmcgugan** [comment]
@davep Feels like something you might want to tackle?

**Comment by davep** [comment]
Sounds fun, and if I get stuck I can hassle my son. ;-)

**Comment by davep** [comment]
Now set up for:

- Rich
- Rich-CLI
- Textual
- Frogmouth

We'll add more as other applications and libraries get added.
