### ISSUE TITLE
Validator Framework

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2523]
We need a generic validator framework for inputs.

This should consist of small objects which are passed to Inputs (and other controls), which will check the user as entered something in the expected format and return errors.

Something like the following:

```python
yield Input("A number", validators=[Integer(), Range(0, 10)]
```

The above is just for illustration. Names of the objects TBD.

- Declarative. i.e. You say *what*, not *how*.
- Report human readable error(s).
- Easy to implement.

**Comment by TomJGooding** [comment]
I suppose my thinking is that because there are _so_ many possible contexts for input validation, this parameter should be as flexible as possible. But I appreciate what you're saying about having "the validator generate the error message itself"...

**Comment by TomJGooding** [comment]
I'm sure Textual are way ahead of me on this, but if you are set on passing objects you could borrow some ideas from the [Django Validators](https://github.com/django/django/blob/main/django/core/validators.py).
