### ISSUE TITLE
Console has too much data even when filtering out some categories

### ISSUE THREAD

**Issue by lolbat** [Textualize/textual#2533]
I find it difficult to debug with the Console. I currently run it with system and event disabled.

`textual console -x SYSTEM -x EVENT`

But even then I get far too much information. And I am also concerned that I am missing reports and notices from Textual because there is too much text or I have shut off a category that it was sent to. 

So an error appears but there might be some confirmation that the error was fixed that gets sent to System which I won't see. 

Is it possible to have the Console use tabs to show the results for each category?

**Comment by lolbat** [comment]
Some options

* disable everything except warning, errors, and print statements by default
* add a flag and attribute to enable the other groups

**Comment by willmcgugan** [comment]
We will at some point have dev tools running as a Textual app, so there will be more interactive controls to change the log level.

I'm surprised you get a log of messages if you disable events. What messages do you get?
