### ISSUE TITLE
Textual Console should report working CSS after reporting an error

### ISSUE THREAD

**Issue by lolbat** [Textualize/textual#2534]
Currently when there is a CSS error in Textual you get a very good error report. But when you fix the issue you don't get a report that the CSS processed correctly. 

This may be related to #2533. I have a lot of information disabled and the CSS "all clear" might be getting sent to a category that I have shut off.

**Comment by willmcgugan** [comment]
Suggest we write a green panel to the console whenever CSS has gone from a non-working state to a working state.
