### ISSUE TITLE
Allow private validate and compute methods

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2539]
Following up on #2382 and #2442, and exactly for the same reasons, it also makes sense to allow for validate and compute methods to be private.
Can we implement this feature?

**Comment by willmcgugan** [comment]
I think this is implemented. Need to confirm.

**Comment by davep** [comment]
Grabbing to at least confirm (will look for tests and if none exist, add them).

**Comment by davep** [comment]
Confirmed as *not* implemented.

**Comment by rodrigogiraoserrao** [comment]
For `validate`, I wouldn't be surprised if we had `new_value` -> private validate -> public validate.
For `compute`, I'd raise an error saying you can't have two?

**Comment by davep** [comment]
@rodrigogiraoserrao Aye, I like that flow for `validate`; that makes sense to me.
