### ISSUE TITLE
App keybindings are displayed in the footer of a ModalScreen

### ISSUE THREAD

**Issue by GingerIndustries** [Textualize/textual#2549]
Despite app-level keybindings being disabled when a `ModalScreen` is open, they are still shown in any `Footer`s within it.

**Comment by TomJGooding** [comment]
I _think_ the advice below from @davep on a [similar discussion](https://github.com/Textualize/textual/discussions/1745) might be helpful here, but it a minimal example might help if not?

> Likely your best approach here is to not bind those keys on the app, and to not use the default screen as your main screen. Instead supply your own main screen and bind the keys on that.
> 
> See https://textual.textualize.io/blog/2022/11/26/on-dog-food-the-original-metaverse-and-not-being-bored/#dont-use-the-default-screen for example.

**Comment by GingerIndustries** [comment]
This does work, but I feel like there should be a better way. Closing as completed for now. Maybe add a way to set bindings for the default screen?
