### ISSUE TITLE
How do I do try/except block

### ISSUE THREAD

**Issue by Gcat101** [Textualize/textual#255]
When I make a try/except block it does nothing:

```py
try: self.console.style = f'on {self.input.value}'
except errors.MissingStyle: pass
```

It just quits and throws a regular error.

**Comment by sanders41** [comment]
Are you using the console later on? I'm guessing the issue is the error isn't happening when you think it is.

```py
try:
    self.console.style = f'on {self.input.value}'
except errors.MissingStyle:
    pass

self.console.print("here")  # this wil raise MissingStyle exception, but it is past the try/except block so it isn't caught
```

```py
try:
    self.console.style = f'on {self.input.value}'
    self.console.print('here')  # now the print is inside the try/except so it get caught
except errors.MissingStyle:
    pass
```

**Comment by willmcgugan** [comment]
@Gcat101 I wouldn't set the console style like that. It's designed to be set on the constructor, and should probably be private. You can set the style in a few places, including the `print` method.
