### ISSUE TITLE
Select with OptionsList CSS selector hides all options

### ISSUE THREAD

**Issue by WouterVandeWiele** [Textualize/textual#2560]
Hello all,

While playing around with Textualize, I came across IMHO some suspicious behavior when using the Select and OptionList widgets in the same screen and styling the OptionList.  

> Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed

yes, using filter: `is:issue is:closed css select `, none of the issue titles seem to match.

> Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**

Adding the OptionList CSS style selector, to the CSS class variable, seems to hide all Select items.
It is still possible to select the items, You're just not able to see them.

Minimal working example, switch between the commented CSS variable to see the suspicious behavior:

```python
from textual.app import App
from textual.widgets import Select

options = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
]


class DemoApp(App):

    # CSS = '''
    # Screen {
    #     align: center middle;
    # }
    # '''

    CSS = '''
    Screen {
        align: center middle;
    }
    OptionList {
        background: $panel;
        border: round $primary;
        width: 70%;
        height: 30%;
    }
    '''

    def compose(self):
        yield Select(((x, x) for x in options), allow_blank=False)

if __name__ == '__main__':
    DemoApp().run()

```

I'm running the example on 
- windows 11, Windows Terminal, Version: 1.16.10262.0
- textual  version 0.24.1

Some screenshots:

- normal behavior: ![select_normal](https://github.com/Textualize/textual/assets/30046626/57f279ef-6617-44bf-9c18-361cd3e85a06)
- options disappear when adding the OptionList CSS selector: ![select_bug](https://github.com/Textualize/textual/assets/30046626/25797c2b-fc5c-4f65-8baf-aefef9be2b95)

**Comment by willmcgugan** [comment]
The select overlay is unique in that it is rendered outside of its container. So height 30% is making it invisible.

So the behaviour is expected. If you want the height to be 30% of the screen you could use `height: 30vh`.

**Comment by WouterVandeWiele** [comment]
Indeed, you are right. The relative viewport height work correctly.
Thanks for the fast response!
