### ISSUE TITLE
Publish GPT compatible docs.

### ISSUE THREAD

**Issue by wowitsjack** [Textualize/textual#2573]
We ditched this project as a possible inclusion because the docs are locked up in some horrifically bad webapp with no way to easily extract large amounts of reference data to show code GPTs.

Bard, ChatGPT, Clause all think Textual is a dead project, and output failing useless code because it's too painful to click around into every single tiny little section about every tiny little function instead of just being able to pass the docs into a GPT as usual.

**Comment by willmcgugan** [comment]
Please don't post nonsense like this.
