### ISSUE TITLE
It looks like `on_hide` is not called when a widget is hidden in some way

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2574]
I would expect the following application to crash when the button is pressed:

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Button, Label

class ShouldCrash( Label ):

    def on_hide( self ) -> None:
        _ = 1/0

class NoHideApp( App[ None ] ):

    CSS = """
    Vertical {
        align: center middle;
    }
    """

    def compose( self ) -> ComposeResult:
        with Vertical():
            yield Button( "Press to hide the label below" )
            yield ShouldCrash( "Press the button above me to hide me" )

    def on_button_pressed( self ):
        self.query_one( ShouldCrash ).display = False

if __name__ == "__main__":
    NoHideApp().run()
```

However, when the button is pressed; it doesn't. It would appear that the `Hide` message isn't being sent. Looking in the debug console I don't see the event.

The same is true if I attempt to hide the widget using any of:

```python
self.query_one( ShouldCrash ).display = "none"
self.query_one( ShouldCrash ).visible = False
self.query_one( ShouldCrash ).set_class( True, "hidden" ) # With appropriate CSS to back it up.
```

**Comment by aaronst** [comment]
I may have this wrong, but I think the issue might be in [`_compositor.reflow()`](https://github.com/Textualize/textual/blob/main/src/textual/_compositor.py#L366-L395).

It looks like `self.widgets = widgets` and then `hidden_widgets = self.widgets - widgets` would mean `hidden_widgets` is always empty?

Should it maybe be `hidden_widgets = old_widgets - new_widgets` instead?

**Comment by aaronst** [comment]
It looks like this was introduced [here](https://github.com/Textualize/textual/commit/11d10db1ab9cc723a5f12bf333d22f9b00d5e9a3#diff-3680fc293baa11cb6d4fd3f21fe9b3b0c16c36131ce36524349c1c00e2a85ca2L267-L271), where `hidden_widgets` was set before `self.widgets = widgets`.
