### ISSUE TITLE
AUTO_FOCUS has no effect in most cases

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2578]
Testing with modal02.py in /docs/examples/guide/screens AUTO_FOCUS doesn't appear to work.

Looking at the code, there doesn't appear to be any check that the thing being auto focused is actually focusable. Suspect it is trying to focus some unrelated widget.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao one for you I think

**Comment by rodrigogiraoserrao** [comment]
So we should go over the query results and focus the first thing that is matched by the query and that is focusable, right?
That would be the idea?

**Comment by willmcgugan** [comment]
Exactly.

**Comment by rodrigogiraoserrao** [comment]
AH
_This_ was why `AUTO_FOCUS` didn't break tests before.

**Comment by willmcgugan** [comment]
Yeah, makes sense now.

We could take the easy route of making `AUTO_FOCUS` default to `None`

**Comment by willmcgugan** [comment]
Or we just fix the tests. Yeah, lets just fix the tests.

**Comment by rodrigogiraoserrao** [comment]
> Or we just fix the tests. Yeah, lets just fix the tests.

I'm already fixing the tests o7
