### ISSUE TITLE
Placeholder cycle per app

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2590]
The placeholder stores the current color in a classvar.

This means that a second app will start where the previous app left off. And may return a different color from the first iteration.

Not much of an issue in practice, but in the docs the colors change every screenshot. I think we need a separate cycle per app. Suggest we have an independent sequence for each app instance.

**Comment by rodrigogiraoserrao** [comment]
We already have `reset_color_cycle` as an attempt to fix that, but I don't like it.
Can I get rid of `reset_color_cycle` while I'm at it?

**Comment by willmcgugan** [comment]
Sure

**Comment by willmcgugan** [comment]
You might be able to do this with a WeakKeySet where the keys are apps. Just a thought.

**Comment by rodrigogiraoserrao** [comment]
> You might be able to do this with a WeakKeySet where the keys are apps. Just a thought.

Thanks. I was doing it with a standard dictionary with app IDs as keys.

**Comment by willmcgugan** [comment]
That would work. Downside is that the app IDs wouldn't be removed when the app is deleted.

**Comment by rodrigogiraoserrao** [comment]
But that's also a marginal issue, no?
How many apps will you create and destroy after loading the `Placeholder`..?

**Comment by willmcgugan** [comment]
It's unlikely to be an issue, sure. But its not much more work to do the weak dict. May as well?
