### ISSUE TITLE
AUTO_FOCUS on App should apply to screen

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2594]
If you don't define a screen, there is no way to set `AUTO_FOCUS`. We should make `AUTO_FOCUS` on App apply to the default screen.

**Comment by rodrigogiraoserrao** [comment]
I tought about that but I concluded that if you want a non-default auto focus, you should create your own screen.
The default screen _has_ limitations and is just a convenience, right?

If you still want `App.AUTO_FOCUS`, isn't there a possibility for people to think that `App.AUTO_FOCUS` should apply to all screens in the app?
I suggest:

 - `App.AUTO_FOCUS = "*"` by default;
 - `Screen.AUTO_FOCUS = None` by default;

The auto focus is then taken from the app's and the screen's, with the screen's taking precedence if it is not `None`.

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan pinging you explicitly to ask for your feedback on this ^

**Comment by willmcgugan** [comment]
How then would you disable AUTO_FOCUS on a screen? Set it to empty string?

**Comment by rodrigogiraoserrao** [comment]
After some discussion, we're going with this:

 - `App.AUTO_FOCUS` defaults to `"*"`;
 - `Screen.AUTO_FOCUS` defaults to `None`;
 - Setting `AUTO_FOCUS` to `""` explicitly disables it; and
 - Setting `AUTO_FOCUS` to `None` (on a screen) means we “inherit” the value of `AUTO_FOCUS` from the app.
