### ISSUE TITLE
Pushing a screen should send Leave message

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2606]
If you have an action that opens a screen, it leaves the footer stuck in the highlight state.

I think we need to call `_set_mouse_over(None)` on the current screen when pushing another screen.

**Comment by rodrigogiraoserrao** [comment]
I can't repro this.

**Comment by rodrigogiraoserrao** [comment]
> I suspect you could reproduce this will any app with a footer that launches a modal.

That's it. The original issue wasn't explicit and I was using regular screens. I can repro it when pushing a modal.
