### ISSUE TITLE
How to: Do something busy in the background and show a `LoadingIndicator`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2613]
With [this Discord thread in mind](https://discord.com/channels/1026214085173461072/1106601154944704533/1106606551843733524), and as something that's come up more than once over the past few months, and given we've got some really nice tools in place now to easily tackle the problem: a How To that explains how to do something busy in the background and show a loading indicator while it does it would be a good idea.

**Comment by TomJGooding** [comment]
> ...given we've got some really nice tools in place now to easily tackle the problem

Even easier now with the new `Widget.loading` reactive, so perhaps this  task can be closed (also #2954)?

**Comment by willmcgugan** [comment]
Yeah, good call.

**Comment by TomJGooding** [comment]
Sorry Dave, what do you think a 'how to' could add that isn't already explained in the docs?
