### ISSUE TITLE
Strange behaviour trying to work with opacity in screens

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#2616]
Turning discussion #2611 into an issue to be looked at as a possible bug. There seems to be some strange behaviour when trying to work with opacity in screens - if this functionality should be supported in Textual? 

I've created a simple example below which hopefully demonstrates the issue. The screen only contains a single widget, and the opacity of both the screen and the widget are initially set to 0%. But when you start the app, you'll see there are **two** red boxes (the background colour of the screen) until the actual widget "fades in" to green. When you hit the space bar to trigger the animation to fade in the screen, the second box disappears.

The example from @xyxz-web in the original discussion also shows the duplicated widget issue with a more complex example. 

```python
from textual.app import App, ComposeResult
from textual.screen import ModalScreen, Screen
from textual.widgets import Footer, Static


class OpacityScreen(Screen):
    DEFAULT_CSS = """
    OpacityScreen {
        align: center middle;
        opacity: 0%;
        background: red;
    }

    OpacityScreen > Static {
        opacity: 0%;
        background: green;
        width: auto;
        content-align: center middle;
    }
    """

    BINDINGS = [("space", "fade_in", "Fade in screen")]

    def compose(self) -> ComposeResult:
        yield Static("Widget with fade in animation")
        yield Footer()

    def on_mount(self) -> None:
        widget = self.query_one(Static)
        widget.styles.animate("opacity", value=1.0, duration=2.0)

    def action_fade_in(self) -> None:
        self.styles.animate("opacity", value=1.0, duration=2.0)


class TestApp(App):
    def on_mount(self) -> None:
        self.push_screen(OpacityScreen())


if __name__ == "__main__":
    app = TestApp()
    app.run()
```

**Comment by willmcgugan** [comment]
The issue there is that you have opacity 0% on the *screen*. Which would normally allow content beneath it to show through. There is nothing below the screen so it won't refresh properly.

That's something we should special case for the screen.

If you don't set the screen opacity to 0%, I think the behaviour makes sense?

**Comment by xyxz-web** [comment]
If you disable setting the screen opacity:
1. The duplicate element on the left side still appears
2. The Screen doesn't fade in, just the widget changes colors

**Comment by TomJGooding** [comment]
> The issue there is that you have opacity 0% on the _screen_. Which would normally allow content beneath it to show through. There is nothing below the screen so it won't refresh properly.
> 
> That's something we should special case for the screen.

Thanks Will for confirming, that makes sense.

I've created a quick new attempt below, this time closer to [the original example from the discussion ](https://github.com/Textualize/textual/discussions/2611) where the screen is rather a `ModalScreen`.

I've changed the screen to animate the **background**, while the widget still animates the **opacity**.  Both now should "fade in" at the same time after pressing `space`.

There's what looks like a "blank" box (and I'm also seeing a bit of a flicker). I'm not sure if there is any workaround for that? Or I am just still doing this wrong?

```python
from textual.app import App, ComposeResult
from textual.screen import ModalScreen, Screen
from textual.widgets import Footer, Label, Static

TEXT = """I must not fear.
Fear is the mind-killer.
Fear is the little-death that brings total obliteration.
I will face my fear.
I will permit it to pass over me and through me.
And when it has gone past, I will turn the inner eye to see its path.
Where the fear has gone there will be nothing. Only I will remain."""


class OpacityScreen(ModalScreen):
    DEFAULT_CSS = """
    OpacityScreen {
        align: center middle;
        background: transparent;
    }

    OpacityScreen > Static {
        opacity: 0%;
        background: green;
        width: auto;
        content-align: center middle;
    }
    """

    def compose(self) -> ComposeResult:
        yield Static("Widget with fade in animation")
        yield Footer()

    def on_mount(self) -> None:
        # animate **background** of the screen to "fade in" from
        # transparent to red
        self.styles.animate("background", "red", duration=2.0)
        # animate **opacity** of widgets to "fade in"
        widget = self.query_one(Static)
        widget.styles.animate("opacity", value=1.0, duration=2.0)


class TestApp(App):
    BINDINGS = [("space", "fade_in", "Fade in screen")]

    def compose(self) -> ComposeResult:
        yield Label(TEXT * 8)
        yield Footer()

    def action_fade_in(self) -> None:
        self.push_screen(OpacityScreen())


if __name__ == "__main__":
    app = TestApp()
    app.run()
```

**Comment by willmcgugan** [comment]
Fix incoming...

https://github.com/Textualize/textual/assets/554369/6f93f464-fe03-4272-a565-6f7bb248b2a2

**Comment by TomJGooding** [comment]
I hate to be that guy as I see the work involved in your commit, but guessing there's nothing that can be done about that "ghost" box you can see in the middle at the start of the fade-in?

**Comment by willmcgugan** [comment]
Probably not. The opacity and blend effects are kind of a trick. There's no way to really blend one character in to another.

**Comment by TomJGooding** [comment]
Understood. It's a credit to Textual that you can sometimes forget its all somehow happening in a terminal!
