### ISSUE TITLE
Investigate potential window of opportunity for `DirectoryTree` to double up loading of its `root`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2659]
See https://github.com/Textualize/frogmouth/issues/50 for the motivation to check this. I *think* the recent changes to `DirectoryTree` might have left a window of opportunity for the doubling up of the populating of the `root` node. I can see where it might happen in the code, it would explain the issue that's been seen in Frogmouth, what I can't quite get at the moment is a clean way of forcing the problem.

Take a bit of time to try and write a simple, standalone, "worst case" situation for the mounting of a `DirectoryTree` and try and recreate the issue at will.

**Comment by willmcgugan** [comment]
@davep Was this fixed?

**Comment by davep** [comment]
@willmcgugan After multiple attempts I never managed to write a stand-alone "worst case" version of this; on the other hand with #2660 in Frogmouth I couldn't reproduce the problem.

I think it's safe to close this unless we see it crop up again.
