### ISSUE TITLE
Rendering Binary Files (non utf-8) Breaks Display Outside Container

### ISSUE THREAD

**Issue by juftin** [Textualize/textual#2707]
When trying to display the contents of large binary files inside a `Static` widget, a scroll will break outside that container and mess up the entire Textual display screen. I haven't encountered this issue when scrolling on utf-8 encoded files. 

https://github.com/Textualize/textual/assets/49741340/4deabcc4-54ff-4bca-8125-1373bc6d723e

I encountered this issue on my textual-based project, browsr. There is an active issue for it on that project as well: https://github.com/juftin/browsr/issues/12

<details>
<summary>Textual Diagnostics</summary>

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.25.0 |
| Rich    | 13.3.5 |

## Python

| Name           | Value                                                                                                 |
|----------------|-------------------------------------------------------------------------------------------------------|
| Version        | 3.10.7                                                                                                |
| Implementation | CPython                                                                                               |
| Compiler       | Clang 14.0.0 (clang-1400.0.29.102)                                                                    |
| Executable     | /Users/justinflannery/Library/Application Support/hatch/env/virtual/browsr/MhJJvbGv/browsr/bin/python |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 22.4.0                                                                                                |
| Version | Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.19) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=270, height=25 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 270                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 25                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

</details>

**Comment by willmcgugan** [comment]
Binary files can contain data that may be interpreted by the terminal as control codes. You would need to pre-process these files to render them as text. Try `data = data.replace("\x1b", "^")`

**Comment by willmcgugan** [comment]
How would you want it to be displayed? You could remove the control codes, but it still isn't going to display anything meaningful.

**Comment by willmcgugan** [comment]
If you filter out code points less than 32, you should exclude all escape sequences.

But if you are going attempt to render arbitrary codepoints, you might also end up corrupting the display. Personally, I think your best bet is to detect a possible binary file and display an error, or switch to rendering hex.

**Comment by juftin** [comment]
Yeah, after working on this and trying to filter out all possible escape sequences I'm in agreement here. I ended up just detecting files that can't be properly encoded and raising an error instead. 

<img width="1840" alt="image" src="https://github.com/Textualize/textual/assets/49741340/fb65ccf0-b833-4a28-b052-241a695ef69e">

Thank you for all the control code knowledge Will.

**Comment by davep** [comment]
This seems to have found a good resolution, so closing.
