### ISSUE TITLE
On Windows `set_interval` blocks a full exit of the application until the next interval fires

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2711]
Take this code as an example:

```python
from textual.app        import App, ComposeResult
from textual.containers import Center
from textual.reactive   import var
from textual.widgets    import Label

class WindowsIntervalBugApp( App[ None ] ):

    CSS = """
    Screen {
        align: center middle;
    }
    """

    counter: var[int] = var(0)

    def compose( self ) -> ComposeResult:
        yield Center( Label() )

    def watch_counter( self ) -> None:
        self.query_one( Label ).update( str( self.counter ) )

    def bump_counter( self ) -> None:
        self.counter += 1

    def on_mount( self ) -> None:
        self.set_interval( 30, self.bump_counter )

if __name__ == "__main__":
    WindowsIntervalBugApp().run()
```

When run on macOS, if you run it up and then <kbd>Ctrl</kbd>+<kbd>C</kbd> right away, the application instantly exits. On Windows, the display of the application will close down but you don't get your shell prompt back for around 30 seconds, minus the time it took you to <kbd>Ctrl</kbd>+<kbd>C</kbd>.

I've not tested this yet but I suspect the same would be true with `set_timer` as well.

**Comment by willmcgugan** [comment]
We need to implement a cancelable timer on Windows.

Talk to @willmcgugan before attempting this.
