### ISSUE TITLE
Some inline screenshots in the docs have been broken by `AUTO_FOCUS`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2720]
Following on from #2718: it looks like some other widget examples in the docs are broken after #2527. After a quick `ripgrep` of the docs to find likely candidates, followed by a quick visual inspection of those examples, the following seem to be in need of fixing:

- [x] [`ProgressBar` widget examples](https://textual.textualize.io/widgets/progress_bar/#complete-app-example)
- [x] [`Input` widget example](https://textual.textualize.io/widgets/input/#a-simple-example) (albeit it still works, but the input is in the wrong field now)
- [x] [`Input` gallery entry](https://textual.textualize.io/widget_gallery/#input) (ditto)
- [x] [`ProgressBar` gallery entry](https://textual.textualize.io/widget_gallery/#progressbar)
- [x] [The reactivity examples](https://textual.textualize.io/guide/reactivity/) all still work, but have a <kbd>Tab</kbd> that isn't needed (it works because they're just the one widget that can receive focus anyway)
- [x] [The input focus example](https://textual.textualize.io/guide/input/#input-focus) is likely off from what it used to be, although I think it still sort of works
- [x] [`byte02.py` in the compound widgets example](https://textual.textualize.io/guide/widgets/#__tabbed_16_1) is likely different from what it used to be.
- [x] [`byte03.py` in the compound widgets example](https://textual.textualize.io/guide/widgets/#attributes-down) is very obviously not working any more.

This is likely not an exhaustive list, it's just the result of a very quick `rg "textual.*press.*tab"` within the `docs/`, so I'd say a more comprehensive search would be worth it when it comes to completing this issue.

**Comment by willmcgugan** [comment]
Good catch

**Comment by davep** [comment]
A bit of a wider search turns up nothing else; except for the tutorial. Checking the "blame" for `tutorial.md`, I'm not seeing any edits to the relevant lines post-add-`AUTO_FOCUS`, but on the other hand it's not exactly obvious to me if there is a problem with any of the tutorial screenshots.

@willmcgugan: as the author of the tutorial, would you mind glancing over the published version when you get a moment and check if anything looks wrong with the generated screenshots? I feel they should have problems but it might be the nature of each one means it doesn't stand out like some of the others I've fixed.
