### ISSUE TITLE
A lone `Static` results in a `TooManyMatches` error when using `query_one`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2723]
I've not dived into this beyond knocking up this example to isolate what I saw (about to head out of the door but wanted to record this as a reminder). With 0.27.0 (perhaps before too, just noting the version here for the record), this code:

```python
from textual.app     import App, ComposeResult
from textual.widgets import Static

class OneStatic( App[ None ] ):

    def compose( self ) -> ComposeResult:
        yield Static()

    def on_mount( self ) -> None:
        self.query_one( Static ).update( "Hello, World!" )

if __name__ == "__main__":
    OneStatic().run()
```

results in a `TooManyMatches` error being raised from the `query_one`. With very early testing this only seems to be the case with `Static` (at least, I tested with `Label` and `Button` and they're fine).

I think most people would rightly find this surprising.

**Comment by TomJGooding** [comment]
Looks like the problem is that the new `Tooltip` inherits from `Static`?

**Comment by willmcgugan** [comment]
Ahh. Good call. Might have to think about how to do things like tooltips without being visible in the DOM.
