### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by viega** [Textualize/textual#2724]
It would be super incredibly helpful to have a default that makes all text on any kind of widget selectable, as even in terminal-land, people want to be able to cut-and-paste, especially if their terminal doesn't support clickable links.

**Comment by TomJGooding** [comment]
Looks like the bot missed the mark here! This FAQ entry is probably more helpful: [How can I select and copy text in a Textual app?](https://github.com/textualize/textual/blob/main/FAQ.md#how-can-i-select-and-copy-text-in-a-textual-app)

**Comment by davep** [comment]
Dear gods bot you had one job. ONE! JOB!

**Comment by viega** [comment]
@TomJGooding So that's nice, but most people who have text selection by default in their terminal aren't going to know about it, so it's a core core usability issue.  And, the fact that there's not a uniform way to do it across terminals doesn't even make apps telling people about it reasonable way to mitigate it.

In my view, Textual's notion of "application mode" really needs to have an option to NOT mask selection to not be a usability and support nightmare.  If the current behavior is on-by-default that's fine, but I feel there needs to be an easy button to turn it off, because telling people "your terminal probably has a way to deal with this issue" isn't a solution in my view.

**Comment by willmcgugan** [comment]
@viega Application mode is a feature provided by your terminal emulator, as is selecting text. When an app requests handling mouse input, the terminal emulator will disable text selection. This is not something that Textual or any other TUI library has control over.

**Comment by viega** [comment]
Granted, not recently, but I've written a lot of low-level tty code directly against termios over the years, and I don't remember any such thing. I've gone through the termios man page in detail, and I'm not seeing any such thing.  Could you please point me at it?

**Comment by viega** [comment]
@willmcgugan I'm pretty surprised you closed this out without responding, as you are definitely not correct. Plenty of graphical terminal apps, including most editors, work fine without inhibiting the terminal's ability to cut-and-paste.  In fact, I just took a quick look in the xterm control spec, and there's absolutely a protocol in there for "highlight tracking", for applications that want to support it. 

I was trying to be polite suggesting my memory might be off there being no such "application mode" that gives you no control over the mouse highlighting. But if you're rude enough to brush me off and close thing thing out without responding, I'm happy to be rude enough to more directly say that your understanding of the underlying terminal is just wrong.

**Comment by TomJGooding** [comment]
What control sequence(s) _would_ allow text selection? I'm not trying to start an argument, just interested in how this all works under the hood.

From running a few quick tests, only 1003 worked for me which I think is 'any-event' mode

**Comment by viega** [comment]
> What control sequence(s) _would_ allow text selection? 

It seems like you have to first send 1001, and if you don't follow the protocol the terminal will hang waiting for an event back from you.  See the section "Highlight Tracking" in the [xterm control spec document](https://invisible-island.net/xterm/ctlseqs/ctlseqs.pdf).

> I'm not trying to start an argument, just interested in how this all works under the hood.

I'm not here to argue.  I *was* here to try to help, and am glad you're interested in digging in. Still, I doubt there will be a second time.

> From running a few quick tests, only 1003 worked for me which I think is 'any-event' mode

**Comment by plotski** [comment]
> Application mode is a feature provided by your terminal emulator, as is selecting text. When an app requests handling mouse input, the terminal emulator will disable text selection. This is not something that Textual or any other TUI library has control over.

@willmcgugan Of course Textual has control over it. It is sending escape sequences to the terminal that enable "application mode":
https://github.com/Textualize/textual/blob/df145385e54718284a60985b8a61ff7179a925f1/src/textual/drivers/linux_driver.py#L76-L82

More information on those sequences: https://stackoverflow.com/a/5970472

urwid provides a simple `handle_mouse` switch for the application developer: https://urwid.org/reference/main_loop.html#urwid.MainLoop

It very much depends on the individual application if mouse clicks or mouse selection is more useful. The textual examples make heavy use of mouse clicks while a text editor like Vim wouldn't even know what to do with most of them. The application developer can even make this user-configurable.

I'm surprised Textual, awesomely powerful as it is, doesn't have a simple switch for this.

**Comment by ofek** [comment]
This would be quite useful to have as a core option.
