### ISSUE TITLE
custom namespace on custom message stopped working

### ISSUE THREAD

**Issue by blob42** [Textualize/textual#2725]
My custom message handlers with custom namespaces stopped working with the latest release. 

```
from textual.message import Message

class MyMessage(Message):
    namespace = "myns"

---

In [8]: MyMessage.handler_name
Out[8]: 'on_my_message'

```

EDIT: Not sure if this how I'm supposed to use it. I don't remember if this was documented before. 

Using python 3.10.3, textual v0.27.0

EDIT2:

I could dig a bit more, the namespace has to be passed as argument to the class
including all child classes.

## In v0.26.0 
```python

class MyClass(Message):
    namespace = "myns"

class MySubClass(MyClass):
    pass

```

All messages of MySubClass have the custom namespace so:
`on_myns_my_class`
`on_myns_my_sub_class`

## In v0.27.0 this is what I need to do

```python

class MyClass(Message, namespace="myns"):
    pass

class MySubClass(MyClass, namespace="myns"):
    pass
```

I have to pass the namespace argument to every child class.

**Comment by willmcgugan** [comment]
That is the way to do it. We can look in to making the namespace inheritable.

You may be interested in the new [@on](https://textual.textualize.io/guide/events/#on-decorator) decorator.

**Comment by blob42** [comment]
@willmcgugan Ok thanks for clarifying I don't think it's an issue but might be worth mentioning in the doc.
