### ISSUE TITLE
docs: `Message` not exported from `textual.messages`

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#2745]
Just something minor I spotted while playing with the [Messages up](https://textual.textualize.io/guide/widgets/#messages-up) example in the docs. The code still works but my editor complains that:

> "Message" is not exported from module "textual.messages"
> Import from "textual.message" instead [reportPrivateImportUsage]

Happy to submit a quick PR if deemed worth fixing!

**Comment by willmcgugan** [comment]
Good catch. PR would be great!
