### ISSUE TITLE
`Markdown`: Sections missing in the rendering

### ISSUE THREAD

**Issue by nkh** [Textualize/textual#2781]
50% of this file is missing in the rendering https://github.com/nkh/ftl/blob/main/config/ftl/man/ftl.md, all the other renderes I use renders the missing sections, the link above also shows a rendering.

**Comment by davep** [comment]
Thanks; given that this really comes down to how the Textual `Markdown` widget sees the file you point to, I've moved the issue to here.

**Comment by nkh** [comment]
There is no MD handling on my side, I just run: "frogmouth file-name" on my command line, and 50% is not rendered.

I've given the same input to 4 different renderers and it's the same input I give to pandoc to generate a man page.

**Comment by nkh** [comment]
here's a minimum markdown that doesn't work:


## General *ftl* Commands

        «?»             Show this man page

**Comment by nkh** [comment]
'''
## General *ftl* Commands

        «?»             Show this man page 
'''

**Comment by nkh** [comment]
## General *ftl* Commands
    
            «?»             Show this man page

**Comment by davep** [comment]
Nice job! Thanks. As minimal examples go it doesn't get better than that! 👍

**Comment by davep** [comment]
Thanks for diving in and checking this @TomJGooding, very helpful (good recollection of the other issue too). Looking like `Markdown` does need a bit more love soon (there's a couple or so Frogmouth issues that would benefit from `Markdown` being extended).

**Comment by willmcgugan** [comment]
Going to put this on the ToDo for next week.
