### ISSUE TITLE
DataTable resize not happening on column resize and also resizing oddly

### ISSUE THREAD

**Issue by joshbduncan** [Textualize/textual#2782]
When updating a cell inside of a DataTable, if the width of the updated cell goes outside of the window bounds the DataTable container doesn't resize to allow scrolling so you can't see the updated content. Oddly enough, if you update the cell a second time the DataTable container does resize and the scrollbars are drawn. You can see the Resize method being called from the console on the second update but not the first.

And a weird side-effect of the resize (from a user view/interaction stand point), is the last row of the table which was previously viewable is "covered" by the horizontal scrollbar after the resize. I tried digging into the Widget `refresh()` method, but it seemed like somewhere I shouldn't be messing around without more knowledge of the API.

![CleanShot 2023-06-14 at 22 04 42](https://github.com/Textualize/textual/assets/44387852/09204be9-48d7-4a8c-a889-3ab220502599)

![CleanShot 2023-06-14 at 22 07 21@2x](https://github.com/Textualize/textual/assets/44387852/e0330861-7040-4607-93ed-93faca07b19c)

![CleanShot 2023-06-14 at 22 07 32@2x](https://github.com/Textualize/textual/assets/44387852/a7bf986a-fcf3-4b98-bc7a-503d60ae7c6c)

![CleanShot 2023-06-14 at 22 07 42@2x](https://github.com/Textualize/textual/assets/44387852/18c2e533-3e65-4605-bfff-fdfa2df8a2ad)

The script for this demo is based on your DataTable example script from the docs.

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import DataTable, Footer

ROWS = [
    ("lane", "swimmer", "country", "time"),
    (4, "Joseph Schooling", "Singapore", 50.39),
    (2, "Michael Phelps", "United States", 51.14),
    (5, "Chad le Clos", "South Africa", 51.14),
    (6, "László Cseh", "Hungary", 51.14),
    (3, "Li Zhuhao", "China", 51.26),
    (8, "Mehdy Metella", "France", 51.58),
    (7, "Tom Shields", "United States", 51.73),
    (1, "Aleksandr Sadovnikov", "Russia", 51.84),
    (10, "Darren Burns", "Scotland", 51.84),
]


class TableApp(App):
    BINDINGS = [
        Binding("ctrl+u", "update_records", "Update Records", show=True),
    ]

    def compose(self) -> ComposeResult:
        yield DataTable()
        yield Footer()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.cursor_type = "row"
        table.zebra_stripes = True
        table.add_columns(*ROWS[0])
        table.add_rows(ROWS[1:])

    def action_update_records(self):
        table = self.query_one(DataTable)
        table.update_cell_at(
            (0, 3),
            "[Disqualified]",
            update_width=True,
        )


app = TableApp()
if __name__ == "__main__":
    app.run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.27.0 |
| Rich    | 13.3.5 |

## Python

| Name           | Value                                                       |
|----------------|-------------------------------------------------------------|
| Version        | 3.11.3                                                      |
| Implementation | CPython                                                     |
| Compiler       | Clang 14.0.0 (clang-1400.0.29.202)                          |
| Executable     | /Users/jbd/Dropbox/DEV/projects/renamer/venv/bin/python3.11 |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 22.5.0                                                                                                |
| Version | Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.19) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=79, height=36 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 79                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 36                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by joshbduncan** [comment]
I also noticed that while resizing the terminal window, the refresh method only draws scrollbars if the window width goes below the original row width even when a row has been updated and it's size if larger.

![CleanShot 2023-06-15 at 00 59 17](https://github.com/Textualize/textual/assets/44387852/d12e77d2-fc8b-4525-bad9-62d44a215a4c)

![CleanShot 2023-06-15 at 00 58 36@2x](https://github.com/Textualize/textual/assets/44387852/61bbeabb-0a1a-48d9-b53e-1d968b646d26)


![CleanShot 2023-06-15 at 00 58 48@2x](https://github.com/Textualize/textual/assets/44387852/43fefa5d-4507-456b-8988-2ed2f34ea620)

**Comment by darrenburns** [comment]
Josh, thanks so much for such a detailed report. We really appreciate the time and effort you put into your issues - they really make things so much easier for us to investigate.

**Comment by darrenburns** [comment]
I think I have a fix for this in #2788. When a column was resized, we weren't updating the virtual size of the `DataTable`.

**Comment by joshbduncan** [comment]
@darrenburns, yes I downloaded the PR code and all works well 👍.

The only other question I have (and this may a design decision or more complex than I understand), but when the DataTable (ScrollView) updates and adds the scrollbars in a case where there is plenty of vertical room why add the vertical scrollbar and hide the last row? As you can see in the first screen recording, when the container refreshes your name gets hidden by the horizontal scrollbar which then causes a vertical scrollbar to be added when it wasn't really needed (IMO).

![CleanShot 2023-06-15 at 13 55 19](https://github.com/Textualize/textual/assets/44387852/fe9ca67b-8504-4eff-9467-c44cc85c1522)

By adding the `self.scrollbar_size_horizontal` to the `get_content_height()` calculation within `scroll_view.py` that problem goes away. This is maybe a bit hacky and probably breaks all sorts of things but it was the first thing  came to that made sense.

As you can see in the next screen recording, when the DataTable is updated, only the horizontal scrollbar is added. This seems more natural to me but maybe not everyone else. Either way, I just wanted to share. Cheers!

```python
def get_content_height(self, container: Size, viewport: Size, width: int) -> int:
    """Gets the height (number of lines) in the content area.

    Args:
        container: Size of the container (immediate parent) widget.
        viewport: Size of the viewport.
        width: Width of renderable.

    Returns:
        The height of the content.
    """
    return self.virtual_size.height + self.scrollbar_size_horizontal
```

![CleanShot 2023-06-15 at 13 54 36](https://github.com/Textualize/textual/assets/44387852/33e376a9-892a-49e3-9798-181e7daf6ff0)

**Comment by darrenburns** [comment]
@willmcgugan Any thoughts on the question in https://github.com/Textualize/textual/issues/2782#issuecomment-1593532189? Is this an intentional design choice (the scrollbar blocking the final row), or should the height of the table grow by 1 to accommodate the new horizontal scrollbar?
