### ISSUE TITLE
Add a method of cancelling a widget's animation

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2786]
Currently we can [animate properties of a widget](https://textual.textualize.io/api/widget/#textual.widget.Widget.animate) but there is a situation where things may change just after the animation starts, such that the animation is heading towards a situation that no longer makes sense. The `Underline` of `Tabs` is one good example, where the "slide" animation of the underline might be kicked off, heading towards a tab, that is subsequently removed while the animation is still happening. This can end up with the underline highlight being the wrong size, or even highlighting a tab that's no longer there because all tabs have been removed.

Given this sort of situation could happen with other widgets (an animation is seeking an end result that might not make sense by the time it ends), it would be useful if there was a way of cancelling any current animations on a widget.

**Comment by willmcgugan** [comment]
Suggest something like  `def stop_animation(attribute:str):`

**Comment by davep** [comment]
After puzzling for too long over the way in here, I think it just clicked. The quick and dirty way of doing this seems to be:

```python
del self.app._animator._animations[(id(self), "the_attribute")]
```

With this as the (terrible, of course, but a clue) core concept, I think I can take it from there.
