### ISSUE TITLE
Separate textual-dev from textual

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2798]
We need to keep all dev dependancies in a separate project. This is so that the `textual` library is essentially the runtime for textual app, with a minimal set of dependancies. `textual-dev` will include dependancies required for developing / debugging textual.

There is a repo for [textual-dev](https://github.com/Textualize/textual-dev) and a package on PyPi. The code is stale, so feel free to start afresh.

Ultimately, the `dev` extras will just install `textual-dev`.

This will require 2 PRs: one for `textual` and one for `textual-dev`.

**Comment by amin0616** [comment]
Hey, I was having issues when trying to install the dev version of textual. When just downloading textual with 'pip install textual' it works great and downloads the most recent version 0.28.0. However, when I try installing the dev version of textual with 'pip install "textual[dev]" it downloads the 0.1.18 version and states: WARNING: textual 0.1.18 does not provide the extra 'dev'. and ends up downloading the 0.1.18 version. It also doesn't add a textual.exe at all. Thanks!

**Comment by willmcgugan** [comment]
Hi, this is unrelated to this issue. Would you mind creating a new issue and we will take a look.

**Comment by davep** [comment]
> Ultimately, the dev extras will just install textual-dev.

At first glance, this feels like it would create a circular dependency. Isn't it likely that `textual-dev` will depend on parts of `textual`, and yet the `dev` extras for `textual` will depend on `textual-dev`.

I'll admit to not being too strong on Python packaging, but my initial reaction to this would be to have `textual-dev` depend on `textual` and then when someone wants to develop a textual app they use `textual-dev` as their development dependency, but use `textual` as their deployment/runtime dependency.

**Comment by willmcgugan** [comment]
It should be the same, wether you install `textual[dev]` or `textual-dev`. I'd keep the requirements for `textual-dev` as loose as possible.

**Comment by willmcgugan** [comment]
Done. https://github.com/Textualize/textual-dev
