### ISSUE TITLE
Rendered Markdown links are broken into chunks when source text is multi-line

### ISSUE THREAD

**Issue by jamescooke** [Textualize/textual#2805]
## Current behaviour

When a link in Markdown is split over two or more lines, the rendered link will be "broken" and not continue through the whitespace created for each of those broken lines.

Given the Markdown document:

```
My site [has
this
URL](https://example.com)
```

When we run that on [markdown-it](https://markdown-it.github.io/) it renders as a "single link" (sorry mouse disappeared when triggering screenshot):

![Screenshot 2023-06-19 at 15 04 15](https://github.com/Textualize/textual/assets/781059/bd9816db-7f35-49b5-a49d-6de5a37cd773)

However, when embedding that document into the [Markdown widget `markdown.py` example](https://textual.textualize.io/widgets/markdown/#__tabbed_1_2) from the docs as follows:

```py
from textual.app import App, ComposeResult
from textual.widgets import Markdown

EXAMPLE_MARKDOWN = """\
My site [has
this
URL](https://example.com)
"""


class MarkdownExampleApp(App):
    def compose(self) -> ComposeResult:
        yield Markdown(EXAMPLE_MARKDOWN)


if __name__ == "__main__":
    app = MarkdownExampleApp()
    app.run()
```

Then running with `python markdown.py` gives the following render - where you can see the link is "broken" to appear as 3 items:

![Screenshot from 2023-06-19 15-07-27](https://github.com/Textualize/textual/assets/781059/0b765e80-cc45-400e-b72f-22f75f60c68e)

And on hover:

![Screenshot from 2023-06-19 15-07-39](https://github.com/Textualize/textual/assets/781059/58109b6b-fb30-4c2a-93a6-ef61b4ca7b2c)

One subtle issue I've found with this bug, is when I hover over the white space gaps, the link does _not_ highlight 😞 

## Expected behaviour

Link is expected to render the same as if it was on a single line in the Markdown file:

![Screenshot from 2023-06-19 15-08-44](https://github.com/Textualize/textual/assets/781059/fb8d2b28-c69f-425d-afd8-890763dff7e4)

## Debug info...

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.28.0 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                  |
|----------------|----------------------------------------|
| Version        | 3.11.0                                 |
| Implementation | CPython                                |
| Compiler       | GCC 9.4.0                              |
| Executable     | /tmp/tmp.E7iYfjTaVi/venv311/bin/python |

## Operating System

| Name    | Value                                              |
|---------|----------------------------------------------------|
| System  | Linux                                              |
| Release | 5.15.0-75-generic                                  |
| Version | #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | *Unknown*       |
| TERM                 | screen-256color |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=105, height=58 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 105                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 58                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

Sorry no kittens in this bug report 🙏🏻

**Comment by TomJGooding** [comment]
The fix *might* be as simple as checking the style stack - see 7faf881 - but probably best I leave this to @davep!
