### ISSUE TITLE
`DataTable` issues with adding new columns to a table that has existing data in it

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#2833]
Turning discussion #2826 into an issue to be looked at as a possible bug, as I think this could trip others up too.

If you try to add a new column to a DataTable with existing data, the app crashes with a KeyError and a long traceback.

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable

class DataTableAppFail(App):
    def compose(self) -> ComposeResult:
        yield DataTable()
    
    def on_mount(self):
        table = self.query_one(DataTable)
        
        table.add_columns(*["col1", "col2", "col3"])
        table.add_rows([[1, 2, 3], [4, 5, 6]])

        table.add_columns(*["col4", "col5"])

DataTableAppFail().run()
```

Perhaps `add_column` should update the table data if necessary to add `None` values?

If you clear the table and add back the same rows, it works as expected thanks to `itertools.zip_longest`.

**Comment by darrenburns** [comment]
Thanks for the report, should be fixed by https://github.com/Textualize/textual/pull/2836
