### ISSUE TITLE
Implement TextArea

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2848]
We need a TextArea widget to allow for multi-line inputs and editing text files.

This will probably broken out in to several tasks, consider this a overview of requirements:

- Multi-line text editing.
- Line numbers column, that remains on screen when the text is scrolled right.
- Syntax highlighting (using tree sitter)
- Word wrap
- Undo / Redo

**Comment by willmcgugan** [comment]
@darrenburns @davep Feel free to update as required.

**Comment by willmcgugan** [comment]
Will require a discussion re data structures before we start work on this.

**Comment by Menschomat** [comment]
I really would appreciate this feature for my project.
