### ISSUE TITLE
Some subprocesses get stuck on mouse events

### ISSUE THREAD

**Issue by flupke** [Textualize/textual#2858]
Some subprocesses get stuck on mouse events when run under textualize, piping their output and in a process group. See [this repo](https://github.com/flupke/textualize-streams-bug) for a complete reproduction and explanation.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.28.1 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                                    |
|----------------|----------------------------------------------------------|
| Version        | 3.11.4                                                   |
| Implementation | CPython                                                  |
| Compiler       | GCC 13.1.1 20230429                                      |
| Executable     | /home/flupke/src/textualize-streams-bug/.venv/bin/python |

## Operating System

| Name    | Value                                                  |
|---------|--------------------------------------------------------|
| System  | Linux                                                  |
| Release | 6.3.8-arch1-1                                          |
| Version | #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 |

## Terminal

| Name                 | Value         |
|----------------------|---------------|
| Terminal Application | tmux (3.3a)   |
| TERM                 | tmux-256color |
| COLORTERM            | truecolor     |
| FORCE_COLOR          | *Not set*     |
| NO_COLOR             | *Not set*     |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=191, height=45 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 191                  |
| is_terminal    | False                |
| encoding       | utf-8                |
| max_height     | 45                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
I haven't ran the code, but I suspect what may be happening is that one of your subprocesses is reading from `stdin`. If that happens Textual won't be able to process mouse events. You may need to pipe stdin to your processes.

**Comment by flupke** [comment]
Yes that was the issue! adding
```
        stdin=asyncio.subprocess.DEVNULL,
```
to the subprocess creation fixes it. This was a very confusing and time consuming bug, not sure there's anything Textual can do about it though :(

**Comment by willmcgugan** [comment]
Glad we got to the bottom of it.

Yeah, probably nothing that Textual could do about it. But we are finding that a lot of people are combining Textual with processes, so at some point we will add that to the How-Tos where we can document the potential pitfalls.
