### ISSUE TITLE
Focus change doesn't always update `text-style`style

### ISSUE THREAD

**Issue by nmay231** [Textualize/textual#2859]
## Diagnostics

<details>

<summary>

Results of `textual diagnose`.

</summary>

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.28.1 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                       |
|----------------|---------------------------------------------|
| Version        | 3.10.6                                      |
| Implementation | CPython                                     |
| Compiler       | GCC 11.3.0                                  |
| Executable     | /home/nmay/cur/textual_bug/.venv/bin/python |

## Operating System

| Name    | Value                                                            |
|---------|------------------------------------------------------------------|
| System  | Linux                                                            |
| Release | 5.19.0-45-generic                                                |
| Version | #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | guake          |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=137, height=56 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 137                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 56                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

</details>

## Bug description

The following is a complete example:

```python
from rich.console import RenderableType
from textual.app import App, ComposeResult
from textual.widgets import Button, Static

class BugDemo(Static, can_focus=True):
    DEFAULT_CSS = """
    BugDemo {
        background: $panel;
        color: $text;
        text-style: bold;
    }

    BugDemo:focus {
        # color: $text 100%;
        text-style: bold reverse;
    }
    """

    # def render(self) -> RenderableType:
    #     return "testing"
    
    def compose(self) -> ComposeResult:
        yield Static("testing")

class MyApp(App):
    def compose(self) -> ComposeResult:
        yield Button("Button1")
        yield BugDemo()
        yield Button("Button2")

if __name__ == "__main__":
    MyApp().run()
```

As you tab over the `BugDemo` element, notice it doesn't change styles at all. However, if you use `.render()` instead of `.compose()` **OR** if you uncomment the line `color: $text 100%;`, the CSS does get updated on focus change.

## Notes

I feel like this is unintended, but I'm honestly not certain since I don't even know the full difference between the `.render()` and the `.compose()` methods. You can read other people's confusion [here](https://github.com/Textualize/textual/discussions/1683) and in other issues/discussions. *Regardless of whether this is a bug or not, some documentation on the differences between render and compose is highly warranted imo.*

Thank you for your time and work on this awesome project :)

**Comment by willmcgugan** [comment]
There is a fix incoming. The issue was that text style was inherited, which means that is should have refreshed children.

The `compose` method create a [compound widget](https://textual.textualize.io/guide/widgets/#compound-widgets) (a widget containing other widgets).
