### ISSUE TITLE
stdout  redirect shouldn't set sys.stdout to None

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2879]
It looks as though the `redirect_stdout(None)` (and stderr version) sets `sys.stdout` to `None`.

Nothing has broken up until now, which suggest that the `print` function treats `None` as a special case. However, this won't be the case where `sys.stdout` is expected to contain a file like object.

This is the root cause of https://github.com/Textualize/textual/issues/2877 and https://github.com/Textualize/textual/issues/2878

The redirected stdout should go to dev/null. See `os.devnull`

**Comment by rodrigogiraoserrao** [comment]
Closed with #2880.

**Comment by alexiri** [comment]
@willmcgugan This fix seems to be missing from the changelog of 0.29.0, but it's included, right?

**Comment by rodrigogiraoserrao** [comment]
> This fix seems to be missing from the changelog of 0.29.0, but it's included, right?

Wooops, when we reviewed your PR #2880 we should've asked you to add the fix entry to the changelog, but we forgot and we didn't add it later.
Your fix should be in 0.29.0 regardless of this omission from the changelog.
