### ISSUE TITLE
Implement syntax highlighting for Textual css

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2888]
It would be great to be able to syntax highlight Textual css. I think we can do this with a VSCode extensions which uses TextMate grammar files. In theory we could also use these for other IDEs. https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

This may also require us to pick an extension over CSS. Suggest `.tcss` unless there is a better idea.

**Comment by rodrigogiraoserrao** [comment]
Closing in favour of #3083
