### ISSUE TITLE
SelectionList with long lines throws an exception when the window is too small

### ISSUE THREAD

**Issue by valberg** [Textualize/textual#2900]
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.29.0 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                                |
|----------------|------------------------------------------------------|
| Version        | 3.11.3                                               |
| Implementation | CPython                                              |
| Compiler       | GCC 13.1.1 20230429                                  |
| Executable     | /home/valberg/.pyenv/versions/textual-dev/bin/python |

## Operating System

| Name    | Value                                                  |
|---------|--------------------------------------------------------|
| System  | Linux                                                  |
| Release | 6.4.1-arch2-1                                          |
| Version | #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=62, height=34 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 62                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 34                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

# Bug report

Running the following in a smallish window, or resizing below the length of the selection length:

```python
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, SelectionList


class TestApp(App):

    def compose(self) -> ComposeResult:
        yield Header()

        yield SelectionList(
            ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 1),
        )

        yield Footer()


if __name__ == "__main__":
    app = TestApp()
    app.run()
```

results in the following exception:

```
OptionDoesNotExist: There is no option with an index of 1
```

**Comment by davep** [comment]
Good catch; some work should either be done to truncate options longer than the width, or `OptioinList` needs to be improved to handle the underlying selection list's wrapping of long options. If I quickly hack Textual to eat the error you can see how the underlying lines and the check boxes get out of sync too.

![Screenshot 2023-07-07 at 12 34 04](https://github.com/Textualize/textual/assets/28237/d349e84f-c2f3-4548-b561-f14777fe3536)

**Comment by valberg** [comment]
I have worked around it by simply having shorter labels - for now.

**Comment by davep** [comment]
It's all down to how `SelectionList` sits on top of `OptionList`, and how the former has been done with "each thing only takes up one line" in mind, but the latter is super flexible and can have one option spanning many lines. So really I guess the first thing for us to do is to decide if we should restrict the prompts for `SelectionList` (that was the intention: to have it act like a `CheckBox`-adjacent take on `RadioSet`) so they never "wrap", or if we relax that and then how and where the checks go when a prompt spans multiple lines.

I sense it's a quick design chat we'll need internally first before fixing this.

**Comment by zdovcj** [comment]
I have also tried to size my content upon resize event, but it doesn't solve the issue. In this case, it will even crash on increasing the terminal size. I assume that the function that sets the content length might be called before the the code that crashes.

Code to reproduce the crash upon increasing:
```python
import textual.widgets
import textual.app
import textual.events
import textual  

class App(textual.app.App):

    @textual.on(textual.events.Resize)
    def resize_handler(self):
        width = self.size.width
        text = 'a' * (width - 4)
        widget = self.query_one(textual.widgets.SelectionList)
        widget.clear_options()
        widget.add_option((text, 0, None))

    def compose(self):
        yield textual.widgets.SelectionList (('random_text', 0), id='widget_id')

if __name__ == '__main__':
    App().run()
```
