### ISSUE TITLE
Send mouse move events to screen

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2905]
It look like mouse move events never make it to the Screen object. I think they should.

**Comment by rodrigogiraoserrao** [comment]
[Install the Textual devtools](https://textual.textualize.io/guide/devtools/), open the console with `textual console`, and run the app below in a different window with `textual run --dev myapp.py`:

```py
from textual.app import App


class MyApp(App):
    pass


if __name__ == "__main__":
    MyApp().run()
```

If you click the app, the console will log the `Click` event twice, once in the (default) screen and once in the app.
Many other events exhibit this bubbling behaviour, and so should the `MouseMove` event.

**Comment by seifertm** [comment]
I'll try to implement this as part of the sprint today.
