### ISSUE TITLE
Hovering over an empty DataTable row does not reset hover effect

### ISSUE THREAD

**Issue by ThatOtherAndrew** [Textualize/textual#2909]
_Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed_

Yes, I have.

_Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**_

To reproduce the issue, run the below code and hover the cursor above one of the cells. Then, move the cursor down into the empty space below, and observe how the orange highlighting on the cell persists.

```py
from textual.app import App
from textual.widgets import DataTable

class ExampleApp(App):
    def compose(self):
        table = DataTable()
        table.add_columns('foo', 'bar', 'baz')
        table.add_row('foo', 'bar', 'baz')
        table.styles.height = '100%'
        yield table

ExampleApp().run()
```

_It will be helpful if you run the following command and paste the results:_

```
textual diagnose
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.27.0 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                                              |
|----------------|--------------------------------------------------------------------|
| Version        | 3.11.3                                                             |
| Implementation | CPython                                                            |
| Compiler       | MSC v.1934 64 bit (AMD64)                                          |
| Executable     | C:\Users\Andrew\AppData\Local\Programs\Python\Python311\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.22621 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=120, height=30 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 120                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 30                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

_Feel free to add screenshots and / or videos. These can be very helpful!_

https://github.com/Textualize/textual/assets/26030336/78da926b-915c-46c2-b817-5c9a6e16eb7a

**Comment by TomJGooding** [comment]
I thought this might be a quick fix, but I can't seem to unset the hover cursor similar to when focus leaves the widget.

https://github.com/Textualize/textual/blob/26573b9cffa0be57ffcab35bab9a7fe84ae8a063/src/textual/widgets/_data_table.py#L1979-L1992

**Comment by TomJGooding** [comment]
I've been looking at this issue again as it feels like it should be such an easy fix.

If the mouse isn't hovering a cell in the table, then there's no `meta` info. But I can't seem to conditionally unset the hover cursor no matter what I try, so there must be something I'm missing.

@darrenburns do you have any ideas? Sorry I normally wouldn't tag individuals, but it seems like you're the DataTable expert!

**Comment by darrenburns** [comment]
I think you're looking at the correct code, but there looks like a cacheing bug too, which is preventing the update from being visible.

The cell render cache key doesn't include `self._show_hover_cursor`, which means subsequent repaints of the cell containing the hover cursor will get the old cached rendered cell (with hover cursor highlighting), regardless of whether `self._show_hover_cursor` is `True` or `False`.

Adding `self._show_hover_cursor` to the cell render cache_key (inside `render_cell`), combined with the changes you suggested above, should do the trick.
