### ISSUE TITLE
Add a Unicode digits display widget

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2916]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

This issue concerns itself with adding [a new widget](https://textual.textualize.io/guide/widgets/) to Textual.
This widget should use [Unicode box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) to create a display for digits.
Each digit should be drawn like shown below.

<details>
<summary>Digits</summary>

```
┏━┓
┃ ┃
┗━┛
 ┓
 ┃
╺┻╸
╺━┓
┏━┛
┗━╸
╺━┓
 ━┫
╺━┛
╻ ╻
┗━┫
  ╹
┏━╸
┗━┓
╺━┛
┏━╸
┣━┓
┗━┛
╺━┓
  ┃
  ┃
┏━┓
┣━┫
┗━┛
┏━┓
┗━┫
╺━┛
```

</details>

The widget should have a [reactive attribute](https://textual.textualize.io/guide/reactivity/) `value` that holds the integer value associated with the display.

To implement the actual display, you'll want to implement the method `render`.
See `_progress_bar.py` or `_placeholder.py` for two examples of widgets that implement the method `render`.

Take a look at #2333 to see what files need to be changed when you implement a new widget.
Then, don't be like me and also do the final step shown in #2399 to add your new widget to the [widget gallery](https://textual.textualize.io/widget_gallery/).

Good luck and have fun!

**Comment by willmcgugan** [comment]
I'm thinking that this should accept a `str`. I can see us wanting to render more than integers. We might also want to pad it with zeros. Consider `001` `002` etc.

We should also consider extending it with a few more characters. I'm thinking "+", "-", and ".". Maybe even "X" for mathematical notation.

**Comment by davep** [comment]
> mathematical notation

Longer-term, this could then feed into https://github.com/Textualize/frogmouth/issues/46

**Comment by eliasdorneles** [comment]
Hello, EuroPython sprinter here, I'd like to take this one! =)

**Comment by willmcgugan** [comment]
Fantastic. Looking forward to this one.
