### ISSUE TITLE
Add a marquee widget

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2917]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

This issue concerns itself with adding [a new widget](https://textual.textualize.io/guide/widgets/) to Textual.
The marquee widget should be similar to HTML marquees (scroll down to the examples [in this page](https://www.tutorialspoint.com/html/html_marquees.htm) to see what the HTML marquee was).

The widget should have a [reactive attribute](https://textual.textualize.io/guide/reactivity/) that holds the string or the [`rich.text.Text` instance](https://rich.readthedocs.io/en/stable/text.html) that should be rotated endlessly.
You'll probably want to take a look at [timers](https://textual.textualize.io/api/timer/) / [the attribute `auto_refresh`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.auto_refresh) to enable the marquee animation.

You will want to implement a method `render` that is responsible for returning the “frames” of your marquee widget.
You may also look at `_progress_bar.py::Bar.render` and `_progress_bar.py::Bar.render_indeterminate` for some inspiration on how to implement a cyclical animation.

After you are done with the implementation, consider adding a reactive attribute that controls the speed of the animation.

Take a look at #2333 to see what files need to be changed when you implement a new widget.
Then, don't be like me and also do the final step shown in #2399 to add your new widget to the [widget gallery](https://textual.textualize.io/widget_gallery/).

Good luck and have fun!

**Comment by willmcgugan** [comment]
For reference, here is what a marquee looks like...


https://github.com/Textualize/textual/assets/554369/bfda6bf3-f8ee-4141-a93a-c035599758e2

**Comment by tonteg** [comment]
I'll have a look at this.

**Comment by rodrigogiraoserrao** [comment]
Hey @tonteg, are you still working on this or did you drop it?
If you are working on this, do you have any _rough_ estimate of when you might be ready for a PR?
If you are _not_ working on this, do you mind letting us know?
Thanks!

**Comment by tonteg** [comment]
Hi, I temporarily put this aside, but I'd definitely like to finish it. I'll try to get it ready for a PR in the next two weeks.

**Comment by rodrigogiraoserrao** [comment]
Sure thing, @tonteg . Looking forward to your PR.

**Comment by TomJGooding** [comment]
![marquee](https://github.com/Textualize/textual/assets/101601846/39efc508-b38e-4997-a967-1dc395eb2765)

**Comment by willmcgugan** [comment]
Closing for now, but if there is a PR somewhere I'd be happy to take a look!
