### ISSUE TITLE
ScrollView and ANSI codes

### ISSUE THREAD

**Issue by davidbrochart** [Textualize/textual#292]
There are strange effects when some text with ANSI codes is used inside a `ScrollView`. Here is a Minimal Complete Verifiable Example:
```python
import asyncio

from rich.text import Text

from textual import events
from textual.app import App
from textual.widgets import ScrollView


class MyApp(App):

    async def on_load(self, event: events.Load) -> None:
        await self.bind("q", "quit", "Quit")

    async def on_mount(self, event: events.Mount) -> None:

        self.body = body = ScrollView(auto_width=True)

        await self.view.dock(body)

        async def add_content():
            text = Text()
            for i in range(10):
                for j in range(30):
                    text.append("\u001b[32mHello, \033[0m")
                    text.append("World! ")
                text.append("\n")

            for i in range(100):
                text.append("Hello, World! " * 10 + "\n")

            await body.update(text)

        await self.call_later(add_content)

MyApp.run(title="Simple App", log="textual.log")
```

https://user-images.githubusercontent.com/4711805/154379300-492825ec-1e1b-438f-be81-553779b41a9e.mp4

**Comment by willmcgugan** [comment]
Rich / Textual is generally unaware of control codes (that it hasn't generated itself). You probably won't get the output you are expecting and it will break cell length calculations.

Ideally, use the Text.styleize and friends to apply styles. If you can't avoid ansi control codes there is `rich.ansi.AnsiDecoder` class which converts strings with escape codes in to Text objects, but it is undocumented and likely incomplete.

**Comment by davidbrochart** [comment]
I'd like to show some log messages that are not generated by Rich. I'll try `rich.ansi.AnsiDecoder`, and maybe contribute if some control codes are not supported. Thanks!

**Comment by daler-rahimov** [comment]
This is what worked for me. 
```python 
self.body = ScrollView()
with open(self.log_file, "r") as f:
    log = Text.from_ansi(f.read())
await self.body.update(log)

```
