### ISSUE TITLE
Add style variations to the progress bar widget

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2920]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

Currently, [the `ProgressBar` widget](https://textual.textualize.io/widgets/progress_bar/) can have its colours changed, but the bar style is always the same.
This issue concerns itself with adding style variations to the actual bar.
Add the following styles:

 - `default` (the current one)
 - `thick` (use taller block characters)
 - and any other(s) you can think of!

To change the style of the progress bar, you will need to change the characters that are used inside `textual.renderables.bar.py::Bar.__rich_console__`.

The style for the progress bar can be selected via a keyword-only parameter `variant` upon instantiation, like `ProgressBar(variant="thick")`, akin to `Button`.
The progress bar variant should also be exposed as a [reactive attribute](https://textual.textualize.io/guide/reactivity/) `variant`.

Good luck and have fun!

**Comment by petertalaber** [comment]
Hi, I have started to work on this issue in EuroPython Sprint.

**Comment by rodrigogiraoserrao** [comment]
> Hi, I have started to work on this issue in EuroPython Sprint.

Good luck; I'll be around to help.

**Comment by willmcgugan** [comment]
Closing for now. We may have more variations in the future, but this is low priority.
