### ISSUE TITLE
Add command `widgets` to Textual CLI

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2921]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

The [Textual CLI](https://textual.textualize.io/guide/devtools/#devtools) has many useful commands for developers building applications, like `textual keys`, `textual colors`, and `textual borders`.
This issue concerns itself with adding a subcommand `textual widgets` to the Textual CLI.

This command should be a terminal version of the [current widget gallery](https://textual.textualize.io/widget_gallery/).
`textual widgets` should display a simple but interesting example of each widget together with a link to the reference page for that widget.

Consider having a left menu to jump to the different widgets, akin to how `textual borders` works.

It is _very important_ that this is easy to maintain.
For example, when a new widget is added to Textual, it should be straightforward to add it to this app.

See #1409 or #1545 for examples on how to add CLI commands.

Good luck and have fun!

**Comment by pavelkraleu** [comment]
I will look into this issue

**Comment by willmcgugan** [comment]
Still a good idea. But not a priority. Still happy to consider that linked PR.
