### ISSUE TITLE
Extend `textual colors` to show named colours

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2922]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

The [Textual CLI](https://textual.textualize.io/guide/devtools/#devtools) has a command `textual colors` that displays the variables defined by [Textual's design system](https://textual.textualize.io/guide/design/).
Extend this command/app to show the named colours that Textual recognises, as seen in [the `Color` API documentation](https://textual.textualize.io/api/color/#textual.color--named-colors).

Take a look at `color.py` to see how to fetch all named colours that Textual recognises.

To create a separation between the design system variables and the named colours, consider having each in its own tab.
This will also make it easier to extend `textual colors` if we eventually add other "themes".

Good luck and have fun!

**Comment by csernazs** [comment]
I'd like to take this.
