### ISSUE TITLE
wrong escape sequence in textual keys command

### ISSUE THREAD

**Issue by sepsh** [Textualize/textual#2925]
Hi there !
I was using `textual keys` command and found out that pretty printing for key `backslash` has an issue color highlighting the string.
the string terminator is escaped as a single quotes string literal character

![image](https://github.com/Textualize/textual/assets/56169910/aed92bda-6776-4b4b-ae03-150bade31d37)

I am on `windows 11 22H2 22621.1555` using the new `windows terminal`

and `python 3.11.3`, `textual 0.29.0`, `textual-dev 1.0.1`

Here's how one can reproduce the bug

```powershell
pip install textual-dev
textual keys
```

and then type in the `backslash` key and check the result

**Comment by davep** [comment]
I suspect this is down to [Rich's `Pretty`](https://rich.readthedocs.io/en/stable/pretty.html).

**Comment by sepsh** [comment]
you're right it is.
I've opened an issue over there: Textualize/rich#3032

**Comment by davep** [comment]
Given that you've created an issue for Rich on this (thanks!), I'll close this one.
