### ISSUE TITLE
Worker interface

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2928]
The `work` decorator possibly makes it too easy to create threads.

If you don't know what you are doing (and sometimes even if you do) threads can be a footgun. I think we should make launching threads more explicit.

I think the decorator should accept a `thread` argument which will create a thread worker if set to `True`.

Without `thread=True` it should be an *error* to decorate a non-coroutine.

i.e. the following should be an error:

```python
@work
def foo(...):
    ...
```

To create a thread, it should be this:

```python
@work(thread=True)
def foo(...):
    ...
```

This should create a thread worker:

```python
@work
async def foo(...):
    ...
```

Note, this is a breaking change, which should be reflected in the CHANGELOG. It will also require an update to the docs.

**Comment by davep** [comment]
Also note this will need an update to `DirectoryTree`.

**Comment by willmcgugan** [comment]
As an addendum. We should also be able to run a coroutine in a thread.

Should be a small update to workers. Essentially you want to call `asyncio.run( )` within the thread.

```python
@work(thread=True)
async def foo(...):
    ...
```

**Comment by davep** [comment]
Might also be worth looking at #2946 while working on this.
