### ISSUE TITLE
Add `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#2933]
Textual currently doesn't have any guidelines for contributing. 

I've been meaning to raise this for a while, but the EuroPython 2023 sprint perhaps makes this more prescient.

There's probably a lot that could just be coped from the Rich guidelines; that's where I started!

**Comment by davep** [comment]
See also [this discussion on Discord](https://discord.com/channels/1026214085173461072/1033752510848053399/1125755514362540133) (and of course the draft TODO item on the internal dev board that came from that).

**Comment by rodrigogiraoserrao** [comment]
For a more comprehensive guide, see also #2923.
Maybe some parts can be reused.

**Comment by clairecharles** [comment]
Hi @rodrigogiraoserrao i see that this hasn't been worked on yet, i'd like to work on it :)

**Comment by rodrigogiraoserrao** [comment]
> Hi @rodrigogiraoserrao i see that this hasn't been worked on yet, i'd like to work on it :)

Hey Claire, feel free to have a go at it!
