### ISSUE TITLE
Strange highlight occurring

### ISSUE THREAD

**Issue by AndrewLighten** [Textualize/textual#2951]
I have a simple application that builds up a tree structure of data, and then when a particular leaf node is selected, a list view is populated with data related to that leaf node.

For some reason, the “ff” in “Coffs Harbour” (a town in NSW, Australia) is highlighted yellow. I cannot understand why.

Here's an example:

<img width="1088" alt="image" src="https://github.com/Textualize/textual/assets/7276027/c25fec0c-493b-40f3-8d35-f21132e417d0">

What do I need to do to turn this off?

**Comment by AndrewLighten** [comment]
Forget that. For some reason it was my console doing it — it's not a textualize issue at all.

**Comment by willmcgugan** [comment]
I think this is the search function in iTerm2. If it makes you feel better, I have made the same mistake more than once.

**Comment by AndrewLighten** [comment]
@willmcgugan That does make me feel better. Was kicking myself for such a stupid mistake.
