### ISSUE TITLE
Input - clicking the right half of a double width character moves the cursor to the wrong character.

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#2968]
こんにちは

Put that text into an `Input` and click on the right half of any character - notice that the cursor incorrectly moves to the character to the right of the one you clicked on.

**Comment by yuvalmo** [comment]
I isolated the source of the bug here:
https://github.com/Textualize/textual/blob/5a662e68aefc695c02203c8b3720a4c90a7dce09/src/textual/widgets/_input.py#L424

Will upload a solution soon.
