### ISSUE TITLE
`max-height: 100%` with a `height: auto` container causes child widget to disappear

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2975]
Given this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable, Static

class HappyDataTableFunApp(App[None]):

    CSS = """
    DataTable {
        max-height: 100%;
    }
    """

    def populate(self, table: DataTable) -> DataTable:
        for n in range(20):
            table.add_column(f"Column {n}")
        for row in range(1000):
            table.add_row(
                *[str(row * n) for n in range(20)]
            )
        return table

    def compose(self) -> ComposeResult:
        with Static():
            yield self.populate(DataTable())

if __name__ == "__main__":
    HappyDataTableFunApp().run()
```

the `DataTable` doesn't show. This seems to be the combination of a child widget that is `height: auto;` and `max-height: 100%;` with a parent container that is `height: auto`.

More generally the issue seems to be that if a child widget is `height: auto` and `max-height: 100%` and the parent container is `height: auto` there's no way to work out a height.

Perhaps there's some scope here to settle on a less astonishing outcome?

**Comment by davep** [comment]
Somewhat related, because I see folk using `Static` as a container quite often, perhaps this wording:

> Can be used for Rich renderables and can also be **the base for other types of widgets**.

in the [the docs for `Static`](https://textual.textualize.io/widgets/static/) could do with a wee revamp, as I suspect it has caused people to think it should be used as a container.

Also, the tutorial uses `Static` as the base class for a compound widget (which now I think about it might account for why I see people do that so often).

**Comment by TomJGooding** [comment]
Yup, I can confirm this is what I was doing too when I was new to Textual based on the docs!

The specific mention of `Static` in the widgets guide to "create custom widgets of your own" might also be compounding this confusion: https://textual.textualize.io/guide/widgets/#static-widget
