### ISSUE TITLE
Generic types with reactive/var

### ISSUE THREAD

**Issue by jeff-foster-trabon** [Textualize/textual#2976]
I've run into a type error from pyright I can't resolve, trying to assign to `Select.value`. The same problem can be seen in `test_widget.py:274`.

The problem seems to be in `reactive` and `var`.

```Python
from typing import Generic, Optional, TypeVar

from textual.reactive import var

T = TypeVar("T")


class TestClass(Generic[T]):
    value1: var[T | None] = var[Optional[T]](None)
    value2: T | None = None


c: TestClass[int] = TestClass()
c.value1 = 1
c.value2 = 1
```

In this case pyright only has a problem with the `value1` assignment, where it produces the following error:

```
Cannot assign member "value1" for type "TestClass[int]"
    "Literal[1]" is incompatible with "int | None" (reportGeneralTypeIssues)
```

**Comment by willmcgugan** [comment]
I don't have an answer to that particular error. Doesn't make sense to me. But `var` does require a Widget or other DOMNode. I wouldn't expect reactivity to work on other classes.

**Comment by jeff-foster-trabon** [comment]
The code is not intended to do anything, just to illustrate that pyright has an issue with the assignment only if the attribute is wrapped in `var`. `value1` is defined the same here as `value` is on `Select`.

As I mentioned, textual's own `tests/test_widget.py` triggers the same error from pyright on line 274.

```Python
class MyScreen(Screen):
    def on_mount(self) -> None:
        self.query_one(Select).value = 1
```

(I have not checked whether mypy has a problem with it.)

Does textual consider not passing mypy and/or pyright checks a bug?

**Comment by jeff-foster-trabon** [comment]
> When the different type checkers can't all agree it can be a difficult issue to solve

I understand. I stopped using mypy and only use pyright now, because all I want is editor support, and I don't want to spend too much effort fighting with this.

I was using pyright 1.1.316. After your comment I updated to 318 and now I have a ton of new errors! Most of which are:

```
Expected no type arguments for class "var"
```

On lines like:

```Python
value1: var[T | None] = var[Optional[T]](None)
```

**Comment by nmay231** [comment]
Looking at other libraries doing something similar, `pydantic` basically cops out and returns [`Any` with its `Field` descriptor](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.Field). While not ideal, might it be best to do the same here until a better resolution comes about?

**Comment by davep** [comment]
Possibly related: https://github.com/microsoft/pyright/issues/5579

**Comment by hmc-cs-mdrissi** [comment]
You may want to respond then to this [topic](https://github.com/microsoft/pyright/discussions/5258) to have textual be included in pyright-primer for additional coverage to help detect issues like this with each pr.

**Comment by davep** [comment]
Checking over some code in Textual just now and pyright [v1.1.320](https://github.com/microsoft/pyright/releases/tag/1.1.320) seems to have fixed this. The fix will also [be making its way to pylance](https://github.com/microsoft/pyright/issues/5579#issuecomment-1661408321).

Especially given the apparent source of the error, and given that the source has now fixed it, I'll close this issue.
