### ISSUE TITLE
Add `Rule` widget

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#2982]
This issue concerns itself with adding [a new widget](https://textual.textualize.io/guide/widgets/) to Textual.
The rule widget should be similar to [HTML rules](https://www.w3schools.com/tags/tag_hr.asp).
The key difference is that HTML only has a horizontal rule and `Rule`'s orientation can be customised (`"horizontal"` or `"vertical"`).

You will want to implement a method `render` that is responsible for returning the characters that make up the rule itself.
You may also look at `_progress_bar.py::Bar.render` and `_progress_bar.py::Bar.render_indeterminate` for some inspiration on how to implement “a line” that you can render.

I suggest you start by implementing a horizontal rule.
After it works well, think about creating a vertical rule as well and make it customisable via a parameter, e.g., `Rule(orientation="horizontal")` and `Rule(orientation="vertical")`.

Take a look at #2333 to see what files need to be changed when you implement a new widget.
Then, don't be like me and also do the final step shown in #2399 to add your new widget to the [widget gallery](https://textual.textualize.io/widget_gallery/).

Good luck and have fun!

**Comment by scriptogre** [comment]
Working on it! 😎

**Comment by rodrigogiraoserrao** [comment]
Hey Chris, we exchanged a couple of messages in private but I'd like to reiterate my question: are you working on this at your own pace or are you dropping this?
I'm asking just so we can know whether we'll need to tackle this ourselves or not.

**Comment by rodrigogiraoserrao** [comment]
This is up for grabs.
See #3060 for a pretty good PR that is almost there.

**Comment by TomJGooding** [comment]
I'm not _necessarily_ volunteering, but just to clarify do you think this is better separated into `HorizontalRule` and `VerticalRule` widgets or just a single `Rule` widget with an `orientation` parameter?

**Comment by willmcgugan** [comment]
I have no strong opinion on that. Surprising, coming from me. 🤷‍♂️

**Comment by TomJGooding** [comment]
Ugh, apparently my fork now has snapshot tests failing on `main` even if I did want to volunteer. Any suggestions?

**Comment by willmcgugan** [comment]
> How 'bout `Rule(..., orientation=...)` but then, like the `Button` variants, maybe provide `Rule.horizontal()` and `Rule.vertical()` class methods?

Sounds like the best of both worlds

**Comment by willmcgugan** [comment]
> Ugh, apparently my fork now has snapshot tests failing on `main` even if I did want to volunteer. Any suggestions?

We have a few flaky tests that are timing sensitive. They run lovely but occasionally fail in CI. You may find you can run them again and they will pass.

**Comment by rodrigogiraoserrao** [comment]
> Ugh, apparently my fork now has snapshot tests failing on `main` even if I did want to volunteer. Any suggestions?

(Not sure what you are forking, but in case you are forking the PR that has some work on this already, do note that the OP had an issue in his code.)

**Comment by TomJGooding** [comment]
Sorry to clarify the tests are failing locally on the same fork I've had kicking around for a while. AFAIR everything was working fine, perhaps due to some changes with `textual-dev`...?

**Comment by willmcgugan** [comment]
Ah. Probably the textual-dev dependency!
