### ISSUE TITLE
TextLog auto_scroll = False doesn't work as intended if max_lines exceeded

### ISSUE THREAD

**Issue by perlsaiyan** [Textualize/textual#2991]
If the amount of text in a TextLog hits max_lines, and the user scrolls back, their viewport will scroll forward as new content is added.

Here's an example where I page up, setting auto_scroll=False.

![scroll](https://github.com/Textualize/textual/assets/524618/9fda4e42-a6cd-4369-821c-e9930bebe0d8)

As new content is added, the point on the scrollbar stays constant, but the content changes.  With auto_scroll = False, I would expect the viewport to remain constant and the scroll bar point to continually get further back, until we reach the edge of history where that is no longer possible.

Screen grab from textual 0.30.0.

**Comment by TomJGooding** [comment]
So rather than the scroll position being 'sticky', when new lines are added you would expect the scrolling to track the currently visible content? Have I understood correctly?

**Comment by perlsaiyan** [comment]
Yes, exactly.  The point of scrolling back in a text log is to view previous content, which means the viewing area should remain constant.

**Comment by willmcgugan** [comment]
Seems fix. Feel free to reopen if I'm wrong about that.
