### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Genius1512** [Textualize/textual#302]
At the top in the README when listing suported platforms, 'Window' is written instead of 'Windows'

**Comment by willmcgugan** [comment]
Care to submit a PR for that?

**Comment by Genius1512** [comment]
Yew

**Comment by Genius1512** [comment]
*yes

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
