### ISSUE TITLE
CSS parsing breaks when using border: $text

### ISSUE THREAD

**Issue by eliasdorneles** [Textualize/textual#3025]
I wanted to create a widget with a border the same color as the text.

However, when I tried using `border: solid $text` I get this error: 

![image](https://github.com/Textualize/textual/assets/37565/1269f302-8fcf-4818-b568-132780b63813)

Other color names like `$primary`, `$secondary`, etc; these work fine, but for some reason it breaks for `$text`.

Here is a simplified example that demonstrates the issue:

```
from textual.app import App, ComposeResult
from textual.widgets import Label


class MyApp(App):
    CSS = """
    Screen Label {
        border: solid $text;
    }
    """

    def compose(self) -> ComposeResult:
        yield Label("Hello, world!")


if __name__ == "__main__":
    app = MyApp()
    app.run()
```

This should work, right?

**Comment by TomJGooding** [comment]
From the docs it looks like `$primary` and `$secondary` are part of the [12 base colors](https://textual.textualize.io/guide/design/#base-colors), whereas `$text` only works with the `color` property for setting [text color.](https://textual.textualize.io/guide/design/#text-color). 

For example `background: $text` won't work either.

**Comment by willmcgugan** [comment]
It's because the `text` variable has a second alpha value, which isn't supported everywhere. Maybe it should, but in the meantime `$foreground` will give you the text color with no alpha.
