### ISSUE TITLE
Binding for `]` renders incorrectly in `Footer`

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#3035]
The binding `Binding("ctrl+right_square_bracket", "toggle_indent_width", "Cycle indent width")` renders like this:

<img width="431" alt="image" src="https://github.com/Textualize/textual/assets/5740731/2c2bd6fa-288b-4205-aba0-48eb1b6c41e0">

It should probably render as `Ctrl+]`.

**Comment by TomJGooding** [comment]
Just to add that this isn't specific to the `right_square_bracket` key. 

For example, the binding for `ctrl+left` will also display the text rather than the symbol:

```python
from textual.app import App, ComposeResult
from textual.widgets import Footer


class ExampleApp(App):
    BINDINGS = [
        ("left", "left", "Symbol"),
        ("ctrl+left", "ctrl_left", "No Symbol"),
        ("right_square_bracket", "right_square_bracket", "Symbol"),
        ("ctrl+right_square_bracket", "ctrl_right_square_bracket", "No Symbol"),
    ]

    def compose(self) -> ComposeResult:
        yield Footer()

    def action_left(self) -> None:
        self.bell()

    def action_ctrl_left(self) -> None:
        self.bell()

    def action_right_square_bracket(self) -> None:
        self.bell()

    def action_ctrl_right_square_bracket(self) -> None:
        self.bell()


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by TomJGooding** [comment]
Sorry to bump this issue, but it has been hanging around for a while and should just be a simple fix?

**Comment by darrenburns** [comment]
@willmcgugan this is a really common key binding- could we prioritise this?

**Comment by willmcgugan** [comment]
It's in ToDo...

**Comment by darrenburns** [comment]
@willmcgugan cool thanks - the GitHub mobile app doesn't show project stuff so I didn't see that.

**Comment by TomJGooding** [comment]
I'm not sure whether the mobile app show linked PRs or not, but I did attempt to fix this here:

- #3050
