### ISSUE TITLE
Emojis in footer on Windows cause artifacts in the interface

### ISSUE THREAD

**Issue by mzebrak** [Textualize/textual#3040]
# Description
Here are some screenshots about what I mean:

After pushing screen (We can observe, there is an additional line below):
![image](https://github.com/Textualize/textual/assets/73518558/c56e3bd4-a84b-42a9-972a-5f1d962f697d)

And when hovering over footer buttons (all you need is f10, no need to hover over the emoji):
![image](https://github.com/Textualize/textual/assets/73518558/464230c6-db02-43b8-9e38-c537820d1be9)

This is only observable on the `Windows` platform. (`Windows Termnial` app). While using `MobaXterm` on `Windows`, this does not appear. Also, everything is fine on `Ubuntu 22.04` with the `x-terminal-emulator (terminator)`.

Here's the output of `textual diagnose` from the problematic `Windows` using `Windows Terminal`.  Also, we already checked and this problem still occurs with `0.30.0`, so please do not bother with the version in the log below:

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.17.3 |
| Rich    | 13.3.5 |

## Python

| Name           | Value                                                                          |
|----------------|--------------------------------------------------------------------------------|
| Version        | 3.10.6                                                                         |
| Implementation | CPython                                                                        |
| Compiler       | GCC 11.3.0                                                                     |
| Executable     | /home/admin/.cache/pypoetry/virtualenvs/venv-lNdCDQsZ-py3.10/bin/python |

## Operating System

| Name    | Value                               |
|---------|-------------------------------------|
| System  | Linux                               |
| Release | 5.15.90.1-microsoft-standard-WSL2   |
| Version | #1 SMP Fri Jan 27 02:56:13 UTC 2023 |

## Terminal

| Name                 | Value     |
|----------------------|-----------|
| Terminal Application | *Unknown* |
| TERM                 | xterm     |
| COLORTERM            | truecolor |
| FORCE_COLOR          | *Not set* |
| NO_COLOR             | *Not set* |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=132, height=43 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 132                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 43                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
Do you think you could give a minimal example bit of code, that can run stand-alone, that we can test, so we know we're testing the same thing as you?

**Comment by mzebrak** [comment]
> Do you think you could give a minimal example bit of code, that can run stand-alone, that we can test, so we know we're testing the same thing as you?

Here's the example:

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import Footer, Header, Placeholder


class MyApp(App[None]):
    BINDINGS = [
        Binding("enter", "enter", "🗑️"),
    ]

    def compose(self) -> ComposeResult:
        yield Header()
        yield Placeholder("Hello, world!")
        yield Footer()

    def action_enter(self) -> None:
        pass


if __name__ == "__main__":
    MyApp().run()

```

**Comment by willmcgugan** [comment]
Emojis tend to render differently across platforms. Windows in particular struggles with certain emoji.

There's not much Textual can do about that I'm afraid. It's best to stick to emojis that are in the Unicode 9 database, or stick to plain text.

**Comment by davep** [comment]
Looks to be an issue with kitty on macOS too:

![Screenshot 2023-08-01 at 20 44 45](https://github.com/Textualize/textual/assets/28237/08dd7164-0793-40e8-ada7-9a8a8a3f4de9)

**Comment by mzebrak** [comment]
So it's not just Windows that's the problem here.


> Emojis tend to render differently across platforms. Windows in particular struggles with certain emoji.
> 
> There's not much Textual can do about that I'm afraid. It's best to stick to emojis that are in the Unicode 9 database, or stick to plain text.

Do you mean **all up to** Unicode 9 i.e. 1,2,...,9? Is each new version an extension of the previous one?
if so,
 > Wastebasket was approved as part of [Unicode 7.0](https://emojipedia.org/unicode-7.0/) in 2014 and added to [Emoji 1.0](https://emojipedia.org/emoji-1.0/) in 2015. 
 
 so, in theory, should be compatible.

**Comment by TomJGooding** [comment]
Try just pasting a bunch of wastebaskets in your terminal. Do you see anything strange with the cursor position and if you press backspace to delete?

**Comment by willmcgugan** [comment]
I'm assuming this is just a classic emoji issue. Terminals don't agree on how wide they should be. Not much we can do about it alas.
