### ISSUE TITLE
Snapshot report not generated with `pytest-textual-snapshot` version 0.3.0

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#3042]
The terminal output which links to the snapshot report no longer appears after the tests run, and it seems like the snapshot report isn't actually generated.

I've confirmed it still works on 0.2.0, so have pinned my branch to that for the time being.

<img width="476" alt="image" src="https://github.com/Textualize/textual/assets/5740731/e0a197c2-9eff-44d7-b801-62e8022c33dc">

**Comment by davep** [comment]
*Making a note of what we concluded while chatting in person*

That would implicate the PR that fixed the Textual coverage problem: https://github.com/Textualize/pytest-textual-snapshot/pull/3

**Comment by davep** [comment]
Should be fixed once v0.4.0 is live on PyPi.
