### ISSUE TITLE
Tooltips should be removed on widget unmount and scrolling

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#3045]
When a tooltip is visible on screen, and the widget it's associated with gets unmounted. The tooltip remains on screen, which looks kind of weird.

Also, if a tooltip is visible, and you scroll such that the widget is no longer on screen, the tooltip remains. When you finally move the cursor, it disappears.

When the parent is unmounted, or when we scroll, I believe the tooltips should be hidden immediately.

**Comment by davep** [comment]
> Also, if a tooltip is visible, and you scroll such that the widget is no longer on screen, the tooltip disappears. When you finally move the cursor, it disappears.

Just to check: there's a typo here @darrenburns? This is trying to say that if you scroll the tooltip *remains*, or something else?

**Comment by darrenburns** [comment]
It remains, yeah

**Comment by davep** [comment]
Another situation: if a widget is `visible`, has a tooltip shown, and then it is made not `visible`.

**Comment by davep** [comment]
And another situation: if a widget is `display: block`, has a tooltip shown, and then becomes `display: none`.

**Comment by davep** [comment]
#4191 is working well and seems to cover all the bases. We've decided that we should open it up a little and make this based off a signal, which will be published when a layout change happens, and so they the tooltip system can subscribe to it (the idea being someone's third party tooltip system could do the same).

Also, in addition to this: tooltips don't go away if a screen is pushed on top of a screen that is currently displaying a tooltip, so we'll look at taking that into account too.
