### ISSUE TITLE
Windows cmd.exe terminal buffer written over

### ISSUE THREAD

**Issue by ArneBachmannDLR** [Textualize/textual#305]
Hi,

this is a repost of https://github.com/nschloe/tiptop/issues/63 as the issue is likely stemming from Textual:

Inside Windows' `cmd.exe`, a part of the terminal lines buffer is written over when exiting tiptop.

This happened when I quit tiptop via Ctrl+C, but also when pressing `q`:
I can only see commands of the shell history from around 30 lines up/ago, but not the ones that were under the Textual application just before starting titop, as the screen buffer wasn't restored when quitting tiptop.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
