### ISSUE TITLE
Screens do not flush updates the same as the App/top-level screen

### ISSUE THREAD

**Issue by nmay231** [Textualize/textual#3052]
## Details
The below example works as expected. When you click the button, it updates the child to say `PENDING` then updates to `COMPLETE` after doing some "work". The `self.counter` variable is just there for reference.

If you uncomment the multiline comment, it no longer immediately updates during the handling of `on_button_pressed()`, though the counter does increment.

## Example
```python
import asyncio

from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Button, Static

class MyApp(App):
    # HERE! Uncomment the following to nest everything inside a screen
    """
    def on_mount(self):
        self.push_screen(MyScreen())


class MyScreen(Screen):
    """
    def compose(self) -> ComposeResult:
        self.static_widget = Static("INIT")
        yield self.static_widget
        yield Button("click me!")

    counter = 0

    async def on_button_pressed(self):
        self.static_widget.update(f"PENDING {self.counter}")
        await asyncio.sleep(1)
        self.static_widget.update(f"COMPLETE {self.counter}")
        self.counter += 1

MyApp().run()
```

## System info

<details>

<summary>
`textual diagnose`
</summary>

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.31.0 |
| Rich    | 13.5.2 |

## Python

| Name           | Value                                                |
|----------------|------------------------------------------------------|
| Version        | 3.10.6                                               |
| Implementation | CPython                                              |
| Compiler       | GCC 11.3.0                                           |
| Executable     | /home/nmay/cur/statement-downloader/.venv/bin/python |

## Operating System

| Name    | Value                                                       |
|---------|-------------------------------------------------------------|
| System  | Linux                                                       |
| Release | 5.19.0-50-generic                                           |
| Version | #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.80.2) |
| TERM                 | xterm-256color  |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=151, height=8 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 151                 |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 8                   |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

</details>

**Comment by willmcgugan** [comment]
Widgets (including Screen) can not refresh themselves while a message is being processed. By sleeping for a second, you are preventing the  the screen from updating.

If you want this kind of behaviour, you could run it inside a worker.


```python
import asyncio

from textual import work
from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Button, Static


class MyApp(App):
    # HERE! Uncomment the following to nest everything inside a screen

    def on_mount(self):
        self.push_screen(MyScreen())


class MyScreen(Screen):
    def compose(self) -> ComposeResult:
        self.static_widget = Static("INIT")
        yield self.static_widget
        yield Button("click me!")

    counter = 0

    async def on_button_pressed(self):
        self.update_buttons()

    @work
    async def update_buttons(self) -> None:
        self.static_widget.update(f"PENDING {self.counter}")
        await asyncio.sleep(1)
        self.static_widget.update(f"COMPLETE {self.counter}")
        self.counter += 1


MyApp().run()
```

**Comment by nmay231** [comment]
I now understand you have to wrap the work in a worker, but shouldn't the behavior be the same for `App`s as for `Widget`s?
