### ISSUE TITLE
Remove docstrings from "protocol" methods

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3076]
Some public methods are used internally, but never need to be called directly by the dev. If these have docstrings they appear in the API docs. I feel these are noise, and we shouldn't be showing these to the developer.

I think the docstrings on Widgets *subclasses* should be removed, for the following methods:

`get_content_width()`
`get_content_height()`
`def compose()`
`def render()`

But review what other methods may be covered by this.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao Thoughts?

**Comment by rodrigogiraoserrao** [comment]
> Some public methods are used internally, but never need to be called directly by the dev.

Does that mean they should/could be private, then..? 🤔 

---

For trivial one-line docstrings, I'm not _opposed_ to removing them.
But there might be cases where we use the docstrings to add more information, so I think it is preferable that we use a filter to exclude those methods from being included.

**Comment by willmcgugan** [comment]
> Does that mean they should/could be private, then..? 🤔

Not really. If you subclass widget, you need to implement them.

> so I think it is preferable that we use a filter to exclude those methods from being included.

How can we filter them? Is there a mkdocs option?

**Comment by rodrigogiraoserrao** [comment]
> > Does that mean they should/could be private, then..? 🤔
> 
> Not really. If you subclass widget, you need to implement them.

I don't get the causation here.
Can't something be private and still need overriding when subclassing?

> How can we filter them? Is there a mkdocs option?

[Yes](https://mkdocstrings.github.io/python/usage/configuration/members/#filters).
If you assign this to me I'll get this done.

**Comment by willmcgugan** [comment]
> 
> I don't get the causation here. Can't something be private and still need overriding when subclassing?

You can in Python. Although in classic OOP, private means only for use by the one class. 

> 
> > How can we filter them? Is there a mkdocs option?
> 
> [Yes](https://mkdocstrings.github.io/python/usage/configuration/members/#filters). If you assign this to me I'll get this done.

Make it so.

**Comment by rodrigogiraoserrao** [comment]
> > I don't get the causation here. Can't something be private and still need overriding when subclassing?
> 
> You can in Python. Although in classic OOP, private means only for use by the one class.

Hmmm ok, I thought the leading `_` in Python could also mean "protected", in the Java sense.

> Make it so.

👍
