### ISSUE TITLE
Textual CSS VScode integration

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3083]
It's looking really good. Just a little more work before we push it.

Some things I think we will need:

- Variables. e.g. `$foo`. This is important, and if we have to give up some finely grained highlighting, so be it.
- Comments (multiline or starting with a #)
- `!mportant` seems to highlight in red, which suggests an error. It should be another color.
- `rgba(...)` colors should be highlighted

Nice to haves:

- Highlighting selectors. e.g. `DataTable:focus` where the `:focus` is different
- Selectors in general

**Comment by rodrigogiraoserrao** [comment]
- [ ] Variables. e.g. `$foo`. This is important, and if we have to give up some finely grained highlighting, so be it.
  - [x] variables as complete rule values, e.g., `background: $some_color;` (https://github.com/Textualize/tcss-textmate-grammar/commit/1e392b31ba97e8b9627976a83a41bd8c3eedf0ee)
  - [ ] variables as partial rule values, e.g., `padding: 1 $two_three 4;`
  - [ ] variable assignment, e.g., `$two_three: 2 3;`
- [ ] Comments (multiline or starting with a #)
- [x] `!important` seems to highlight in red, which suggests an error. It should be another color. (https://github.com/Textualize/tcss-textmate-grammar/commit/812efbd56c524197083c12921c7acff15752f764)
- [x] `rgba(...)` colors should be highlighted (https://github.com/Textualize/tcss-textmate-grammar/commit/1cca1656050b670ad3b7b2d749799842233cbcdd)

Nice to haves:

- [ ] Highlighting selectors. e.g. `DataTable:focus` where the `:focus` is different
- [ ] Selectors in general
