### ISSUE TITLE
Add a Textual testcard to help diagnose visual problems

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3087]
Possibly done as part of the developer tools, or perhaps even as a standalone application that can be installed via `pip` or `pipx` so developers can instruct end users of their applications to install it: create a Textual [testcard](https://en.wikipedia.org/wiki/Test_card) to help with diagnosing visual issues with applications.

Things that it could do might include:

- Show a full range of colours to help check what colour range is available.
- Show the operating system (with version), terminal information where possible, etc.
- Show some key and often problematic widgets (see [this on Discord](https://discord.com/channels/1026214085173461072/1033754296224841768/1139119187340574820), which relates to [this question](https://discord.com/channels/1026214085173461072/1033754296224841768/1139014261394378843)).
- If possible, be very clear on screen about what *should* be visible (for example: with a checkbox, have text that says "this should be dark grey" or something like that).
- Perhaps ideally show some of the common terminal attributes (bold, underline, italic, strikethrough, etc...).
- Anything else *visual* that makes sense.

This might seem like it has an overlap with `textual diagnose`, but the intention here is that it's different. It will be all about the visuals, would allow people to create a screenshot and make it available to us, the screenshot would contain information useful to us (see OS version and terminal above), and would also be as easy as possible to deploy and use (which is why I think a stand-alone application that can be `pipx`-installed makes a lot of sense).

**Comment by willmcgugan** [comment]
I don't think we need this. With Textual being more mature, there are few issues that this would diagnose.
