### ISSUE TITLE
Profile startup

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3095]
A user reported that starting up the demo is slow on a Raspberry Pi zero, but runs adequately.

We should profile startup and look for improvements.

`demo.py` seems a good place to start.

**Comment by willmcgugan** [comment]
I think we should configure an app to exit immediately (on App.on_ready), and profile that with pyinstrument.

There may be slow routines that stand out. If those are easily optimizable it could be done as part of this issue. Or it could result in optimization issues for later work.

**Comment by davep** [comment]
Initially starting with this app:

```python
from textual.app import App

class GNDN(App[None]):

    def on_ready(self) -> None:
        self.exit()

if __name__ == "__main__":
    GNDN().run()
```

**Comment by davep** [comment]
Starting on macOS... using the above, initially it looks like the two main areas of work on startup are in getting the driver up and running, and also parsing the initial styles:

<img width="1073" alt="Screenshot 2023-08-28 at 09 49 13" src="https://github.com/Textualize/textual/assets/28237/eaa1fe94-9012-4f99-9ba8-5de434a61a6d">

**Comment by davep** [comment]
Testing on Windows 11 (under Parallels on macOS), there seems to be a split of similar nature, but with a rather different balance.

<img width="886" alt="Screenshot 2023-08-28 at 09 55 48" src="https://github.com/Textualize/textual/assets/28237/876aaab2-8ca4-4c25-be01-c6bc1bd66de0">

**Comment by EricWF** [comment]
What tool are you using to generate those profiles?

**Comment by davep** [comment]
pyinstrument; see https://github.com/davep/profile-textual for the repo where I've put together some files and a Makefile for testing.

**Comment by willmcgugan** [comment]
@davep is this in progress or is it stalled?

**Comment by davep** [comment]
As mentioned a couple of weeks back: waiting until you're happy for me to spend some time testing out on the Pi - you said to leave it some time back.

**Comment by willmcgugan** [comment]
As I said: it doesn't need to be on the Raspberry PI. I'm looking for optimisation wins. Going to move this back to Todo.

For the benefit of whoever picks this up. Please don't spend more than half a day. If there are quick wins, go ahead and implement them. Otherwise document them here.

Resolution may very well be that there are no significant improvements.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/pull/3753

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/pull/3756
