### ISSUE TITLE
Textual breaks stdout tty detection

### ISSUE THREAD

**Issue by dhallas** [Textualize/textual#3111]
If you have an application that uses textual and try to detect if stdout is a tty, it doesn't work after pull request #2971 was merged.

I have a textual application that uses the [python kubernetes client](https://github.com/kubernetes-client/python) to interface with kubernetes. This library tries to detect if stdout is an interactive tty to adapt is behavior accordingly. This was working with textual v0.30.0 and kubernetes-client v27.2.0 but broke after updating to textual v0.31.0. I did a git bisect and found that pull request #2971 is the culprit.

I can work around the issue by making the following change in textual:

```
diff --git a/src/textual/app.py b/src/textual/app.py
index f505bdfb6..081074c29 100644
--- a/src/textual/app.py
+++ b/src/textual/app.py
@@ -236,7 +236,7 @@ class _PrintCapture:
     def isatty(self) -> bool:
         """Pretend we're a terminal."""
         # TODO: should this be configurable?
-        return True
+        return False
 
 
 @rich.repr.auto
```

Here is a link to a ticket in kubernetes-client that explains how they detect if stdout is an interactive tty: https://github.com/kubernetes-client/python/issues/1986

**Comment by willmcgugan** [comment]
I'm confused as to what the issue is. `sys.stdout.isatty()` will report `True`. Presumably it is running in a terminal. Why is this not correct?

**Comment by dhallas** [comment]
I am not sure exactly what goes wrong. But I can observe the following when running
```
sys.stdout.isatty()
```
return value

textual version 0.30.0 return False
textual version 0.31.1 return True

My application uses the kubernetes-client library to interface with kubernetes. Form what I can see from the code is they try to detect if stdout is a tty and use this information to determine how to communicate with sub-processes. Here is a code snippet from the kubernetes-client library code that does the check (and presumably fails)

```
    def run(self, previous_response=None):
        is_interactive = hasattr(sys.stdout, 'isatty') and sys.stdout.isatty()
        kubernetes_exec_info = {
            'apiVersion': self.api_version,
            'kind': 'ExecCredential',
            'spec': {
                'interactive': is_interactive
            }
        }
        if previous_response:
            kubernetes_exec_info['spec']['response'] = previous_response
        self.env['KUBERNETES_EXEC_INFO'] = json.dumps(kubernetes_exec_info)
        process = subprocess.Popen(
            self.args,
            stdout=subprocess.PIPE,
            stderr=sys.stderr if is_interactive else subprocess.PIPE,
            stdin=sys.stdin if is_interactive else None,
            cwd=self.cwd,
            env=self.env,
            universal_newlines=True)
        (stdout, stderr) = process.communicate()
```

Could the problem be that the new _PrintCapture class doesn't behave like a tty as expected by the above code snippet? If I modify the code snippet above to force _is_interactive_ to be False it also works. 

With all this said, I am not sure if the problem is the tty detection code in kubernetes-client or if the problem is within textual.

**Comment by willmcgugan** [comment]
I'll need to understand what behaviour you want. Are you wanting to run Textual in a subprocess in a way that is non interactive?

Textual is assuming it will be run in an interactive terminal, because it won't generate any useful output otherwise. Which is why `isatty` returns True.

**Comment by dhallas** [comment]
Let me try to explain. I am building a textual app that runs as normal in an interactive terminal. All is good there :) The application is using the Kubernetes Client Python library to interface with kubernetes. This library tries to determine if it is running in an interactive terminal. This is used when the Kubernetes Client Python library needs to spawn processes to handle authentication. The problem I am facing seems to come from this detection logic in the Kubernetes Client Python library. The library uses the following code to determine if it is running in an interactive terminal:

`is_interactive = hasattr(sys.stdout, 'isatty') and sys.stdout.isatty()`

if this detection returns _true_ the Kubernetes Client Python library passes `sys.stdin` and `sys.stderr` directly the sub-process that it is spawning to handle authentication. This doesn't work since textual uses stdin and stderr. In previous versions of textual, this check returned _false_ and the Kubernetes Client Python library uses a pipe instead to communicate with the authentication sub-process and everything worked just fine. After the change introducing the `_PrintCapture` class in textual the `is_interactive` check returns `true` causing the sub-process communication to fail.

Hope this makes sense :)

**Comment by dhallas** [comment]
After digging some more, I think I have found the actual root cause of the problem. And you were absolutely right that it is not related to the return value of `isatty`
I created the following example program to illustrate the problem:
```
#!/usr/bin/env python3

import subprocess
import sys

from textual.app import App, ComposeResult
from textual.widgets import Header, Footer


class TestApp(App):
    BINDINGS = [("r", "run_process", "Run Sub Process")]

    def compose(self) -> ComposeResult:
        yield Header()
        yield Footer()

    def action_run_process(self) -> None:
        is_interactive = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
        args = ["ls", "-la"]
        process = subprocess.Popen(
            args,
            stdout=subprocess.PIPE,
            stderr=sys.stderr if is_interactive else subprocess.PIPE,
            stdin=sys.stdin if is_interactive else None,
            universal_newlines=True,
        )
        (stdout, stderr) = process.communicate()
        exit_code = process.wait()


if __name__ == "__main__":
    app = TestApp()
    app.run()

```

If you run the above program, you get a Python exception from the Python subprocess module, trying to access the file descriptor from stderr using this function: `stderr.fileno()` But since this method doesn't exist on the _PrintCapture class a `AttributeError` is raised, and that is the reason for why I see failures in Kubernetes authentication. Adding a `fileno` function to `_PrintCapture` solves the issue for me.

I can make a pull request with this change if needed?

Hope it makes sense :)

**Comment by willmcgugan** [comment]
Ah, got you. If adding a `fileno()` to `_PrintCapture` fixes the issue, then I'm onboard with that.

> I can make a pull request with this change if needed?

Sure
