### ISSUE TITLE
CSS class + id/python-class not being applied

### ISSUE THREAD

**Issue by brisvag** [Textualize/textual#3120]
Pardon if this is a silly CSS newbie question; I googled around and found nothing helpful, and the guide and tutorial seem to imply that this should work.

Consider this simple program:

```py
from textual.app import App
from textual.widgets import Label


class MyApp(App):
    DEFAULT_CSS = """
    .disabled #lab {
        display: none;
    }
    """

    def compose(self):
        yield Label("Some text", id='lab', classes='disabled')

if __name__ == "__main__":
    app = MyApp()
    app.run()
```

My understanding is that the label should be hidden. However, neither `.disabled #lab` (which AFAICT is [exactly equivalent to the example in the guide](https://textual.textualize.io/tutorial/#dynamic-css)) nor `.disabled Label` work as selector for me. If I however change it to just `.disabled`, this works as intended.

So, how should I specifically disable that one label (assuming a more complex program where the `disabled` class is used elsewhere)? Or is this a bug?

**Comment by willmcgugan** [comment]
Your selector is close, but not quite correct.

```css
.disabled #lab
```

This selector says any widget with an id of "lab" with that has a parent with class "disabled"

I suspect you want this:

```css
#lab.disabled
```

This says a widget with id "lab" which also has the class "disabled". Not there is no space, so the class must be on the same widget.

**Comment by brisvag** [comment]
Hah! Thanks @willmcgugan, and now I see that the tutorial does specify this parent/child relationship... I skimmed too fast ^^' Thanks for the help! Loving textual so far :)
