### ISSUE TITLE
Auto expanding height

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3122]
You can set a height when you add a row to the DataTable, but there is currently no way to make it expand to fit the content.

I think that `add_row` should grow an option to automatically calculate the optimal height of a row.

If we make this the default, we should be able to explicitly override it with a height. Perhaps a `height` of None means auto-detect, and a integer sets it explicitly. An explicit height will be faster, which might be significant if the user adds a lot of rows.

**Comment by charles-001** [comment]
+1 this would be great to have. Rich's `Table` currently have this behavior.

**Comment by willmcgugan** [comment]
This does actually work. These is a edge case with an auto height table, in an auto height container. The max height of the table is set to 100% which prevents the table from expanding. We need a workaround for that/
