### ISSUE TITLE
Button background stuck in hover style if disabled programatically 

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3130]
### Is there an existing issue for this?

I found this issue #790 closed last November, but it isn't quite describing the same thing.

- [x] I have searched the open issues

### Description of the bug

If you are hovering a `Button` that is then disabled programmatically, the button background colour seems to be stuck in the hover style.

### To Reproduce

```python
from textual.app import App, ComposeResult
from textual.containers import Center
from textual.widgets import Button, Footer, Label


class ExampleApp(App):
    CSS = """
    Screen {
        align: center middle;
    }
    """

    BINDINGS = [("space", "toggle_button", "Toggle Button")]

    def compose(self) -> ComposeResult:
        with Center():
            yield Label("Hover the button then hit space")
        with Center():
            yield Button("Enabled", id="disable-btn")
        yield Footer()

    def action_toggle_button(self) -> None:
        self.app.bell()
        button = self.query_one("#disable-btn", Button)
        if button.disabled is False:
            button.disabled = True
            button.label = "Disabled"
        else:
            button.disabled = False
            button.label = "Enabled"


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by TomJGooding** [comment]
I've found a workaround by setting `mouse_over` to False when disabling the button - despite the documentation saying this is read only!

Should something similar be added to the  base Widget class...?

```python
from textual.app import App, ComposeResult
from textual.containers import Center
from textual.widgets import Button, Footer, Label


class ExampleApp(App):
    CSS = """
    Screen {
        align: center middle;
    }
    """

    BINDINGS = [("space", "toggle_button", "Toggle Button")]

    def compose(self) -> ComposeResult:
        with Center():
            yield Label("Hover the button then hit space")
        with Center():
            yield Button("Enabled")
        yield Footer()

    def action_toggle_button(self) -> None:
        button = self.query_one(Button)
        if button.disabled is False:
            button.disabled = True
            button.label = "Disabled"
            # Workaround for https://github.com/Textualize/textual/issues/3130
            button.mouse_over = False
        else:
            button.disabled = False
            button.label = "Enabled"


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by klott** [comment]
This is biting me too, thanks for the workaround!

**Comment by TomJGooding** [comment]
This issue has just come up again in #4198, weirdly only a couple of days after the linked PR has apparently  been abandoned!

I'm happy to look at a new PR for this, but I feel like setting `mouse_over` is a bit of a hack? I do remember struggling instead to handle the hover style, so I'm afraid I would need some guidance if that is the correct approach.

**Comment by willmcgugan** [comment]
A note for myself when I pick this up later. The root cause is that Enter and Leave events are explicitly disabled when a widget is disabled. https://github.com/Textualize/textual/blob/main/src/textual/widget.py#L3725
