### ISSUE TITLE
Rename CSS to TCSS

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3137]
Now that we have an awesome Textual CSS syntax highlighter, we should change the extension in the code and docs.

All *.css files should be renamed to *.tcss, and code updated accordingly.

There should also be a brief explanation in the guide regarding the naming, which also mentions the vscode extension.

**Comment by Emasoft** [comment]
TCSS should be much simpler and easier to write and debug than CSS. Currently I spend more time debugging TCSS than writing the python part. Apply a style to a simple object is too complicated.

**Comment by davep** [comment]
@Emasoft This isn't really the right place for that. If you need help or support getting going with Textual's CSS then please either ask questions [in discussions](https://github.com/Textualize/textual/discussions) or, if it's more to your taste, come ask for help in [our Discord server](https://discord.gg/Enf6Z3qhVr).

You'll also find a great introduction [to styles](https://textual.textualize.io/guide/styles/) and [to Textual CSS](https://textual.textualize.io/guide/CSS/) in [the guide to Textual](https://textual.textualize.io/guide/).

If you have any followup to this, please don't use this issue for that, as mentioned above: please use discussions or Discord.

**Comment by willmcgugan** [comment]
> There should also be a brief explanation in the guide regarding the naming, which also mentions the vscode extension.

@rodrigogiraoserrao Did you miss this?

**Comment by rodrigogiraoserrao** [comment]
> > There should also be a brief explanation in the guide regarding the naming, which also mentions the vscode extension.
> 
> @rodrigogiraoserrao Did you miss this?

I did, sorry.
