### ISSUE TITLE
Revisit the removal of "protocol" methods from the docs

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3141]
While on the whole #3076 made perfect sense, there are some situations where we would want to keep the "protocol" methods in the docs. An example would be `textual.app.App.compose`; the idea here being that when such a method is introduced, it should go into the documentation; only the overrides in child classes need to be excluded.

Not keeping the implementation that introduces the method means the method doesn't get documented at all, and so then results in things like this in the docs:

<img width="833" alt="Screenshot 2023-08-22 at 14 19 37" src="https://github.com/Textualize/textual/assets/28237/4d4e4b85-a129-4221-acc9-79e1eb516721">

(note how `compose()` [isn't a link any more](https://textual.textualize.io/guide/app/#composing))

More generally: we seem to have acquired a lot more warnings and similar things during docs generation; we should perhaps look to them to see if they're related to this change.

**Comment by rodrigogiraoserrao** [comment]
The increased number of things in the log are a bunch of INFO logs that we get as of a more recent mkdocs version (or a more recent version of one of the plugins) where we get warned about absolute links that the logs recommend be made relative, so it's unrelated to the “protocol” changes.
