### ISSUE TITLE
Please make CSS optional

### ISSUE THREAD

**Issue by Emasoft** [Textualize/textual#3147]
I understand that some will find the idea of styling a TUI app with CSS appealing, but I don't. For the following reasons:  
  - No way to debug CSS. (I spend a lot of time to fix css issues that before would require one line of python to just work)
  - CSS is hard to use from code (there is no way to import CSS in a manageable data structure like a set of dictionaries).
  - No simple setters for assigning css classes to objects (like: my_textview.css_class = 'dark_style_textview').
  - CSS is too complex because is made for browsers. A TCSS should be a greatly simplified version of it (much more than now).
  - CSS rules syntax is messy to begin with.  
  - Having to make sure that the tcss files are compatible with the version of Textual used in the project is a pain (this will end with multiple version of each css file).
   
 Because of this, I humbly ask for the CSS styling to be optional in Textual, and for all the styling peoperties to be also available programmatically. Behind the scenes the CSS is already converted in python code, so it should not be difficult to expose the internal methods and properties. Thanks in advance.🙏

**Comment by davep** [comment]
> No simple setters for assigning css classes to objects

- [`set_class`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.set_class)
- [`set_classes`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.set_classes)
- [`toggle_classes`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.toggle_class)
- [`remove_class`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.remove_class)
- [`classes`](https://textual.textualize.io/api/dom_node/#textual.dom.DOMNode.classes)

As for the more general request to make "CSS optional", I suspect you'll find that it already is. You can [manage styles from code if that is your preference](https://textual.textualize.io/guide/styles/). If you refer to [the style guide](https://textual.textualize.io/styles/) you'll see that every style has its Python-based set/access approach documented; just look for the `Python` section in each page (see [the entry for `color` for example](https://textual.textualize.io/styles/color/#python)).

**Comment by willmcgugan** [comment]
@Emasoft CSS is [entirely optional](https://textual.textualize.io/guide/styles/#styling-widgets) But still the best way of separating logic from presentation. It also enables live editing, in a way you couldn't do if all your styles are in Python.

Textual CSS has a tiny fraction of the footprint of browser CSS. But as with any technology, you still need to learn it.

> No simple setters for assigning css classes to objects (like: my_textview.css_class = 'dark_style_textview').

```python
mt_textview.classes = "dark_style_textview"
```

Your comments suggest that you haven't read the docs in much detail. I'd recommend you do that. And if you run in to any problems, ask in one of the [help](https://textual.textualize.io/help/) channels.

**Comment by davep** [comment]
> In other words: you first need to query using the id to get the object handle, then you need to add the class to it. Those look like two lines of code to me.
> How can I do this with one line of code?

Textual widgets are simply Python objects, so you can do it how you would when you call any function or method that returns an object that has attributes. For example:

```python
self.query_one("#hello", Static).add_class("dark_style")
```

If you would prefer to not query every time, you can again use the fact that they're just Python objects and keep a reference to them around when you first create them, then refer to that reference.

> At the moment the documentation seems to suggest that CSS is the only way.

The documentation [first introduces you to styles](https://textual.textualize.io/guide/styles/), without CSS. That introduction to styles is pretty comprehensive and makes it *very* clear you can do this from code.

**Comment by davep** [comment]
@Emasoft If a developer wants to retain a reference to a widget they'd normally go with something like this:

```python
def compose(self) -> ComposeResult:
    self.hello = Static("Hello, World!", id="hello")
    yield self.hello

...

def some_other_method(self) -> None:
    self.hello.update("Hey look I'm saying hello a different way!")
```

and then direct access to that widget is available to the rest of the app/screen/widget that `compose` is a member of.

> So with this pattern the references are not declared, and the user must then do an additional Query every time he needs to access the instance of the object. Isn't this overcomplicating things?

As a discerning Python developer you have the choice to write your code to your own taste; we obviously don't dictate the style that best suits you. :-)

**Comment by davep** [comment]
For what it's worth, if you want to set the class for a widget you can do it like this:

```python
def compose(self) -> ComposeResult:
    yield Static("Hello, World!", id="hello", classes="dark_style")
```

More generally though, a few of the things you're now bringing up aren't really related to CSS at all, and seem to be more to do with working with the Textual DOM. As such it's really straying off the topic of this closed issue. If you have questions about how to get to grips with that I can only offer the same advice both Will and I have already given, and that's [use the docs and the help resources](https://textual.textualize.io/help/).

**Comment by Emasoft** [comment]
Ok, I just hope that you will make examples for both CSS and NoCSS mode of using Textual.
