### ISSUE TITLE
[DOCS] Add prominent link to demo.py and introduce Screens earlier in the docs

### ISSUE THREAD

**Issue by and-viceversa** [Textualize/textual#3158]
Hacker News brought me here. Thank you for this excellent framework! I'm testing it out by adding a front end to some of my Python CLI tools.

2 doc suggestions as new Rich and textual user.
- Add a link to the actual demo.py file in README.md and in the tutorial. It's otherwise featured prominently and it'd be nice to quickly jump to the source.
- Bump the Guide docs for Screens higher in the guide's progression. Starting out I read too much about CSS and Widgets without realizing what I was actually "standing on" in the background. Once Screens are introduced, it makes it easier to envision the app's flow and how the other pieces fit together.

**Comment by willmcgugan** [comment]
Not sure demo.py is all that useful as documentation. It's one of the earlier bits of code in the project, and will change soon.

Not sure if it makes sense to introduce Screens after CSS and widgets. How can you talk about screens without knowing about widgets? I'm open to linking forward to screens somewhere though. Open to suggestions,
