### ISSUE TITLE
Documentation menu problem with initial page load

### ISSUE THREAD

**Issue by nmstoker** [Textualize/textual#3182]
In the documentation at https://textual.textualize.io/ there appears to be some sort of initial page load issue where the menus that you see first are a very basic, cut down form and you only see the full menus if you click to close that cut down menu in a specific way.

I have only confirmed this on Android 13, and not on desktop, but it happens under both mobile Chrome and mobile Firefox (both up to date).

There is a video showing it here (it may be easier to follow what is being done if you read the steps to reproduce it below.

https://github.com/Textualize/textual/assets/3694484/2b10263e-d4cb-49ab-9a45-f928e1a7beca

## To reproduce issue

1. Go to https://textual.textualize.io/ in your browser (_this may require Android but am currently unsure_)
2. Click the menu (observe that it opens without the full range of menu items shown)
3. Click anywhere outside the menu to close it - this means that the reduced menu remains present as you will see if you repeat point 2
4. Now repeat point 2 but this time close the menu by clicking the little arrow at the top of the menu itself - this reveals the more detailed menu behind it (which I believe is the one meant to show up all along)
5. Refreshing the page results in the initial menu being reinstated

**Comment by willmcgugan** [comment]
I think this is by-design. It's just how mkdocs-material implements the menus. That arrow in the side bar isn't for dismissing the sidebar, its to go up one level in the TOC.

I don't actually like how that is implemented. I think it does tend to hide information from mobile users. But we don't have much control over it. :(

**Comment by nmstoker** [comment]
Ah, I see. Thanks for explaining it. If it isn't feasible to fix then I'll close this.
