### ISSUE TITLE
Screens should have a title and subtitle

### ISSUE THREAD

**Issue by MartijnBraam** [Textualize/textual#3195]
When implementing a multi-screen application that has Header widgets in the screens the title and subtitle displayed in the Header should be stored in the Screen as overrides instead of only using the global values from the application.

This would simplify displaying titles in screens properly with keeping the title and subtitle synchronized with the screen stack.

**Comment by willmcgugan** [comment]
Should be easy to implement. Screen would have `title` and `subtitle`, which would override the App attributes if not None. We would need to manage titles when the active screen changes.
