### ISSUE TITLE
Provide a method for manual triggering reactive watchers / a way to trigger watchers when a plain python (data)class stored in a reactive attribute changes

### ISSUE THREAD

**Issue by mzebrak** [Textualize/textual#3245]
This one is related to: https://github.com/Textualize/textual/discussions/3215

The final solution could probably appear with the introduction of the [abstraction of reactive attributes](https://textual.textualize.io/roadmap/#features), but at the moment I would be very grateful if there was even a method on the textual side, allowing to manually inform the watchers about the change taking place in the reactively stored class.

Our current solution seems to stop working after textual version of `0.35.1`, and we cannot bump any further so I would like to ask for a similar method in the textual library itself.

<details>
<summary>current workaround looks like this</summary>

```python
from textual.app import App
from textual.binding import Binding
from textual.dom import DOMNode
from textual.reactive import var
from textual.widgets import Footer, Label


class ManualReactive(DOMNode):
    def update_reactive(self, attribute_name: str) -> None:
        """
        Updates the given reactive attribute.

        Reactive attributes of Textual are unable to detect changes to their own attributes
        (if we are dealing with a non-primitive type like a class).
        In order to notify watchers of a reactive attribute, it would have to be re-instantiated with the modified
        attributes. (See https://github.com/Textualize/textual/discussions/1099#discussioncomment-4047932)
        This is where this method comes in handy.
        """
        try:
            attribute = getattr(self, attribute_name)
        except AttributeError as error:
            raise AttributeError(f"{error}. Available ones are: {list(self._reactives)}") from error

        descriptor = self.__class__.__dict__[attribute_name]

        # now we trigger the descriptor.__set__ method like the `self.attribute_name = value` would do
        if not descriptor._always_update:
            # that means, watchers won't be notified unless __ne__ returns False, we could bypass with `always_update`
            descriptor._always_update = True
            setattr(self, attribute_name, attribute)
            descriptor._always_update = False
        else:
            # we just need to trigger descriptor.__set__
            setattr(self, attribute_name, attribute)

        self.log(f"Manually updated reactive attribute {attribute_name} of {self.__class__.__name__}")


class ReactiveClass:
    def __init__(self) -> None:
        self.some_property = "I am an initial value :("


class MyApp(App[None], ManualReactive):
    BINDINGS = [
        Binding("f5", "update", "Update"),
    ]

    reactive_class = var(ReactiveClass(), init=False)

    def action_update(self) -> None:
        self.reactive_class.some_property = "I was updated :)"
        self.update_reactive("reactive_class")  # this is required to notify watchers of the change

    def compose(self):
        yield Label(self.reactive_class.some_property)
        yield Footer()

    def watch_reactive_class(self, value: ReactiveClass) -> None:
        self.query_one(Label).update(value.some_property)


if __name__ == "__main__":
    MyApp().run()

```
</details>

**Comment by davep** [comment]
As an aside, but in case you've not seen it mentioned before...

```python
def action_update(self) -> None:
        self.reactive_class.some_property = "I was updated :)"
        self.update_reactive("reactive_class")  # this is required to notify watchers of the change
```

A common Textual idiom here would be to have the reactive `always_update=True` and then assign it to itself to force the refresh. For example:

```python
from dataclasses import dataclass

from textual import on
from textual.app import App, ComposeResult
from textual.reactive import var
from textual.widgets import Button, RichLog

@dataclass
class ComplexThing:

    value: int = 0

class ForceWatchApp(App[None]):

    thing: var[ComplexThing] = var(ComplexThing, always_update=True)

    def compose(self) -> ComposeResult:
        yield Button("Push me to update the property")
        yield RichLog()

    def watch_thing(self) -> None:
        self.query_one(RichLog).write(f"Changed {self.thing!r}")

    @on(Button.Pressed)
    def update_thing(self) -> None:
        self.thing.value += 1
        self.thing = self.thing

if __name__ == "__main__":
    ForceWatchApp().run()
```

**Comment by mzebrak** [comment]
> As an aside, but in case you've not seen it mentioned before...
> 
> ```python
> def action_update(self) -> None:
>         self.reactive_class.some_property = "I was updated :)"
>         self.update_reactive("reactive_class")  # this is required to notify watchers of the change
> ```
> 
> A common Textual idiom here would be to have the reactive `always_update=True` and then assign it to itself to force the refresh. For example:
> 
> ```python
> from dataclasses import dataclass
> 
> from textual import on
> from textual.app import App, ComposeResult
> from textual.reactive import var
> from textual.widgets import Button, RichLog
> 
> @dataclass
> class ComplexThing:
> 
>     value: int = 0
> 
> class ForceWatchApp(App[None]):
> 
>     thing: var[ComplexThing] = var(ComplexThing, always_update=True)
> 
>     def compose(self) -> ComposeResult:
>         yield Button("Push me to update the property")
>         yield RichLog()
> 
>     def watch_thing(self) -> None:
>         self.query_one(RichLog).write(f"Changed {self.thing!r}")
> 
>     @on(Button.Pressed)
>     def update_thing(self) -> None:
>         self.thing.value += 1
>         self.thing = self.thing
> 
> if __name__ == "__main__":
>     ForceWatchApp().run()
> ```

Thanks for the quick response. Yeah, I know about the `always_update` parameter. This behavior is used by the `update_reactive` function I presented, it also assigns the reactive to itself to notify watchers. In addition, it deals with the situation when reactive did not have the `always_update=True` set because it sets this flag for a moment.  I expect that here after the new version, there may be some race that causes it not to work as it should.

In my opinion, this method has the right to exist, because it does not require `always_update `on reactive to be set previously, and from what I remember, when `self.a = self.a` was done - python code linters were dissatisfied.

But yes, thanks for the reminder, such a workaround could help.

**Comment by willmcgugan** [comment]
Fixed by https://github.com/Textualize/textual/pull/4731
