### ISSUE TITLE
Add  TERM_PROGRAM and TERM_PROGRAM_VERSION to Textual web

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3269]
Add TERM_PROGRAM which should be "textual-web", and TERM_PROGRAM_VERSION which should be the version of textual-web

**Comment by rodrigogiraoserrao** [comment]
These go in `AppSession.open` in `textual-web`, next to the other environment variables like `TEXTUAL_DRIVER` and `TEXTUAL_FPS`, right?
