### ISSUE TITLE
Command Palette shows intermediate frames

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3277]
The command palette show an intermediate frame before showing the results.

It may be hard to see in this video, but the first character produces a frame were the list is present, but there is no content. I think we should be able to suppress showing the list when no results have been retrieved.

https://github.com/Textualize/textual/assets/554369/8ae13d37-5c90-48a7-abba-1faa877241d8

**Comment by davep** [comment]
> I think we should be able to suppress showing the list when no results have been retrieved.

Should be, although we also need to take into account that we *do* want to show the list before results are received at some point, so that it can be shown that we're busy (there's pretty much already logic for that so hopefully it'll just be an extra step/check).
