### ISSUE TITLE
Add documentation for `RenderableType` and `TextType`

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3310]
There are a number of references to `RenderableType` and `TextType` in the documentation, but there are no links explaining these types.

**Comment by rodrigogiraoserrao** [comment]
From a couple of quick experiments, I think the only thing that needs to be done is add a docstring to both on the `rich` side.

**Comment by TomJGooding** [comment]
Will this be added automagically after #3341, or will it still require editing of docstings etc?

Let me know if I can help in any way?

**Comment by willmcgugan** [comment]
That's live now.
