### ISSUE TITLE
DataTable doesn't update styles when component classes are changed with hot-reloading

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3312]
If you change the data table cursor component style `.datatable--header` with hot reloading, then the style update isn't applied properly.
I suspect this is transversal to all other component classes and it's related to the dead coroutine `_on_styles_updated`.

**Comment by willmcgugan** [comment]
That may have been the original name. If you rename it to `notify_style_update` I think it will work.

**Comment by rodrigogiraoserrao** [comment]
Yup, I figured that much. I'm just writing a decent regression test.
I'm glad I found this because it gives also some clarity on the caching issue you brought up in https://github.com/Textualize/textual/pull/3213#discussion_r1326071862
