### ISSUE TITLE
`TimeoutError` when finding nothing in the Command Palette (Python <3.11)

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3320]
To test this, make a fresh installation of Textual, then run:

```sh
$ python -m textual
```

To run up the demo. Press <kbd>Ctrl</kbd>+<kbd>\\</kbd> to pull up the command palette, then type something that won't be found, such as "hello". Within a moment or so you should get a `TimeoutError`.

Note that this seems to *only* be an issue with Pythons less than 3.11.

**Comment by SkwalExe** [comment]
I was able to reproduce the issue on python 3.10

**Comment by davep** [comment]
As best as I can tell, this comes down to this commit: eaa749665f9b8271eff45be8e5e1e72ac8729b9e

@willmcgugan Was there a reason for switching from `asyncio.TimeoutError` to `TimeoutError` here? I also gather that there is a change from 3.11 onward that we need to take into account?
