### ISSUE TITLE
Consider the issue of message leakage from "system" screens

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3323]
If a developer were to write a simple all-on-the-app tool, with very broad message handlers, expecting them to *only* catch messages from widgets they compose into their application, they could end up receiving unexpected messages from any system popup tools; the `CommandPalette` being a current obvious source.

Consider this code as an example:

```python
from textual import on
from textual.app import App, ComposeResult
from textual.message import Message
from textual.widgets import Label, Log

class MessageLeakApp(App[None]):

    def compose(self) -> ComposeResult:
        yield Label("Use the command palette")
        self.message_log = Log()
        yield self.message_log

    @on(Message)
    def logger(self, event: Message) -> None:
        try:
            self.message_log.write_line(f"{event!r}")
        except:
            pass

if __name__ == "__main__":
    MessageLeakApp().run()
```

If you run this up and pull up the command palette and interact with it, you'll see messages being caught that relate to the workings of the `CommandPalette` and the widgets it is composed of. While the `CommandPalette` can (and generally does -- even more so with #3322) `stop` events, it can generally only do that with events that it itself is handling. There may be unhandled events that will end up bubbling up and subsequently being caught by event handlers on the developer's app.

![Screenshot 2023-09-16 at 10 25 06](https://github.com/Textualize/textual/assets/28237/c8f0bfee-4e7e-412b-8bc5-a7431caadcce)

An example here would be `OptionList.OptionHighlighted`, which doesn't need to be taken care of in the `CommandPalette`. While the `CommandPalette` *could* be defensive and catch that, `stop` it, and otherwise be `no-op`, the `CommandPalette` can't easily anticipate all messages that could be posted from the widgets it's composed of, and even if that were done more messages could be added in the future to the component widgets and those can't easily be accounted for up front (unless of course each widget gave its messages a common base class -- see other issues on that subject).

So, the question here is: is there a way in Textual right now to have a screen go "no message from a widget shall pass through me to the app", and if there isn't should be think about something like that?

**Comment by willmcgugan** [comment]
I think adding this to the Screen would achieve that.

```python
def on_event(self, event):
    event.stop()
```

Easy enough, but you have a point. Maybe there should be a classvar on DOM nodes, like `NO_BUBBLE=True`. Which would prevent any message from bubbling.

**Comment by davep** [comment]
Would we be safe in assuming that won't stop events that should make it to the app? A resize event or something similar? (Not near a keyboard at the moment so this is more a reminder to myself to clarify in my own mind than a direct question)

**Comment by willmcgugan** [comment]
The command palette currently does stop relevant messages from reaching the app.

This isn't currently a problem, but it is something to keep in mind.

closing for now.
