### ISSUE TITLE
ListView from ScrollView

### ISSUE THREAD

**Issue by styk-tv** [Textualize/textual#334]
Hi @willmcgugan. I'd like to open this issue a s a means of tracking one of the backlog items. Maybe there are more people interested in this feature.  After days of trying I was unable to do it myself.

<img width="544" alt="Screenshot 2022-03-15 at 06 40 40" src="https://user-images.githubusercontent.com/838921/158321745-bd8500fd-1511-4b1a-adf4-6c2f1afb4c50.png">

I was not able to find a way to create a scrollable list that could overflow out of screen with a nice scroll bar.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/838921/158322720-d9525eaf-7f6d-4feb-ab36-9ab10ae1ed10.gif)

DirectoryTree was my main inspiration but I couldn't find a way to make it dockable like this:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/838921/158324178-e802ee4a-1099-4aa4-ac9e-c7c210ddcaed.gif)

```
        await self.view.dock(
            ScrollView(self.directory), edge="left", size=48, name="sidebar"
        )
```
It would be great to make the new ListView for example to contain a list of object, then bind a property like name to display something visible and then on selection to be able simply pass itself (full object) to another destination panel.

Anyone can share some ideas/tips on how to proceed or what to try?

**Comment by wasi-master** [comment]
Something like this was discussed in https://github.com/Textualize/textual/discussions/196 I believe

**Comment by styk-tv** [comment]
thanks @cvaniak and for the demo and thanks @wasi-master for ping on the solution

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
