### ISSUE TITLE
More `DataTable` supplementary types should be included in the documentation

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3340]
Following on from #3273 -- it looks like there might be some more types need pulling into the docs. Some of the types that have been pulled in with @TomJGooding's PR (#3276) inherit from `StringKey`, which isn't in the docs but which devs may wish to know the details of.

We may want to keep an eye out for anything else like that.

**Comment by TomJGooding** [comment]
I'm happy to help since I might have inadvertently created this new issue, but can I just confirm that  this means `StringKey` should be public (i.e. including in data_table.py?

**Comment by TomJGooding** [comment]
Should `CellType` also be added?

**Comment by willmcgugan** [comment]
@darrenburns could you check this. Feel free to close if its no longer an issue.
