### ISSUE TITLE
Content written to devtools doesn't wrap correctly on first load

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3364]
It appears as though the first batch of things written to the devtools isn't aware of the width of the devtools console.

I suspect this occurs when writing something prior to the devtools communicating the width. As it seems to work once the app is running.

**Comment by rodrigogiraoserrao** [comment]
Any pointers on how to repro this? I started the console in a slim terminal window and attached an app and everything looked properly wrapped.
