### ISSUE TITLE
Broken output on old windows cmd

### ISSUE THREAD

**Issue by Dobatymo** [Textualize/textual#3378]
Windows 7 x64, cmd.exe
Python 3.8.10 x64
textual==0.38.1
rich==13.5.3

Colors are working fine with rich, however textual output is full of ANSI(?) sequences.

![grafik](https://github.com/Textualize/textual/assets/7647594/b4145c5f-8e97-4cd9-a845-2f8dabed9f19)
![grafik](https://github.com/Textualize/textual/assets/7647594/c7a0670a-f54e-40f1-ac48-606c6d6e7bd3)

It is working on a Windows 10 machine with otherwise same environment. I remember in the past it worked on Windows 7 as well (maybe when colorama was still used?)

The issue template mentions a `textual diagnose` command which I cannot find anywhere...
EDIT: maybe you meant `py -m rich.diagnose`?

```
┌───────────────────────── <class 'rich.console.Console'> ─────────────────────────┐
│ A high level console interface.                                                  │
│                                                                                  │
│ ┌──────────────────────────────────────────────────────────────────────────────┐ │
│ │ <console width=159 ColorSystem.WINDOWS>                                      │ │
│ └──────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                  │
│     color_system = 'windows'                                                     │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 41                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = True                                                          │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=159, height=41),             │
│                        legacy_windows=True,                                      │
│                        min_width=1,                                              │
│                        max_width=159,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=41,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=159, height=41)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 159                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
┌─── <class 'rich._windows.WindowsConsoleFeatures'> ────┐
│ Windows features available.                           │
│                                                       │
│ ┌───────────────────────────────────────────────────┐ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ └───────────────────────────────────────────────────┘ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
└───────────────────────────────────────────────────────┘
┌────── Environment Variables ───────┐
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
└────────────────────────────────────┘
platform="Windows"
```

EDIT: after installing `textual-dev`

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.38.1 |
| Rich    | 13.5.3 |

## Python

| Name           | Value                                |
|----------------|--------------------------------------|
| Version        | 3.8.10                               |
| Implementation | CPython                              |
| Compiler       | MSC v.1928 64 bit (AMD64)            |
| Executable     | C:\Program Files\Python38\python.exe |

## Operating System

| Name    | Value    |
|---------|----------|
| System  | Windows  |
| Release | 7        |
| Version | 6.1.7601 |

## Terminal

| Name                 | Value     |
|----------------------|-----------|
| Terminal Application | *Unknown* |
| TERM                 | *Not set* |
| COLORTERM            | *Not set* |
| FORCE_COLOR          | *Not set* |
| NO_COLOR             | *Not set* |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=159, height=41 |
| legacy_windows | True                 |
| min_width      | 1                    |
| max_width      | 159                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 41                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
> The issue template mentions a textual diagnose command which I cannot find anywhere...
> EDIT: maybe you meant py -m rich.diagnose?

The reason for this is you're reporting this issue in the Textual repository; it seems you're looking to post an issue for [Rich](https://github.com/Textualize/rich)?

**Comment by TomJGooding** [comment]
I found lots of references to `legacy_windows` in Rich for its rendering, but searching Textual the only code I could find sets this to false in the App. I might be completely off base as I haven't spent much time yet looking into this, but might this explain the difference?

**Comment by Dobatymo** [comment]
> > The issue template mentions a textual diagnose command which I cannot find anywhere...
> > EDIT: maybe you meant py -m rich.diagnose?
> 
> The reason for this is you're reporting this issue in the Textual repository.

I report it here because rich is working as expected but textual is not even though the rendering should be based on rich.

> [Edit to add] The `textual` command is provided by [`textual-dev`](https://textual.textualize.io/guide/devtools/).

Thanks. I didn't find this before.

**Comment by willmcgugan** [comment]
I'm afraid Textual is unlikely to work in Windows 7. Microsoft introduce better terminal support in Windows 10. Prior to that it was abysmal. 

It would be possible to get it kind of working, but with disturbing visual glitches and it would be too slow to be useable.

One option (other than upgrading) would be to use [textual-web](https://github.com/Textualize/textual-web) which runs a terminal in the browser.

**Comment by Dobatymo** [comment]
> I'm afraid Textual is unlikely to work in Windows 7. Microsoft introduce better terminal support in Windows 10. Prior to that it was abysmal.

@willmcgugan What features did not work in Windows 7? I know that ANSI sequence support was added in Windows 10. But can they do anything which wasn't supported before by the Windows API? I thought that's exactly the thing colorama solved in the past before rich stopped using it. Or maybe I should ask: What terminal support is required for textual to work, but not required for rich? Since rich seems to work perfectly on Windows 7.

**Comment by willmcgugan** [comment]
Sorry for the slow response.

The approach colorama and Rich takes for older Windows versions just wouldn't work for Textual apps. You only get 16 ugly colors and there is no explicit full screen support. You can't turn the cursor off. Even if you can tolerate those issues, the legacy terminal is incredibly slow. Until a few years ago Microsoft didn't consider the terminal to be a priority...
