### ISSUE TITLE
Refreshing a ScrollView scrolls it back to the top

### ISSUE THREAD

**Issue by Flurrywinde** [Textualize/textual#338]
I'm in the process of making an interactive tree object in a ScrollView where the user can use the arrow keys to move the currently highlighted node around the tree. It's working well so far except that if the ScrollView gets `update`ed, it returns to the top.

For example, if you run the following code and scroll to the bottom, then hit 't'. Node 10's label gets reversed like it's supposed to, but I'd like the scroll position to stay the same. Is that possible?

```
from textual.app import App
from textual.widgets import ScrollView
from rich.tree import Tree

class MyApp(App):
	async def on_load(self) -> None:
		await self.bind("t", "test", "Reverse node 10's label")
		await self.bind("q", "quit", "Quit")

	async def action_test(self):
		self.tree10.label = '[r]' + self.tree10.label
		await self.body.update(self.tree)

	async def on_mount(self) -> None:
		self.body = ScrollView(gutter=1)
		await self.view.dock(self.body, edge="top", size=5)
		self.tree = Tree('0')
		tree3 = self.tree.add('1').add('2').add('3')
		tree3.add('4').add('5').add('6').add('7')
		tree3.add('8').add('9')
		self.tree10 = tree3.add('10')
		await self.body.update(self.tree)

MyApp.run(log="textual.log", log_verbosity=2)
```

**Comment by HiPeople21** [comment]
You can pass `home=False` to the update method call to prevent it from going back to the top.

**Comment by Flurrywinde** [comment]
Great! That works. Thanks. Since I posted this, I discovered you're working on a tree in Textual too. When it's ready, I'll switch over.
