### ISSUE TITLE
Pilot.click can't use `Screen` as selector.

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3395]
If you try something like `pilot.click(Screen)`, you get a `NoMatches` exception from the query.

**Comment by willmcgugan** [comment]
Ah, it looks like it is doing `screen.query_one`. It should probably be `app.query_one`.

**Comment by rodrigogiraoserrao** [comment]
> Ah, it looks like it is doing `screen.query_one`. It should probably be `app.query_one`.

Let the records show I had the fix locally before this comment was made! 😆
