### ISSUE TITLE
Swiss keyboard is inconvenient to access the palette command.

### ISSUE THREAD

**Issue by gl-yziquel** [Textualize/textual#3403]
Hi.

I have a french keyboard mapped to a swiss french keyboard. I'll keep it this way, because the swiss keyboard is one of the best in the world: access to all the weird characters for french, italian, and german.

It thus is inconvenient when it comes to accessing the keyboard palette. I need to type AltGr + Shift + Ctrl + [7|è]. Four fingers immobilised accross the whole keyboard. It feels even more inconvienent than hooking a piano pedal into emacs to have extra special keys accessible with one's feet...

I may be old school, but I do find the modal ideology of keybindings to be fairly effective. An Esc + ':' like in vim would do the job. Or even a modal approach à la Spacemacs wouldn't be too dumb: Get into modal mode and Spacebar, though that would likely be overkill.

But, oh, well, do consider the modal approach. It's not that dumb for this use case. Though likely orthogonal to what Textual has in mind.

**Comment by davep** [comment]
Thanks, this is useful to know; we'll think on a better binding, or at least an additional binding that is more portable.

**Comment by RasmusB** [comment]
There is a related but slightly different issue with the Swedish key layout. Using `textual keys`, the combination Ctrl + Backslash is reported as two separate keypresses:

```
Key(key='ctrl+@', character='\x00', name='ctrl_@', is_printable=False)
Key(key='backslash', character='\\', name='backslash', is_printable=True)
```

If I switch to an English (UK) layout, the combination Ctrl-Backslash is registered as a separate keypress and a non-printable character:

```
Key(key='ctrl+@', character='\x00', name='ctrl_@', is_printable=False)
Key(key='ctrl+backslash', character='\x1c', name='ctrl_backslash', is_printable=False)
```

This means that even if you are pressing the right keys on a Swedish keyboard, the palette command is still not working.

**Comment by RasmusB** [comment]
There is a related but slightly different issue with the Swedish key layout. Using `textual keys`, the combination Ctrl + Backslash is reported as two separate keypresses:

```
Key(key='ctrl+@', character='\x00', name='ctrl_@', is_printable=False)
Key(key='backslash', character='\\', name='backslash', is_printable=True)
```

If I switch to an English (UK) layout, the combination Ctrl-Backslash is registered as a separate keypress and a non-printable character:

```
Key(key='ctrl+@', character='\x00', name='ctrl_@', is_printable=False)
Key(key='ctrl+backslash', character='\x1c', name='ctrl_backslash', is_printable=False)
```

This means that even if you are pressing the right keys on a Swedish keyboard, the palette command is still not working.

**Comment by davep** [comment]
@RasmusB Which OS(s)?

**Comment by RasmusB** [comment]
Windows 10

**Comment by RasmusB** [comment]
If you want to recreate it, you can switch to the Swedish keyboard layout. Backslash is entered by holding `AltGr` and pressing the button to the right of `0`:

![The key to press](https://github.com/Textualize/textual/assets/2670254/0d2ff99a-b357-4770-80b6-cd74eb98eff6)

**Comment by gl-yziquel** [comment]
I would honestly suggest a cross platform solution. `Esc` seems to me to be the quintessential key for that kind of situation.

Is there a way to hack a replacement of `Ctrl+\' into `Esc` with the current codebase ?

**Comment by davep** [comment]
@gl-yziquel We'll obviously look for and settle on a choice that works in all places, although <kbd>Esc</kbd> would be a really bad choice, I think -- plenty of applications use it as the "escape out of here" key.

Thanks all for letting us know it's not a great choice and for adding more detail; we'll be sure to find a more portable selection.

**Comment by RasmusB** [comment]
Thanks for looking into it. Maybe this should be escalated to a bug since the current implementation doesn't work with some layouts?

**Comment by davep** [comment]
@gl-yziquel The calling of the command palette [is an action on `App`](https://textual.textualize.io/api/app/#textual.app.App.action_command_palette); so you can add an apporpriate binding to your app that is [bound](https://textual.textualize.io/guide/input/#bindings) to `"command_palette"`.

**Comment by davidfokkema** [comment]
Would it be strange to propose cmd/ctrl-shift-p? The default Atom / Nuclide / VS Code command palette binding? Or PyCharm's cmd/ctrl-shift-a?

**Comment by davep** [comment]
@davidfokkema Have you tried those with `textual keys` in some of the common terminals?

**Comment by davidfokkema** [comment]
Apparently... I had not.🥲

**Comment by TomJGooding** [comment]
The command palette binding was changed to `ctrl+p` in Textual v0.77.0, so I wonder if this issue can be closed?

**Comment by gl-yziquel** [comment]
@TomJGooding I don't react quickly to issues, and I have moved on. I don't have time to test that code, so I leave that to the judgement of the repo owners.
