### ISSUE TITLE
Tree `disabled=True` breaks when setting at initialization

### ISSUE THREAD

**Issue by joshbduncan** [Textualize/textual#3407]
Using the `Tree` example from the docs, if you pass in `disabled=True` during initialization the app break with 2 exceptions.

**Thrown Exceptions:**
1. `AttributeError: 'Tree' object has no attribute '_line_cache'`
2. `ScreenStackError: No screens on stack`

I can see in the source that the call to `super().__init__()` on the base `Widget` object is called before setting the `_line_cache` so I'm not sure if that is the problem or not.

```python
from textual.app import App, ComposeResult
from textual.widgets import Tree


class TreeApp(App):
    def compose(self) -> ComposeResult:
        tree: Tree[dict] = Tree("Dune", disabled=True)
        tree.root.expand()
        characters = tree.root.add("Characters", expand=True)
        characters.add_leaf("Paul")
        characters.add_leaf("Jessica")
        characters.add_leaf("Chani")
        yield tree


if __name__ == "__main__":
    app = TreeApp()
    app.run()
```

Enabling and disabling the Tree after the app is composed works just fine as can be seen using this example (using the 'D' keybinding).

```python
from textual.app import App, ComposeResult
from textual.widgets import Footer, Header, Tree


class TreeApp(App):
    BINDINGS = [
        ("d", "disable_tree", "Toggle Tree Availability"),
    ]

    def compose(self) -> ComposeResult:
        tree: Tree[dict] = Tree("Dune")
        tree.root.expand()
        characters = tree.root.add("Characters", expand=True)
        characters.add_leaf("Paul")
        characters.add_leaf("Jessica")
        characters.add_leaf("Chani")
        yield Header()
        yield Footer()
        yield tree

    def action_disable_tree(self) -> None:
        tree = self.query_one(Tree)
        tree.disabled = not tree.disabled


if __name__ == "__main__":
    app = TreeApp()
    app.run()
```

**Comment by davep** [comment]
Confirmed in `main`. At a quick glance, and with a quick test, it looks like the fix is simply:

```diff
diff --git a/src/textual/widgets/_tree.py b/src/textual/widgets/_tree.py
index b094f756..aa43ade9 100644
--- a/src/textual/widgets/_tree.py
+++ b/src/textual/widgets/_tree.py
@@ -597,7 +597,6 @@ class Tree(Generic[TreeDataType], ScrollView, can_focus=True):
             disabled: Whether the tree is disabled or not.
         """
 
-        super().__init__(name=name, id=id, classes=classes, disabled=disabled)
 
         text_label = self.process_label(label)
 
@@ -610,6 +609,8 @@ class Tree(Generic[TreeDataType], ScrollView, can_focus=True):
         self._tree_lines_cached: list[_TreeLine] | None = None
         self._cursor_node: TreeNode[TreeDataType] | None = None
 
+        super().__init__(name=name, id=id, classes=classes, disabled=disabled)
+
     @property
     def cursor_node(self) -> TreeNode[TreeDataType] | None:
         """The currently selected node, or ``None`` if no selection."""
```

In other words: the call to `super().__init__()` needs to come *after* the setup of the `Tree`, not before (not PRing this just yet as it needs tests adding and the like and also needs to be checked for any knock-on effects and I just saw the apparently obvious cause and wanted to note it down).

**Comment by joshbduncan** [comment]
@davep, yes that was what I did to fix it (hence the hat-tip above) but I was certain it couldn't be that easy, and I didn't have the ability to run the test package at the time. Thanks!

**Comment by joshbduncan** [comment]
@davep, I did the work of moving the single line and writing a few tests...

As you can see, the PR #3409 is failing on Windows. I've reviewed the failing test and can't see where this simple change would cause any issues. Everything passes on Ubuntu and Mac (locally, GitHub Actions stop before getting to Mac). I know I have had issues using `tmp_file` with Pytest on Windows before but I can see where this test passed for the other recent PRs so I'm at a loss and I don't have a good way of testing on a Windows machine.

**Comment by davep** [comment]
Thanks Josh; could just be a flaky run (we get them sometimes). I'm re-running now and if the same issue happens I'll dive in and see if I can see what the issue is.

**Comment by davep** [comment]
Ran fine so that looks to have been a coincidental flaky test run.
