### ISSUE TITLE
Support extended keys

### ISSUE THREAD

**Issue by mistotebe** [Textualize/textual#3411]
Several terminals support the [Extended keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) which emits keys in a way that's much easier to parse. It has to be requested, but would allow textual to receive any key+modifier combination.

xterm also sends a (seemingly compatible) subset, which the specification is based on. In the longer term, this might enable keypress/release monitoring and other features, AFAIK not necessary to handle right now.

See also https://github.com/tmux/tmux/wiki/Modifier-Keys

**Comment by willmcgugan** [comment]
This is definitely worth looking in to. @darrenburns @davep

**Comment by davep** [comment]
Seconded. If it carries on working fine on the least-best-supported emulators but improves things in better-supported ones I really like the idea.

**Comment by darrenburns** [comment]
The protocol has a specific escape sequence for Esc so you don't need craziness to differentiate between presses of the escape key and the start of an escape sequence - wow

**Comment by willmcgugan** [comment]
The Extended key protocol is now supported in Textual.
