### ISSUE TITLE
Assertion Error on Tabs in TabPane

### ISSUE THREAD

**Issue by UihyunKim** [Textualize/textual#3412]
I got an Assertion Error when I place Tabs widget in TabPane.
I would like to know how to Tabs can be implemented in TabPane. 

Thanks !

```python
from textual.app import App, ComposeResult
from textual.widgets import Tabs, TabbedContent, TabPane


class TabsApp(App):
    def compose(self) -> ComposeResult:
        with TabbedContent():
            with TabPane("outer tab"):
                yield Tabs("Bindable tab")


if __name__ == "__main__":
    app = TabsApp()
    app.run()
```

The error message is below;

<img width="1218" alt="image" src="https://github.com/Textualize/textual/assets/3087809/b9393f42-c2b3-4dab-98c9-3543be56fc3e">

**Comment by davep** [comment]
My initial reaction is that this is a leaky `TabActivated` event, and `TabbedContent` might need to be a wee bit more discerning about how it handles events it wasn't personally expected. Marking as a bug.

**Comment by TomJGooding** [comment]
This could just be a guard clause in the `tab_activated` handler rather than an assert, unless I'm missing something?

There's obviously other events such as `tabs_cleared` that might be more difficult to account for.
