### ISSUE TITLE
Should messages only post after user interaction?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3417]
Should messages only post after user interaction? Currently there's some inconsistency between widgets which is causing confusion. See discussion #3400 for context.

> @TomJGooding Based on previous conversations I've been involved in, I think the design choice for Textual is that it's those widgets [posting messages after a programmatic change] that are behaving "incorrectly" (for what it's worth my own personal taste is they're doing it correctly; but I don't get final say on that 😉).
> 
> I think you raise a good point and it's issue-worthy that one approach or another is settled on and applied across all widgets with such behaviour.

Also for what it's worth, I agree with Dave that those widgets are actually behaving correctly. 

If some messages such as `Select.Changed` are different by design to only post after user interaction, I think this deserves a note in the docs at least.

[Edited to add more detail. Sorry, somehow I clearly messed up when originally creating this issue.]

**Comment by davep** [comment]
One caveat I'd make to the above, which I don't think is in opposition to anything above, more adding to it and increasing clarity: it should be 100% fine to prevent certain messages from bubbling up from compound widgets (consider [how `RadioSet` handles changes while stopping the `RadioButton` messages](https://github.com/Textualize/textual/blob/3f33cd1f8671e4610d2a6cebc717f97f36fa19f2/src/textual/widgets/_radio_set.py#L198)).

Some thought about any initial `Changed` event might also need to be taken into account.

**Comment by TomJGooding** [comment]
Sorry to bump this issue, but I think the design choice for Textual messages is important and needs some clarification.

I missed #2500 from back in May when I created this issue, and there's been a number of other issues/discussions since.

@willmcgugan I think your input is needed here!

**Comment by rodrigogiraoserrao** [comment]
I personally feel like this is a wart we should get rid of ASAP.

Regardless of what is decided, we need to go through the widgets and make sure their messages adhere to the “standard” we decide on.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao I'm confused about what your position is. What is the wart that you want to get rid of?

My feeling is that we should always send messages, and use the `prevent` context manager to suppress messages we don't want. Otherwise it is going to be difficult to know if something was initiated by the "user" or the "developer".

**Comment by rodrigogiraoserrao** [comment]
The “wart” was the inconsistency because we weren't doing neither thing consistently (always post or always ignore messages initiated by the developer).

**Comment by rodrigogiraoserrao** [comment]
If it's settled that we want to always post messages and then the developer can `prevent` the ones it doesn't care about, I'll close this issue and open a new one specifically to track the task of going through the widgets and making sure we're doing this consistently.
