### ISSUE TITLE
Inconsistent treatment of overlapping markup and TCSS

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3421]
I created this issue to track the issue found and explained in https://github.com/Textualize/textual/pull/3415#issuecomment-1738895398 in its generality.

As it stands, we treat markup and TCSS in inconsistent ways, as we can see below.
The label widget and the label of the checkbox have the same markup and the same TCSS and yet they look different:

![Screenshot 2023-09-28 at 13 44 27](https://github.com/Textualize/textual/assets/5621605/259c1575-ea3a-4be7-aab2-d2688da0c8ec)

It's also arguable whether any of the two options are the correct one.

<details>
<summary>Code for the app above</summary>

```py
from textual.app import App
from textual.widgets import Checkbox, Label


class CheckboxApp(App):
    CSS = """
    Checkbox > .toggle--label, Label {
        color: white;
        text-opacity: 50%;
    }
    """

    def compose(self):
        yield Checkbox("[red bold]This is just[/] some text.")
        yield Label("[red bold]This is just[/] some text.")


if __name__ == "__main__":
    CheckboxApp().run()
```

</details>

**Comment by willmcgugan** [comment]
The toggle widget gives the tcss priority. Alas when you get to that level, you need to take care to apply styles in the correct order.

Going to attempt a fix for the toggle button, but there may be similar issues in other widgets.
