### ISSUE TITLE
Add ability to remove cell padding

### ISSUE THREAD

**Issue by rmurray2** [Textualize/textual#3435]
I haven't been able to modify the style of a DataTable so that there is zero space between the columns. This in contrast to the rows, which are stacked with zero space between the cells. 

I've tried setting `margin`, `grid-gutter` and `padding` to zero in the TCSS file, with no success: 

```
DataTable {
	grid-gutter: 0;
	padding: 0;
	margin: 0;
} 
```

**Comment by TomJGooding** [comment]
I assume you mean the cell padding that's baked in https://github.com/Textualize/textual/discussions/2503#discussioncomment-5822737

**Comment by willmcgugan** [comment]
@rmurray2 There's no way to remove the cell padding at the moment. Without cell padding the cells would be right next to each other, and it would be difficult to read.

Perhaps you could explain why you want this? We might be able to offer alternative suggestions.

**Comment by rmurray2** [comment]
@willmcgugan thanks for your reply. 

I'd ultimately like to generate a heatmap, like the image below, in which the backgrounds correspond to an intensity value for that row/column combination

![heatmap](https://github.com/Textualize/textual/assets/5521035/0c9a6411-49b0-4b27-bfbb-fa467bc807fd)

**Comment by willmcgugan** [comment]
That's a novel use for the datatable! I doubt it will be difficult for use to add an option to remove cell padding. We will look in to it for the next version.

**Comment by rmurray2** [comment]
Great, thanks, just one suggestion: The column header row will become difficult to read if the padding is removed, so I would suggest, if it's possible, tilting the right side of the labels at about a 45 or more degree angle. Or any arbitrary, user-defined angle. That way they won't run into each other.

**Comment by willmcgugan** [comment]
I may not have followed what you are suggesting there, but its impossible to rotate text in the terminal I'm afraid.
