### ISSUE TITLE
Border demonstration acts improperly under scrolling

### ISSUE THREAD

**Issue by holdenweb** [Textualize/textual#3437]
Recipe to reproduce:

Run `textual borders`. Click on `[Heavy`]. Border will change. Scroll down buttons panel to click on `[Wide]`. At top of screen click topmost visible button (in my case `[Heavy]`, but YMMV). _Ensure that only the bottom two rows of the topmost button is visible._

Expected action: Tool selects appropriate border, and is otherwise unchanged.

Actual result: Buttons panel scrolls up to top and the topmost item (`[ascii]`) and selects that border.

The actual response seems to vary depending on exact elements selected and scrolling position, but this report should be sufficient to at least observe the anomalous behaviour.

`textual diagnose` output:
```
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.38.1 |
| Rich    | 13.5.3 |

## Python

| Name           | Value                                                                                   |
|----------------|-----------------------------------------------------------------------------------------|
| Version        | 3.10.13                                                                                 |
| Implementation | CPython                                                                                 |
| Compiler       | Clang 14.0.3 (clang-1403.0.22.14.1)                                                     |
| Executable     | /Users/sholden/Library/Caches/pypoetry/virtualenvs/textutils-sKIyU2bn-py3.10/bin/python |

## Operating System

| Name    | Value                                                                                                |
|---------|------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                               |
| Release | 22.1.0                                                                                               |
| Version | Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.20) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=80, height=38 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 80                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 38                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |
```
Feel free to add screenshots and / or videos. These can be very helpful!

**Comment by willmcgugan** [comment]
Thanks. I can reproduce this.

I'm guessing it is because the scroll in to view is occurring on mouse down, but the button press is registered on mouse up. Or something of that nature.

**Comment by holdenweb** [comment]
Great, glad the report gave you the information you needed. Not a major problem, just another small positive improvement :)

**Comment by rodrigogiraoserrao** [comment]
I can repro as well.
If I press the mouse button down and hold it down, the scroll into view happens. If I hold for long enough (cf. code below), when I release the mouse button the border preview doesn't change.

https://github.com/Textualize/textual/blob/89991025e9c21fc293ee3233fde5c0b4f679061b/src/textual/driver.py#L103

So, this seems to corroborate Will's suspicion that the scroll/preview change happen on different events.
