### ISSUE TITLE
`OptionList` duplicate ID detection not working as expected

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3455]
Consider the following code:

```python
from textual.app import App, ComposeResult
from textual.widgets import OptionList, Log, Footer
from textual.widgets.option_list import Option

class OptionListAddBug(App[None]):

    BINDINGS = [
        (str(n), f"add({n})", f"Add {n}") for n in range(10)
    ]

    CSS = """
    OptionList, Log {
        height: 1fr;
        border: round cornflowerblue;
    }
    """

    def compose(self) -> ComposeResult:
        yield OptionList()
        yield Log()
        yield Footer()

    def action_add(self, value: int) -> None:
        try:
            self.query_one(OptionList).add_option(
                Option(f"Added {value} just fine", id=f"id-{value}")
            )
        except Exception as error:
            self.query_one(Log).write_line(f"{error!r}")


if __name__ == "__main__":
    OptionListAddBug().run()
```

If you run it and press keys 0-9, you'll find that corresponding options are added to the `OptionList`.

![Screenshot 2023-10-04 at 15 26 43](https://github.com/Textualize/textual/assets/28237/b66c94d8-7706-4d64-a0d9-3d5214a5ec13)

However, if you start the app afresh, then press (for example) <kbd>2</kbd> twice, resulting in a logged `DuplicateID` exception (expected and desired), after than you can't add any more options to the list, and the attempted added option is always reported as having the original duplicate ID:

![Screenshot 2023-10-04 at 15 28 53](https://github.com/Textualize/textual/assets/28237/d670fb29-1a25-47e6-a2ed-198f53ded001)

In the above I pressed <kbd>2</kbd> twice and then a number of other number keys.

It would appear that `OptionList` is getting every confused in its `id` tracking and/or duplicate detection.

**Comment by TomJGooding** [comment]
I found a quick workaround would be:

```python
        except Exception as error:
            self.query_one(Log).write_line(f"{error!r}")

            self.query_one(OptionList)._contents.pop()
```

The exception is raised by `_refresh_content_tracking` which loops through `_contents`.

https://github.com/Textualize/textual/blob/6d79e7782d0d4e50e6e953db7d03da85090831ab/src/textual/widgets/_option_list.py#L543-L546

**Comment by davep** [comment]
Yeah, pretty sure the duplicate check needs to to waaaaaaay before anything gets added.

**Comment by davep** [comment]
Smoking gun.

```diff
diff --git a/tests/option_list/test_option_list_create.py b/tests/option_list/test_option_list_create.py
index 7e0bbc49..98130d75 100644
--- a/tests/option_list/test_option_list_create.py
+++ b/tests/option_list/test_option_list_create.py
@@ -119,5 +119,8 @@ async def test_add_later() -> None:
 async def test_create_with_duplicate_id() -> None:
     """Adding an option with a duplicate ID should be an error."""
     async with OptionListApp().run_test() as pilot:
+        option_list = pilot.app.query_one(OptionList)
+        assert option_list.option_count == 5
         with pytest.raises(DuplicateID):
-            pilot.app.query_one(OptionList).add_option(Option("dupe", id="3"))
+            option_list.add_option(Option("dupe", id="3"))
+        assert option_list.option_count == 5```
```

with that change the tests it fails.
