### ISSUE TITLE
`Hide` event not working as advertised?

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3460]
As I read [the docs for `Hide`](https://textual.textualize.io/events/hide/), it's my understanding that this code should show show and hide notifications as I hit the spacebar:

```python
from textual.app import App, ComposeResult
from textual.widgets import Label

class ShowHideLabel(Label):

    def on_show(self) -> None:
        self.notify("Show!")

    def on_hide(self) -> None:
        self.notify("Hide!")

class ShowHideApp(App[None]):

    BINDINGS = [("space", "toggle")]

    def compose(self) -> ComposeResult:
        yield ShowHideLabel("Here I am")

    def action_toggle(self) -> None:
        self.query_one(ShowHideLabel).visible = not self.query_one(ShowHideLabel).visible

if __name__ == "__main__":
    ShowHideApp().run()
```

but I only ever see show events.

**Comment by TomJGooding** [comment]
I think the root of the problem is here:

https://github.com/Textualize/textual/blob/3aaecd39200c2251cb9af8e450c5291839638b7f/src/textual/_compositor.py#L361-L368

**Comment by willmcgugan** [comment]
I think so, yes. Widgets with `visible = False` are still considered in the layout, but filtered out somewhere else.

**Comment by TomJGooding** [comment]
Well I've confirmed it wasn't that commit as changing back to `visible_only=True` doesn't work either.

I think best left to the experts, but it was interesting digging deeper into Textual!

**Comment by willmcgugan** [comment]
I think what is happening is that the sets for shown / hidden / resized ignore the `visible` property.

It would be nice if setting visible=False did produce a `Hide` in the same way as setting `display=False`. But only if it can be done in a way that doesn't impact performance too much.

Worth investigating.

**Comment by darrenburns** [comment]
We need to discuss what the Hide event should do.

Right now, the docs says a Hide event will fire when a widget moves off-screen, which feels very wrong to me.

I think Hide should only fire when `visibility` or `display` is changed.

**Comment by willmcgugan** [comment]
The `Hide` event is sent when the widget was in the previous layout, but not in the new one. Essentially the logical inverse of the `Show` event.

`visibility` is a bit of a special case. If `visibility` is False it is still considered to be in the layout, but never actually drawn.

The logic is somewhat determined by how the compositor is implemented. It uses set operations to very efficiently figure out what is shown / hidden.

I'd be interested in understanding why you think it should work differently. Let's have a chat about it tomorrow!

**Comment by willmcgugan** [comment]
@darrenburns Does this need any work?

**Comment by willmcgugan** [comment]
Going to park this for now. I think there may be two concepts that are being conflated:  Events when widgets come in to the viewport, and events when something is toggled. Until we have a use case we can consider, it is hard to know what the behaviour shoulld be.
