### ISSUE TITLE
Allow for basic "from CSS" theming of a `TextArea`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3468]
It would be good to have a mode of theming a `TextArea` such that you don't set an actual theme, but instead the `TextArea` sets the text and background colour from CSS; this would be perfect for those times where the `TextArea` is being used for the most basic of plain text editing jobs.

This may also tie in with #3398.

**Comment by TomJGooding** [comment]
There's currently a big difference between `Input` and `TextArea` in Textual. If you only want multi-line input, the TextArea is overkill and awkward to work with.

Obviously this would be a breaking change, but perhaps `TextArea` should just be a simple multi-line input and the code editing functionality is moved to new widget?

**Comment by TomJGooding** [comment]
Can this be closed now that by default `TextArea` is "a standard multi-line input box" where the theme "takes values entirely from CSS"?

**Comment by darrenburns** [comment]
Yup!
