### ISSUE TITLE
[QUESTION] Way to stop or change intervals once set?

### ISSUE THREAD

**Issue by kraanzu** [Textualize/textual#347]
Is there a way to change the Widget's `set_interval` refresh time or maybe stop it, once started?

**Comment by droctothorpe** [comment]
@kraanzu did you ever figure out how to do this?

**Comment by droctothorpe** [comment]
Figured it out how to do this In case anyone else is curious. Might not be a bad idea to include in the docs. Don't mind contributing an example if you think it might be helpful.

```python
     async def refresh_toggler(self) -> None:
        if not self.done:
            self.refresh()
        else:
            await self.timer.stop()
    
     def on_mount(self):
        self.timer = self.set_interval(3, self.refresh_toggler)
  ```

**Comment by kraanzu** [comment]
> Don't mind contributing an example if you think it might be helpful.

Yeah, I should have. Thanks for the contribution :)
