### ISSUE TITLE
DataTable crash

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3470]
"When updating a cell in DataTable with update_width=True, then remove the row, a crash will happen when on_idle run."

From the following PR:

https://github.com/Textualize/textual/pull/3211

**Comment by rodrigogiraoserrao** [comment]
In the linked PR you say we're going with a different approach than the one in the PR. Have you thought of a specific alternative?

**Comment by willmcgugan** [comment]
The approach suggested by Darren in the linked PR.
