### ISSUE TITLE
Allow setting a scrollbar's size to 0

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3482]
Motivated by #3479 it would be handy if a developer could turn off a scrollbar but retain the ability to scroll. Setting a scrollbar's size to 0 seems like a sensible method of approaching this (so keeping the desired `overflow` while "hiding" the scrollbar).

**Comment by darrenburns** [comment]
+1 for this - I've hit the same issue in the past and the first thing I tried was setting the scrollbar-size to 0.

**Comment by superlevure** [comment]
I'm so happy the new release is called `The invisible scrollbar release` 😊 

Thank you very much!
