### ISSUE TITLE
Revisit flaky tests

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3484]
We have some flaky tests. It seems to be a handful that are particularly sensitive to timing. I suspect that the issue lies in the tests themselves, and there is some genuine issue there. Let's look at those tests and see if we can make them stable.

**Comment by rodrigogiraoserrao** [comment]
Tests I often find flaky:
 - a test related to the `textual borders` preview (possibly related to #3437)
 - a test that checks tabs messages

**Comment by darrenburns** [comment]
@rodrigogiraoserrao Thanks for doing this summary - it's really helpful!
