### ISSUE TITLE
Exception handling in async tasks.

### ISSUE THREAD

**Issue by bkayalibayarg** [Textualize/textual#3489]
I am wondering about best practices for handling exceptions in async tasks. Below is a minimal app which counts up to 20 and then raises an exception. I would like the app to crash upon this exception and print the traceback, but I am not sure how to do that with textual. I went over the documentation and guides but couldn't find an answer there.

```python
import asyncio
from textual.app import App
from textual.widgets import Header, Footer, Pretty

async def write(pretty):
    counter = 0
    while True:
        if counter == 20:
            raise Exception("HAHAHA")
        pretty.update(counter)
        counter += 1
        await asyncio.sleep(0.1)

class SomeApp(App):

    def compose(self):
        yield Header()
        yield Pretty(None, id="pretty")
        yield Footer()

    def on_mount(self):
        pretty = self.query_one("#pretty")
        asyncio.create_task(write(pretty))

if __name__ == "__main__":
    app = SomeApp()
    app.run()
```

**Comment by willmcgugan** [comment]
You could print the exception and then call `app.exit`. However, you are probably better off using Textual's [worker API](https://textual.textualize.io/guide/workers/) which has this as the default behaviour.

**Comment by bkayalibayarg** [comment]
Thank you, changing `asyncio.create_task(write(pretty))` to `self.run_worker(write(pretty))` gave me exactly what I wanted!
