### ISSUE TITLE
Auto scroll when cursor moves out of the screen inside the TextArea

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3494]
When typing inside the text area, if you change lines and the new line is not visible, the screen should probably scroll so that the new line becomes visible.

Current behaviour:

https://github.com/Textualize/textual/assets/5621605/ff9eac69-6d9d-410b-b613-7b8313241ca2

**Comment by willmcgugan** [comment]
Is the text area off the bottom of the screen? What happens if you put a border around the text area? Do you see the bottom border?

**Comment by rodrigogiraoserrao** [comment]
The text area is off the bottom of the screen, yes.
The bottom border is not visible, no.


https://github.com/Textualize/textual/assets/5621605/359fffe9-152d-455f-ba2e-b49cfb9fd311

**Comment by davep** [comment]
Isn't this essentially a problem for *all* widgets that implement a cursor of some description? Or moreover, isn't this a styling choice within the app? For example:

```python
from textual.app import App, ComposeResult
from textual.widgets import OptionList

class ScrollApp(App[None]):

    def compose(self) -> ComposeResult:
        yield OptionList(
            *[f"This is option {n}" for n in range(500)]
        )

if __name__ == "__main__":
    ScrollApp().run()
```

You could probably do similar with `DataTable` there too.

**Comment by willmcgugan** [comment]
Then I don't think it should scroll. It's too much to expect a widget to keep its cursor visible within its container.

**Comment by rodrigogiraoserrao** [comment]
It's “too much” in what sense? Isn't this the expected behaviour?

**Comment by willmcgugan** [comment]
Maybe. But it seems a low priority. We can revisit it later.
