### ISSUE TITLE
Excalidraw diagrams don't look good in dark mode on Safari

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3497]
I think this is due to the CSS that modifies the SVGs when in dark mode.

The CSS in question uses css `"filter:"`. I wonder duplicating those rules with `"-webkit-filter"` would fix it.

**Comment by rodrigogiraoserrao** [comment]
Do you mean specifically in mobile?

**Comment by willmcgugan** [comment]
No, Safari on macBook.

**Comment by rodrigogiraoserrao** [comment]
Safari + macbook the filter is being applied properly (not on mobile, though).
For example, this (v) is the diagram I get for [pushing screens](https://textual.textualize.io/guide/screens/#push-screen):

![Screenshot 2023-10-10 at 15 11 52](https://github.com/Textualize/textual/assets/5621605/5677c6e5-a858-428d-bae4-46563ae7cfb1)

Renaming `filter` to `-webkit-filter` or duplicating it and making a `-webkit-filter` rule don't make a different on safari + macbook.

So, do you see something different, or do you mean to say you don't like these colours?

**Comment by willmcgugan** [comment]
What version of Safari do you have? This is what I see.

<img width="1021" alt="Screenshot 2023-10-10 at 15 15 51" src="https://github.com/Textualize/textual/assets/554369/c48d4e2a-a017-430a-88b6-8d0c5eae7e0d">

I have 17.0 (19616.1.27.211.1)
