### ISSUE TITLE
Add the ability of changing class attributes at the moment of widget Instanciation.

### ISSUE THREAD

**Issue by wiseaidev** [Textualize/textual#350]
edit: I wasn't aware of how that `Reactive` descriptor works. Now, I am familiar with how it works.

I think it is worth allowing programmers to have control over the value of class attributes at the moment of widget Instanciation. Take the following as an example:

```python
class AwesomeWidget(Widget):

    content: Reactive[str] = Reactive(default="")
    name: Reactive[str] = Reactive(default="")
```

I need to have the ability to provide values at the Instanciation phase:

```python
awesome_widget = AwesomeWidget(name='awesome widget', content='awesone content')
```

Probably it can be accomplished by doing something similar to [`attrs`](https://www.attrs.org/en/stable/init.html):

```python
class AwesomeWidget(Widget):

    content: Reactive[str] = Reactive(default="", init=True)
    name: Reactive[str] = Reactive(default="", init=True)
```

edit: i knew that it can be done with `__init__`, but i don't want to add boilerplate to the code base:

```python
class AwesomeWidget(Widget):

    content: Reactive[str] = Reactive(default="", init=True)
    name: Reactive[str] = Reactive(default="", init=True)

    def __init__(self, name: str, content: str):
        super().__init__(name)
        self.content = content
        self.name = name
```

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
