### ISSUE TITLE
Consider a `:loading` pseudo class

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3517]
It's not uncommon to have an array of widgets where, say, the border is used to help emphasise where focus is, for example:

```python
from textual.app import App, ComposeResult
from textual.containers import Grid, Container

class BusyBox(Container, can_focus=True):

    DEFAULT_CSS = """
    BusyBox {
        border: panel red;
    }
    BusyBox:focus {
        border: panel green;
    }
    """

    def __init__(self, number: int) -> None:
        super().__init__()
        self.border_title = f"Busy box {number}"
        self.loading = bool(number % 3)

class LoadingApp(App[None]):

    CSS = """
    Grid {
        grid-size: 4;
    }
    """

    def compose(self) -> ComposeResult:
        with Grid():
            for n in range(16):
                yield BusyBox(n)

if __name__ == "__main__":
    LoadingApp().run()
```

I feel it would be *very* useful if it were possible to also style a widget that is in the loading state. While it's true that a class could be applied when the `loading` value is set to `True`, and removed when set to `False`, allowing it to be done fully in CSS would mean there's no need to manage multiple locations where such changes could be made on a widget. Likewise, while this could be managed by the developer with a watch on `loading`, that then would generally require subclassing of all widgets that need this functionality; a pure-CSS solution would mean that a couple of rules could handle all sorts of widgets.

**Comment by willmcgugan** [comment]
I'm going to say no for now. Just because I don't want to keep adding to the very growing list of pseudo classes.

Happy to reconsider if we are asked for it.
