### ISSUE TITLE
textual-plotext should use Textual color system

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3532]
Textual-plotext appears to use ANSI colors, which means that plots are going to look quite different across terminals.

We should use the Textual theme colors by default so plots have a consistent look across terminals. It does look like plotext can use RGB colors.

**Comment by davep** [comment]
Currently we're just wrapping Plotext, and so using its themes. Presumably we should create a whole nee set of compatible themes.

**Comment by davep** [comment]
Looking into this via https://github.com/Textualize/textual-plotext/issues/3
