### ISSUE TITLE
How to completely disable rich tracebacks

### ISSUE THREAD

**Issue by sam-kleiner** [Textualize/textual#354]
To be added by @willmcgugan

I was wondering if there is a way to completely disable rich tracebacks?

What I have tried in my main.py 
Here I am purposely raising an error in the \_\_rich_console\_\_ method that ends up being rendered

```python
import rich
import textual
from rich.traceback import install

import myapp

install(suppress=[myapp, rich, textual])

myapp.MyApp.run(log="textual.log")
```

Rich itself does not show the pretty tracebacks if I print the panel directly instead of from the widget

```python
from rich import print
from rich.panel import Panel

import myapp

panel = Panel(myapp.MyClass())
print(panel)
```

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
