### ISSUE TITLE
Off-by-one error in data table height when a horizontal scrollbar is needed

### ISSUE THREAD

**Issue by godlygeek** [Textualize/textual#3556]
When the terminal is tall enough to display all rows of a DataTable, but not wide enough to display all columns, the table chooses a height for itself that's one row too short.

For example, try resizing your terminal to 45 columns by 24 rows, and then run `python docs/examples/widgets/data_table.py`, and you'll see something like:

![image](https://github.com/Textualize/textual/assets/29423/81b8d09a-8c0e-4596-b526-f35d75067aa6)

If you hit PageDn to scroll that, you'll see just one more line:

![image](https://github.com/Textualize/textual/assets/29423/442b5f4d-734c-4eca-be0e-6729b867b369)

It seems like the data table is choosing to only use 10 lines out of the available 24 because it only has 10 rows worth of data to display, _then_ it decides it needs a horizontal scrollbar, and suddenly it's got 10 rows of data and only 9 remaining rows to display them in, so it winds up adding a vertical scrollbar as well.

This seems unexpected to me. I don't think there should be a vertical scrollbar when the widget has plenty of room to grow vertically.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.40.0 |
| Rich    | 13.6.0 |

## Python

| Name           | Value                                                        |
|----------------|--------------------------------------------------------------|
| Version        | 3.11.5                                                       |
| Implementation | CPython                                                      |
| Compiler       | GCC 10.2.1 20210130 (Red Hat 10.2.1-11)                      |
| Executable     | /home/mwoznisk/.pyenv/versions/3.11/envs/textual/bin/python3 |

## Operating System

| Name    | Value                               |
|---------|-------------------------------------|
| System  | Linux                               |
| Release | 5.15.90.1-microsoft-standard-WSL2   |
| Version | #1 SMP Fri Jan 27 02:56:13 UTC 2023 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | putty-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=239, height=64 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 239                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 64                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by godlygeek** [comment]
Alright, I guess this is wontfix.

**Comment by godlygeek** [comment]
Actually - reopening this. https://github.com/Textualize/textual/issues/1289#issuecomment-1370969052 suggests a workaround - setting the scrollbar to always visible. But, as far as I can tell, that doesn't actually work around the issue. I see the same problem even if I add:
```py
table.styles.overflow_x = "scroll"
```
to the `on_mount` of `docs/examples/widgets/data_table.py`.

Am I doing something wrong?

**Comment by willmcgugan** [comment]
When the scrollbars appear they don't adjust the height of the widget. So when you get a horizontal bar it takes up one line of the widget, and forces a vertical scrollbar.

The solution is `scrollbar-gutter: stable`, which reserves space for scrollbars regardless if they are visible:

In CSS:

```css
    DataTable {
        scrollbar-gutter: stable;        
    }
```

You may be thinking why not adjust the auto height when a scrollbar is visible. And I did to, but that makes it impossible to create consistent layouts. And you can get in to a situation where a scrollbar pops in, forces a layout, which makes another scrollbar disappear, and forces another layout. And the whole UI flickers as a result.

**Comment by willmcgugan** [comment]
Works for me. Can you share your code?

**Comment by willmcgugan** [comment]
A doc PR would be very welcome!
