### ISSUE TITLE
Tree.clear doesn't respect root expanded state

### ISSUE THREAD

**Issue by davetapley** [Textualize/textual#3557]
This is quite pedantic, but caused me trouble which will make more sense in the context of an upcoming discussion r.e. 'refreshing' a Tree widget and preserving which nodes are expanded vs collapsed.

---

TLDR:

When you create a `Tree` it creates a root node with:
https://github.com/Textualize/textual/blob/3b170b074802fab825a698ca66be2196871700cf/src/textual/widgets/_tree.py#L605

which has `expand` as `False` by default:
https://github.com/Textualize/textual/blob/3b170b074802fab825a698ca66be2196871700cf/src/textual/widgets/_tree.py#L641-L646

But when you `Tree.clear` it sets `expand` to `True`:

https://github.com/Textualize/textual/blob/3b170b074802fab825a698ca66be2196871700cf/src/textual/widgets/_tree.py#L710-L716

---

This is a problem for me because I'd _theorized_ that I could capture the `is_expanded` state of all nodes, then `clear()` and recreate it, then `expand()` the relevant nodes back to restore the previous 'expansion' state...

... but this doesn't _quite_ work because the `clear()` will `expand()` the root node regardless of whether it was expanded before.

Edge case, but I _presume_ was accidental?

**Comment by willmcgugan** [comment]
I don't think it was intentional. The root should probably maintain its expanded state.
