### ISSUE TITLE
Bug with `validate_highlighted` after empty OptionList?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3560]
This follows on from discussion #3559 about confusing errors when trying to remove options from a `SelectionList`.

It looks like parent `OptionList` widget was designed to always have a highlighted option based on the validation?

https://github.com/Textualize/textual/blob/e68e6e37b546c8c7d760bc2ffd7fa8cfa3064907/src/textual/widgets/_option_list.py#L987-L992

But if you start with an empty `OptionList` and then add options later, the `highlighted` reactive is still None which suggests this validation must not be called.

**Comment by TomJGooding** [comment]
This might cause issues with the `Command Palett` if I'm right that `OptionList` is expected to have a highlighted option.

**Comment by davep** [comment]
My recollection is that the intended design is that it retains a highlight once there is a highlight

**Comment by TomJGooding** [comment]
My memory is a little hazy on this issue but I _think_ this is now fixed, likely as part of #3912. Closing.
