### ISSUE TITLE
A default template for a control panel ala Gooey

### ISSUE THREAD

**Issue by thisismygitrepo** [Textualize/textual#3564]
More often than not, we have cases where a commandline utility has too many options to be conveniently written as a command.
A brilliant solution is Gooey that simply takes in the possible options and make a gui out of it https://github.com/chriskiehl/Gooey

I don't like it because its not terminal-based so it fails me when I work with headless machines. 
Can we please have this features in Textual?

Concretely, this will be for someone who doesn't want to spend time designing buttons and dropdown menus and is happy with whatever is the default. All that the user need to pass are keys and possible values for each key and boom, you have  a gui control panel that runs and returns a dictionary with the choices made.

Thank you for making this amazing framework.

**Comment by KevinRodriguez777** [comment]
what you want is https://github.com/Textualize/trogon :)

**Comment by thisismygitrepo** [comment]
Oh that was quick! It's almost exactly what I wanted except that it is more of an ad-on to `click` library, as opposed to being standalone tool.

I think I will just raise a request for there minimal interface with its api in isolation of `click`.
