### ISSUE TITLE
Refreshing the DirectoryTree without resetting the selected node.

### ISSUE THREAD

**Issue by JoeZiminski** [Textualize/textual#3574]
We are really enjoying using the textual for our project and are impressed with its ease of use and powerful features.

Currently we have a DirectoryTree widget that is integral to the project. If a file or folder is deleted through the filesystem (i.e. not through our application), we would like to ensure the DirectoryTree in the app is refreshed to reflect this.

Currently the `reload` function serves this purpose, and it is sufficient for us to call every now and then (e.g. when a file or folder is clicked on the DirectoryTree). However, the only problem is that the `reload` function moves the currently selected folder back to the root folder. Is there a way to call `reload()` without changing the currently selected folder, and avoid having the dropdown structure of entire tree reset?

**Comment by willmcgugan** [comment]
Polling the filesystem can be quite inefficient. A better approach might be to use [watchdog[(https://pythonhosted.org/watchdog/) which uses an OS level API to get notifications when the filesystem changed.

Either way though, I think an incremental `reload` is a good idea.

**Comment by davep** [comment]
Wouldn't https://textual.textualize.io/widgets/directory_tree/#textual.widgets._directory_tree.DirectoryTree.reload_node be most of an incremental reload?

**Comment by darrenburns** [comment]
How do you actually use `reload_node` though if you want to reload a node other than the one under the cursor?

Do we need a mechanism for "given a path contained within the tree, return the corresponding TreeNode"?

I can see that on `Tree` we have a `get_node_by_id`, but the IDs of the nodes in `DirectoryTree` seem to be integers. Perhaps the node IDs should the paths?

**Comment by JoeZiminski** [comment]
Thanks a lot, I did not know about watchdog that is very useful.

For our case, partial refreshing of the DirectoryTree is nice. However the primary change that would be useful for us is to maintain the currently selected node after refreshing the entire directory tree. At present, if I understand correctly on a reload the gui is set back to the root node being selected - so the user must manually click to return to the node they had selected. 

If it is possible, it would be nice to add an option such that the DirectoryTree is reloaded such that the currently selected node is not set back to root.

**Comment by willmcgugan** [comment]
Replaced with https://github.com/Textualize/textual/issues/4056
