### ISSUE TITLE
`renderables/background.py` calls missing method

### ISSUE THREAD

**Issue by patha454** [Textualize/textual#3585]
Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. 

A code branch in `renderables/background.py` calls a Rich Style method `clear_meta_and_links()`. The method does not appear the exist in the pinned Rich version, nor the latest Rich version.

I noticed this bug with Textual/Trogon, where the default implementations of the `(F1) About` and `(CTRL-O) Command Info` bindings trigger this bug, causing a crash.

Feel free to add screenshots and / or videos. These can be very helpful!

![textual-clear-meta-links](https://github.com/Textualize/textual/assets/26947190/d95a047f-152c-488c-80ae-3ab215291b2a)

**Comment by darrenburns** [comment]
This method was added to Rich in 13.3.3.

Textual depends on `rich >= 13.3.3`.

https://github.com/Textualize/rich/blob/e9f75c9912ed25b9777bc0257853370951220b17/rich/style.py#L649

It looks like it might be an issue with your environment - are you using a virtualenv?

**Comment by patha454** [comment]
I'm on Rich 13.3.1. That explains a lot. Seems it's just internal package management weirdness. Thanks!

**Comment by patha454** [comment]
Looks like the Poetry lockfile accepts Rich >= 12.0.0 

https://github.com/Textualize/textual/blob/main/poetry.lock#L856

Could it be updated? I'm not familiar with Poetry as a package manager.

**Comment by darrenburns** [comment]
That line is specifying the required version of Rich for one of the dependencies, `pytest-textual-snapshot`. It's not the version of Rich required by Textual itself.
