### ISSUE TITLE
`Button.update` method?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3603]
I'm often caught out by `Button.update` not updating the label (or doing anything!)

I thought about overriding the method to simply assign `Button.label`, but the argument type for the `Static` base class is `RenderableType` whereas the button label is `TextType` (I'm afraid I don't fully understand the difference!)

Am I the only one who gets caught out by this?

**Comment by rodrigogiraoserrao** [comment]
At the present time, it's nonsensical for `Button` to inherit from `Static`, so I'm guessing this inheritance is remnant of a previous `Button` implementation.

The point of `Static` is to cache the rendering and use the cache in its method `render`.
The implementation of `Button` overrides `Static.render`, so we're not making use of what the only thing we get by inheriting from `Static`...

So, we'll drop inheritance of `Static` and instead you can make use of the reactive attribute `label`.

**Comment by TomJGooding** [comment]
Thanks @rodrigogiraoserrao - I didn't think to check whether `Button` actually needed to inherit from `Static`!

**Comment by rodrigogiraoserrao** [comment]
I get it, @TomJGooding. I checked. I replaced `Static` for `Widget`. I ran the tests. They passed. And I was so suspicious of having broken something without realising it... I spent a lot of time going over that tiny change to make sure I wasn't missing anything 😆
