### ISSUE TITLE
Assigning to the reactive Select.value doesn't post a Changed message

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3611]
The reactive `Select.value` can be assigned to and it will change the selection of the widget but it won't post a message `Select.Changed`.

**Comment by davep** [comment]
Isn't this in keeping with a few other widgets within Textual, where setting its corresponding "value" won't result in a message, when user interaction would[^1]?

[^1]: I tend to think any change should result in a message, but I'm just mentioning this as it feels like it's something that should be idiomatic to *all* widgets, one way or another.

**Comment by rodrigogiraoserrao** [comment]
Maybe. I was looking at `Input` where assigning to its `value` _will_ result in a message.

I have a very strong opinion in favour of _all changes_ posting the relevant messages.

**Comment by TomJGooding** [comment]
See also issue #3417 where this has come up before.

**Comment by rodrigogiraoserrao** [comment]
Closed in favour of the issue linked above.
