### ISSUE TITLE
Use of command palette cancels previously-running non-thread workers

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3615]
### Discussed in https://github.com/Textualize/textual/discussions/3613

<div type='discussions-op-text'>

<sup>Originally posted by **otherjason** October 30, 2023</sup>
I have an app that uses several long-lived workers to asynchronously poll external services for data and update the UI. I found that closing the command palette, either via `ESC` or by selecting a command, seems to cancel any pending workers. Here's a small example:

```python
import asyncio
from textual import work
from textual.app import App, ComposeResult
from textual.widgets import RichLog

class Test(App):
    CSS = '''
    RichLog {
        height: 100%;
    }
    '''
    def compose(self) -> ComposeResult:
        yield RichLog(id = 'log')

        self.my_worker()

    @work(exclusive = False)
    async def my_worker(self):
        counter = 1

        log = self.query_one('#log')
        while True:
            log.write(f'test {counter}')
            counter += 1
            await asyncio.sleep(1)

if __name__ == "__main__":
    Test().run()
```

When running the above, it will print a new line to the `RichLog` every second. If you open the command palette, then the worker stays running. But it seems that after the palette comes up, as soon as I press a key, the worker stops running.

Is this behavior intended, or is this a bug?</div>

**Comment by davep** [comment]
Hat tip to @otherjason for reporting this.

Bumping straight to the todo list as it's a bit of a show-stopper.

**Comment by davep** [comment]
As mentioned in the discussion, I would suspect that:

```python
self.workers.cancel_all()
```

is doing more than I expected it to (I expected `self.workers` to be all the workers running against the current screen/widget). Don't know for sure, but that's the first thing I'd double-check.

Also, in retrospect, it might make sense to ensure that any worker in the command palette is in an "internal" group of some sort?

**Comment by rodrigogiraoserrao** [comment]
`self.workers` is a property that points to `self.app.workers`, so the fact that `self.workers.cancel_all()` is stopping _all_ workers is definitely intended behaviour.

Having `self.workers` be an alias to `self.app.workers` looks like a terrible idea to me...

And I guess you're right in that it makes sense to have the command palette workers have an internal group of some sort.

**Comment by rodrigogiraoserrao** [comment]
You'd probably want to use either `self.workers.cancel_node(self)`, or the aforementioned worker group that needs to be created.

**Comment by davep** [comment]
> Having self.workers be an alias to self.app.workers looks like a terrible idea to me...

Yeah, that's a *very* curious choice. I wonder if we should review that?
