### ISSUE TITLE
`outline` causes layout issues for `Button`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3628]
It might be that this is an issue elsewhere too, but it was first noticed with `Button` (#3570). Given this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Button

class ButtonIssue(App[None]):

    CSS = """
    Button {
        outline: white;
    }
    """

    def compose(self) -> ComposeResult:
        yield Button("Test")

if __name__ == "__main__":
    ButtonIssue().run()
```

the resulting display looks like this:

![Screenshot 2023-11-02 at 11 00 12](https://github.com/Textualize/textual/assets/28237/57b58fe5-8fc5-4c15-84ad-69b35bf956d4)

**Comment by willmcgugan** [comment]
Possibly a glitch with `outline`

**Comment by holdenweb** [comment]
Love the careful engineering that went into this apparently tiny change.
