### ISSUE TITLE
Tree.refresh_line can fail to re-render.

### ISSUE THREAD

**Issue by paul-ollis** [Textualize/textual#3637]
This can be demonstrated using this program.

```python
from rich.style import Style
from rich.text import Text
from textual.app import App, ComposeResult
from textual.widgets import Button, Tree
from textual.widgets.tree import TreeNode


class MyTree(Tree):
    """Subclass of Tree."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.test_counter = 0
        self.render_history: set[str] = set()

    def render_label(
            self, node: TreeNode, base_style: Style, style: Style
        ) -> Text:
        """Render nodes to include the test_counter."""
        node_label = node._label.copy()
        node_label.stylize(style)
        prefix = (f'{self.test_counter} ', base_style)
        text = Text.assemble(prefix, node_label)
        self.render_history.add(text.plain)
        return text


class TreeApp(App[None]):
    """Test tree app."""

    def compose(self) -> ComposeResult:
        yield MyTree("Test")
        yield Button('Click me')

    def on_mount(self) -> None:
        tree = self.query_one(Tree)
        tree.root.expand()
        node = tree.root.add_leaf('Leaf')

    def on_button_pressed(self, event: Button.Pressed) -> None:
        tree = self.query_one(Tree)
        tree.test_counter += 1
        tree.refresh_line(tree.root.children[0].line)


if __name__ == '__main__':
    app = TreeApp()
    app.run()
```

Pressing the button has no effect on the Leaf node. It stays showing as '0
Leaf'.  A fix for this is to change refresh_line to increment he node's
`_updates` attribute.

```python
    def refresh_line(self, line: int) -> None:
        """Refresh (repaint) a given line in the tree.

        Args:
            line: Line number.
        """
        node = self.get_node_at_line(line)
        if node:
            node._updates += 1
        region = Region(0, line - self.scroll_offset.y, self.size.width, 1)
        self.refresh(region)
```

Then the tree node's representation updates when the button is clicked.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.41.0 |
| Rich    | 13.6.0 |

## Python

| Name           | Value                                                                        |
|----------------|------------------------------------------------------------------------------|
| Version        | 3.11.3                                                                       |
| Implementation | CPython                                                                      |
| Compiler       | GCC 11.3.0                                                                   |
| Executable     | /home/paul/.virtualenvs/np/os/python/textual/textual/fork/textual/bin/python |

## Operating System

| Name    | Value                                       |
|---------|---------------------------------------------|
| System  | Linux                                       |
| Release | 5.15.0-71-generic                           |
| Version | #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 |

## Terminal

| Name                 | Value         |
|----------------------|---------------|
| Terminal Application | tmux (3.2a)   |
| TERM                 | tmux-256color |
| COLORTERM            | truecolor     |
| FORCE_COLOR          | *Not set*     |
| NO_COLOR             | *Not set*     |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=164, height=88 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 164                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 88                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by paul-ollis** [comment]
Pull request #3639 created for this issue.

**Comment by rodrigogiraoserrao** [comment]
Hey Paul, thanks for the report and for the fix. It seems like you diagnosed the problem correctly. I'll just have a look at related things to see if there are any other issues that we're overlooking.
I'll leave feedback in your PR.
