### ISSUE TITLE
Mouse movements example does not work

### ISSUE THREAD

**Issue by porridge** [Textualize/textual#3652]
When I run the example at https://textual.textualize.io/guide/input/#mouse-movements in gnome-terminal all I can see is black screen, and nothing I do (apart from CTRL+C) seems to have any effect.

```
textual diagnose
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.41.0 |
| Rich    | 13.6.0 |

## Python

| Name           | Value                                                                     |
|----------------|---------------------------------------------------------------------------|
| Version        | 3.11.2                                                                    |
| Implementation | CPython                                                                   |
| Compiler       | GCC 12.2.0                                                                |
| Executable     | /srv/home/porridge/.local/share/virtualenvs/reconcile-Vnvz65ja/bin/python |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.1.0-13-amd64                                      |
| Version | #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=87, height=27 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 87                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 27                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by TomJGooding** [comment]
It looks like the CSS for this example hasn't kept up with Textual updates. For example, TextLog should be RichLog, but also opacity no longer seems to work with layers - is this a bug?

```python
from textual.app import App, ComposeResult
from textual.containers import Container
from textual.widgets import Footer, Static


class LayersWithOpacityApp(App):
    BINDINGS = [("space", "add_transparent_layer", "Add transparent layer")]
    CSS = """
    Screen {
        layers: below above;
    }

    #below {
        layer: below;
    }

    #above {
        layer: above;
        opacity: 0%;
        background: red;
    }
    """

    triggered = False

    def compose(self) -> ComposeResult:
        yield Static("BELOW " * 1250, id="below")
        yield Footer()

    def action_add_transparent_layer(self) -> None:
        if not self.triggered:
            transparent_layer = Container(id="above")
            self.mount(transparent_layer)
            self.triggered = True
        else:
            self.bell()


if __name__ == "__main__":
    app = LayersWithOpacityApp()
    app.run()
```

**Comment by TomJGooding** [comment]
For what it's worth, I don't think it really sense that the `Ball` widget was still visible when its container had an opacity of 0%.

But this change might have introduced a bug for layers with opacity. Here's a simple example adapted from [the docs for Layers](https://textual.textualize.io/guide/layout/#layers), with a binding that changes the opacity of `#box1`:

### Before v0.29.0

![before-screenshot](https://github.com/Textualize/textual/assets/101601846/d5cf4a50-9f4e-4b32-93fa-2c01d6f442cf)

### After v0.29.0

![after-screenshot](https://github.com/Textualize/textual/assets/101601846/56cda5e1-6c77-4336-a668-5adec361e338)
