### ISSUE TITLE
The new `Input` `type` `number` restriction shouldn't hard-code the decimal point

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3662]
Currently if `type="number"` on an `Input` it will insist on the decimal point being a `.`. It should probably use `locale.localeconv()["decimal_point"]`, or at least should allow the developer to say if it should be locale-sensitive or not.

**Comment by butteredwaffles** [comment]
Hi! I tried my hand at fixing this one. https://github.com/Textualize/textual/pull/3719

**Comment by willmcgugan** [comment]
After consideration, browsers restrict the input to the decimal point, and disallow commas. I think we should stick to this behaviour, but happy to reconsider at a future date.
