### ISSUE TITLE
Word wrapping TextArea

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3672]
Implement a multi-line input, that word wraps.

I think we should call this `TextArea`, and rename the current `TextArea` to `TextEditor`.

The new `TextArea` should be broadly similar to a browser's text area, with basic editing.

**Comment by TomJGooding** [comment]
I wonder if the current `TextArea` should instead be a `CodeEditor`? See discussions in #3468.

**Comment by darrenburns** [comment]
This is now in main - should be in the next release, which will likely be this week.

@TomJGooding there ends up being a kind of weird overlap between functionality in some cases, e.g. Markdown is technically code in that it has a syntactic structure, but the editing behaviour is akin to plain-text. In the end we ended up offering an alternative constructor. `TextArea` is a basic, plain text box with wrapping enabled (similar to an HTML text area). `TextArea.code_editor()` instantiates a `TextArea` with defaults equivalent to the current "code editor" version.
