### ISSUE TITLE
Setting `loading` to `True` causes widgets to overwrite notifications

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3677]
Given this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Label

class LoadingOverlayApp(App[None]):

    CSS = """
    Label {
        width: 90%;
        height: 1fr;
        text-align: center;
        border: solid red;
    }
    """

    def compose(self) -> ComposeResult:
        yield Label("This is a really big label")

    def on_mount(self) -> None:
        self.notify(
            "This is a really big notification. Loading should not overwrite it.",
            timeout=9_999_999
        )
        self.query_one(Label).loading = True

if __name__ == "__main__":
    LoadingOverlayApp().run()
```

you get this result:

![Screenshot 2023-11-14 at 15 32 15](https://github.com/Textualize/textual/assets/28237/9dedad31-c5f6-412f-a61f-864af1ee9876)

a widget in `loading=True` state shouldn't appear to overwrite notifications.

**Comment by davep** [comment]
As previously requested, tagging @willmcgugan on something that should probably TODO sooner rather than later.

**Comment by rodrigogiraoserrao** [comment]
Here's another interesting one:
if you set a scrollable container to load, you can still scroll, it'll show content that was past the current scrolling position, and the loading indicator overlay will move around as well:

https://github.com/Textualize/textual/assets/5621605/503094d6-1049-44ee-8d10-7f41f8ded433
