### ISSUE TITLE
Better documentation of hyperlinks.

### ISSUE THREAD

**Issue by JoeZiminski** [Textualize/textual#3685]
I see that hyperlinks are [supported in rich](https://www.willmcgugan.com/blog/tech/post/real-working-hyperlinks-in-the-terminal-with-rich/) and work in textual simply by pasting in the formatted link into a `Label` e.g. `[link=https://www.willmcgugan.com]blog[/link]`.

Looking at the [links](https://textual.textualize.io/styles/links/) documentation it was not immediately obvious that this was possible, and had to do some digging into Rich history to figure it out. It's such an awesome feature, I'd suggest documenting here.

In general Textual has some of the best docs I've ever read, I've found picking up the package extremely easy - as such I will raise an issue if I have trouble finding something. However if this is not helpful or an Issue is not the place for it please let me know. Cheers!

**Comment by TomJGooding** [comment]
Interesting, I remember looking at this fairly recently and the Rich link markup didn't seem to work in Textual. What's your terminal emulator?

**Comment by JoeZiminski** [comment]
Ah, this would explain the docs if it is not robust cross platform!

I'm running in Windows (10) 'Terminal' app version 1.18.2822.0, powershell. 

It renders like:

![image](https://github.com/Textualize/textual/assets/55797454/dfc04e3c-345d-4aaf-aa04-dac8e91f0fb8)

with a little popup (ignoring other background widgets)

![image](https://github.com/Textualize/textual/assets/55797454/029f9e6a-fa41-4898-9c99-4567540e1d9a)

and clicking (+ CTRL) opens in my default browser.

**Comment by JoeZiminski** [comment]
Okay that makes sense, so in this case it is advisable to use a Textual link, triggering an [action](https://textual.textualize.io/guide/actions/#__tabbed_1_1) to a custom function that handles opening the link?

**Comment by JoeZiminski** [comment]
Thanks!

**Comment by Jerakin** [comment]
How do I write a "terminal link" as a "textual link"?
I found this https://textual.textualize.io/guide/actions/#links but it doesn't mention anything about http(s) links.

**Comment by JoeZiminski** [comment]
Hi @Jerakin, you can find an example [here](https://github.com/neuroinformatics-unit/datashuttle/blob/apply_meeting_feedback/datashuttle/tui/screens/get_help.py).  A textual link in a label e.g. `[@click=screen.link_github()]GitHub page[/]` links to an action function that opens the browser:

```
  def action_link_github(self) -> None:
      webbrowser.open(links.get_github_link())
```

**Comment by Jerakin** [comment]
Oh I see. Just wrap it. I thought there was a special @click for html links or something (like @html) :)
