### ISSUE TITLE
CommandList flaky test

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3700]
https://github.com/Textualize/textual/actions/runs/6905798401/job/18789367935?pr=3699
https://github.com/Textualize/textual/actions/runs/6927692008/job/18842335114?pr=3706

**Comment by willmcgugan** [comment]
We've discovered that these are often genuine bugs, so let's see if we can remove the flakiness.

**Comment by davep** [comment]
To save having to dive into the links...

![Screenshot 2023-11-20 at 12 07 38](https://github.com/Textualize/textual/assets/28237/05c1fadc-e838-4ab5-878e-e3912b36642e)

![Screenshot 2023-11-20 at 12 07 56](https://github.com/Textualize/textual/assets/28237/0528cb42-0c4a-4795-9d75-f60939b711af)

**Comment by davep** [comment]
Core failing test code:

![Screenshot 2023-11-20 at 12 12 06](https://github.com/Textualize/textual/assets/28237/aa3f0b29-f5e8-46af-b9b9-75f45c6dd5ab)

**Comment by davep** [comment]
This looks to have been introduced in #3399 and, I think, this is a genuine example of a flaky test, in that the pause is for *exactly* the countdown time for no-matches display; given we know that the resolution of times on Windows can be a little off, I think this will be a case of "pause the countdown and then a bit of wiggle room".
