### ISSUE TITLE
Save screenshot on App.run_test failure

### ISSUE THREAD

**Issue by ab-10** [Textualize/textual#3702]
Suggestion to add an option `screenshot_on_fail: Optional[Path|str] = None` in `App.run_test` to save a screenshot of the app upon a test failure and error.
Happy to implement the feature myself, if it aligns with the project's goals.

## Example functionality

```python
async with app.run_test(screenshot_on_fail="logs/") as pilot:  
    # Test pressing the R key
    await pilot.press("r")  

    assert app.screen.styles.background == Color.parse("red")
```

If the assertion would fail, this would save a screenshot of the app at the time of the failure in `logs/textualize-<timestamp>.svg`

## Open questions

1. How to enable the user to configure the save location and filename for the tests? What would be reasonable defaults here?
2. Do other contributors find such functionality desirable?

**Comment by willmcgugan** [comment]
Interesting idea. Can you describe the kind of tests you might want this feature for?

@davep @rodrigogiraoserrao thoughts?

**Comment by rodrigogiraoserrao** [comment]
> @davep @rodrigogiraoserrao thoughts?

This looks _helpful_ to debug tests.
It's something that could even be turned off by default and we just turn on locally when a test is failing for some reason we don't understand.

**Comment by davep** [comment]
I'm not opposed to the idea, although I'm struggling to see the utility in it; the couple of examples given above seem to be like things I wouldn't ascertain from a screenshot anyway (you can't see IDs in a screenshot, for example).

**Comment by rodrigogiraoserrao** [comment]
> I'm not opposed to the idea, although I'm struggling to see the utility in it; the couple of examples given above seem to be like things I wouldn't ascertain from a screenshot anyway (you can't see IDs in a screenshot, for example).

Maybe the example isn't great but I've found myself wishing for this feature in the past, fyi...
Maybe that's not enough to implement it, but I would've used it in the past.

**Comment by ab-10** [comment]
Thank you @willmcgugan, @rodrigogiraoserrao, and @davep for commnents. The feature is a bit more controversial than I initially expected. I will close this issue, especially since I expect the actual implementation to have a couple of subjective elements in it as well (e.g. how to configure the storage path for the images).
