### ISSUE TITLE
Wrong Type Signature of ListView.watch_index

### ISSUE THREAD

**Issue by AulonSal** [Textualize/textual#3705]
The type signature of parameters `old_index` and `new_index` in `ListView.watch_index` should be `int | None`.
https://github.com/Textualize/textual/blob/78d9c4c59cbcacb27c0fa80935fdcbd4bb516ce3/src/textual/widgets/_list_view.py#L157C25-L157C25
```python
def watch_index(self, old_index: int, new_index: int) -> None:
```
-- should be -->
```python
def watch_index(self, old_index: int | None, new_index: int | None) -> None:
```
## Reason
`ListView.index` has type `reactive[Optional[int]]`

**Comment by davep** [comment]
Good catch; thanks.
