### ISSUE TITLE
`TextArea` should (optionally?) hide its cursor when it doesn't have focus

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3722]
Especially when building an input dialog, it would be natural to include `Input` and `TextArea` for different types of input, and so then also natural to want to style them in the same way in respect to focus. For example:

```python
from textual.app import App, ComposeResult
from textual.events import Key
from textual.widgets import Input, TextArea

class TabbyTextArea(TextArea):

    DEFAULT_CSS = """
    TabbyTextArea {
        background: $boost;
        color: $text;
        padding: 0 2;
        border: tall $background;
    }

    TabbyTextArea:focus {
        border: tall $accent;
    }
    """

    def on_mount(self) -> None:
        self.show_line_numbers = False

    async def _on_key(self, event: Key) -> None:
        if event.key == "tab":
            event.prevent_default()
            self.screen.focus_next()

class CursorApp(App[None]):

    def compose(self) -> ComposeResult:
        for _ in range(5):
            yield Input()
            yield TabbyTextArea()

if __name__ == "__main__":
    CursorApp().run()
```

This mostly works except for the fact that `TextArea` keeps a cursor showing (albeit one that doesn't flash when there is no focus).

https://github.com/Textualize/textual/assets/28237/9aeea5b3-9539-4ae3-b51b-f3d7856196a3

I feel we should make it so that the cursor isn't visible when the `TextArea` doesn't have focus.

---
See also #3405

**Comment by darrenburns** [comment]
I've covered this off in #4074.

**Comment by TomJGooding** [comment]
If you _didn't_ want to hide the cursor when blurred, presumably it would be simple enough to inherit and just override a method or two?

**Comment by darrenburns** [comment]
@TomJGooding You should be able to do:

```python
    def watch_has_focus(self, value: bool) -> None:
        super().watch_has_focus(value)
        self._cursor_visible = True
```
