### ISSUE TITLE
HowTo package Textual apps

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3728]
We could use a HowTo which covers how to package a Textual app.

It shouldn't be much more than a description of how to package any Python app. The only difference (I think) is that the dev has to be conscious to include the `*.tcss` files.

We should make a repo with a very basic app (suggest the calculator example), following these guidelines: https://packaging.python.org/en/latest/tutorials/packaging-projects/

We should also mention, and link, to other packaging tools.

As with all the docs, please keep the writing tight. Omit needless words.

**Comment by rodrigogiraoserrao** [comment]
Why not poetry?

**Comment by willmcgugan** [comment]
Poetry is a bit polarizing. Want to stick to whatever the standard is these days.

**Comment by TomJGooding** [comment]
> Want to stick to whatever the standard is these days.

Thankfully there should be one obvious way to do it, maybe ask a Dutchman?

**Comment by ndegroot** [comment]
We are not in Python Packaging heaven yet. 
It's too early (alpha stage) but I (Dutchman) am using [Pixi](https://github.com/prefix-dev/pixi). It can install Python as well, can create a virtual env, but you still need 'something' to get the files at the destination. Pixi can handle that too and creates a package for an anaconda repo. I didn't use that,  Git in combination with a repo works better for my situation. Just a suggestion.
