### ISSUE TITLE
Dashboard?

### ISSUE THREAD

**Issue by OhadRubin** [Textualize/textual#373]
Hey Will and the Textual team!
I want to use textual to write a continuously updating dashboard (something similar to htop for example).
Perhaps you can you give me some guidance in doing so?
Thanks!

**Comment by sanders41** [comment]
Check out [tiptop](https://github.com/nschloe/tiptop). It is like htop created with Textual.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
