### ISSUE TITLE
Maybe `ContentSwitcher` should be made public via `textual.containers`

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3752]
Currently, you import `ContentSwitcher` from `textual.widget`.
Since it's a container, shouldn't you import it from `textual.containers`?

Ref: https://github.com/Textualize/textual/pull/3751#discussion_r1405960907

**Comment by willmcgugan** [comment]
I don't think so. It's job is more than as a container. i.e. it doesn't just exist to apply a layout to a group of widgets, it has functionality on top of that.
