### ISSUE TITLE
Clicking blank part of TextArea scrollbar moves the cursor instead of scrolling

### ISSUE THREAD

**Issue by godlygeek** [Textualize/textual#3763]
Reproducer:
```py
from textual.app import App, ComposeResult
from textual.widgets import TextArea

TEXT = """\
def hello(name):
    print("hello" + name)

def goodbye(name):
    print("goodbye" + name + " I will miss you and can't wait until the day when we might one day meet again, perhaps bumping into each other at a bustling cafe in a city far from home, surprised by the serendipity of the encounter and overjoyed to reunite with an old friend")
"""


class TextAreaExample(App):
    def compose(self) -> ComposeResult:
        yield TextArea(TEXT, language="python")


app = TextAreaExample()
if __name__ == "__main__":
    app.run()
```

Run that program, and then click the black part of the horizontal scrollbar, to the right of the "slider" part. That should jump the slider to the right, but it instead moves the cursor to the last column of the first line. Clicking and dragging the slider works as expected, but clicking next to the slider doesn't.

Weirdly, clicking it several times in a row does seem to make it eventually scroll right as it should - but it also selects from the first line of the text area to the last.

I was able to reproduce this in a few different terminal emulators, so I'm pretty sure it's Textual itself at fault.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.42.0 |
| Rich    | 13.7.0 |

## Python

| Name           | Value                                       |
|----------------|---------------------------------------------|
| Version        | 3.11.4                                      |
| Implementation | CPython                                     |
| Compiler       | GCC 10.2.1 20210110                         |
| Executable     | /home/godlygeek/3ps/textual/venv/bin/python |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.1.62-08726-g0148b209c1d6                          |
| Version | #1 SMP PREEMPT_DYNAMIC Sun Nov 12 18:54:23 PST 2023 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | *Not set*      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=80, height=24 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 80                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 24                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in 0.43.1 (just released)
