### ISSUE TITLE
Update the tutorial, and the documentation for `Static`, to no longer encourage using `Static` as a container

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3782]
Initially raised [in a pair of comments on #2975](https://github.com/Textualize/textual/issues/2975#issuecomment-1822945665), and related to #3758 and #3781, because `Static` is now `ALLOW_CHILDREN=False`, we should change the tutorial to no longer [encourage the use of `Static` as a container](https://textual.textualize.io/tutorial/#custom-widgets).

Likewise, there are a couple of places in the docs that talk about `Static` as if it should be used as a container (the two that I'm aware of are linked to [here](https://github.com/Textualize/textual/issues/2975#issuecomment-1822945665) and [here](https://github.com/Textualize/textual/issues/2975#issuecomment-1823053132)).

**Comment by davep** [comment]
@rstms That would very much depend on what sort of widget you were going to be creating; if it were a compound widget -- one that composes other widgets into it -- it would probably make more sense to (as you suggest) inherit from `Widget`; or often from one of the containers.

**Comment by willmcgugan** [comment]
Redundant now, since we reversed the `ALLOW_CHILDREN` idea.
