### ISSUE TITLE
Suggestion: document state/roadmap of CSS branch

### ISSUE THREAD

**Issue by HappyEinara** [Textualize/textual#381]
As a user, I'm excited by the features promised for the the future of Textual. I have a project that would benefit from a UI I'd like to implement with Textual, but I'm not sure how to approach it right now. I'm suggesting an update to the README and/or docs to answer some or all of the following questions:

- How significant are the API changes in the CSS branch?
- Should I hold off working with 0.1 and start/wait for the CSS branch or is migrating 0.1 interfaces going to be easy?
- What is the (very rough) roadmap/timeline for the CSS branch?
- How usable is the CSS branch now?
- How soon will the CSS branch be suitable for (non-prod) work?

Roadmap-wise, I had in mind maybe a checklist of features, with strikethrough or ticks as each is implemented.

I realise you're flat-out on feature work, but if it's appropriate could you consider documenting at least some basics of the new API (on the docs of the working branch) as you go? That way we could either risk playing with the prerelease code, or know how to write against 0.1 with a view to a smooth migration?

I think even a brief edit of the README to manage expectations and clarify some of these questions would be very helpful.

TIA, congrats on the birth of Textualize and good luck!

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
