### ISSUE TITLE
Documentation Correction for guide/styles/box-sizing section

### ISSUE THREAD

**Issue by 1dancook** [Textualize/textual#3833]
Where: https://textual.textualize.io/guide/styles/#box-sizing

Paragraph in question:

> If you set box_sizing to "content-box" then space required for padding and border will be added to the widget dimensions. The default value of box_sizing is "border-box". Compare the box model diagram for content-box to the to the box model for border-box.

1. `then space` --> `then the space`
2. `to the to the` --> `to the`

Will be:

> If you set box_sizing to "content-box" then the space required for padding and border will be added to the widget dimensions. The default value of box_sizing is "border-box". Compare the box model diagram for content-box to the box model for border-box.

**Comment by willmcgugan** [comment]
Any chance of a PR ?

**Comment by 1dancook** [comment]
Yes. I'll try this morning.
