### ISSUE TITLE
RadioButton still selectable by keyboard when disabled

### ISSUE THREAD

**Issue by geoff-va** [Textualize/textual#3839]
It appears that when a `RadioButton` is disabled, click events no longer respond as expected, but you can still navigate to it with the keyboard and select it with `space` or `enter`.

![radio-select-disabled](https://github.com/Textualize/textual/assets/11033703/d3e8667f-a704-4d22-8692-c30873dd106a)

```python
from textual.app import App, ComposeResult
from textual.widgets import RadioButton, RadioSet, Static


class Test(App):
    DEFAULT_CSS = """
    RadioButton:disabled {
        color: red;
    }
    """

    def compose(self) -> ComposeResult:
        with RadioSet():
            yield RadioButton("Enabled 1")
            yield RadioButton("Disabled 2", disabled=True)
            yield RadioButton("Disabled 3", disabled=True)
        yield Static("Selected:", id="selected")

    def on_radio_set_changed(self, radio_set: RadioSet.Changed) -> None:
        self.query_one("#selected").update(f"Selected: {radio_set.pressed.label}")


if __name__ == "__main__":
    app = Test()
    app.run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.44.1 |
| Rich    | 13.7.0 |

## Python

| Name           | Value                                                     |
|----------------|-----------------------------------------------------------|
| Version        | 3.8.10                                                    |
| Implementation | CPython                                                   |
| Compiler       | Clang 12.0.5 (clang-1205.0.22.9)                          |
| Executable     | /Users/geoff/Documents/projects/test/venv/bin/python |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 22.5.0                                                                                                |
| Version | Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.85.0) |
| TERM                 | xterm-256color  |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=158, height=40 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 158                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 40                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment]
Good spot: for clarification, this looks to be a `RadioSet` bug, not a `RadioButton` bug.

**Comment by willmcgugan** [comment]
This may impact other widgets where you can press a key to select. Suggest we also check other widgets.

**Comment by rodrigogiraoserrao** [comment]
> This may impact other widgets where you can press a key to select. Suggest we also check other widgets.

You were right.
 - `SelectionList` and `OptionList` allow highlighting disabled items (with keyboard & mouse) but don't allow selection.
 - `ListView` allows highlighting with keyboard but not with mouse (and doesn't allow selection).
 - As of [PR 3872](https://github.com/Textualize/textual/pull/3872), `RadioSet` don't allow neither navigation nor selection.

I feel like we should disable navigation everywhere and instead <kbd>Up</kbd> / <kbd>Down</kbd> should only go through enabled children.

**Comment by willmcgugan** [comment]
Agree, please adds that to ToDo

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Infrastructure error during execution: Command '['git', 'clone', '--depth', '1', '--filter=blob:none', '--single-branch', 'https://x-access-token:<redacted>@github.com/Textualize/textual.git', '/home/morganbest/.repopilot/repos/Textualize-textual']' timed out after 180 seconds

Relevant files:
- src/textual/demo/widgets.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=79.243; matched issue terms: radiobutton, still, selectable, when, disabled, click; bm25 rerank score=95.298; matched issue terms: radiobutton, still, selectable, when, disabled, click; bm25 rerank score=107.635; matched issue terms: radiobutton, still, selectable, when, disabled, click; bm25 rerank score=104.684; matched issue terms: radiobutton, still, selectable, when, disabled, click
- src/textual/demo/home.py: path components match issue terms, source file; bm25 rerank score=73.072; matched issue terms: keyboard, click, no, but, you, can; bm25 rerank score=77.825; matched issue terms: keyboard, click, no, but, you, can; bm25 rerank score=76.871; matched issue terms: keyboard, click, no, but, you, can
- src/textual/widgets/_radio_set.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=49.434; matched issue terms: radiobutton, when, disabled, click, events, respond; bm25 rerank score=68.659; matched issue terms: radiobutton, when, disabled, click, events, respond; bm25 rerank score=72.510; matched issue terms: radiobutton, when, disabled, click, events, respond; bm25 rerank score=71.904; matched issue terms: radiobutton, when, disabled, click, events, respond
- src/textual/widgets/_select.py: path components match issue terms, source file; bm25 rerank score=71.552; matched issue terms: when, disabled, click, events, no, you; bm25 rerank score=69.527; matched issue terms: when, disabled, click, events, no, you
- src/textual/widgets/_option_list.py: path components match issue terms, source file; bm25 rerank score=64.599; matched issue terms: selectable, when, disabled, click, events, no; bm25 rerank score=63.080; matched issue terms: selectable, when, disabled, click, events, no
- examples/merlin.py: matched GitHub code search; bm25 rerank score=76.404; matched issue terms: keyboard, when, disabled, events, no, you

Attempts:
Attempt 1: success=False
File: src/textual/widgets/_radio_set.py
Result: execution_error
Error:
Command '['git', 'clone', '--depth', '1', '--filter=blob:none', '--single-branch', 'https://x-access-token:<redacted>@github.com/Textualize/textual.git', '/home/morganbest/.repopilot/repos/Textualize-textual']' timed out after 180 seconds

Token usage: 45639/100000
