### ISSUE TITLE
DataTable move_cursor animate doesn't do anything?

### ISSUE THREAD

**Issue by davetapley** [Textualize/textual#3840]
While working on:
- https://github.com/Textualize/textual/discussions/3606

I wanted to check `animate` for `move_cursor` behaves correctly, but it doesn't seem to do anything?

---

Repro:

```py
from random import randint
from textual.app import App, ComposeResult
from textual.widgets import DataTable, Button
from textual.widgets._data_table import RowKey
from textual.containers import Horizontal
from textual import on
from textual.reactive import Reactive, reactive

ROWS = [
    ("lane", "swimmer", "country", "time"),
    (4, "Joseph Schooling", "Singapore", 50.39),
    (2, "Michael Phelps", "United States", 51.14),
    (5, "Chad le Clos", "South Africa", 51.14),
    (6, "László Cseh", "Hungary", 51.14),
    (3, "Li Zhuhao", "China", 51.26),
    (8, "Mehdy Metella", "France", 51.58),
    (7, "Tom Shields", "United States", 51.73),
    (1, "Aleksandr Sadovnikov", "Russia", 51.84),
    (10, "Darren Burns", "Scotland", 51.84),
]


class TableApp(App):
    CSS = """
    DataTable {
    height: 80%;
    }
    """

    keys: Reactive[RowKey] = reactive([])

    def compose(self) -> ComposeResult:
        yield DataTable(cursor_type="row")
        with Horizontal():
            yield Button("True")
            yield Button("False")

    @on(Button.Pressed)
    def goto(self, event: Button.Pressed):
        row  = randint(0, len(self.keys) - 1)
        print(row)

        animate = str(event.button.label) == "True"
        table = self.query_one(DataTable)
        table.move_cursor(row=row, animate=animate)

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.add_columns(*ROWS[0])
        for _ in range(20):
            keys = table.add_rows(ROWS[1:])
            self.keys.extend(keys)


app = TableApp()
if __name__ == "__main__":
    app.run()
```

---

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.39.0 |
| Rich    | 13.3.3 |

## Python

| Name           | Value                                             |
|----------------|---------------------------------------------------|
| Version        | 3.11.4                                            |
| Implementation | CPython                                           |
| Compiler       | Clang 14.0.0 (clang-1400.0.29.202)                |
| Executable     | /Users/dave/.pyenv/versions/3.11.4/bin/python3.11 |

## Operating System

| Name    | Value                                                                                                   |
|---------|---------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                  |
| Release | 21.6.0                                                                                                  |
| Version | Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.85.0) |
| TERM                 | xterm-256color  |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=90, height=68 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 90                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 68                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by davetapley** [comment]
I thought maybe because neither `duration` nor `speed` were set, but seems to default:
https://github.com/Textualize/textual/blob/82d6e3e05f87939166364e805f35e8260f395c9d/src/textual/widget.py#L1860-L1863

**Comment by rodrigogiraoserrao** [comment]
Using `_scroll_cursor_into_view(animate=True)` directly works fine.
So far, it looks like some interesting interaction between `call_after_refresh` and `_scroll_cursor_into_view`.

**Comment by rodrigogiraoserrao** [comment]
Turns out it was much more interesting than that.
It's an issue with ordering because inside `move_cursor` we assign to `cursor_coordinate` and its watch method also wants to scroll into view.
Supposedly, there's a comment explaining that we do something inside said watch method so that scrolling from `move_cursor` (which is potentially animated) happens first, but that's not enough.
I _think_ it's because synchronous watch methods are called immediately but I need to double-check that.
