### ISSUE TITLE
Ability to rename tabs (TabPane).

### ISSUE THREAD

**Issue by ggozad** [Textualize/textual#3901]
Currently this is not supported AFAIK. If one wants to change the title of a tab, they need to remove and add it again.
Fetching the `Tab` within `TabPane` and updating it doesn't fully work, for instance the underline does not adapt.

**Comment by davep** [comment]
To add to the above, this can pretty much be done right now with code like this:

```python
from textual.app import App, ComposeResult
from textual.widgets import TabbedContent, TabPane, Label

class TCRenameApp(App[None]):

    BINDINGS = [
        ("space", "rename"),
    ]

    def compose(self) -> ComposeResult:
        with TabbedContent():
            with TabPane("One", id="one"):
                yield Label("Press space to change my Tab's label")
            with TabPane("Two", id="two"):
                yield Label("This one won't rename")

    def action_rename(self) -> None:
        self.query_one(TabbedContent).get_tab("one").update("Renamed!")

if __name__ == "__main__":
    TCRenameApp().run()
```

but the `Tab.update` doesn't refresh the underline, so you go from this:

![Screenshot 2023-12-19 at 07 48 17](https://github.com/Textualize/textual/assets/28237/5245fcd6-32ce-4946-8580-d8a5918c2d2c)

to this:

![Screenshot 2023-12-19 at 07 48 23](https://github.com/Textualize/textual/assets/28237/16ea5f1b-5208-4cd9-9f96-cc99c3fee12c)

At its most basic level this could be an issue to ensure that the underline gets a refresh; but it could also be an issue for adding a `TabbedContent` API call for relabelling a tab.

---
@ggozad Thinking about it some more this morning, you *can* do what you want like this:

```python
from textual.app import App, ComposeResult
from textual.widgets import TabbedContent, TabPane, Label, Tabs

class TCRenameApp(App[None]):

    BINDINGS = [
        ("space", "rename"),
    ]

    def compose(self) -> ComposeResult:
        with TabbedContent():
            with TabPane("One", id="one"):
                yield Label("Press space to change my Tab's label")
            with TabPane("Two", id="two"):
                yield Label("This one won't rename")

    def action_rename(self) -> None:
        tabbed_content = self.query_one(TabbedContent)
        tabbed_content.get_tab("one").update("Renamed!")
        tabbed_content.query_one(Tabs).show("one")

if __name__ == "__main__":
    TCRenameApp().run()
```

that call to `show` the tab again will cause it to refresh (although I do feel a more coherent API call for this would make sense).

**Comment by ggozad** [comment]
Oooh thank you @davep !
This covers me, at least I no longer need to recreate the tab.
I will leave this open in case you decide you want to wrap it up in a documented API, but if you feel this is too much of an edge case please close the issue.

**Comment by davep** [comment]
@ggozad My pleasure. I'm inclined to leave this open as I feel this is an obvious thing to want to do and it should probably have a very obvious API. Thanks for raising it.

**Comment by willmcgugan** [comment]
Let's add a more elegant API for this.

**Comment by davep** [comment]
@ggozad A PR to address this is incoming: https://github.com/Textualize/textual/pull/3979
