### ISSUE TITLE
get_option in SelectionList not working

### ISSUE THREAD

**Issue by stefgmz** [Textualize/textual#3903]
The function `get_option` in `SelectionList` does not work as intended. The following raises `OptionDoesNotExist`

```
from textual.app import App
from textual.widgets import SelectionList
from textual.widgets.selection_list import Selection
class QuickApp(App):

    def compose(self):
        yield SelectionList(
            Selection("a", 1, id="a")
        )

    def on_mount(self):
        list = self.query_one(SelectionList)
        list.get_option("a")
```

I looked through the code and it looks like `_option_ids` is never set in `OptionList` but gets evaluated in `get_option_index`.

**Comment by davep** [comment]
This would seem to be down to the internals of the underlying `OptionList` not being fully-built until the widget itself is fully displayed (which it won't be in `on_mount`). Compare the above with:

```python
from textual.app import App
from textual.widgets import SelectionList
from textual.widgets.selection_list import Selection

class QuickApp(App):

    BINDINGS = [
        ("f", "find"),
    ]

    def compose(self):
        yield SelectionList(
            Selection("a", 1, id="a")
        )

    def action_find(self):
        self.notify(f"{self.query_one(SelectionList).get_option('a')}")

if __name__ == "__main__":
    QuickApp().run()
```

Once the app is up and running, press <kbd>f</kbd>.

(aside: IIRC this isn't the only widget in Textual where this can be a gotcha).

**Comment by rodrigogiraoserrao** [comment]
Given Dave's clarification, I'm not sure we can do a lot here...
Maybe in `get_option` raise a different exception saying it's too early to query options by ID?

**Comment by willmcgugan** [comment]
This should work. The `Mount` message is a guarantee that child widgets are ready to be used. We don't want to deviate from that.
