### ISSUE TITLE
Documentation annotations don't render

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3906]
There are some annotations in code listings that aren't rendering correctly.
So far, I've identified these:

 - https://textual.textualize.io/styles/visibility/#__tabbed_2_3
 - https://textual.textualize.io/styles/border_subtitle_align/#__tabbed_2_3
 - https://textual.textualize.io/styles/border_title_align/#__tabbed_2_3

They look like this:

![Screenshot 2023-12-19 at 12 32 57](https://github.com/Textualize/textual/assets/5621605/54b2101c-8a95-4718-abda-278fdc67ad88)

For reference, the extra `*/` to the right of the only annotation that renders has been around for a long time now.

**Comment by TomJGooding** [comment]
The [docs for code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#fn:1) say that "Code annotations require syntax highlighting with Pygments"

Thankfully the Pygments website has a demo - you can see the results of my experimentation [on this link](https://pygments.org/demo/?lexer=sass&style=bw&formatter=tokens&code=Horizontal+%7B%0A++++padding%3A+1+2%3B+++++++++%2F%2F+%281%29%21%0A++++background%3A+white%3B%0A++++height%3A+1fr%3B%0A%7D%0A%0A%23top+%7B%0A++++++++++++++++++++++++++%2F%2F+%282%29%21%0A%7D%0A%0A%23middle+%7B%0A++++visibility%3A+hidden%3B+++%2F%2F+%283%29%21%0A%7D%0A%0A%23bot+%7B%0A++++visibility%3A+hidden%3B+++%2F%2F+%284%29%21%0A%7D%0A%0A%23bot+%3E+Placeholder+%7B%0A++++visibility%3A+visible%3B++%2F%2F+%285%29%21%0A%7D%0A%0APlaceholder+%7B%0A++++width%3A+1fr%3B%0A%7D%0A).

Here's how the code annotations look after these changes:

![image](https://github.com/Textualize/textual/assets/101601846/7f3f01ee-6303-4fb4-9173-e5fa70cd682d)

**Comment by rodrigogiraoserrao** [comment]
Fixed with #3905.
