### ISSUE TITLE
Support nesting in syntax highlighting

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3958]
The addition of nesting has broken the syntax highlighting a little. Let's see if we can support it.

Additionally I think `keyline` is not covered by the highlighting (not surprising as it was a recent addition).

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao This is probably one for you.

**Comment by rodrigogiraoserrao** [comment]
Closed in favour of the issue above.
Keyline support is issue 6 there.
