### ISSUE TITLE
Initial Textual CLI

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#396]
A CLI tool for textual. It will be built using `click`.

The initial feature exposed by this will be access to the devtools console.

Running `textual console` will run the devtools console server, allowing textual apps to connect to it.

- `textual --help` will display help information
- `textual --version` will display the Textual version

**Comment by DanielATucker** [comment]
I apologize for the novel.
Can you please implement the following features into the CLI.
-"/" command feature that can be customized. eg, /loggerOn /loggerOff //(Admin rights only commands)
-The ability for multiple consoles to run on one machine. eg, one for each widget.
-(this one might be crazy) One for each web-socket room connected to a server. 
    I see this one working as such.. I have a python application that is based mostly on Rich and a web-socket server-client program (https://github.com/Branbados/irc-application.git) that separates multiple clients into rooms while only using one port, I've been working on stitching in a command interface mixed in with a journaling application I built that allows multiple clients to have access to their own "journal" (https://github.com/DanielATucker/Brain/) and I'm now implementing Textual so that I can have multiple rooms in different widgets so I can monitor them as an admin. It would be really nice to have this type of connection built into Textual in some way, maybe as an extension? it would just help because I am going to try to allow each client to have their own console so that I can teach basic Linux commands and basic Python with each client having their own environment to play around with, eg create and modify files that are JSON encoded and stored on my neo4j server

![Git](https://user-images.githubusercontent.com/70778655/163529339-e7ea181c-4e04-4f46-8f5c-73edb9734700.png)
