### ISSUE TITLE
Incorrect type for DataTable.get_cell_coordinate column_key?

### ISSUE THREAD

**Issue by geoff-va** [Textualize/textual#3972]
Was noticing mypy was giving me flack for using a `ColumnKey` in [DataTable.get_cell_coordinate](https://github.com/Textualize/textual/blob/b3efc3ffdb8d109c119873e8f09bfbe3de185a9a/src/textual/widgets/_data_table.py#L863) as the `column_key`. Looks to be typed as `Column`, but given the name and usage I'm guessing it should be a `ColumnKey`?

Thanks!

**Comment by rodrigogiraoserrao** [comment]
Thanks for spotting this!
