### ISSUE TITLE
Border type panel is missing from docs

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#3978]
The border type `panel` is missing from the documentation, both in the CSS type for the border (it's not in the table) and in the “border_all” example in https://textual.textualize.io/styles/border/#__tabbed_2_2.

Check if there are other border types also missing.

**Comment by rodrigogiraoserrao** [comment]
Checked; `panel` is the only type missing. Also needs to be added to the TCSS grammar.

**Comment by AkintolaRichard** [comment]
Hi @rodrigogiraoserrao I would love to help with resolving the issue.

**Comment by kyle-lillup** [comment]
Hi I would like to help with resolving the issue.

**Comment by Kyl67899** [comment]
Hi I would like to contribute and help resolving the issue.

**Comment by rodrigogiraoserrao** [comment]
Feel free to have a go at this.

Disclaimer: in a week or two if there hasn't been any progress I'll do this myself :)

**Comment by rodrigogiraoserrao** [comment]
> Also needs to be added to the TCSS grammar.

The grammar and the VS Code extension have been updated. ✅

**Comment by AkintolaRichard** [comment]
Hi @rodrigogiraoserrao, you were really fast with it and this swept me off my feet.
I am in a straight now, how do I go about this?

**Comment by AkintolaRichard** [comment]
@rodrigogiraoserrao I am still going through the documentation and I found out that the concerned files are located in the border.md file in the css_types directory and the border.md file in the styles directory.

**Comment by rodrigogiraoserrao** [comment]
Yeah. The file in the `css_types` directory contains the table inside and it can be modified directly.
The file `border.md` in the `styles` directory will have some funny syntax with

````
```textual ...
```
````

That's used to run a Textual app in the file path specified.
One of those should be a `border_all.py` app that tries to show all border types.
For that one, you need to modify the Textual app and make sure it runs well and that it includes the `panel` border type.

**Comment by AkintolaRichard** [comment]
Thank you, I will reach out to you as I progress.

**Comment by AkintolaRichard** [comment]
Hello @rodrigogiraoserrao 
I am sorry for keeping you waiting, having gone through the tutorial in the doc, I am in a straight on putting the description for the panel border.

**Comment by AkintolaRichard** [comment]
Okay, I noticed that there is a short description for each border type, so I want to ask if there is a formal description or I should create the description myself.
I am really sorry for stressing you, this is my first open source contribution experience.

**Comment by AkintolaRichard** [comment]
Hello @rodrigogiraoserrao 
Please do check out the changes I made, thank you for your patience, I do appreciate and I don't take it for granted because I don't think I would be able to navigate my way through without your guidance.
