### ISSUE TITLE
Editing CSS with e.g. vim can crash an app

### ISSUE THREAD

**Issue by Alphix** [Textualize/textual#3996]
Editing the CSS of a running app (with the `--dev` switch) using e.g. `vim` causes frequent crashes when saving the changed CSS.

The code that causes it is: https://github.com/Textualize/textual/blob/4da008d5cb5d4c8485c57969b6c27b1bedeae0fc/src/textual/file_monitor.py#L32-L34

Where the `os.stat` call can raise a `FileNotFoundError` (I assume that `vim` stores a temporary version of the edited file, removes the original and renames the temporary to the original file name, meaning that the CSS file doesn't exist for a short time window).

I've added a temporary workaround which loops/sleeps a couple of times, but that's obviously not a real solution...I'm not 100% sure what the right solution would be...

**Comment by TomJGooding** [comment]
I always forget the live editing feature so don't use it as often as I should, but I can't seem to reproduce this with a quick few tests.

Out of interest, do you have backups in vim off or on?

```
:set backup?
````

**Comment by Alphix** [comment]
> I always forget the live editing feature so don't use it as often as I should, but I can't seem to reproduce this with a quick few tests.

I should have mentioned (or though of, rather) that when I hit this, I was working on a textual project that's stored on a NFS share. I tried reproducing it with a local copy, and I can't (did a quick couple of tests). It anyway seems to be a bug to not handle the potential exception from `os.stat` in the code I referred to above though?

> Out of interest, do you have backups in vim off or on?

```
:set backup?
nobackup
```

> It might be useful to know what versions of textual and textual-dev you're working with too?

The latest via `pip` in a custom `venv`:
```
Using cached textual-0.47.1-py3-none-any.whl
Using cached textual_dev-1.4.0-py3-none-any.whl (26 kB)
```

**Comment by davep** [comment]
> It anyway seems to be a bug to not handle the potential exception from os.stat in the code I referred to above though?

I'd second this; there's enough editor backup approaches that do a move then write approach to make this a sensible approach.

**Comment by Alphix** [comment]
> ...I can't seem to reproduce this with a quick few tests.

@TomJGooding another (contrived) way to reproduce it is to start a Textual app and then rename the CSS file...that'll also cause a crash...
