### ISSUE TITLE
Code Viewer example does not support scrolling on macOS

### ISSUE THREAD

**Issue by zachriggle** [Textualize/textual#400]
When playing with the examples, at first the Code Viewer seems to work!  However, attempting to scroll the code shown causes control characters to be printed to the screen.  Lots of bells are printed.

This happens with macOS terminal (default configuration) and in iTerm2 (lots of custom configuration).  Both fail in the same way.

Screenshot and video attached.

<img width="800" alt="Screen Shot 2022-04-15 at 9 40 12 PM" src="https://user-images.githubusercontent.com/111640/163658395-7670fb1e-d7b3-405a-b9e4-43d80b29e9a2.png">

https://user-images.githubusercontent.com/111640/163658400-8df11f33-c70b-4e05-9123-3bead4f6ca44.mov

**Comment by willmcgugan** [comment]
I can't reproduce that here, on MacOS. Do you have any kind of shell integration or extension active?

Is it only the code viewer where this happens, or other examples? How are you scrolling? Touch pad or mouse?

Can you use the mouse with other TUI apps, such has htop ?

**Comment by ayasyrev** [comment]
Got same issue with ScrollView on linux.
If run app with stdin input (from pipe) arrors keys and mouse moves cause same effect.
Regular run -> OK.
Same effect with rich-cli.
Tested on ubuntu, different terminals, same with remote ssh access.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
