### ISSUE TITLE
Tooltip does not disappear even if the widget is not visible anymore

### ISSUE THREAD

**Issue by kraanzu** [Textualize/textual#4052]
> Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed

Yes

> Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**

If the tooltip of a widget is set and then the widget is not visible anymore, the tooltip stays there until the mouse is moved

> It will be helpful if you run the following command and paste the results:

```
textual diagnose
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.47.1 |
| Rich    | 13.7.0 |

## Python

| Name           | Value                                             |
|----------------|---------------------------------------------------|
| Version        | 3.11.6                                            |
| Implementation | CPython                                           |
| Compiler       | GCC 13.2.1 20230801                               |
| Executable     | /home/kraanzu/Documents/termtyper/venv/bin/python |

## Operating System

| Name    | Value                                                  |
|---------|--------------------------------------------------------|
| System  | Linux                                                  |
| Release | 6.6.2-arch1-1                                          |
| Version | #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 |

## Terminal

| Name                 | Value                              |
|----------------------|------------------------------------|
| Terminal Application | WezTerm (20230712-072601-f4abf8fd) |
| TERM                 | xterm-256color                     |
| COLORTERM            | truecolor                          |
| FORCE_COLOR          | *Not set*                          |
| NO_COLOR             | *Not set*                          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=144, height=34 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 144                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 34                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

Feel free to add screenshots and / or videos. These can be very helpful!

```python
from textual import on
from textual.app import App, ComposeResult
from textual.widgets import Button

TEXT = "I am a tooltip"


class TooltipApp(App):
    CSS = """
    Screen {
        align: center middle;
    }
    """

    def compose(self) -> ComposeResult:
        yield Button("Click me", id="button")

    def on_mount(self) -> None:
        self.query_one(Button).tooltip = TEXT

    @on(Button.Pressed)
    def test(self, event: Button.Pressed):
        event.button.styles.visibility = "hidden"


if __name__ == "__main__":
    app = TooltipApp()
    app.run()
```

**Comment by TomJGooding** [comment]
Possibly related issue:

- #3045

**Comment by kraanzu** [comment]
oops. My bad for opening a dup
I'll close this one :)
