### ISSUE TITLE
Possible dev tools and threads issue

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4060]
While debugging Tailless, I often find the app gets stuck, but only when running devtools.

I *suspect* there is some interaction with threads and devtools here.

If any one picks this up, please try first to reproduce with an MRE. I may be wrong.

*Update:* I suspect what I'm seeing is just because I am writing very large print statements. It may not be a threading issue per se.

**Comment by tconbeer** [comment]
I've noticed this when moving a lot of data through workers and messages. Kind of related to https://github.com/Textualize/textual/issues/2588 because the default output to console can end up calling repr on and then printing some very large objects, which noticeably slows things down.

This app runs in 0.4 s without the console (`python app.py`), but doesn't even finish the first paint before hanging for >5 minutes when run with `textual run --dev app.py`.

```py
from __future__ import annotations
from textual._path import CSSPathType
from textual.app import App, CSSPathType, ComposeResult
from textual.driver import Driver
from textual.widgets import Static
import time
from textual import work, on
from textual.message import Message


class SlowConsole(App):
    class Result(Message):
        def __init__(self, len: int) -> None:
            self.len = len
            super().__init__()

    def __init__(
        self,
        driver_class: type[Driver] | None = None,
        css_path: CSSPathType | None = None,
        watch_css: bool = False,
    ):
        self.data = [(i, "one", "two", "three", "four") for i in range(1_000_000)]
        self.start = time.monotonic()
        super().__init__(driver_class, css_path, watch_css)

    def compose(self) -> ComposeResult:
        self.static = Static("working")
        yield self.static

    def on_mount(self) -> None:
        self.check_data(self.data)

    @work(thread=True)
    def check_data(self, data: list) -> None:
        self.post_message(self.Result(len(data)))

    @on(Result)
    def update_static(self, message: Result) -> None:
        self.static.update(f"{message.len}  {time.monotonic() - self.start}")


SlowConsole().run()
```

**Comment by darrenburns** [comment]
We've decided to park this for now after thinking about alternative approaches. We couldn't think of anything that we can do that wouldn't massively interfere with how useful the devtools are in general.
