### ISSUE TITLE
Tidy the return type of `App.render`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4063]
Currently the return type of `App.render` is `RenderableType`; in our docs and in most places we talk about `App.render` returning a `RenderResult`. `RenderResult` is an alias for `RenderableType` and is a top-level value in `textual.app`.

This can cause a lint/type warning in dev's apps if they let their IDE complete the signature when writing their own `render` method, as it will often complete to something like this:

```python
    def render(self) -> RenderableType:
        return super().render()
```

which in turn will auto-import `RenderableType` from `textual.app`. This can then result in a warning like this:

![Screenshot 2024-01-23 at 14 16 46](https://github.com/Textualize/textual/assets/28237/df847da3-0171-4181-93b9-17ea7393338c)

We should change `App.render` so that it's typed as returning `RenderResult` rather than `RenderableType`, then such completion will use the type that *is* exported from `textual.app`.

Also note that [the code in the compose/render HOWTO seems to have fallen foul of this](https://textual.textualize.io/how-to/render-and-compose/) and has that type warning.

**Comment by TomJGooding** [comment]
This seems a simple enough fix that I could help (if wanted!). But I can't seem reproduce this in my editor, so I just wanted to check where you've seen/tested this?

**Comment by davep** [comment]
> But I can't seem reproduce this in my editor, so I just wanted to check where you've seen/tested this?

In my case Emacs+eglot+pyright while auto-completing `def render`.
