### ISSUE TITLE
typing_extensions ^3.10 makes it impossible to use the newer typing_extensions features

### ISSUE THREAD

**Issue by Hmiku8338** [Textualize/textual#407]
I am building a CLI/GUI tool based on one of my libraries and textual. The problem is: textual requires typing_extensions ^3.10.0 and my library requires typing_extensions ^4.1.1 because I use typing.Self.

This is an easily fixable issue yet it completely blocks my development. Would you consider upgrading your typing_extensions dependency? Seems like a safe upgrade yet it would greatly assist all developers who want to use the bleeding edge typing functionality along with textual.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
