### ISSUE TITLE
Rendering issue with soft hyphens (~~long/wrapped text in `OptionList`~~)

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4073]
At the suggestion of @willmcgugan I'm recording this *without* an MRE (although I have tried to make one; see below). In an application I'm currently toying with, over the weekend, I ran into this curious rendering bug:

![Screenshot 2024-01-28 at 12 42 56](https://github.com/Textualize/textual/assets/28237/ff95e951-c313-4b31-9887-e529d92d7b97)

Note the effect seen to the right of question 9.

The widget is an `OptionList`, the `Option`s within are made up of Rich renderables which in turn are made up of a `Group` that contains two `Table.grid`s.

I've attempted to isolate the issue from the wider application, adding all the relevant styles (also doing it as a `ModalScreen` as this was part of such):

```python
from rich.table import Table
from rich.console import Group

from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.screen import ModalScreen
from textual.widgets import OptionList

NAMES = [
    "Cardiff",
    "Swansea",
    "Aberdare",
    "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
    "Mountain Ash",
    "Hirwaun"
]

class Names(ModalScreen[None]):

    CSS = """
    Names {
        align: center middle;

        Vertical {
            width: auto;
            max-width: 60%;
            height: auto;
            max-height: 80%;
            padding: 1 2 0 2;
            background: $surface;
            border: panel $primary;
            border-title-color: $accent;

            OptionList {
                height: 1fr;
                margin: 1 0 1 0;
                &> .option-list--option {
                    padding: 0 5 1 0;
                }
            }
        }
    }
    """

    def gridify(self, n: int, name: str) -> Group:
        question = Table.grid()
        question.add_column(width=3, justify="right")
        question.add_column(width=1)
        question.add_column(ratio=1)
        question.add_row(str(n), "", f"{name} is the name of a place in Wales." )
        answer = Table.grid()
        answer.add_column(width=4)
        answer.add_column(ratio=1)
        answer.add_row("", "[red]Here is the[/] [green]second line[/]")
        return Group(question, answer)

    def compose(self) -> ComposeResult:
        with Vertical():
            yield OptionList(*[self.gridify(n, name) for n, name in enumerate(NAMES)])

class TruncatedTextOptionApp(App[None]):

    CSS = """
    Screen#_default {
        background: red;
    }
    """

    def on_mount(self) -> None:
        self.push_screen(Names())

if __name__ == "__main__":
    TruncatedTextOptionApp().run()
```

the result however seems fine:

![Screenshot 2024-01-29 at 10 20 24](https://github.com/Textualize/textual/assets/28237/5a6f62d5-835c-444c-b683-662272abd434)

**Comment by davep** [comment]
Update: I'm starting to suspect it doesn't have much to do with long/wrapped text at all, and it could be there is a problematic character or similar in [the underlying data](https://opentdb.com/). I'm thinking this based on the fact that, while testing/developing some more just now, I got the same issue, only this time, if I make the window wide enough that the suspect word itself doesn't overflow, I still see the rendering issue:

![Screenshot 2024-01-29 at 20 16 22](https://github.com/Textualize/textual/assets/28237/ed467ab0-8e70-4976-b572-cad0a5ff46d3)

I'll leave this open for now and see if I can hunt down the question itself (it's simply pulled down from the API and used in-app; no copy is stored locally, so I an't view the underlying data), but this seems less of an issue now.

**Comment by davep** [comment]
[Found it](https://opentdb.com/user_profile.php?user=369). And if I copy the question from the web view and paste it into a scratch buffer in Emacs:

![Screenshot 2024-01-29 at 20 22 42](https://github.com/Textualize/textual/assets/28237/e9e1950f-bfcc-4cad-8f04-5899f797665e)

Inspecting what it is:

![Screenshot 2024-01-29 at 20 24 08](https://github.com/Textualize/textual/assets/28237/7ab62031-33da-41f2-b172-d3507aaeb7a8)

**Comment by davep** [comment]
And, just for final confirmation, plugging that into the test code above:

![Screenshot 2024-01-29 at 20 28 55](https://github.com/Textualize/textual/assets/28237/f3ecad05-cacf-4684-870e-272b9254548d)

**Comment by willmcgugan** [comment]
Good catch. Soft hyphens. Zero length, they indicate where the word is permitted to wrap.

Rich is reporting them as having a length of 1, where they should have a cell length of 0.

**Comment by davep** [comment]
We should make @darrenburns's day by plugging this into soft-wrapped `TextArea`. 😏

**Comment by willmcgugan** [comment]
I think this may be fixable from Rich. If you tackle this, ask @willmcgugan for an overview of how Rich calculates cell lengths.

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan for this to be fixed in Textual we need a Rich release and then we need to update the Rich dependency in Textual.
Do you have a Rich release planned?

**Comment by willmcgugan** [comment]
Can do a Rich release shortly.

Can I just confirm that you have tested Textual with the update to Rich, and it fixes this issue?

**Comment by rodrigogiraoserrao** [comment]
Yes. I installed rich locally and this fixed the issue in Textual.

**Comment by willmcgugan** [comment]
Pushed Rich 13.7.1

**Comment by rodrigogiraoserrao** [comment]
Since we won't be pinning rich to 13.7.1, this can be closed already.
