### ISSUE TITLE
TextArea docs missing syntax highlighting

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4094]
I spotted that the updated TextArea docs following the release of v0.48.0 seem to be missing the syntax highlighting. I'm not sure why yet as I've only actually only skimmed the new docs so far.

![image](https://github.com/Textualize/textual/assets/101601846/e84a2cdc-09d4-472b-8051-e9b1d3d2e1ea)

![image](https://github.com/Textualize/textual/assets/101601846/517bb436-368c-487c-a7b3-e5b20124ca11)

**Comment by darrenburns** [comment]
Ah, I forgot to update the docs examples to use `TextArea.code_editor(...)` instead of `TextArea(...)` 😄

**Comment by TomJGooding** [comment]
Ah, so setting the `language` only works with a `TextArea.code_editor`? I confess I've only skimmed the docs so far but that might need emphasising a bit?
