### ISSUE TITLE
`TextArea` still has a cursor, until it's had focus and then lost it

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4109]
Sort of related to #3722: a `TextArea` still has a cursor when not focused, if it hasn't received focus yet. For example, this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Input, TextArea

class TextAreaCursorApp(App[None]):

    def compose(self) -> ComposeResult:
        yield Input()
        yield TextArea()

if __name__ == "__main__":
    TextAreaCursorApp().run()
```

starts up looking like this:

![Screenshot 2024-02-02 at 21 07 37](https://github.com/Textualize/textual/assets/28237/fca3f112-7553-43a6-8353-c849ce45acba)

**Comment by darrenburns** [comment]
Cheers - I reckon this will be changing a True to a False somewhere 😄

**Comment by TomJGooding** [comment]
I had a quick look at this and found that if you set `cursor_blink = False` (needed for snapshot testing), the `TextArea` still has a cursor even after focussing then blurring:

```python
from textual.app import App, ComposeResult
from textual.widgets import Input, TextArea


class TextAreaCursorApp(App[None]):
    def compose(self) -> ComposeResult:
        input = Input()
        text_area = TextArea()
        input.cursor_blink = False
        text_area.cursor_blink = False
        yield input
        yield text_area


if __name__ == "__main__":
    TextAreaCursorApp().run()
```

Then I spotted that the `_on_blur` method actually also seems to set the cursor to be visible which is confusing? Changing this to False has no effect, which suggests the cursor visibility must actually be updated elsewhere...?

https://github.com/Textualize/textual/blob/6459878b80360243e9daee3036e1b576f7542f02/src/textual/widgets/_text_area.py#L1291-L1292

**Comment by darrenburns** [comment]
Oh yeah, the `_on_blur` can probably be removed. It was intended to ensure that the cursor remains visible when it's blurred for consistency. Otherwise the visibility of the cursor depended on when you blurred the widget.

I was thinking initialising `self._cursor_visible` to `False` in the constructor might be enough.

**Comment by TomJGooding** [comment]
Just to note for whoever picks this up (maybe me!), potentially any fix should also account for this issue:

- #3405

**Comment by TomJGooding** [comment]
> Oh yeah, the `_on_blur` can probably be removed. It was intended to ensure that the cursor remains visible when it's blurred for consistency. Otherwise the visibility of the cursor depended on when you blurred the widget.

Sorry I'm not sure I fully understand this - is it related to #2476?

**Comment by darrenburns** [comment]
Sorry, I meant the `_on_blur` could be removed because we could handle the logic of pausing the blink inside`watch_has_focus` instead, rather than doing blur-related stuff in 2 places. We'll probably need to pause blink in `watch_has_focus` with visible=False.

**Comment by darrenburns** [comment]
I'm going to pick this up now.
