### ISSUE TITLE
Tests for devtools occasionaly fail

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#411]
The tests for devtools fail from time to time. Suspect a race condition in the networking. I can reproduce this locally. Here's an instsance where it failed in CI:

https://github.com/Textualize/textual/runs/6128751468?check_suite_focus=true

**Comment by darrenburns** [comment]
You can or can't reproduce locally?

**Comment by willmcgugan** [comment]
I can. But not consistently.
