### ISSUE TITLE
Show all commands in command palette

### ISSUE THREAD

**Issue by chbndrhnns** [Textualize/textual#4111]
When I'd like to explore an app, I would want to see all available commands available in the command palette just by pulling it up, just like VS Code does it.

**Comment by willmcgugan** [comment]
I think this is very good idea.

**Comment by darrenburns** [comment]
Just to make sure I'm understanding correctly - does this mean when the search box is empty, we show everything?

**Comment by davep** [comment]
Just to add context (not really to answer that question), this stems from [this conversation on Discord](https://discord.com/channels/1026214085173461072/1033754296224841768/1203090041803636808), as far as I can tell.

In terms of my own ideas on it: I'm not a huge fan of "show everything by default", but I can see the value in "cursor down when empty shows everything".

**Comment by willmcgugan** [comment]
We might want to have some mechanism to cherry pick the commands we show, just so it doesn't get too large. But I do think they should show when the input is empty.

**Comment by davep** [comment]
Picking this up... defining characteristics of the enhancement request so far:

- All applicable hits start to trickle into the display the moment the command palette opens.
- Some method of deciding what is an applicable hit needs to be decided and added.

My initial feeling is that the bulk of the work here is around deciding and implementing the latter; my gut reaction is that one or more of the following could be approaches (just thinking out loud before diving back into the code):

- It could be left totally up to the providers; if given a empty string to search for, they could decide what to yield up.
- It could be left totally up to the providers; but instead there's a method that's parallel to `Provider.search` that is more like `Provider.default` or something, and this yields up all of the commands the provider wants to provide by default.
- It could be left totally up to the providers; but it's a on/off switch at the provider level that says if it wants to take part in providing default hits.

One question stands out right away:

- What ordering to use when there's no match score to go off.

Seems that alphabetical order would make sense.

**Comment by darrenburns** [comment]
> What ordering to use when there's no match score to go off.

Could we use the order that would be used when the search value is `""`?

**Comment by davep** [comment]
That would mean that every `Hit` has a score of either 0 or 1 (not sure which would make more sense I guess), so the order is probably going to be the speed with which they come in. Not sure that quite makes sense (or rather, it does, but might not be useful)?

**Comment by willmcgugan** [comment]
Do we really want to search? I was thinking each provider would offer up some text that tells the user what it accepts.

Like ("Help", "Show the help screen.") or ("open FILENAME", "Open a file.")
