### ISSUE TITLE
[CSS Branch] TypeError in _style_properties.py

### ISSUE THREAD

**Issue by lllama** [Textualize/textual#413]
On line 645:
```python
return cast(tuple[str, ...], obj.get_rule(self.name, ()))
```
the call to `cast` raises a `TypeError` on python 3.8 and lower. Bumping to python 3.9 removes the error. Raising the issue as `pyproject.toml` has python 3.7 or newer specified.

**Comment by tusharsadhwani** [comment]
You can simply stringify the cast argument:

`cast('tuple[...]', ...)`

**Comment by lllama** [comment]
Done in #415

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
