### ISSUE TITLE
check error in the "textual colors" app

### ISSUE THREAD

**Issue by traveller1011** [Textualize/textual#4164]
1. Running the command ```textual colors``` opens a useful demonstration app (wish I had found this sooner). 

2. Within this color demo app, it the "boost" group colors all look the same to me:

![image](https://github.com/Textualize/textual/assets/93844523/1dc97809-8354-40f5-8d3f-5bd4320a853c)

**Comment by TomJGooding** [comment]
Thanks for your issue. `$boost` will look different on different backgrounds [as noted in the Theme Reference docs](https://textual.textualize.io/guide/design/#theme-reference), see also the previous issue about this:

- #3649

**Comment by traveller1011** [comment]
ah, apologies for the duplicate issue. i did try in both powershell and command prompt and got the same result. so i suppose i will not rely on boost in my programs. thank you much Tom.

**Comment by traveller1011** [comment]
in a situation like this should I close the issue? im a hermit and dont know what the social norms are!

**Comment by TomJGooding** [comment]
No apology needed, I just spend too much time here so remembered seeing this come up before!

I didn't mean to dissuade you from using `$boost`, in fact you'll find this style in many Textual widgets. Probably the lighten and darken variants aren't useful though, if I've understood the linked issue correctly.

Feel free to close this issue unless something isn't clear?

**Comment by traveller1011** [comment]
I meant to say I would not rely on $boost _variants_. And okay sweet, i will close the issue and do the same in future equivalent situations. ty and good day to you!
