### ISSUE TITLE
No display on non-UTF8 locale

### ISSUE THREAD

**Issue by jose1711** [Textualize/textual#4168]
This is related to #4156 which is easily reproducible on Linux hosts.
```
LANG=en_US.iso88591 python -m textual
```
Instead of a demo a black screen is shown. Ctrl-Q works to quit the application. Other terminal applications I tried are all able to run but - as expected - there are rendering issues:
a screenshot from file manager `vifm`:
![obrázok](https://github.com/Textualize/textual/assets/1406222/c33433eb-8fe5-4411-82e7-34bd423d0c12)

I believe textual should handle such cases more gracefully (either display a warning and refuse to run or continue with a semi-broken display).

**Comment by willmcgugan** [comment]
Works find with latest Textual. Assuming fixed.
