### ISSUE TITLE
Stop `TextArea` cursor moving beyond end of line in `read_only` mode?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4173]
This is really only a small issue, but when the `TextArea` is in read-only mode should the cursor move beyond the end of the line[^1]?

I would expect navigation in read-only mode to navigate only the raw "document-space",  similar to Normal mode in Vim.

![image](https://github.com/Textualize/textual/assets/101601846/c7094156-b52b-4d8a-9a70-16d3cec654ca)

<details>
<summary>Example code</summary>

```python
from textual.app import App, ComposeResult
from textual.widgets import TextArea


class TextAreaExample(App):
    def compose(self) -> ComposeResult:
        yield TextArea(
            "You shall not pass!",
            read_only=True,
        )

    def on_mount(self) -> None:
        self.query_one(TextArea).cursor_blink = False


if __name__ == "__main__":
    app = TextAreaExample()
    app.run()
```

</details>

[^1]: By "end of the line" I mean the last character in the text, as I know this has a different meaning in the TextArea Document!

**Comment by darrenburns** [comment]
I think I typed out a response a couple of weeks ago, but apparently I didn't send it!

If you can't move the cursor beyond the end of the text when in read-only mode, you wouldn't be able to select the final character in the line. This would mean, for example, if you had a subclass which you used pyperclip in to copy text to the clipboard, you would no longer be able to select the final character.

**Comment by TomJGooding** [comment]
Ah, I would actually expect the selection to include the character under the cursor block.

I just tried VSCode with a block cursor and see this doesn't though. Is this what the `TextArea` was based on? This behaviour seems a bit strange to me [and apparently I'm not the only one](https://github.com/microsoft/vscode/issues/202373).

**Comment by darrenburns** [comment]
I used Jetbrains IDEs as the primary reference, and sometimes VSCode. The cursor behaves the same way in both of them, and to be honest I'm surprised that people are calling the VSCode behaviour a bug - it feels "right" to me. I never considered that people might expect a "block" cursor to behave in a different way from the common "vertical line" cursor. I think it's mostly just down to what you're used to working with.

**Comment by TomJGooding** [comment]
> I think it's mostly just down to what you're used to working with.

You're probably right, vim might be the odd one out with the "inclusive" selection behaviour. Thanks Darren for your reply, closing this now.
