### ISSUE TITLE
`grid-rows: auto` seems to be broken when `column-span`/`Pretty` is used

### ISSUE THREAD

**Issue by mzebrak** [Textualize/textual#4179]
Looks like there is a rendering issue when `column-span` (or `Pretty` widget) is used together with `grid-rows: auto`.

Consider such a  example:

```python
from __future__ import annotations

from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.containers import Grid
from textual.widgets import Footer, Pretty, Static


class MyGrid(Grid):
    """A simple grid with 2 columns and 2 rows."""


class MyApp(App):
    BINDINGS = [
        Binding("a", "add", "Add a new item"),
    ]

    DEFAULT_CSS = """
    MyGrid {
        height: auto;
        grid-rows: auto;
        grid-size: 2;
        grid-gutter: 1;
        background: green;
    }

    Pretty {
        background: red;
    }

    Static {
        background: blue;
    }
"""

    def compose(self) -> ComposeResult:
        with MyGrid():
            yield Pretty(["Something that should have colspan=2"])
            yield Static("")
            yield Static("I want this")
            yield Static("... in a single row")
        yield Footer()

    def action_add(self):
        pretty = self.query_one(Pretty)
        before = pretty._renderable._object
        pretty.update([*before, before[0]])


MyApp().run()
```

Results (correctly) in:

![image](https://github.com/Textualize/textual/assets/73518558/e2521b70-c2d8-4f43-9aed-333a3c12fe5e)
![image](https://github.com/Textualize/textual/assets/73518558/dd913fb4-78d9-4a7c-906c-c4100b4dbb92)

But not quite correct when we change the terminal size a bit (adds a lot of free green space):

![image](https://github.com/Textualize/textual/assets/73518558/dd3e7b78-11b6-4b5b-9ae6-0a6849d9a661)

When using column-span:

```python
from __future__ import annotations

from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.containers import Grid
from textual.widgets import Footer, Pretty, Static


class MyGrid(Grid):
    """A simple grid with 2 columns and 2 rows."""


class MyApp(App):
    BINDINGS = [
        Binding("a", "add", "Add a new item"),
    ]

    DEFAULT_CSS = """
    MyGrid {
        height: auto;
        grid-rows: auto;
        grid-size: 2;
        grid-gutter: 1;
        background: green;
    }

    Pretty {
        column-span: 2;
        background: red;
    }

    Static {
        background: blue;
    }
"""

    def compose(self) -> ComposeResult:
        with MyGrid():
            yield Pretty(["Something that should have colspan=2"])
            yield Static("I want this")
            yield Static("... in a single row")
        yield Footer()

    def action_add(self):
        pretty = self.query_one(Pretty)
        before = pretty._renderable._object
        pretty.update([*before, before[0]])


MyApp().run()
```

Results (correctly) in:

![image](https://github.com/Textualize/textual/assets/73518558/ffcaca13-ca9d-4fe9-8791-c2b726d80b71)

But incorrectly when we add something (adds extra green space):
![image](https://github.com/Textualize/textual/assets/73518558/7bc4ccff-4160-4d49-99ea-a5c2512d1d2d)
![image](https://github.com/Textualize/textual/assets/73518558/53dbef99-7c0c-4760-ba21-22fbabae8398)

**Comment by willmcgugan** [comment]
Actually, @rodrigogiraoserrao This may be the fix https://github.com/Textualize/textual/pull/4219

Would you mind confirming, and adding a snapshot test? The code on this issue is probably good enough, if you find a terminal size where it breaks.

**Comment by rodrigogiraoserrao** [comment]
> Would you mind confirming, and adding a snapshot test? The code on this issue is probably good enough, if you find a terminal size where it breaks.

Done
