### ISSUE TITLE
SyntaxWarning for loading indicator widget

### ISSUE THREAD

**Issue by charles-001** [Textualize/textual#4188]
I receive this warning after upgrading to `0.52.0`:

```
/Users/cthompson/Library/Caches/pypoetry/virtualenvs/dolphie-z84eXs3q-py3.11/lib/python3.11/site-packages/textual/widgets/_loading_indicator.py:57: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.app.animation_level is "none":
```

https://github.com/Textualize/textual/blob/main/src/textual/widgets/_loading_indicator.py#L57

Seems we just need to change `is "none"` to `== "none"`

**Comment by willmcgugan** [comment]
Let's fix this and get a patch release out today
