### ISSUE TITLE
Provide a method to unmount and mount current Screen or Widget for python hot-reload

### ISSUE THREAD

**Issue by xtay** [Textualize/textual#4218]
I'm working on a giant app...

It takes minutes to launch and so many clicks to navigate to the screen which I'm working on.
But live-mode provided by textual-dev only enables the **hot-reload of css files**.

It would be much much better if the **python code itself could be hot-reload** too...

so i found a way to use [jurigged](https://github.com/breuleux/jurigged) with textual,

```
if __name__ == "__main__":
    jurigged.watch("./super_app", poll=True)
    app.run()
```
and then run with command
```
textual run --dev ./super_app/main.py
```

everything works like a charm (things like butten event handlers has been reloaded successfuly), **except the UI content never changes accordingly**...

my workaround is to manually pop and push a new screen so that the UI would be reconstructed. but this ruins the SCREENS / MODES functionality provided by textual itself.

so, it would be greate if there is a `Screen.remount()` or something alike. (`Screen.refresh()` can't do the work...)

**Comment by willmcgugan** [comment]
There is also [watchfiles](https://github.com/samuelcolvin/watchfiles).

I think you would be better off with an environment variable that puts your app in a state you want to test. The way "jurigged" hot patches code, is not something I would expect to work in moderately complex apps, not just Textual.
