### ISSUE TITLE
Align center middle not working correctly with scrollbars

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#422]
With the CSS below on the uber.py example, the content gets pushed behind the scrollbar. There is an unexpected space on the left hand side.
```
#uber1 {
  layout: vertical;

  background: dark_green;
  overflow: hidden auto;
  border: heavy white;
}

.list-item {
  height: 8;
  align: center middle;
  background: dark_blue;
}
```

<img width="689" alt="image" src="https://user-images.githubusercontent.com/5740731/165308917-a51d2f79-a542-4883-93c0-75a4559e8294.png">

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
