### ISSUE TITLE
`Select` `OptionHighlighted` message leakage

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4224]
The `Select` widget makes use of `OptionList`; when the user opens the `Select` to pick a value, `OptionHighlighted` messages "leak" out of the `Select`. This could result in unexpected messages for the developer who has an `OptionList` and a `Select` in their DOM and who doesn't expect to actually have two `OptionList`s that might send messages.

I think we should either stop the `OptionHighlighted` from bubbling outside of the `Select`, or we should turn them into `SelectionHighlighted` if it's felt necessary that they can be handled.

To illustrate:

```python
from textual import on
from textual.app import App, ComposeResult
from textual.widgets import OptionList, Select, Log

class LeakySelectApp(App[None]):

    def compose(self) -> ComposeResult:
        yield Log()
        yield OptionList(*(f"This is option {n}" for n in range(10)))
        yield Select[int](((f"This is selection {n}", n) for n in range(10)))

    @on(OptionList.OptionHighlighted)
    def log_some_option(self, event: OptionList.OptionHighlighted) -> None:
        self.query_one(Log).write_line(f"{event}")

if __name__ == "__main__":
    LeakySelectApp().run()
```

I think the dev would reasonably expect to *only* get calls to `log_some_option` from the `OptionList` they composed in.

**Comment by willmcgugan** [comment]
I think we should quell those messages. I can't see a use for an additional message that reports what the user has currently selected.
