### ISSUE TITLE
Errors in devtools on startup - possibly related to tooltip cleanup

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4225]
I can't reproduce this, but I on launching a Textual app on the `main` branch I got a bunch of errors:

```
error publishing signal to Screen(id='_default') ignored; No widget under screen coordinate (110, 12)
```

I think these arrived before I interacted with the code at all. The code didn't explicitly use any tooltip functionality.

From @davep in Slack: I take it back, it will be that [tooltip clearing] code. `Screen._maybe_clear_tooltip` should catch whatever exception `get_widget_at throws`; that’ll be it. Name in log still a good idea though.

**Comment by davep** [comment]
>Name in log still a good idea though.

This part referring to the fact that `Signal` has a `name` but the code that logs the error isn't including the name on the log.
