### ISSUE TITLE
Disabled widgets prevent mouse scrolling

### ISSUE THREAD

**Issue by xavierog** [Textualize/textual#4242]
# Context

My application used to disable entire Collapsible Contents, which is how I noticed this issue in the first place.

Notes:

- in this issue, "scrolling" and "scroll using the mouse" are both short for "scrolling using the mouse scroll wheel or any similar device"
- this issue is similar to https://github.com/Textualize/textual/issues/1912 but applies to enabled containers.

# Expectations

When an enabled scrollable container contains disabled widgets, disabled widgets should not prevent scrolling the container.

# Current behaviour

The MRE below reflects the issue. It alternates enabled and disabled widgets in a way that prevents effective scrolling.

![textual-scroll-mre](https://github.com/Textualize/textual/assets/18504173/747e5063-a4bc-485d-bf23-0638dfad9d27)

```python
#!/usr/bin/env python3
from textual.app import App, ComposeResult
from textual.widgets import Static

class MyBoringWidget(Static, can_focus=True):
    DEFAULT_CSS = "MyBoringWidget { height: 90%; background: $primary; border: tall yellow; }"

class ScrollMRE(App):
    DEFAULT_CSS = "Static { text-align: center; }"
    def compose(self) -> ComposeResult:
        instructions = 'Place your cursor in the middle of the app and try scrolling to the bottom using the mouse'
        yield Static(instructions)
        for i in range(10):
            yield MyBoringWidget(disabled=bool(i%2))
            yield Static(instructions)

if __name__ == "__main__":
    app = ScrollMRE()
    app.run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.52.1 |
| Rich    | 13.7.0 |

## Python

| Name           | Value                                              |
|----------------|----------------------------------------------------|
| Version        | 3.11.8                                             |
| Implementation | CPython                                            |
| Compiler       | GCC 13.2.0                                         |
| Executable     | ~/whatever/venv/bin/python3 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.6.15-amd64                                        |
| Version | #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2 (2024-02-04) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | tmux (3.4)     |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=232, height=54 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 232                  |
| is_terminal    | False                |
| encoding       | utf-8                |
| max_height     | 54                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
Scrolling with the scrollbar works. This issue relates to scrolling with the wheel / gestures.

**Comment by xavierog** [comment]
Now that the fix is available in `main`, I confirm the issue no longer happens on my side (tested with both the MRE  and my application). Thanks for your work.
