### ISSUE TITLE
Discord invite link not working

### ISSUE THREAD

**Issue by msafi** [Textualize/textual#4246]
When I click on the Discord invite link, I see this

<img width="1253" alt="image" src="https://github.com/Textualize/textual/assets/4027731/acd33136-e092-494a-8c46-a4985001286f">

According to a quick Google search, it means the invite link has expired.

**Comment by willmcgugan** [comment]
Where did you get the Discord link?

**Comment by davep** [comment]
@msafi We still have people joining the server and have had since you first reported this. Also, I've just this moment had someone who wasn't a member follow the link and join just fine. I also don't see anything in the admin page for the server to suggest the invite has expired.

**Comment by msafi** [comment]
My bad. Something was wrong with my account. I fixed my Discord login and tried again, now it works. Thanks!

**Comment by willmcgugan** [comment]
No worries @msafi Welcome to the Discord!
