### ISSUE TITLE
Intermittently failing test (`test_pilot.py::test_pilot_target_on_widget_that_is_not_visible_errors`)

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4269]
Recently, on occasion, I've seen this fail in CI:

![Screenshot 2024-03-07 at 09 43 24](https://github.com/Textualize/textual/assets/28237/c9de1b4b-07d3-4fde-834a-fee289c41576)

So far a subsequent run has gone through fine.

[This seems to be the problem test](https://github.com/Textualize/textual/blob/f7460829c333ca3c913768b6719f12223097e52a/tests/test_pilot.py#L272-L281).

**Comment by TomJGooding** [comment]
I've not seen this test fail in CI recently, though not sure what may have fixed it!

**Comment by willmcgugan** [comment]
Haven't seen this in a long time. Assumed fixed.
