### ISSUE TITLE
TextArea CTRL-k behavior request

### ISSUE THREAD

**Issue by BillScherer** [Textualize/textual#4277]
Requesting CTRL-k (C-k) behavior be modified as follows.

C-k currently does not kill new lines, and on a line with printable content, this is correct. On a line with only a newline, C-k *should* kill the new line. This will allow the TextArea user to kill multiple lines simply with repeated application of C-k. The current behavior of never killing a newline requires more effort that in it should. Thanks!

**Comment by davep** [comment]
While I agree this would make sense, meanwhile, you could possibly go with something like this in your app:

```python
from textual.app import App, ComposeResult
from textual.widgets import TextArea

class TextAreaEx(TextArea):
    """Extended TextArea."""

    def action_delete_to_end_of_line(self) -> None:
        if self.selection.end != self.get_cursor_line_end_location():
            super().action_delete_to_end_of_line()
        else:
            self.action_delete_line()

class CtrlKApp(App[None]):

    def compose(self) -> ComposeResult:
        yield TextAreaEx()

if __name__ == "__main__":
    CtrlKApp().run()
```

**Comment by BillScherer** [comment]
Thanks! I'll give that a try.

**Comment by BillScherer** [comment]
That works perfectly. Thanks again!

**Comment by willmcgugan** [comment]
This feels like it should be the default behaviour.

**Comment by BillScherer** [comment]
This is how it works in Emacs

**Comment by davep** [comment]
`(1+ team-emacs)`
