### ISSUE TITLE
Command palette for searching through actions/keybindings

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#429]
We're going to have a bunch of keybindings/actions available in the average Textual App. These actions could be put into a command palette. Users of a Textual app could press a standardised keybinding to pull up the command palette, and fuzzy search through available keybindings.

The command palette could contain the keybind, help text, widget it's associated with.

The palette could also contain the widgets and allow users to filter widgets and shift focus to one of the widgets. For example, in a text editor with two widgets, the command palette might contain additional options:

* Switch focus to File Tree
* Switch focus to Editor

This could be built on top of a reusable widget for fuzzy searching data and displaying the results in a list. This would allow users to re-use the widget for e.g. "fuzzy file search" widgets and other things.

This would help differentiate Textual applications by providing a globally useful feature. It would also aid learning and discoverability of features. For example "I can't remember the dark mode toggle keybind" - so you open the command palette and search for dark, then press enter :)

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
