### ISSUE TITLE
`Placeholder` has no `disabled` `__init__` keyword parameter

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4296]
It is intended that `disabled` is one of the "standard" keyword parameters for widgets in Textual; this seems to have never been added to `Placeholder`.

**Comment by willmcgugan** [comment]
Not sure if a disabled placeholder makes much sense.

**Comment by davep** [comment]
One would hope that it would dim, as per disabled widgets, and if you're laying things out or testing things being able to disable from queries where eventually the `Placeholder` would be swapped out for a widget of the same class or ID is great for testing (which is exactly now I just noticed it).

**Comment by willmcgugan** [comment]
Fair enough. It would be trivial to add.

**Comment by davep** [comment]
As a PS: Turns out it doesn't dim; as the global dimming style seems only to be aimed at widgets that can receive focus. Might be worth taking that into account too.
