### ISSUE TITLE
Did you Mean?

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#431]
I'm a big fan of when software detects typos and offers suggestions.

We should have a function in the project which uses [Levenshtein Word distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to offer suggestions when a symbol is not found.

The first application of this should probably be CSS declarations. i.e. if I use the UK spelling of "colour" it the error would contain a message to the effect of `Did you mean "color" ?`

However I would imagine there are multiple uses for this.

IIRC there is a routine in the standard library that already does this. Might want to google for that.

**Comment by darrenburns** [comment]
The thing that I know of that could handle this in the stdlib is `difflib` - when you match two sequences you can ask for a "similarity ratio" back from the SequenceMatcher. There might be other things in the stdlib too though :)
