### ISSUE TITLE
Custom exception handler/pretty printer exits with code 0

### ISSUE THREAD

**Issue by WinFan3672** [Textualize/textual#4325]
When the Textual app crashes, a custom exception printer displays the error. While it looks fancy, it has one major flaw. The program ends up exiting normally (with exit code 0), instead of something like exit code 1. This is bad. It makes scripts think the command run successfully, so things like Bash's double-pipe (`||`) just don't work.

Fixing this is as simple as adding the following code:
```
exit(1)
```

To the place where that exception gets pretty-printer. It's so simple that I'd do it myself and make a pull request, but I'm not familiar with textual's codebase enough to take a stab at it.

**Comment by willmcgugan** [comment]
It's not the responsibility of a library such as Textual to explicitly end the process. It is up to the app developer to decide when to exit, and what the return code should be.

See the following note on return codes.

https://textual.textualize.io/guide/app/#return-code

**Comment by WinFan3672** [comment]
I think you misunderstood the issue. The app has crashed, meaning an exception has been raised. Textual then formats the exception, but acts like the process exit normally. **This is not normal behaviour**. Although, yes, it isn't Textual's job to exit, that doesn't mean it should misreport an error as a normal exit.
