### ISSUE TITLE
Button doesn't render Rich Markup correctly

### ISSUE THREAD

**Issue by goblin** [Textualize/textual#4328]
If I'm reading the docs correctly, the `Button` widget *should* accept Rich Markup for its `label`, but in 0.53.1, it doesn't seem to do this.

Here's my test app:

```python3
from textual.app import App
from textual.widgets import Button, SelectionList
import sys

class MyApp(App):
	def compose(self):
		if len(sys.argv) > 1:
			yield SelectionList(('one', 1), ('two', 2))
		yield Button(label='[red]hell[/]o')

MyApp().run()
```

And here are my findings regarding versions:

# Textual 0.39.0 and 0.40.0
## Two `Widget`s
If run with any argument, the app behaves exactly as expected, i.e. renders red "hell" and uncolored "o":

![v0 40 0-double](https://github.com/Textualize/textual/assets/2834/9314ddad-b92f-4214-a6af-b757096bd2fe)

## One `Widget`
However if the Button is the only thing to be rendered, i.e. when you run it without any arguments, then the meaning of "red" becomes somehow inverted:

![v0 40 0-single](https://github.com/Textualize/textual/assets/2834/34e32234-9c1a-463b-90e8-de9a9f0bae36)

# Textual 0.41.0 – 0.51.3
## Two `Widget`s:
Here markup seems totally ignored:
![v0 41 0-double](https://github.com/Textualize/textual/assets/2834/9405bc18-9329-4a89-8303-92a5948982d7)

## One `Widget`:
When run without arguments, we still see the inverted text, even in the latest version:
![v0 41 0-single](https://github.com/Textualize/textual/assets/2834/a5155529-db4a-4301-9ad3-d2770a686070)

# Thoughts
I would like to add Rich Markup to `Button` labels to indicate hotkeys for those buttons nicely, however for some reason latest version doesn't let me do that. How can I get Rich Markup to work on `Button` labels?

What causes the weird inversion behaviour depending on how many `Widget`s the app is rendering, is that normal?

Am I doing something else wrong?

# Diagnostics
My `textual diagnose` output (on version 0.53.1):

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.53.1 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                            |
|----------------|--------------------------------------------------|
| Version        | 3.11.2                                           |
| Implementation | CPython                                          |
| Compiler       | GCC 12.2.0                                       |
| Executable     | /home/goblin/venv/bin/python3 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.1.0-11-amd64                                      |
| Version | #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=80, height=24 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 80                  |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 24                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by goblin** [comment]
FYI, I was running everything in a `venv` and only changing the version of `textual` with things like `pip install textual==0.40.0`. Rich and everything else remained the same throughout my runs (Rich is on 13.7.1).

**Comment by TomJGooding** [comment]
The reason for the difference when the `Button` is the only widget is that it will have focus:

https://github.com/Textualize/textual/blob/5170a64bb2271924ca7a6b8650177119b925029f/src/textual/widgets/_button.py#L53-L54

The missing Rich markup looks like it _might_ be a regression after #3539.

**Comment by goblin** [comment]
Focus is such an obvious thing I didn't think of, thanks!

The point of using Rich markup in the label was to show hotkeys in a different colour, i.e. have `c` be in a different color in a string like `'([green]c[/])onfirm'`. I am now also wondering if it's possible to specify a CSS class for a *part* of a `Button` label: instead of a direct "green" colour, specify a CSS class, similarly to `<span class="hotkey">c</span>onfirm`. This should make it easier to add themes later. Is this doable? Can I maybe glue up a TextType from various subtexts of different CSS classes?

**Comment by TomJGooding** [comment]
Sorry but you've lost me there as Textual CSS works at the widget level,. I think using Rich markup is probably the right approach, but there's been a few changes to how the `Button` is rendered since v0.40.0 and it seems the markup isn't properly taken into account.

**Comment by goblin** [comment]
OK, if it works at the widget level then styling parts of a label doesn't make sense. Sorry for confusion, thanks for the answer.

So yeah, the main issue here is with the regression introduced somewhere around v0.41.0.
