### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by valentingregoire** [Textualize/textual#4348]
https://github.com/Textualize/textual/blob/9550f0b83b10c33ec94ce9687bc8861c49ded8b7/docs/guide/animation.md?plain=1#L3

**Comment by davep** [comment]
A little bit more detail (perhaps pointing out the typo) would be helpful. Or feel free to [PR the fix](https://github.com/Textualize/textual/blob/main/CONTRIBUTING.md).
