### ISSUE TITLE
Merlin example app broken

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#4354]
The merlin example app is broken, likely because of recent changes to the way widths are resolved.

The problem is that there is no way to have a container with two children, with the container having its size set to `auto` and one of the children saying “be as large as the container” while the container hugs the other child widget.
(I think @davep merged a related PR recently but I can't seem to find it.)

In the merlin app, the issue is in the `SwitchLabel` widget.
The switch label widget contains a switch and we want the label to be as wide as the switch so that we can centre the label but there's no way of making the label automatically as wide as the switch without fixing both widths to a fixed absolute value.

After fixing the merlin example app we can merge #4036 that adds the example apps to the tests.

**Comment by davep** [comment]
You might be looking for the interim fix I did on Trogon? Frogmouth has similar issues too (doubtless other apps, not just our own). 

@willmcgugan has been mulling over the problem; perhaps either to roll back the change that caused this, or to come up with a different approach to this sort of layout.

**Comment by davep** [comment]
Given this affects a few things across different repos I've added #4360 as a metaissue that they can all tie back to and which folk can be pointed at if they run into this.

**Comment by TomJGooding** [comment]
Just to confirm the Merlin example looks good now on v0.55.0 following #4369:

![image](https://github.com/Textualize/textual/assets/101601846/8d18f1ef-7198-4f83-be4a-3bf3bf1c95b0)
