### ISSUE TITLE
Inline mode and the command palette don't play well together

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4385]
As of Textual v0.55.1, if you run an application in inline mode, and then call on the command palette, the result isn't a great experience. For example, using the code from the HOWTO on styling inline applications:

https://github.com/Textualize/textual/assets/28237/c1be9519-92f8-4cec-813f-8bd3ca0d7ebf

**Comment by TomJGooding** [comment]
I've just tested this with the same demo on v0.56.0 just released, while it definitely now looks better than Dave's recording, I'm afraid the command palette will flicker when the clock is updated:

https://github.com/Textualize/textual/assets/101601846/81b29b25-87f8-4c59-8b6f-7cc44a0774e4
