### ISSUE TITLE
Adding columns to empty `DataTable` won't appear?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4386]
I'm not sure if this is a bug or possibly the intended behaviour for a empty DataTable (i.e. without rows).

Try pressing the <kbd>c</kbd> key with the app below to add new columns to the `DataTable` - notice they won't appear. Then press the <kbd>r</kbd> key to add a new row, then all columns will show.

EDIT: Actually this isn't specific only to an empty table, but rather new columns won't appear if there isn't any row with corresponding data in that column. Is that intentional?

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable, Footer


class ExampleApp(App):
    BINDINGS = [
        ("c", "add_column", "Add Column"),
        ("r", "add_row", "Add Row"),
    ]

    column_number = 1

    def compose(self) -> ComposeResult:
        yield DataTable()
        yield Footer()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.add_column(f"Column #{self.column_number}")
        self.column_number += 1

    def action_add_column(self) -> None:
        table = self.query_one(DataTable)
        table.add_column(f"Column #{self.column_number}")
        self.column_number += 1
        self.notify("No column added?", severity="error")

    def action_add_row(self) -> None:
        table = self.query_one(DataTable)
        table.add_row()
        self.notify("Now columns appear!", severity="information")


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by TomJGooding** [comment]
Possibly related is #3449 where again perhaps the updates to column widths aren't being triggered?

**Comment by arcivanov** [comment]
I have worked around this via flipping `show_header` to `True` from `False`.

**Comment by TomJGooding** [comment]
Thanks @willmcgugan, confirmed this works in Textual v0.70.0! Sorry I could have sworn I tried incrementing the `_update_count`...
