### ISSUE TITLE
Relative links in docs are not correct

### ISSUE THREAD

**Issue by valentingregoire** [Textualize/textual#4389]
In some places in the docs, relative links to other pieces in the docs are incorrect: 

* https://textual.textualize.io/styles/links/link_style/: link[`<text-style>`](https://textual.textualize.io/styles/css_types/text_style)
* https://textual.textualize.io/styles/links/link_style_hover/: link [`<text-style>`](https://textual.textualize.io/styles/css_types/text_style)
* ...

It seems that all links that are in sub folder that pointing to a relative location yield a `404` (redirected to the `404` page).

**Comment by valentingregoire** [comment]
Fixed in: https://github.com/Textualize/textual/pull/4390

Also fixed typo `bakcground` to `background`.

**Comment by valentingregoire** [comment]
> It would be helpful to know how they're incorrect? What exactly are you seeing that is incorrect?

@davep, just click the links and you'll see. All relative links of documents inside a folder are impacted it seems.

**Comment by davep** [comment]
I clicked both the links *before* asking for clarification.

**Comment by willmcgugan** [comment]
@davep The links @valentingregoire is referring to are in those pages, in the Syntax section. The links in the description are fine.

**Comment by valentingregoire** [comment]
I have recreated the links in the description of this issue, just like they are displayed in the docs section where I am pointing at.

**Comment by davep** [comment]
> in the Syntax section

Thanks @willmcgugan -- I'd initially clicked every possible link I could find before originally asking for clarification, but hadn't even registered that that was a link in the syntax section.
