### ISSUE TITLE
Is inline mode currently supported on Windows?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4409]
If not perhaps worth adding a note in the docs?

**Comment by Zaloog** [comment]
@TomJGooding to my knowledge its not supported, cause it relies on termios, which is not available for windows.

**Comment by dontascii** [comment]
Might want to add a note about the lack of windows support in a few other places in the docs.  If you use the docs search feature and search for "inline", the first several pages that match do not mention the lack of windows support.  Thanks!
