### ISSUE TITLE
Wrap overloads with `if TYPE_CHECKING`

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4431]
The `@overload` decorator incurs a small performance penalty.

If we wrap overloaded methods with `if TYPE_CHECKING` we can save a little import time.

Pointed out by @bswck https://github.com/willmcgugan/declare/pull/3

**Comment by bswck** [comment]
Feel free to assign me! I'll be happy to help.

**Comment by willmcgugan** [comment]
Much appreciated!
