### ISSUE TITLE
textual-web embedded demos in the docs don't appear to work

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4432]
I was just pointing someone at the inline textual-web-based examples in the docs and they seem to be failing, with a start of them instantly showing:

![Screenshot 2024-04-19 at 15 30 07](https://github.com/Textualize/textual/assets/28237/44a4afd6-f35c-4d56-ba99-29e9b3f75d59)

(as of the time of writing).

Pinging @willmcgugan in case something needs a wee nudge on the back end.

**Comment by darrenburns** [comment]
Closing as it appears to be fixed 🤷‍♂️
