### ISSUE TITLE
Width of Static is miscalulated when markup is used

### ISSUE THREAD

**Issue by valentingregoire** [Textualize/textual#4447]
When adding markup to a text in a `Static` (`markup=True`), then the width of the text is based on the content with the style characters.

Example without markup:
![image](https://github.com/Textualize/textual/assets/32612304/5485d76b-b083-4926-8225-08237809188d)

Example with markup:
![image](https://github.com/Textualize/textual/assets/32612304/044d3758-1246-4977-befd-3ee9c71a7dca)

I think the width is calculated by the amount of characters (columns) before parsing. Perhaps if `markup=True`, the width can be calculated after parsing?

**Comment by valentingregoire** [comment]
Version info:

```
rich              13.7.1 Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
textual           0.54.0 Modern Text User Interface framework
textual-dev       1.5.1  Development tools for working with Textual
```

**Comment by TomJGooding** [comment]
Thanks, could you possibly provide a minimal reproducible example (MRE): i.e. a short piece of code that can reproduce the issue?

**Comment by valentingregoire** [comment]
Here you go:

```py
from rich.style import Style
from textual.app import App, ComposeResult
from textual.widgets import Static


class BorkedApp(App):
    """The main application class for the Songbook TUI."""

    text = "Hello, world!"
    style = Style(bgcolor="#333333", bold=True)
    text_styled = style.render(text)

    CSS_PATH = "app.tcss"
    DEFAULT_CSS = """
        Static {
            width: auto;
            border: round green;
        }
    """
    BINDINGS = [("q", "exit", "Quit")]

    def compose(self) -> ComposeResult:
        """Compose the main application."""
        yield Static(self.text)
        yield Static(self.text_styled)


if __name__ == "__main__":
    app = BorkedApp()
    app.run()
```

Result:

![image](https://github.com/Textualize/textual/assets/32612304/b93d6aff-7069-47ba-9eb5-dccd8389b7b1)

**Comment by valentingregoire** [comment]
This also causes some weird see-through issues with the screen below btw. I can solve that by adding another entire black screen behind, it's just inconvenient, but I might open up a separate ticket for that.

**Comment by valentingregoire** [comment]
You are right, this works well. Styling with `Style` objects is then not what is supposed to be done, thanks for the info!

**Comment by darrenburns** [comment]
@valentingregoire You can style with Style objects e.g. `Text("hello", style=Style(...))`. Then you can shove that inside a `Static` as you were doing before.
