### ISSUE TITLE
Make `cursor_location` a reactive attribute

### ISSUE THREAD

**Issue by joostrijneveld** [Textualize/textual#4457]
I'm using a TextArea to create a fairly specific 'editor' Widget, and would like to constantly report to the user what the location of their cursor is (i.e., offset from the start of the line), like many editors do in the their footer.

Rather than polling the current value of `cursor_location`, it would be nice if this is a [reactive attribute](https://textual.textualize.io/guide/reactivity/) that I can watch for.

**Comment by TomJGooding** [comment]
You might instead watch the `TextArea.selection` which is a reactive attribute:

https://github.com/Textualize/textual/blob/0f62d130f057658a651ef582f23f329ca5b04b97/src/textual/widgets/_text_area.py#L1685-L1691

**Comment by joostrijneveld** [comment]
Excellent! That solved my issue perfectly.
