### ISSUE TITLE
Unfocusing and refocusing the terminal has undesirable scrolling behaviour

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4459]
If I have a widget focused and a tab away from my terminal to do something else briefly, then tab back, the application will refocus the widget and subsequently scroll to the top of it.

This is really jarring when the widget is e.g. a longer piece of text which I'm using as a reference for another task (imagine following a tutorial on the web, and every time you refocus the web page it scrolls back to the top of the page).

When the terminal is refocused, I think we should refocus the previously focused widget WITHOUT scrolling.

**Comment by willmcgugan** [comment]
Fixed in main.
