### ISSUE TITLE
Add information about  ToastRack styling to the toast widget documentation

### ISSUE THREAD

**Issue by mxovd** [Textualize/textual#4473]
There's no mention of the ToastRack widget in the [Toast widget documentation](https://textual.textualize.io/widgets/toast/). It could be useful to mention that styling the ToastRack is necessary to move the position of notifications. Maybe something like this:

If you wish to change the location of Toasts, it is possible by targeting the `ToastRack` CSS type. For example:
```scss
ToastRack {
        align: right top;
    }
```

I can make a PR if it is acceptable.

**Comment by willmcgugan** [comment]
PR would be appreciated!
