### ISSUE TITLE
The introduction to `query_one` is potentially misleading

### ISSUE THREAD

**Issue by davep** [Textualize/textual#4488]
When [`query_one` is introduced in the docs](https://textual.textualize.io/guide/queries/#query-one) it says:

> If you call it with a selector it will return the first matching widget.

This isn't how it works. IIRC it was true for a wee while, in the run up to the release of v0.2; but it hasn't been the case for at least 18 months.

This part should probably either be scrubbed, or it should mention the error that can be raised and perhaps stress that the selector *must* result in a single hit.

**Comment by willmcgugan** [comment]
Thanks. Fixed in main. https://github.com/Textualize/textual/commit/a9e87b59c082326e841627faff3968b958e5309f
