### ISSUE TITLE
Clicking `Select` doesn't properly collapse overlay

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4489]
It looks like there might have been an unintended change to the behaviour of the `Select` widget.

You can reproduce this using the [basic example](https://textual.textualize.io/widgets/select/#basic-example) from the docs. Try clicking the `Select` to expand the overlay, then click it again. This should collapse the overlay, but it now quickly pops back up again.

I haven't dived into details yet but it looks like the relevant commit is ab9ea3f.

**Comment by TomJGooding** [comment]
I don't understand why yet, but I found if you click exactly on the ▲ arrow everything works as expected.

**Comment by willmcgugan** [comment]
I noticed that. Weird. It's something to do with the mechanism that hides the drop down with the widget is blurred. But I haven't dug up any more than that...

**Comment by TomJGooding** [comment]
Comparing the logs from `textual console`, if you click the arrow the `SelectOverlay` seems to be hidden **before** the `Static` arrow is hidden. For reasons I don't understand yet, this means the `Click` event which triggers the `Toggle` message is never actually fired, yet everything works as expected. Whereas clicking anywhere apart from the arrow **also** then fires the `Click` event, causing the overlay to expand again after just being collapsed.
