### ISSUE TITLE
Add the ability to customise scrollbar bar segments

### ISSUE THREAD

**Issue by mon** [Textualize/textual#4500]
Currently, the characters that make up a scrollbar [are hardcoded](https://github.com/Textualize/textual/blob/e21f57529d4e70bf421acb7cb5e7d041a43e5a2f/src/textual/scrollbar.py#L101-L104). It would be nice if they could be overridden. Personally, I need to support poor fonts, so need to replace missing glyphs. But it would be neat to use braille characters for a unique style.

Thoughts on making them a classvar, so they can be monkeypatched in for now? I can do that PR if it's an OK change.

**Comment by willmcgugan** [comment]
You can patch in a new scrollbar renderable as follow:

```python
from textual.scrollbar import Scrollbar

ScrollBar.renderer = MyScrollbarRenderer
```

Have a look at how the [original](https://github.com/Textualize/textual/blob/main/src/textual/scrollbar.py#L72) is implemented. You can copy that and customize it.

**Comment by mon** [comment]
For sure! I was just hoping for an easier way than duplicating the ~72 line render function. Textual is still developing pretty quickly, and I'm wary vendoring too much of its code to fix things.

**Comment by davep** [comment]
@mon For what it's worth, the scrollbar renderer has been in place for well over a year, has been stable as far as I can remember, [and is part of the documented API](https://textual.textualize.io/api/scrollbar/#textual.scrollbar.ScrollBar.renderer).

**Comment by willmcgugan** [comment]
Yeah, that's not going to change. Textual's API is quite stable now.

**Comment by mon** [comment]
That's good to know! I guess then - would a PR changing the bar glyphs to be a classvar be rejected? I still do like the idea of a 3-line way to modify the class.

**Comment by willmcgugan** [comment]
I think that would be reasonable. Happy to accept a PR.
