### ISSUE TITLE
Auto width results in zero-width when applied to `OptionList`

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4506]
It seems like the `virtual_size` might not be getting set correctly inside `OptionList`.

In the app below I'd expect the OptionList to be able to render at the maximum cell width in the child `Lines`.

This app:

```python
from textual.app import App, ComposeResult
from textual.widgets import OptionList

class OptionListAutoWidth(App[None]):
    CSS = "OptionList{ width: auto; }"

    def compose(self) -> ComposeResult:
        yield OptionList(*["one", "two", "three"])

app = OptionListAutoWidth()
app.run()
```

Produces this result:

<img width="82" alt="image" src="https://github.com/Textualize/textual/assets/5740731/08d36859-3583-4cac-8cb2-67e443239c01">

Marking as a bug for now - feel free to update if I'm misunderstand.

**Comment by willmcgugan** [comment]
It's a line API widget. Looks like it is missing a `get_content_width` method.
