### ISSUE TITLE
Footer bindings invisible on app launch

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4550]
If I declare a binding in a widget, it doesn't appear on the new footer until I move my mouse:

https://github.com/Textualize/textual/assets/5740731/85f1132e-c404-4e7c-89c8-886408084363

In the video above, the footer is empty. When the mouse cursor moves, it populates.

MRE:

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import Footer, Input

class MyInput(Input):
    BINDINGS = [Binding("escape", "app.quit", "Exit Elia", key_display="esc")]

class FooterDelay(App[None]):
    def compose(self) -> ComposeResult:
        yield MyInput()
        yield Footer()

app = FooterDelay()
if __name__ == "__main__":
    app.run()

```

**Comment by TomJGooding** [comment]
Looks like the bad commit is 135fab6 -  presumably the `self.mouse_over` check.
