### ISSUE TITLE
Add `isort` to dev dependencies

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4554]
Sorry I would do this myself but I'm not yet familiar enough with poetry.

**Comment by darrenburns** [comment]
Opened a PR for this.

For future reference, to add a development dependency in Poetry you can do:

```bash
poetry add --group dev isort
```

**Comment by TomJGooding** [comment]
Thanks Darren! I did check the Poetry docs but the large diff to the lock file gave me pause!
