### ISSUE TITLE
Bindings in footer sometimes don't update

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4565]
Making this as a note - don't have an MRE yet, but if you tab through widgets sometimes the footer doesn't update until you move your mouse (it shows bindings for the previously focused widget).

**Comment by TomJGooding** [comment]
Here's a quick MRE, tested against Textual v0.63.5. If you ensure the first widget is _definitely focused_ by clicking on the first `FooWidget` with the mouse, then tabbing through the widgets then seems to update the `Footer` as expected.

I suspect this is related to a similar issue I posted in this discussion?

- https://github.com/Textualize/textual/discussions/4549

```python
from textual.app import App, ComposeResult
from textual.widget import Widget
from textual.widgets import Footer


class TestWidget(Widget, can_focus=True):
    DEFAULT_CSS = """
    TestWidget {
        border: tall $background;
        height: 1fr;
    }

    TestWidget:focus {
        border: tall $accent;
    }
    """


class FooWidget(TestWidget, can_focus=True):
    BINDINGS = [("f", "app.bell", "Foo")]


class BarWidget(TestWidget, can_focus=True):
    BINDINGS = [("b", "app.bell", "Bar")]


class BazWidget(TestWidget, can_focus=True):
    BINDINGS = [("z", "app.bell", "Baz")]


class BindingsApp(App):
    def compose(self) -> ComposeResult:
        yield FooWidget()
        yield BarWidget()
        yield BazWidget()

        yield Footer()


if __name__ == "__main__":
    app = BindingsApp()
    app.run()
```


I wonder if perhaps related to this?

= #4549
