### ISSUE TITLE
Style(bgcolor="$success") results in an exception, same with Text("value", "bgcolor: $success")

### ISSUE THREAD

**Issue by arcivanov** [Textualize/textual#4608]
Is it possible to use common variables in constructed Styles and Texts?

**Comment by darrenburns** [comment]
No - those are `Rich` objects and are unaware of Textual CSS.

You could grab the values from the variables like this:

```python
self.app.get_css_variables()
```

Although internally in Textual we generally use [component classes](https://textual.textualize.io/guide/widgets/#component-classes) when bridging from Textual CSS to Rich objects.

**Comment by arcivanov** [comment]
Thank you!
