### ISSUE TITLE
Add feature: TCSS property font-size

### ISSUE THREAD

**Issue by MatixAndr09** [Textualize/textual#4609]
I want to add a TCSS property that changes size of text displayed for example in Static

**Comment by willmcgugan** [comment]
Terminals don't support changing the text size. In most terminals you can zoom with ctrl + plus and ctrl + minus, but that's it.

**Comment by MatixAndr09** [comment]
> Terminals don't support changing the text size. In most terminals you can zoom with ctrl + plus and ctrl + minus, but that's it.

Okay, sorry for opening im stupid LOL

**Comment by willmcgugan** [comment]
It wasn't stupid. Every day is a school day!

**Comment by MatixAndr09** [comment]
Yea
