### ISSUE TITLE
Header Expansion

### ISSUE THREAD

**Issue by MatixAndr09** [Textualize/textual#4611]
Hi everyone!

So I was working on a project using textual, and I saw that 'Header' compared to other elements like 'Button' or 'Static' is neglected. So I want to add a little of work to the Header. First of the icon of the header '⭘' should be customizable so you can enter as an argument to header -> 'yield Header(header_icon='your_icon_here')', second I would change the clock to be possible to show in these formats:

1. Time 24h -> '22:22:22'
2. Time 12h -> '10:22:22 PM'
3. Date Simple + Time 24h -> '05.06 22:22:22'
4. Date Simple + Time 12h -> '05.06 10:22:22 PM'
5. Full Date + Time 24h -> '05.06.2024 22:22:22'
6. Full Date + Time 12h -> 05.06.2024 10:22:22 PM'

so for example you want the **6** format so you do -> 'yield Header(show_clock=True,clock_style="full_date time_12h")'

That's all. I think I can do that my self. Let me know what you think.

**Comment by TomJGooding** [comment]
This issue from some months ago might be relevant here - unfortunately I know the Textual maintainers haven't had the resources to review the `Header` widget as planned.

- #3536

**Comment by ThisModernDay** [comment]
Might be worth noting you can make the time in the Header toggleable between 12hr and 24hr like this

```python
def on_mount(self):
    self.timefmt = False

def render_12hour_format(self):
    return Text(datetime.now().time().strftime("%I:%M %p"))

def render_24hour_format(self):
    return Text(datetime.now().time().strftime("%X"))

def action_toggle_12hr_time(self) -> None:
        self.timefmt = not self.timefmt
        self.query_one('Header HeaderClock').render = self.render_12hour_format if self.timefmt else self.render_24hour_format
```

**Comment by MatixAndr09** [comment]
Okay but what about the icon

**Comment by ThisModernDay** [comment]
It could be done like this.

```python
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer
from rich.text import Text
import random

class MyApp(App):
    BINDINGS = [
        ("ctrl+b", "change_icon", "Change Icon"),
    ]

    def on_mount(self) -> None:
        self.query_one("Header HeaderIcon").render = self.change_button

    def change_button(self):
        return Text("🦕")

    def compose(self) -> ComposeResult:
        yield Header()
        yield Footer()

if __name__ == "__main__":
    MyApp().run()
```

However I suggest you look at the widget files [here](https://github.com/Textualize/textual/tree/main/src/textual/widgets)

I say that because this is how you can learn to tweak things.

I knew I could change the header Icon by looking at the code [here](https://github.com/Textualize/textual/blob/main/src/textual/widgets/_header.py)

the HeaderIcon is a class inside the header so i know that I can find it in a query
