### ISSUE TITLE
The type of dark attribute of class App might be inaccurate. (Reactive[bool] -> bool)

### ISSUE THREAD

**Issue by Haphaistos2333** [Textualize/textual#4614]
Current code in src/textual/app.py:
```
    dark: Reactive[bool] = Reactive(True, compute=False)
```
I personally believe the type of the attribute "dark" should be bool instead of Reactive. (Correct me if I was wrong.)

Reactive class does not implement `__bool__` method, so `Reactive(False)` is actually `True` when casted to bool, which is quite confusing. 
In the code example, the first execution of `self.app.dark = not self.app.dark` is actually setting `self.app.dark` to boolean type `False`, which mean if I initially set `self.app.dark` to `Reactive(False)`, the theme is still light unless I toggle it once.
The code seems not using features of Reactive on dark attribute, so it will be more convincing changing the type to bool.

**Comment by Haphaistos2333** [comment]
Directly setting self.dark to False will raise a type-check lint:
![image](https://github.com/Textualize/textual/assets/34897000/8ab15c41-a25e-4a42-a7ba-a5ad652a167b)

**Comment by davep** [comment]
Dark should be `Reactive` as it is a [reactive](https://textual.textualize.io/guide/reactivity/). Moreover, setting `dark` to `False` has the desired effect with this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Label

class LightApp(App[None]):

    def __init__(self):
        super().__init__()
        self.dark = False

    def compose(self) -> ComposeResult:
        yield Label("This is a light app")

if __name__ == "__main__":
    LightApp().run()
```

I also see no type issues with the code (in this case using pyright):

![Screenshot 2024-06-06 at 14 54 24](https://github.com/Textualize/textual/assets/28237/9a78e0c5-7aaa-4b92-a2f1-84e57573b5a6)

It might be a good idea to say what you're using for type checking, and perhaps with IDE you're using. For example, the type checker in (some versions of?) PyCharm are known to be lacking a little and sometimes can mislead people.

**Comment by willmcgugan** [comment]
Yeah, PyCharm doesn't understand descriptors all that well.  @Haphaistos2333 feel free to report this to the PyCharm folks.
