### ISSUE TITLE
pageup and pagedown bindings not firing on `main` branch

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4632]
Tested with `DataTable` and `TextArea`.

**Comment by willmcgugan** [comment]
Must be an issue with the new keyboard protocol. But I can see them in `textual keys`. What do you get?

**Comment by willmcgugan** [comment]
Oh I think the name may have change. Textual keys repots "page_up", but the bindings are  "pageup".

**Comment by willmcgugan** [comment]
Yeah confirmed. I guess the easiest fix would be to stick with the original name.

**Comment by willmcgugan** [comment]
Pushed to main. Give it a try?

**Comment by darrenburns** [comment]
Working - thanks!
