### ISSUE TITLE
Method to add content to Content Switcher

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4642]
We could use a method to add new content to a ContentSwitcher. At the moment you can call `mount` but you need also need to set `display=False`.

Something like this:

```python
def add_content(self, content:Widget, make_current=False) -> AwaitMount:
    ...
```

**Comment by TomJGooding** [comment]
It looks like you've already pushed this feature to main, but perhaps before/after params similar to `mount` could be useful?

**Comment by willmcgugan** [comment]
Isn't that redundant, if only one child widget is ever visible at a time?

**Comment by TomJGooding** [comment]
Maybe. Perhaps I'm overthinking this, but perhaps the order of the child widgets might matter in some contexts.

```python
 content_switcher = self.query_one(ContentSwitcher)
 first_content = content_switcher.children[0]
 content_switcher.current = first_content.id
````

**Comment by willmcgugan** [comment]
I think in the 99% case, the order doesn't matter. Going to leave that as a "if anyone asks" possible addition.
