### ISSUE TITLE
Add Image support using imgcat

### ISSUE THREAD

**Issue by AM-I-Human** [Textualize/textual#4654]
I know that is on roadmap and I think I can help by suggesting this.
I found this Python package that enable you to see images on the terminal.
It supports Wezterm, so with it you have full resolution images.
https://pypi.org/project/imgcat/

Considering that is python it's possible to take inspiration from it to make it.
This can enable a full markdown previewer for the terminal, I think the neovim community will love this.

**Comment by SkwalExe** [comment]
This uses Kitty's Terminal graphics protocol, which isn't supported by most terminal emulators...

**Comment by nithin-mk** [comment]
> This uses Kitty's Terminal graphics protocol, which isn't supported by most terminal emulators...

No, imgcat uses the iTerm2 Inline Images Protocol, which is supported by many terminals, including VS Code now.
