### ISSUE TITLE
`Tree.select_node` doesn't select the node, it highlights it

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4660]
The Tree message names make a distinction between _highlighting_ a node and _selecting_ a node.

This method name strongly suggests it'll select a node, but in reality it only highlights it (moves the cursor to a node).

I'd suggest renaming to something like `move_cursor(node)`.

**Comment by TomJGooding** [comment]
The docs do say that this will only "move the cursor to the given node", but the method name is a bit confusing.

**Comment by darrenburns** [comment]
True - I think the problem is we're confusing the naming since we have a message called `NodeSelected` which does not get posted here.

I think renaming this to something like `move_cursor(node)` would be clearer.

**Comment by merriam** [comment]
FYI, DataTable carefully delineates hovering, moving, and selecting.   It sounds like it would be good to make the breaking change to rename the message or change its meaning.

**Comment by darrenburns** [comment]
Opened a PR for this in #4753.

- Tree.move_cursor added - which just moves the cursor without selecting.
- Tree.select_node updated to move the cursor to a node and then select it.
