### ISSUE TITLE
Using standard python logger

### ISSUE THREAD

**Issue by takeda** [Textualize/textual#4663]
Is there a reason why textual implements its own logging?

Would it be possible to use standard python logger, and have an option to redirect log via Textual LogHandler? I feel like that would be better, as it is more powerful, allows to pass context variables and most importantly it is standardized.

**Comment by willmcgugan** [comment]
Textual's log methods can log things that aren't necessarily strings.

You can use Python's logging system in your app. You can write to the dev tools with https://textual.textualize.io/guide/devtools/#textual-log, or configure it in any way you wish
