### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by hyhcrh** [Textualize/textual#4665]
As the title depicts. For example, documentation says this: 
```An alternative to a refresh is recompose. If you set recompose=True on a reactive, then Textual will remove all the child widgets and call compose() again, when the reactive attribute changes.```
But I couldn't find this attribute, and when I typed it, the IDE reported accidental arguments.
Then I went into the source code and found that it was renamed to ```repaint```.

Here is another example and I currently can't solve it:
Documentation says this in [this link](https://textual.textualize.io/widgets/footer/#textual.widgets.Footer):
```
ctrl_to_caret = reactive(True)
```
Convert 'ctrl+' prefix to '^'.
将“ctrl+”前缀转换为“^”。

But I couldn't find similar arguments in the source code. What is it? Or it is removed?

Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
Yes

It will be helpful if you run the following command and paste the results:

```
textual diagnose
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.46.0 |
| Rich    | 13.6.0 |

## Python

| Name           | Value                              |
|----------------|------------------------------------|
| Version        | 3.10.10                            |
| Implementation | CPython                            |
| Compiler       | MSC v.1929 64 bit (AMD64)          |
| Executable     | D:\testTUI\venv\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19041 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=120, height=30 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 120                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 30                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
The documentation is up-to-date, but you are using a very old version of Textual. Please update.
