### ISSUE TITLE
Workers report RUNNING state twice

### ISSUE THREAD

**Issue by Joe-TheBro** [Textualize/textual#4670]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
Yes

The worker reports a RUNNING state when PENDING, causing a double report when the worker is actually in a RUNNING state.
![image](https://github.com/Textualize/textual/assets/28988269/8cab4564-6434-4a43-b56a-5adeaeee52db)

There is no error shown on the command line, and TUI launches fine.

I'm wondering if this is the intended behavior, as I wrote some code similar to the code below surrounding the `Worker.StateChanged` event.
```Python
def on_worker_state_changed(self, event: Worker.StateChanged) -> None:
        worker_name = event.worker.name
        worker_state = str(event.worker.state).split(".")[1]
        self.log(event.worker.state)
        match worker_name:
            case "get_arduino":
                match worker_state:
                    case "PENDING":
                        pass
                    case "RUNNING":
                        pass
                    case "CANCELLED":
                        pass
                    case "ERROR":
                        pass
                    case "SUCCESS":
                        pass
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.67.1 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                      |
|----------------|------------------------------------------------------------|
| Version        | 3.12.3                                                     |
| Implementation | CPython                                                    |
| Compiler       | MSC v.1938 64 bit (AMD64)                                  |
| Executable     | \env\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 11         |
| Version | 10.0.22631 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.90.1) |
| TERM                 | *Not set*       |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=159, height=27 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 159                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 27                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
I suspect what you are seeing is that by the time the event is received, the state has change.

The `StateChange` event has a `state` property that contains the state when the event was processed. If you log that, you may find it works as expected.

**Comment by Joe-TheBro** [comment]
I appreciate the quick response. This was exactly what I was looking for. I realize now that when I set `worker_state = event.worker.state`, it was referencing the worker itself. Because that takes time, there is no guarantee that it will be the state advertised in the event. Thanks!
