### ISSUE TITLE
Several command palette issues on 0.71.0

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4705]
I found 3 issues with the command palette in the latest release.

1. The help text doesn't appear for the initial "discovery" hits. When you start to search, the help text starts to appear.
2. There's something wrong with scrolling when you use the keyboard to move the cursor through the option list. In the example below, scrolling seems to break after you've started searching.
3. The initial commands listed (DiscoveryHits) are sorted alphabetically, which seems wrong (I want control over the order - it's easy enough for me to sort my commands if that's what I require). Normal hits from searches are not sorted (as expected).

```python
from typing import Any
from textual.app import App, ComposeResult
from textual.command import DiscoveryHit, Hit, Hits, Provider
from textual.widgets import Label


class MyProvider(Provider):
    @property
    def commands(self) -> list[tuple[str, Any, str]]:
        return [(f"option-{i}", lambda: 1, f"This is option {i}") for i in range(30)]

    async def discover(self) -> Hits:
        for name, runnable, help_text in self.commands:
            yield DiscoveryHit(
                name,
                runnable,
                help_text,
            )

    async def search(self, query: str) -> Hits:
        matcher = self.matcher(query)
        for name, runnable, help_text in self.commands:
            if (match := matcher.match(name)) > 0:
                yield Hit(
                    match,
                    matcher.highlight(name),
                    runnable,
                    help=help_text,
                )


class OptionListScrolling(App[None]):
    COMMANDS = {MyProvider}

    def compose(self) -> ComposeResult:
        yield Label("hey!")


if __name__ == "__main__":
    app = OptionListScrolling()
    app.run()

```

**Comment by TomJGooding** [comment]
> The help text doesn't appear for the initial "discovery" hits. When you start to search, the help text starts to appear.

It looks like you just need a small tweak to your `DiscoveryHit`:

```python
    async def discover(self) -> Hits:
        for name, runnable, help_text in self.commands:
            yield DiscoveryHit(
                name,
                runnable,
                help=help_text,
            )

**Comment by TomJGooding** [comment]
> There's something wrong with scrolling when you use the keyboard to move the cursor through the option list.

From a quick look at the recent changes to the `OptionList`, I'm not sure the "line position for the start of the option" is correctly tracked here?

https://github.com/Textualize/textual/blob/37f0f26f1c9380a9fe45866dd383005686df7839/src/textual/widgets/_option_list.py#L363-L364

If `OptionList

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Context collection made no progress (located the same files again).

Relevant files:
- src/textual/command.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=87.413; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=112.678; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=117.530; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=117.530; matched issue terms: command, palette, 0, found, 3, 1
- src/textual/system_commands.py: path components match issue terms, source file; bm25 rerank score=42.085; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=68.043; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=73.170; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=73.170; matched issue terms: command, palette, 0, help, text, discovery
- examples/color_command.py: matched GitHub code search; bm25 rerank score=53.987; matched issue terms: command, palette, 0, 3, 1, hits; bm25 rerank score=53.987; matched issue terms: command, palette, 0, 3, 1, hits
- src/textual/widgets/_option_list.py: requested by planner next_checks; bm25 rerank score=44.581; matched issue terms: 0, 1, text, doesn, t, initial; bm25 rerank score=44.581; matched issue terms: 0, 1, text, doesn, t, initial
- src/textual/widgets/_tabbed_content.py: path components match issue terms, source file; bm25 rerank score=43.223; matched issue terms: issues, 0, 1, t, initial, when; bm25 rerank score=44.639; matched issue terms: issues, 0, 1, t, initial, when; bm25 rerank score=44.639; matched issue terms: issues, 0, 1, t, initial, when
- src/textual/lazy.py: path components match issue terms, source file; bm25 rerank score=30.855; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=39.838; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=43.454; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=43.454; matched issue terms: several, 0, i, t, appear, when

Attempts:
No patch attempts were made.

Token usage: 30206/100000

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Context collection made no progress (located the same files again).

Relevant files:
- src/textual/command.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=84.724; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=105.471; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=100.195; matched issue terms: command, palette, 0, found, 3, 1; bm25 rerank score=100.195; matched issue terms: command, palette, 0, found, 3, 1
- src/textual/system_commands.py: path components match issue terms, source file; bm25 rerank score=41.812; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=66.715; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=61.764; matched issue terms: command, palette, 0, help, text, discovery; bm25 rerank score=61.764; matched issue terms: command, palette, 0, help, text, discovery
- examples/color_command.py: matched GitHub code search; bm25 rerank score=45.636; matched issue terms: command, palette, 0, 3, 1, hits; bm25 rerank score=45.636; matched issue terms: command, palette, 0, 3, 1, hits
- src/textual/lazy.py: path components match issue terms, source file; bm25 rerank score=31.255; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=41.150; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=41.171; matched issue terms: several, 0, i, t, appear, when; bm25 rerank score=41.171; matched issue terms: several, 0, i, t, appear, when
- src/textual/document/_history.py: path components match issue terms, source file; bm25 rerank score=29.051; matched issue terms: 0, latest, 1, text, appear, when; bm25 rerank score=29.930; matched issue terms: 0, latest, 1, text, appear, when; bm25 rerank score=29.930; matched issue terms: 0, latest, 1, text, appear, when
- src/textual/widgets/_footer.py: path components match issue terms, source file; bm25 rerank score=21.311; matched issue terms: command, palette, 0, release, 1, text; bm25 rerank score=31.965; matched issue terms: command, palette, 0, release, 1, text; bm25 rerank score=30.784; matched issue terms: command, palette, 0, release, 1, text; bm25 rerank score=30.784; matched issue terms: command, palette, 0, release, 1, text

Attempts:
No patch attempts were made.

Token usage: 27598/50000

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: No relevant files could be located or read.

Relevant files:
None found

Attempts:
No patch attempts were made.

Token usage: 1070/50000

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: No relevant files could be located or read.

Relevant files:
None found

Attempts:
No patch attempts were made.

Token usage: 1064/100000
