### ISSUE TITLE
Trying to remove Footer results in "node has no screen"

### ISSUE THREAD

**Issue by ajantti** [Textualize/textual#4711]
I was playing around with changing binding descriptions like mentioned #1057. (In this case to switch languages.) 

I ran into another issue where trying to remove the footer in any way (including `self.recompose()`) results in "node has no screen" error.

```python
from textual.app import App
from textual import on
from textual.widgets import Footer, Button

class TestApp(App):
    def compose(self):
        yield Button()
        yield Footer()

    @on(Button.Pressed)
    def button_pressed(self):
        self.query_one(Footer).remove()

app = TestApp()
app.run()
```

Clicking the button gives:

```python
╭─────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────
│ C:\Users\jantti\AppData\Local\Programs\Python\Python310\lib\site-packages\textual\widgets\_footer.py:176 in on_unmount
│
│   173 │   │   self.screen.bindings_updated_signal.subscribe(self, bindings_changed)            ╭──── locals ─────╮
│   174 │                                                                                        │ self = Footer() │
│   175 │   def on_unmount(self) -> None:                                                        ╰─────────────────╯
│ ❱ 176 │   │   self.screen.bindings_updated_signal.unsubscribe(self)
│   177 │
│   178 │   def watch_compact(self, compact: bool) -> None:
│   179 │   │   self.set_class(compact, "-compact")
│
│ C:\Users\jantti\AppData\Local\Programs\Python\Python310\lib\site-packages\textual\dom.py:680 in screen
│
│    677 │   │   while node is not None and not isinstance(node, Screen):                         ╭───────────────── locals ─────────────────╮
│    678 │   │   │   node = node._parent                                                          │   node = None                            │
│    679 │   │   if not isinstance(node, Screen):                                                 │ Screen = <class 'textual.screen.Screen'> │
│ ❱  680 │   │   │   raise NoScreen("node has no screen")                                         │   self = Footer()                        │
│    681 │   │   return node                                                                      ╰──────────────────────────────────────────╯
│    682 │
│    683 │   @property
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
NoScreen: node has no screen
```

I tried with the current git main branch.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.71.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                              |
|----------------|--------------------------------------------------------------------|
| Version        | 3.10.11                                                            |
| Implementation | CPython                                                            |
| Compiler       | MSC v.1929 64 bit (AMD64)                                          |
| Executable     | C:\Users\jantti\AppData\Local\Programs\Python\Python310\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19045 |

## Terminal

| Name                 | Value     |
|----------------------|-----------|
| Terminal Application | *Unknown* |
| TERM                 | *Not set* |
| COLORTERM            | *Not set* |
| FORCE_COLOR          | *Not set* |
| NO_COLOR             | *Not set* |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=119, height=30 |
| legacy_windows | True                 |
| min_width      | 1                    |
| max_width      | 119                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 30                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |
```

**Comment by willmcgugan** [comment]
Thanks. Fixed in 0.72.0
