### ISSUE TITLE
DataTable.add_row gives misleading error with too many arguments.

### ISSUE THREAD

**Issue by merriam** [Textualize/textual#4722]
Create a DataTable with one column.   Do a `table.add_row("A", "B")`.  
Get `AttributeError: 'NoneType' object has no attribute 'key'`, which is an odd error.
Instead I should get `ValueError:  Too many column values provided to add_row`

Caused by  widgets/_data_table.py:1583, `for column, cell in zip_longest(self.ordered_columns, cells)`

Will put in  a PR that checks the length and puts an error message that doesn't have me pull hair out for ten minutes.

**Comment by darrenburns** [comment]
Good catch.
