### ISSUE TITLE
Markdown widget - hyperlinks does not open browser on click

### ISSUE THREAD

**Issue by thomasht86** [Textualize/textual#4738]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
Yes. 

To reproduce:

```python
# Sample textual app that renders markdown widget with url link
from textual.widgets import Markdown
from textual.app import App, ComposeResult

MARKDOWN = """
# This is an h1

Rich can do a pretty *decent* job of rendering markdown.

1. This is a list item
2. This is another list item

[Google](https://www.google.com)
"""

class HyperlinkApp(App):

    def compose(self) -> ComposeResult:
        yield Markdown(MARKDOWN)

if __name__ == "__main__":
    app = HyperlinkApp()
    app.run()
```

When running corresponding `rich`-snippet, it does open the url in browser on click.

```python
from rich.console import Console
from rich.markdown import Markdown

console = Console()
md = Markdown(MARKDOWN)
console.print(md)
```

If this is not supported, I will be happy to change it to a feature request.

**Comment by willmcgugan** [comment]
It's left to the developer to implement how to open links. If you want links to open a browser you can handle the [LinkClicked](https://textual.textualize.io/widgets/markdown/#textual.widgets._markdown.Markdown.LinkClicked) message.

**Comment by thomasht86** [comment]
Ah, ok! Noted. Thanks for the swift reply. 
Did you consider keeping the default behavior to open a browser from rich? 
Thanks a lot for all your great work btw. 🙏 
Really good devX!

**Comment by willmcgugan** [comment]
> Did you consider keeping the default behavior to open a browser from rich? 

The links in Rich work differently. They are handled by the terminal, which typically opens them in a browser. But you can't intercept those links. The links in Textual Markdown offer more flexibility, because an app can intercept them.

**Comment by thomasht86** [comment]
I see. Thanks again!

```python
    import webbrowser
    @on(Markdown.LinkClicked)
    def handle_link_clicked(self, event: Markdown.LinkClicked) -> None:
        # Open in a new tab, if possible, else in the default browser
        webbrowser.open_new_tab(event.href)
```

worked like a charm! 👍
