### ISSUE TITLE
tab focus highlight

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#474]
We should compare tab-to-focus against browsers.

There are some differences in behaviour. We may want to replicate the browser functionality.

**Comment by darrenburns** [comment]
Moving focus to something off-screen will cause the browser window to scroll such that the newly focused element is visible, for example.

**Comment by willmcgugan** [comment]
Yeah, got an issue for that https://github.com/Textualize/textual/issues/473

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
