### ISSUE TITLE
set_reactive02.py does not run (AttributeError: 'Greeter' object has no attribute 'set_reactive')

### ISSUE THREAD

**Issue by leemthai** [Textualize/textual#4767]
Just running https://textual.textualize.io/guide/reactivity/#__tabbed_10_1

set_reactive02.py

It doesn't run.  Get the  following error:
AttributeError: 'Greeter' object has no attribute 'set_reactive'

Same happened when I tried to run my own code that used the set_reactive() method.

Cheers,

**Comment by darrenburns** [comment]
Please run `textual diagnose` and copy paste the output directly into this issue :)

**Comment by leemthai** [comment]
| Rich    | 13.7.1 |

## Python

| Name           | Value                                |
|----------------|--------------------------------------|
| Version        | 3.12.4                               |
| Implementation | CPython                              |
| Compiler       | GCC 14.1.1 20240522                  |
| Executable     | /home/lee/trend/.venv/bin/python3.12 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.9.9-1-MANJARO                                     |
| Version | #1 SMP PREEMPT_DYNAMIC Fri Jul 12 10:32:52 UTC 2024 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=137, height=48 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 137                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 48                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by darrenburns** [comment]
Please copy and paste _all_ of the output. Looks like the top (the most important part) is missing.

**Comment by leemthai** [comment]
Apologies :)


# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.43.2 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                |
|----------------|--------------------------------------|
| Version        | 3.12.4                               |
| Implementation | CPython                              |
| Compiler       | GCC 14.1.1 20240522                  |
| Executable     | /home/lee/trend/.venv/bin/python3.12 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.9.9-1-MANJARO                                     |
| Version | #1 SMP PREEMPT_DYNAMIC Fri Jul 12 10:32:52 UTC 2024 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=137, height=48 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 137                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 48                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

    ~/trend    main !4 ?1  textual diagnose                                                                         ✔  trend  

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.43.2 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                |
|----------------|--------------------------------------|
| Version        | 3.12.4                               |
| Implementation | CPython                              |
| Compiler       | GCC 14.1.1 20240522                  |
| Executable     | /home/lee/trend/.venv/bin/python3.12 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.9.9-1-MANJARO                                     |
| Version | #1 SMP PREEMPT_DYNAMIC Fri Jul 12 10:32:52 UTC 2024 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=137, height=48 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 137                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 48                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by leemthai** [comment]
Oh... am I running a terribly old version? oops

**Comment by darrenburns** [comment]
Yup - that's a very old version :)

We're at 0.72.0 now.

Gonna close this - feel free to reach out if you have any more problems!
