### ISSUE TITLE
Clarify API docs following titles change?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4775]
The improvements to the docs look great! But I do just have a minor suggestion where the titles have been changed to the module name.

Here's an example of the new docs for https://textual.textualize.io/api/widget/. Perhaps I'm overthinking this, but the introductory paragraph isn't clear it is talking about the `Widget` class in this module?

![image](https://github.com/user-attachments/assets/5a3d8bae-439a-4613-a2fc-d1f12f520687)

**Comment by darrenburns** [comment]
Yeah, it looks like some of the text is in the wrong place, like it was intended for classes rather than modules.

**Comment by TomJGooding** [comment]
I'm happy to do a quick sweep through the API docs if it helps? I'd just need a little guidance:

- The source of these 'intros' isn't consistent: some are docstrings at the top of the module file whereas others are defined in their `docs/api`' markdown document.
- Should this 'intro' explicitly state something like "This module contains the Widget class which is the basis of all widgets" or maybe "The Widget class is the basis of all widgets" is enough?

**Comment by willmcgugan** [comment]
I did a pass through the docs earlier, I think it makes more sense now but feel free to point out any inconsistencies!
