### ISSUE TITLE
Reduce font size for params in docs?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4776]
Sorry something else I noticed while looking up something in the docs. Did some font sizes intentionally change in the update? For example here's how https://textual.textualize.io/widgets/data_table/ looks on my laptop:

![image](https://github.com/user-attachments/assets/ea5a1b3f-5de1-476a-a1c3-0bf6a8afe924)

**Comment by willmcgugan** [comment]
I don't think they changed, but we did used to have this custom markup to put the attribute and type in one column to give the description more width.

Maybe we can restore that.

**Comment by TomJGooding** [comment]
Ah, looks like it is a combination of both:

### Before

![image](https://github.com/user-attachments/assets/3f8b43e5-e00a-47a2-bc69-8804d2ff7037) 

### After

![image](https://github.com/user-attachments/assets/ea5a1b3f-5de1-476a-a1c3-0bf6a8afe924)

**Comment by willmcgugan** [comment]
I rebuilt the docs, and the font size looks sensible now.
