### ISSUE TITLE
How to refresh DirectoryTree to see new files/folders?

### ISSUE THREAD

**Issue by mayermakes** [Textualize/textual#4777]
Pushing this discussion to issue as it seems critical for a lot of apps based on textual.
A method to reload/refresh the DirectoryTree Widget would be highly appreciated.
self.query(Input).refresh(layout=False, recompose=True)  --> or any Widget I tried works.

self.query(DirectoryTree).refresh(layout=False, recompose=True)  -> does not, but would be expected.

### Discussed in https://github.com/Textualize/textual/discussions/1428

<div type='discussions-op-text'>

<sup>Originally posted by **toiletsandpaper** December 22, 2022</sup>
**This does't work at all:**
```python
def on_button_pressed(self, event: Button.Pressed):
    if event.button.id == 'button-refresh-tree':
        logger.info('Refresh Tree button pressed')
        tree: DirectoryTree = self.query_one('#tree-view', DirectoryTree)
        tree.refresh()
```

**And this is working, but seems very inefficient:**
```python
def on_button_pressed(self, event: Button.Pressed):
    if event.button.id == 'button-refresh-tree':
        logger.info('Refresh Tree button pressed')
        app.pop_screen()
        app.uninstall_screen('file-picker')
        app.install_screen(FilePickerScreen(), name='file-picker')
        app.push_screen('file-picker')
```</div>

**Comment by TomJGooding** [comment]
[`DirectoryTree.reload`](https://textual.textualize.io/widgets/directory_tree/#textual.widgets.DirectoryTree.reload) was added back in Textual v0.23.0 and later also [`DirectoryTree.reload_node`](https://textual.textualize.io/widgets/directory_tree/#textual.widgets.DirectoryTree.reload_node)in v0.33.0.

**Comment by mayermakes** [comment]
thanks, I missed that in the docs /tutorials

**Comment by TomJGooding** [comment]
No problem. Would you mind closing this if that resolves your issue?

**Comment by mayermakes** [comment]
Closing the issue but want to remark that reload only works( at least for me) with 
query_one
like this:
self.query_one(DirectoryTree).reload()
while other widgets can be refreshed all at once and this one has to betrageted once there are more than one .
like this:
self.query_one('#loading-tree').reload()

and the docs did not indicate that to me.

**Comment by TomJGooding** [comment]
Sorry I'm not sure I understand your last remark. 

`self.query_one('#loading-tree').reload()` would a) only target a single widget and b) reload is only a DirectoryTree method?

**Comment by mayermakes** [comment]
self.query(DirectoryTree).reload() does not work.
 -> AttributeError: 'DOMQuery' object has no attribute 'reload'
self.query_one(DirectoryTree).reload() does work.

Now once there is a second DirectoryTree  active. 
--> TooManyMatches: Call to only_one resulted in more than one matched node

but if we target one specific DirectoryTree instance --> the one with id "loading-tree":
self.query_one('#loading-tree').reload()

To reload all all Directory trees in the app we would now need to do a query_one on each of the DirectoryTree Widgets individually.
In contrast we can refresh other Inputs  with self.query(Input),refresh(layout=False, recompose=True).
-> So I would have expected that refreshing would work with all widgets the same way.

**Comment by TomJGooding** [comment]
>  In contrast we can refresh other Inputs with self.query(Input),refresh(layout=False, recompose=True).

I don't think `refresh` does what you think it does. You shouldn't even have any need to call refresh explictly, see the docs: https://textual.textualize.io/api/widget/#textual.widget.Widget.refresh

**Comment by mayermakes** [comment]
For my particular application reactivity did not work, but refreshing all the widgets does.
the app is basically just reading in a file displaying its content ins many editable widgets and can save it back to a file/load in new files or convert to other formats.
all contents are based on a yaml file thats read in on launch , which can be exchanged during operation by loading in a new yaml. Reactivity did not work for me, but refreshing after loading in the yaml does.
I was just expecting DirectoryTree to be refreshable like the other widgets are. but the method turned out to be different.
