### ISSUE TITLE
`DataTable` height maybe doesn't account for horizontal scrollbar?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#4778]
I haven't yet started digging into this, but I discovered a possible bug with the `DataTable` height when there is a horizontal scrollbar. If you run my quick example app below, the row is obscured by the scrollbar:

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable

LORUM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


class ExampleApp(App):
    def compose(self) -> ComposeResult:
        yield DataTable()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.add_column("Column 1")
        table.add_column("Column 2")
        table.add_row(LORUM_IPSUM, LORUM_IPSUM)


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by ihabunek** [comment]
Can confirm this one, Textual 0.73.0.

E.g. here's a data without any scroll bars

![00071](https://github.com/user-attachments/assets/17988a12-e66f-4ded-8b28-640f3e9f78d7)

If I resize the window by decreasing its width until horizontal scroll bar appears, then vertical scroll bar appears as well, even though there's enough room for the full table height:

![00070](https://github.com/user-attachments/assets/f0ace94b-4fa5-4698-93b6-4fd9ea741e76)

**Comment by TomJGooding** [comment]
This looks like possibly an issue with how the base `ScrollView` handles the size with the scrollbars, rather than just the `DataTable` widget.

Here's another example with a `Log` widget where the height is set to auto:

<details>
<summary>Example Code</summary>

```python
from textual.app import App, ComposeResult
from textual.widgets import Footer, Log

LORUM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


class ExampleApp(App):
    BINDINGS = [("space", "write_line", "Write Line")]

    CSS = """
    Log {
        overflow: auto;
        height: auto;
        max-height: 1fr;
        border: solid $accent;
    }
    """

    def compose(self) -> ComposeResult:
        yield Log(auto_scroll=False)
        yield Footer()

    def on_mount(self) -> None:
        log = self.query_one(Log)
        log.border_title = f"{log.line_count} lines"

    def action_write_line(self) -> None:
        log = self.query_one(Log)
        log.write_line(f"{log.line_count + 1}: {LORUM_IPSUM}")
        log.border_title = f"{log.line_count} lines"


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

</details>

This probably isn't the correct fix, but this simple change to [`ScrollView.get_content_height`](https://github.com/Textualize/textual/blob/262b3af00fe36e3c7cb34a72e9a333d1eee2f885/src/textual/scroll_view.py#L58-L69) seems to work:

```diff
-        return self.virtual_size.height
+        return self.virtual_size.height + self.scrollbar_size_horizontal
```

**Comment by darrenburns** [comment]
@TomJGooding I think that may actually be the fix. It's probably a fair assumption that when `height: auto` in a `ScrollView` we don't want scrollbars to sit on top of content, so we need to add that extra leeway of `+ self.scrollbar_size_horizontal` to make room for it in the content area. I'm guessing the same change would be required for the scrollbar on the other axis too.

@willmcgugan any thoughts?

**Comment by willmcgugan** [comment]
The PR above implements those changes. Not to `get_content_width`, but at a slightly lower level.

It fixes the MRE, and no tests broke!

**Comment by ihabunek** [comment]
@willmcgugan I can confirm this fixes the issue in my use case. Thanks!
