### ISSUE TITLE
mutate_reactive doesn't work with data binding

### ISSUE THREAD

**Issue by Banbury** [Textualize/textual#4797]
# Description
mutate_reactive doesn't execute watchers in components, that are connected via data binding. I am using a reactive list in the app. I have bound this list to another reactive list in a child component. When I execute self.mutate_reactive the watcher in the app is called, but the watcher in the child component is not. 

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.73.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                     |
|----------------|-----------------------------------------------------------|
| Version        | 3.10.10                                                   |
| Implementation | CPython                                                   |
| Compiler       | MSC v.1929 64 bit (AMD64)                                 |
| Executable     | d:\work\projects\python\aieditor\.venv\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.22621 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.91.1) |
| TERM                 | *Not set*       |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=151, height=8 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 151                 |
| is_terminal    | True                |
| encoding       | utf-8               |
| max_height     | 8                   |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by willmcgugan** [comment]
Can you give us an MRE? https://label.dev/articles/minimal-reproducible-example/

**Comment by Banbury** [comment]
Maybe on the weekend. But all that is needed is an app, a widget, two reactive lists and two watch functions.

**Comment by willmcgugan** [comment]
Assuming this is the same issue https://github.com/Textualize/textual/issues, it will be fixed next release.
