### ISSUE TITLE
Escape being detected and processed as keyboard input while hoovering on buttons under heavy load

### ISSUE THREAD

**Issue by matkudela** [Textualize/textual#4816]
This https://github.com/Textualize/textual/issues/4613 is still relevant. 
Just tested it on version 0.74. It appears rarer, but after few minutes of testing I succeeded in recreating it.

**Comment by TomJGooding** [comment]
Sorry but could you clarify what you mean by "under heavy load"? Have you tested in other terminal emulators or only Terminator?

**Comment by matkudela** [comment]
> Sorry but could you clarify what you mean by "under heavy load"? Have you tested in other terminal emulators or only Terminator?

Used `sudo stress` command, I tested in on ubuntu builtin terminal not terminator.

**Comment by TomJGooding** [comment]
Sorry but I'm struggling to reproduce this issue. Could you provide the exact steps to reproduce this, including options for the `stress` command?

>  tested in on ubuntu builtin terminal not terminator.

Your `textual diagnose` results in the [previous issue](https://github.com/Textualize/textual/issues/4613#issuecomment-2151953342) reported Terminator?

**Comment by matkudela** [comment]
I use terminator to operate version control system, used it to run textual diagnose but to run apps im using ubuntu native terminal only. 
My steps are:
- run stress command
- run my example app
- hoover through buttons (now it takes longer than before textual 0.71 arrived)
My stress command: `sudo stress --cpu 8 --timeout 1800s --vm 25 --vm-bytes 1024` - it depends on your system and computer. You just have to heavy load it - when i run my command everything is lagging.

Made video with this error, took me 10 minutes to see the notification (it's now in action binded to escape). At the beggining you can see sudo stress command and version of textual: https://youtube.com/watch?v=ltKOPXnl-rw (sorry for this music, had to delete sounds from office)

**Comment by matkudela** [comment]
My textual diagnose from ubuntu terminal:
```
<!-- This is valid Markdown, please paste the following directly in to a GitHub issue -->
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.74.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                 |
|----------------|-------------------------------------------------------|
| Version        | 3.10.12                                               |
| Implementation | CPython                                               |
| Compiler       | GCC 11.4.0                                            |
| Executable     | /home/dev/textual_playground/textual_venv/bin/python3 |

## Operating System

| Name    | Value                                                            |
|---------|------------------------------------------------------------------|
| System  | Linux                                                            |
| Release | 6.5.0-44-generic                                                 |
| Version | #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | GNOME Terminal |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=132, height=43 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 132                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 43                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |
```

**Comment by matkudela** [comment]
Actual code of MRE:
```
from __future__ import annotations

from textual import on
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.screen import Screen, ScreenResultType
from textual.widgets import Button
from textual.containers import Horizontal


class MyApp(App):

    def compose(self) -> ComposeResult:
        yield Button("next screen", variant="success")

    @on(Button.Pressed)
    def next_screen(self):
        self.app.push_screen(Screen2())


class Screen2(Screen[ScreenResultType]):
    BINDINGS = [Binding("escape", "other_screen", "next")]

    def compose(self) -> ComposeResult:
        with Horizontal():
            yield Button("1", variant="success")
            yield Button("2", variant="primary")
            yield Button("3", variant="error")
            yield Button("4", variant="success")
            yield Button("5", variant="primary")
            yield Button("6", variant="error")

    def action_other_screen(self):
        self.notify("notify")
        self.app.notify("app notify")

MyApp().run()
```

**Comment by willmcgugan** [comment]
The root cause is the way terminals handle the escape key. If you press escape you get an escape code in stdin, but escape also introduces escape sequences for other keys. The only way to know if the escape key was pressed OR an escape sequence is to wait for a period of time after the escape code is seen. If more data arrives in a short period, then is was an escape sequence, otherwise it was an escape key.

This is a super brittle mechanism. If your terminal is slowed down, then an escape code may be erroneously reported as being an escape key.

Many terminals support a new protocol, which doesn't have this issue. If you can upgrade your terminal, you may find the issue goes away.

The only other solution would be to expose the delay between escape code and reporting a key, via an env var. Increasing that would likely fix the issue at the expense of the escape key not being reported until a short period after it was actually pressed.

**Comment by willmcgugan** [comment]
Turns out we weren't handling the escape processing correctly.

Please try 0.76.0, which should improve things.

If you can still reproduce the issue, try increasing the env var `ESCDELAY` to `200` or more.

**Comment by matkudela** [comment]
Tested it couple days ago, seems like it's working properly without increasing env var.
