### ISSUE TITLE
Documentation errors on CSS Type Selectors

### ISSUE THREAD

**Issue by merriam** [Textualize/textual#4827]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed

In https://textual.textualize.io/guide/CSS/#type-selector, the documentation states:

The type selector will also match a widget's base classes. Consequently, a Static selector will also style the button because the Button Python class extends Static.

Unfortunately, this is not true.  Button extends Widget.  It can be shown by changing this line in docs/examples/widgets/buttons.tcss:

```
Button {
    margin: 1 2;
}
```
to
```
Static {
    margin: 1 2;
}
```
resulting in no styling being applied when running `python docs/examples/widgets/buttons.py`. 

This is just a small nit.  Let me know if there if my reasoning on selectors is flawed.  Otherwise I will toss in the next Documentation PR after my open PRs are resolved.

**Comment by merriam** [comment]
OK.  Changed from "Button" (an existing widget class) to "BoxedText" and it works well.

**Comment by TomJGooding** [comment]
I agree this example could be confusing. The first paragraph does show creating a new widget, but it might imply that Textual's built-in `Button` also inherits from `Static`, which hasn't been the case since version 0.42.0!

**Comment by willmcgugan** [comment]
I've updated the docs to avoid the Button confusion.

**Comment by merriam** [comment]
Sorry, should I not have put it the Doc update?
