### ISSUE TITLE
Updating a label with text containing square brackets hides those brackets and the word behind it

### ISSUE THREAD

**Issue by michaelochs** [Textualize/textual#4830]
I am trying to present a block of text which is actually Objective-C source code. However if I do that in a Label, the text gets completely scrambled with all the text missing that follows a `[`.

So for example this text:
```
- (void)myFunction {
    [[self someView] doSomething:[self someMethod]]
}
```

Will render as this:
```
- (void)myFunction {
    [ doSomething:]
}
```

I would expect this level of interpretation from some rich text view but not from a standard label and I do not see anything in the API to disable this kind of parsing?

Is this a bug or am I holding it wrong? My code for updating is fairly simple:

```
def compose(self) -> ComposeResult:
    yield Label()

def watch_context(self, context):
    self.query_one(Label).update(context.details)  # context.details returns the above code as a single str
```

**Comment by TomJGooding** [comment]
Try `yield Label(markup=False)`.

`Label` can also "contain more complex Rich renderables" and inherits from `Static` per the docs.

**Comment by michaelochs** [comment]
> Try yield Label(markup=False)

Oh amazing, that did the trick. Sorry for the noise, should have spotted that!
