### ISSUE TITLE
v0.75.0 has massive slowdown

### ISSUE THREAD

**Issue by paulrobello** [Textualize/textual#4832]
Running Python 3.11 on Windows 11 using Windows Terminal Version: 1.20.11781.0
Works properly on textual v0.74.0.
Click around on various list items, the responsiveness of the app is very poor.
I believe the issue is that v0.75.0 changed the way Enter and Leave events bubble.
I don't know that the issue is limited to lists. It most likely would occur with any significant number of widgets.
If you uncomment the on_enter and on_leave handlers which stop the bubble a lot of performance is restored. 
MRE
[https://gist.github.com/paulrobello/cc9de493940f985e8622b4ca4e9a0597](https://gist.github.com/paulrobello/cc9de493940f985e8622b4ca4e9a0597)

**Comment by davidfokkema** [comment]
If enter and leave events are indeed the culprit, maybe bubbling of those events should be optional and off by default? Or if you really need it, handle it in the widget you're interested in and call a .bubble() method on it? That won't work if you want to watch a built-in or third-party widget from 'outside'... Maybe a method to add a watcher for these kinds of events? That may be a complex change.

**Comment by willmcgugan** [comment]
Thanks for the MRE. Please try Textual v0.75.1

The issue was that since Enter and Leave bubble now, an additional check is required to see if the event came from the current widget or a child.

**Comment by paulrobello** [comment]
Confirmed fixed with v0.75.1
