### ISSUE TITLE
Displaybar: decrease CPU consumption by adjusting Bar.auto_refresh when styles.display is None

### ISSUE THREAD

**Issue by xavierog** [Textualize/textual#4835]
Overall, `ProgressBar` is not a CPU-greedy widget. It does bring a small yet noticeable increase in CPU consumption when left in "indeterminate" mode since this mode involves a sliding animation. As far as I can tell, this is both normal and acceptable.

However, I noticed this CPU consumption does not decrease when the progress bar is hidden (e.g. `self.progress_bar.styles.display = 'none'`). This could be improved by adjusting `Bar.auto_refresh` whenever necessary.

Currently, `Bar.auto_refresh` only reacts to changes of the `percentage` attribute:
https://github.com/Textualize/textual/blob/fd369376f21e1c715cdd7d0e08dfb080ffdc9e3d/src/textual/widgets/_progress_bar.py#L90-L95

**Comment by willmcgugan** [comment]
Good point. It probably makes sense for the auto_refresh feature to check if the widget is actually visible before refreshing. Should be a trivial change.
