### ISSUE TITLE
Command palette glitch

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4855]
Strange behavior of Input in command palette.

The input changes position. Possibly related to recent Input changes by @darrenburns ?

https://github.com/user-attachments/assets/c4569fe9-6f56-42d5-a632-3deab8df361f

**Comment by darrenburns** [comment]
This is a weird one. You're not pressing anything here? Is it just moving by itself?

**Comment by willmcgugan** [comment]
> This is a weird one. You're not pressing anything here? Is it just moving by itself?

Yeah. It appears to coincide with the first blink of the cursor. Although that may be a coincidence.

**Comment by TomJGooding** [comment]
Interesting, I can't seem to reproduce this on main trying a few different terminals (alacritty, kitty, wezterm)

**Comment by willmcgugan** [comment]
Fixed by https://github.com/Textualize/textual/pull/4873
