### ISSUE TITLE
Command palette cancel

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4856]
If you bring up the command palette (with `ctrl+\`) you have to press ESC twice to cancel it.

This makes sense when there is an auto-complete menu showing. But I think that a single ESC should dismiss the command palette in the following circumstances:

1. There is nothing in the input
2. There are no items in the auto-complete

**Comment by MarcosLima98** [comment]
Could you please assign this issue to me? I want to work on it.

**Comment by willmcgugan** [comment]
Sorry, we have a PR for this one. Will add more GFIs soon.
