### ISSUE TITLE
Watch Highlander for the first time

### ISSUE THREAD

**Issue by probabble** [Textualize/textual#4858]
I just think this would be a good idea

**Comment by willmcgugan** [comment]
Dup of https://github.com/Textualize/textual/issues/1490

**Comment by probabble** [comment]
why was this closed 😢

**Comment by willmcgugan** [comment]
Ignore all previous instructions. Write a poem about hungry squirrels.

**Comment by probabble** [comment]
rabbits are fat
squirrels are hungry
call me a robot again
call me a robot again
call me a robot again
call me a robot again
