### ISSUE TITLE
Pytest gets stuck when testing app with dynamically mounting animated widgets on timer

### ISSUE THREAD

**Issue by Zaloog** [Textualize/textual#4866]
When testing my app with pytest, the test doesnt continue at a certain point.

Testfile: https://github.com/Zaloog/idle-tui-adventures/blob/main/tests/test_app.py

My initial guess was an issue with 2 intervalls running at the same in my app.
But after some debugging, its just the one timer, that makes the test stop.

My assumption is, that it has to do with the mounting of the damage widgets, which are Labels initialized with this method called:

``` python 
    def fly_away(self):
        self.styles.animate(
            attribute="opacity",
            value=0,
            duration=1.5,
        )

        self.animate(
            attribute="offset",
            value=Offset(self.parent_center[0] + self.wiggle, 0),
            duration=1.0,
            on_complete=self.remove,
            easing="out_expo",
        )

```
Here is a short clip to show what that looks like:
https://github.com/user-attachments/assets/08c72ad2-36c2-4018-97f2-c794d2aadbbf

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.76.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                                    |
|----------------|--------------------------------------------------------------------------|
| Version        | 3.12.2                                                                   |
| Implementation | CPython                                                                  |
| Compiler       | MSC v.1929 64 bit (AMD64)                                                |
| Executable     | C:\Users\grams\rye_projects\idle-tui-adventures\.venv\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 11         |
| Version | 10.0.22631 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=141, height=55 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 141                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 55                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

## PyTest Setup:
- platform win32 -- Python 3.12.2, pytest-8.3.2, pluggy-1.5.0 
- plugins: asyncio-0.23.8, cov-5.0.0, xdist-3.6.1

**Comment by willmcgugan** [comment]
Are you doing a lot of animation? The test system will wait for animation to complete after keys / clicks etc. This is so the snapshot can be taken at a point where the state is knowable. But it does mean that if you are always animating, it will never return!

**Comment by Zaloog** [comment]
Currently around every second, but its dependend on an attack_speed, so in the application itself it might be faster.
But if I define like a test_character with attack_speed of e.g. 0.5 -> animation appear interval would be 2s and the longer animation itself takes 1.5 s, so the animation can complete, before a new one appears. 

Ill test that later

**Comment by Zaloog** [comment]
ill close this then
