### ISSUE TITLE
v0.76.0 breaks buttons with emojis

### ISSUE THREAD

**Issue by charles-001** [Textualize/textual#4870]
I upgraded to v0.76.0 and the button layout I use is broken now. It adds a bar to the right of some of them.

<img width="516" alt="Screenshot 2024-08-12 at 4 30 58 AM" src="https://github.com/user-attachments/assets/b2e24364-58bc-428a-84fd-f9a7dac371cf">

MRE:
```python
from textual.app import App, ComposeResult
from textual.containers import Horizontal
from textual.widgets import Button


class MREApp(App):
    CSS = """
        Button {
            text-style: none;
        }
    """

    def __init__(self):
        super().__init__()

    def compose(self) -> ComposeResult:
        with Horizontal():
            yield Button("⏪  Back", id="back_button")
            yield Button("⏸️  Pause", id="pause_button")
            yield Button("⏩  Forward", id="forward_button")
            yield Button("🔍  Seek", id="seek_button")


if __name__ == "__main__":
    app = MREApp()
    app.run()
````

Thanks!

**Comment by darrenburns** [comment]
Are you 100% sure this is due to upgrading to `v0.76.0`?

**Comment by charles-001** [comment]
Yes. I can downgrade to `v0.75.0` and it's back to normal.

**Comment by darrenburns** [comment]
Thanks! Could you run `textual diagnose` and paste the output here?

**Comment by darrenburns** [comment]
Actually scrap that - I can reproduce! No need.
