### ISSUE TITLE
Mouse enter in a child widget triggers Leave event in parent

### ISSUE THREAD

**Issue by Banbury** [Textualize/textual#4885]
Version: 0.76.0

I have a static widget with a button as a child element. I want to make the button visible, when the mouse enters the parent widget, and hide it when I leave the parent widget. The unhiding of the button works. But when I move the mouse over the button, a Leave event is triggered for the parent widget, and the button is hidden again. The button is then flickering on and off, as long as I don't move the mouse.
Since the mouse is already over the parent widget, no Leave event should be triggered.

**Comment by Zaloog** [comment]
I think leaving is correct, since the mouse is now no longer on the Static, but on the button.
You can check `on_mouse_move` if the current mouse position is inside the region of the parent widget, to enable the button, if you mouse over it.
like:
```python
def on_mouse_move(self):
    if self.region.contains_point(self.app.mouse_position):
        self.query(Button).set_styles("visibility: visible;")
    else:
        self.query(Button).set_styles("visibility: hidden;")
```

**Comment by willmcgugan** [comment]
The mouse is only over one widget at a time. If you move from the container to a button, it has left the container and entered the button.

You can use [`is_mouse_over`](https://textual.textualize.io/api/widget/#textual.widget.Widget.is_mouse_over) to know if the pointer is within the widget's region (a shortcut to @Zaloog 's suggestion).

To achieve you button effect, you could do something like the following:

```python
@on(events.Enter)
@on(events.Leave)
def on_enter(self):
    self.query_one("Button").visible = self.is_mouse_over
```

**Comment by Banbury** [comment]
I disagree. The mouse can be inside the button and the parent at the same time. I can't remember any other UI framework behaving like that (and I have used quite a few).
I will try @willmcgugan's workaround, but I still think the behaviour is wrong.
