### ISSUE TITLE
Don't allow screen instances in App.SCREENS

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#4893]
Textual currently allows a screen instance to be specified in the `SCREENS` classvar. This works fine when launching an app, until a second instance of the app runs. Re-using a previous instance breaks the app.

See the example here: https://textual.textualize.io/guide/screens/#creating-a-screen

Note how the BSOD is given as an instance in a classvar, i.e. `SCREENS = {"bsod": BSOD()}` This would cause the instance to be shared if there is ever more than a single App.

The easiest workaround is to disallow passing instances, and require a string or callable. So the above example should be `SCREENS = {"bsod": BSOD}`

Requirements:

- Adjust typing to not allow a screen instance in `SCREENS` and `MODES`
- Reject screen instances at runtime, by throwing a `TypeError`.
- Update docs and examples accordingly.
- Tests to ensure behavior when not using a string or callable.

**Comment by ZeroIntensity** [comment]
I can give this a go!

**Comment by willmcgugan** [comment]
Good catch re modifying the `MODES` classvar. We should not be doing that. Suggest we copy the classvar to an instance var.

If that looks straightforward. You could do it in this PR. Otherwise, it could be a new issue.

**Comment by ZeroIntensity** [comment]
Sounds easy enough, I'll implement it in this PR.

**Comment by ZeroIntensity** [comment]
Added it under a new `modes` attribute!
