### ISSUE TITLE
Using `pilot.click`, how to select the nth item in a query?

### ISSUE THREAD

**Issue by shapiromatron** [Textualize/textual#4908]
Sometimes when writing tests, I want to click the nth result of a selector.  I can accomplish this using playwright using the [nth](https://playwright.dev/python/docs/locators#get-by-nth-item) selector; is there an equivalent way to to do this using [pilot.click](https://textual.textualize.io/api/pilot/#textual.pilot.Pilot.click)?  Could that method be updated so that the selector could be the result of a query perhaps?

**Comment by willmcgugan** [comment]
I think the following should work:

```python
pilot.click(app.query("Thing")[10])
```

Although I could be convinced to add a parameter to `click()` for that. Just to make it more self documenting.

Adding the nth selector is also a possibility, just more work.

**Comment by shapiromatron** [comment]
Totally agree w/ just using an item in the list instead of a special method.

However, when I try to click an instance of a button, not a query string, I get an error:

```
AttributeError: 'Button' object has no attribute '__name__'. Did you mean: '__ne__'?
```

The docstring for click says it allows for `type[Widget] | str | None`, but not a `Widget` - it doesn't appear to be supported? As a workaround, is there a query selector like [nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) that I could use to get the first one?

**Comment by willmcgugan** [comment]
The not accepting a widget instance is definitely an oversight. There's a PR in the works to fix that.

The nth-of-type selector may happen...
