### ISSUE TITLE
ScrollView/RichLog: Page Up / Page Down off by one with horizontal scrollbar

### ISSUE THREAD

**Issue by xavierog** [Textualize/textual#4914]
I noticed this issue while using the RichLog widget but it may actually stem from ScrollView.

Assuming a 25-line high RichLog widget:
- When there is a horizontal scrollbar, Page Up and Page Down move e.g. from lines 1-25 to lines 26-50, which is the expected behaviour.
  This can be confirmed by running the MRE below this way: `SUFFIX= ./richlogtest.py`
- When there is a horizontal scrollbar, Page Up and Page Down move e.g. from lines 1-24 to lines 26-49, thus hiding line 25, hence this report.
  This can be confirmed by running the MRE below this way: `./richlogtest.py`

MRE:
```python
#!/usr/bin/env python3
import os
from textual.app import App
from textual.widgets import RichLog

class RichLogTest(App):
	def compose(self):
		ri = RichLog(auto_scroll=False)
		suffix = os.environ.get('SUFFIX', 'A'*1000)
		for i in range(1, 1000):
			ri.write(f"This is line number {i} {suffix}")
		yield ri

if __name__ == "__main__":
	app = RichLogTest()
	app.run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.76.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                              |
|----------------|----------------------------------------------------|
| Version        | 3.12.5                                             |
| Implementation | CPython                                            |
| Compiler       | GCC 14.2.0                                         |
| Executable     | /path/to/venv/bin/python3 |

## Operating System

| Name    | Value                                               |
|---------|-----------------------------------------------------|
| System  | Linux                                               |
| Release | 6.10.4-amd64                                        |
| Version | #1 SMP PREEMPT_DYNAMIC Debian 6.10.4-1 (2024-08-12) |

## Terminal

| Name                 | Value         |
|----------------------|---------------|
| Terminal Application | tmux (3.4)    |
| TERM                 | tmux-256color |
| COLORTERM            | truecolor     |
| FORCE_COLOR          | *Not set*     |
| NO_COLOR             | *Not set*     |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=196, height=25 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 196                  |
| is_terminal    | False                |
| encoding       | utf-8                |
| max_height     | 25                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by TomJGooding** [comment]
I think this is the expected behaviour, otherwise the `RichLog` size would need to grow?

```python
from textual.app import App, ComposeResult
from textual.containers import Horizontal
from textual.widgets import Label, RichLog

HEIGHT_GUIDE = """\
▲
│
height=5
│
▼\
"""


class ExampleApp(App):
    CSS = """
    Screen {
        align: center middle;
    }

    Horizontal {
        height: 5;
        width: auto;
    }

    RichLog {
        height: 5;
        width: 14;
    }
    """

    def compose(self) -> ComposeResult:
        with Horizontal():
            yield RichLog(auto_scroll=False)
            yield Label(HEIGHT_GUIDE)

    def on_mount(self) -> None:
        log = self.query_one(RichLog)
        for i in range(1, 21):
            log.write(f"Line #{i}: ..........")


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by willmcgugan** [comment]
Confirmed. It actually goes all the way back to widget.py, so this would impact anything that scrolls.

Fortunately looks like an easy fix.
