### ISSUE TITLE
Reduce Textual test suite runtime

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4919]
I think there are a few easy wins in here. This is from a run that took 33s total:

<img width="831" alt="image" src="https://github.com/user-attachments/assets/7b1084fd-384d-412f-90cf-1e18cd2c6f56">

**Comment by willmcgugan** [comment]
I assume that's on CI? That top test took .46s locally.

Do you think we can get the xdist working on CI? Does it even have more than 1 core?

**Comment by darrenburns** [comment]
Nope, it's locally. If I run it without xdist it takes 2.5 seconds. With xdist as part of the full test suite the results are pretty consistent for me (tried again and got 4.98s).

For reference: `pytest --dist=loadgroup -n 16 --durations 25`

**Comment by darrenburns** [comment]
It's not concurrency because it's consistent for me even without xdist 😢 Must just be down to the different CPUs. Do you want to close this issue or review some of the tests that appear consistently here at some point?
