### ISSUE TITLE
Clearing and adding data to `DataTable` without worker will cause it to sometime not display its content.

### ISSUE THREAD

**Issue by kwevin** [Textualize/textual#4928]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
- Yes

Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**
- When clearing and adding data to `DataTable` without using a `Worker`, the `DataTable` can sometime not properly display its content.

It will be helpful if you run the following command and paste the results:

textual diagnose
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.76.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                                                                |
|----------------|------------------------------------------------------------------------------------------------------|
| Version        | 3.11.1                                                                                               |
| Implementation | CPython                                                                                              |
| Compiler       | MSC v.1934 64 bit (AMD64)                                                                            |
| Executable     | C:\Users\Kevin\AppData\Local\pypoetry\Cache\virtualenvs\listentui-qruDwX8r-py3.11\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.22621 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=125, height=31 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 125                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 31                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

https://github.com/user-attachments/assets/1aecef14-a634-4f5d-a9cc-f310ea40a41e

mre is large because it contains some data, so it is in a gist https://gist.github.com/kwevin/18a543e54ff7336bb802d711481b1d72

**Comment by willmcgugan** [comment]
Could you fix the formatting on the gist?

**Comment by TomJGooding** [comment]
It looks like the problem is the `height=None` on this line:

```python
self.table.add_row(*rows, height=None)
```

**Comment by willmcgugan** [comment]
Yeah, I concur with @TomJGooding Looks like the auto height is breaking something.

**Comment by TomJGooding** [comment]
I confess I'm struggling to follow the code, but posting my findings in case it helps someone else fix this bug.

I think the problem is that when the virtual size is calculated,  the `self._y_offsets` is an empty list:

https://github.com/Textualize/textual/blob/db3fda928ba3f4807f01ae24ecee260ce6206b1b/src/textual/widgets/_data_table.py#L1459-L1462

https://github.com/Textualize/textual/blob/db3fda928ba3f4807f01ae24ecee260ce6206b1b/src/textual/widgets/_data_table.py#L823-L826

Presumably because the `row.height` is still zero rather than the calculated height here?

https://github.com/Textualize/textual/blob/db3fda928ba3f4807f01ae24ecee260ce6206b1b/src/textual/widgets/_data_table.py#L818-L820

**Comment by mitaa** [comment]
I have quite a similar issue which might have the same cause.
Not sure if I should open a new issue for that.

When the `populate_table` method is run for the first time (on startup) everything looks correct.
When it's run for the second time (`on_data_table_cell_selected`) the auto-width of the columns is incorrect and column widths seem to correspond to the header.

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable

ROWS = [
    ("lane", "swimmer", "country", "time"),
    (4, "Joseph Schooling", "Singapore", 50.39),
    (2, "Michael Phelps", "United States", 51.14),
    (5, "Chad le Clos", "South Africa", 51.14),
    (6, "László Cseh", "Hungary", 51.14),
    (3, "Li Zhuhao", "China", 51.26),
    (8, "Mehdy Metella", "France", 51.58),
    (7, "Tom Shields", "United States", 51.73),
    (1, "Aleksandr Sadovnikov", "Russia", 51.84),
    (10, "Darren Burns", "Scotland", 51.84),
]


class ExampleApp(App):
    def compose(self) -> ComposeResult:
        yield DataTable()

    def on_mount(self) -> None:
        self.populate_table()

    def on_data_table_cell_selected(self) -> None:
        self.populate_table()

    def populate_table(self) -> None:
        table = self.query_one(DataTable)
        table.clear(columns=True)
        table.add_columns(*ROWS[0])
        table.add_rows(ROWS[1:])
        self.log.debug("Table populated")


if __name__ == "__main__":
    app = ExampleApp()
    app.run()

```

**Comment by TomJGooding** [comment]
@mitaa This looks like the same issue as #4470?

**Comment by mitaa** [comment]
@TomJGooding You're right! Sorry the confusion.
