### ISSUE TITLE
Make "escape to dismiss" optional for maximised widgets

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4949]
This will allow users to use a custom keybinding for maximising/minimising, and address the issue of "escape" potentially conflicting with other widgets bindings in maximised mode.

This could be passed in as an argument to the maximise action or method. (`escape_to_dismiss=False/True`)

**Comment by willmcgugan** [comment]
I'm thinking this should be a classvar constant on Screen. You probably know in advance if you want the escape_to_dismiss behavior
