### ISSUE TITLE
`clear_panes` and memory leak

### ISSUE THREAD

**Issue by peppedilillo** [Textualize/textual#4959]
Hello! Thanks for this wonderful framework, having a blast with it.
I seem to have a memory leak with my app. I suspect the problem to be caused by my usage of the `TabbedContent`'s method `clear_panes()`. I have a `TabbedContent` which i want to refresh every time a user provides a file input. The widget contains tabs which reference large tables. I was expecting `clear_panes()` to remove all references to the stale tabs, letting the stale tables to the garbage collector.  This doesn't seem to be happening. I have reproduced this behavior with the following MRE:

```python
from textual.app import App
from textual.widgets import Header, TabbedContent, Footer, TabPane
from textual import work


class MyTabPane(TabPane):
    def __init__(self):
        super().__init__("table")
        self.df = [1] * 100_000_000


class Explorer(App):
    BINDINGS = [
        ("ctrl+o", "add_table", "add table"),
    ]

    def __init__(self):
        super().__init__()

    def compose(self):
        yield Header(show_clock=False)
        yield TabbedContent()
        yield Footer()

    @work
    async def action_add_table(self):
        tabs = self.query_one(TabbedContent)
        tabs.loading = True
        await tabs.clear_panes()
        await tabs.add_pane(MyTabPane())
        tabs.loading = False


if __name__ == "__main__":
    app = Explorer()
    app.run()
```

Pressing `ctrl+o` repeatedly I can see an increase in the process's memory usage. I am on MacOS Ventura, iterm2.
What can I do to solve this problem with my program?
Thank you.

**Comment by willmcgugan** [comment]
Will take a look later. In the meantime you could do `del self.df` in `on_unmount`
