### ISSUE TITLE
Initial RichLog width is wrong

### ISSUE THREAD

**Issue by sealor** [Textualize/textual#4969]
The initial `RichLog` rendering uses a width of 80 characters instead of the real terminal size.

Steps to reproduce:
1. run the program -> wrong width
2. click the button "Fix text rendering" -> correct width

```python
from textual.app import App, ComposeResult
from textual.widgets import RichLog, Button

TEXT = "123456789 " * 10


class TerminalSizeBugApp(App):
    def compose(self) -> ComposeResult:
        self.call_after_refresh(self.save_screenshot)

        log = RichLog(wrap=True)
        log.write(TEXT)
        yield log
        yield Button("Fix text rendering")

    def on_button_pressed(self, event: Button.Pressed):
        self.call_after_refresh(self.save_screenshot)

        log = self.query_exactly_one(RichLog)
        log.clear()
        log.write(TEXT)


app = TerminalSizeBugApp()
app.run()
```

**Wrong width after app start:**
![TerminalSizeBugApp_2024-09-05T16_27_00_712130](https://github.com/user-attachments/assets/db2d002d-1ec8-4573-9ca9-842ffbc18414)

**Correct width after button click:**
![TerminalSizeBugApp_2024-09-05T16_27_02_255261](https://github.com/user-attachments/assets/8a834c5b-0822-4ec0-ac47-88ff9aa7dccf)

 Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.79.1 |
| Rich    | 13.8.0 |

## Python

| Name           | Value                                                                          |
|----------------|--------------------------------------------------------------------------------|
| Version        | 3.12.3                                                                         |
| Implementation | CPython                                                                        |
| Compiler       | GCC 13.2.0                                                                     |
| Executable     | /home/stefan/richlog-width-bug/.venv/bin/python |

## Operating System

| Name    | Value                                                       |
|---------|-------------------------------------------------------------|
| System  | Linux                                                       |
| Release | 6.8.0-41-generic                                            |
| Version | #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | GNOME Terminal |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=105, height=21 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 105                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 21                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
As a rule, you can only reliably use a widget in an app once it has been fully mounted. Which isn't the case in compose. The `RichLog` will not have received a Size event, so it won't know how wide it is.

You can start writing in the `on_mount`, but `compose()` should be reserved for basic configuration only, like setting attributes.

**Comment by TomJGooding** [comment]
@willmcgugan Unfortunately the same issue occurs if you write `on_mount`. I've not dived into the code yet but looks very likely related to the change introduced in PR #4223.

```python
from textual.app import App, ComposeResult
from textual.widgets import RichLog

TEXT = "123456789 " * 100


class TerminalSizeBugApp(App):
    def compose(self) -> ComposeResult:
        yield RichLog(wrap=True)

    def on_mount(self) -> None:
        log = self.query_one(RichLog)
        log.write(TEXT)


app = TerminalSizeBugApp()
app.run()
```

**Comment by darrenburns** [comment]
>I've not dived into the code yet but looks very likely related to the change introduced in PR https://github.com/Textualize/textual/pull/4223.

I checked what happens without the change in PR #4223 and the issue is still there, so I think this bug predates that.

I'm looking into this now - think there might be a bit of a chicken and egg scenario with the initial render.

**Comment by darrenburns** [comment]
So the problem is that `RichLog.write` can be called before the width of the `RichLog` is known. Inside `on_mount`, the width of the widget is still unknown. The width is only known after the first `on_resize` handler fires, and this happens after `on_mount`.

`RichLog` tries to render and cache the lines inside `write`, but since the width isn't guaranteed to be known in here, we can't cache them at the expected width.

I think we'll maybe need to defer this rendering and pre-cacheing stuff until after the width has resolved.
