### ISSUE TITLE
Revise tab-to-focus

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#497]
We have a system that shows a highlight for the focused widget for 2 seconds. When you first press tab it will show the current focus, and a second tab will advance it.

In retrospect, and after a discussion, we should remove this.

It would require that anything focusable have an explicit :focus style.

**Comment by darrenburns** [comment]
I think it would be nice to keep the means of "querying" where you currently are. In case you step away, come back, and get lost. Some apps might not make it too obvious, so it'd be nice to provide an easy way for apps to show you where you are.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
