### ISSUE TITLE
Unable to install via pip (TLS/SSL error)

### ISSUE THREAD

**Issue by MGops** [Textualize/textual#4972]
I'm following along with the stopwatch tutorial and tried to install textual but trying to install is throwing an error (see screenshot)
Is there any way to get around this? This doesn't seem to be an issue when I try to install textual on a different system.
![Screenshot from 2024-09-06 22-18-02](https://github.com/user-attachments/assets/6754e264-e4ab-4d7a-91c0-dd79ddf40589)

**Comment by arcivanov** [comment]
You have a broken python installation - nothing to do with Textual
