### ISSUE TITLE
[textual[css] Handle CSS priorities? (it could be a simple "2 levels of priority", a la "important!") As all the CSS code looks to be loaded in a flat way, we will likely need such a machinery to be able to override global styles locally here and there

### ISSUE THREAD

**Issue by DrBenton** [Textualize/textual#498]
My example case: in the "basic" sandbox app settings CSS declarations via the `CSS` field of the `TweetBody` class seem to never take precedence over the declaration of the same property in `basic.css`.

**Comment by willmcgugan** [comment]
`!important` should already work. And also CSS specificity rules...
