### ISSUE TITLE
Mock time

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#499]
We should make sure that there is only one source of time in Textual.

Ideally App should have ` get_time` function which returns the current time.

We should have a mechanism to replace the system time with an alternative time, which we can use to ensure tests are deterministic.

Suggest that App accepts a `get_time` callable which will replace `monotonic`

**Comment by darrenburns** [comment]
We already use `time_machine` in the tests, is that suitable for whatever use case you're thinking of here?

**Comment by DrBenton** [comment]
@willmcgugan yes, I'll try to integrate such a "time control" machinery to our integration test classes! :slightly_smiling_face:

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
