### ISSUE TITLE
Quitting the calculator app with the command palette causes escape sequences to be emitted at the prompt

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#5012]
Suspect this is something do to with the inline driver. We should compare it to the linux driver, to see if something is being handled differently.

**Comment by TomJGooding** [comment]
I can't seem to reproduce this issue. If this is only in iTerm, perhaps related to these lines?

https://github.com/Textualize/textual/blob/c054af8ab9fcd5957f659d77dc814f4021e0bd29/src/textual/drivers/linux_driver.py#L258-L259

**Comment by willmcgugan** [comment]
It wasn't that. There was some updates to the key reader thread that hadn't been replicated in the inline driver.
