### ISSUE TITLE
DataTable Cell Borders?

### ISSUE THREAD

**Issue by arcreigh** [Textualize/textual#5014]
Couldn't find any reference on how to style cells in a DataTable. I'd love to be able to have borders around the cells themselves to better distinguish between the data contained in the cells much like how excel will distinguish the various cells as an individual container.

**Comment by TomJGooding** [comment]
There's no way of adding borders to the cells of the `DataTable` AFAIK. 

Bear in mind that adding borders would make the table considerably less compact, as each border would require an additional row in the terminal.

For example, a table currently renders like this:

```
 lane  swimmer               country        time  
 4     Joseph Schooling      Singapore      50.39 
 2     Michael Phelps        United States  51.14 
 5     Chad le Clos          South Africa   51.14 
 6     László Cseh           Hungary        51.14 
 3     Li Zhuhao             China          51.26 
 8     Mehdy Metella         France         51.58 
 7     Tom Shields           United States  51.73 
 1     Aleksandr Sadovnikov  Russia         51.84 
 10    Darren Burns          Scotland       51.84 
```

If borders were added, it would look something like this:

```
┌──────┬──────────────────────┬───────────────┬───────┐
│ lane │ swimmer              │ country       │ time  │
├──────┼──────────────────────┼───────────────┼───────┤
│ 4    │ Joseph Schooling     │ Singapore     │ 50.39 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 2    │ Michael Phelps       │ United States │ 51.14 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 5    │ Chad le Clos         │ South Africa  │ 51.14 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 6    │ László Cseh          │ Hungary       │ 51.14 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 3    │ Li Zhuhao            │ China         │ 51.26 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 8    │ Mehdy Metella        │ France        │ 51.58 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 7    │ Tom Shields          │ United States │ 51.73 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 1    │ Aleksandr Sadovnikov │ Russia        │ 51.84 │
├──────┼──────────────────────┼───────────────┼───────┤
│ 10   │ Darren Burns         │ Scotland      │ 51.84 │
└──────┴──────────────────────┴───────────────┴───────┘
```

**Comment by arcreigh** [comment]
The need stems from a data dense display of source / destination / ports for firewall rules. Being able to very clearly distinguish one policy from another in the table is quite important as is the ability to dynamically expand / contract the height / width of a cell to fit that content at least in my particular need.

**Comment by willmcgugan** [comment]
Do you need the table widget? You can easily build something table-like with widgets. That way you can have borders and collapsible sections without any effort.

**Comment by willmcgugan** [comment]
I don't think borders on cells would be a good idea. As Tom pointed out, they would use a lot of space.

Zebra striping is useful to help separate lines.

I'd suggest you jump on the Discord server. If you give us more details, I'm sure there would be plenty of suggestions for the UI you are building.
