### ISSUE TITLE
`inline_no_clear` broken in v0.77.0

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#5019]
It looks like the `inline_no_clear` option was broken in v0.77.0, from a quick git bisect the culprit seems to be commit 8c01ef7.

If you run the app below where `inline_no_clear=True`, the app output is cleared on exit:

```python
from textual.app import App, ComposeResult
from textual.widgets import Static


class InlineNoClearApp(App):
    def compose(self) -> ComposeResult:
        yield Static("Quitting should not clear the app output")


if __name__ == "__main__":
    app = InlineNoClearApp()
    app.run(inline=True, inline_no_clear=True)

```

**Comment by machin3io** [comment]
Still broken in 0.79.1 FWIW 

Hope it can be fixed soon.
