### ISSUE TITLE
Crash when instancing a SelectionList with disabled=True

### ISSUE THREAD

**Issue by dmunozv04** [Textualize/textual#5028]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed Yes

Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. 

Attempting to instance a SelectionList with the argument `disabled=True` will crash Textual. This change seems to have been introduced in v0.71 since I'm unable to replicate it on v0.70 or previous versions.
I've attached the full crash log as well as a minimal python script that replicates the issue described. 
```python
from textual.app import App
from textual.widgets import SelectionList

class TestApp(App):
    def compose(self):
        yield SelectionList(
            ("Simple SelectionList", "", False), # Doesn't even need to have options to crash
            disabled=True
        )

app = TestApp()
app.run()
```
[error.txt](https://github.com/user-attachments/files/17083874/error.txt)

Please do let me know if you need anything else from me

It will be helpful if you run the following command and paste the results:

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.79.1 |
| Rich    | 13.8.1 |

## Python

| Name           | Value                                                              |
|----------------|--------------------------------------------------------------------|
| Version        | 3.12.6                                                             |
| Implementation | CPython                                                            |
| Compiler       | Clang 15.0.0 (clang-1500.3.9.4)                                    |
| Executable     | /Users/david/Documents/GitHub/iSponsorBlockTV/.venv/bin/python3.12 |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 24.0.0                                                                                                |
| Version | Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.93.1) |
| TERM                 | xterm-256color  |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=100, height=32 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 100                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 32                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

If you don't have the `textual` command on your path, you may have forgotten to install the `textual-dev` package.

Feel free to add screenshots and / or videos. These can be very helpful!

**Comment by TomJGooding** [comment]
It looks like this isn't just an issue with the `SelectionList`, but other widgets too with a `notify_style_update` method where their caches haven't yet been initialised.

Should the `super()` call be moved to last...?


### AttributeError: 'DataTable' object has no attribute '_row_render_cache'

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable


class ExampleApp(App):
    def compose(self) -> ComposeResult:
        yield DataTable(
            disabled=True,
        )


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

### AttributeError: 'RichLog' object has no attribute '_line_cache'

```python
from textual.app import App, ComposeResult
from textual.widgets import RichLog


class ExampleApp(App):
    def compose(self) -> ComposeResult:
        yield RichLog(
            disabled=True,
        )


if __name__ == "__main__":
    app = ExampleApp()
    app.run()
```

**Comment by dmunozv04** [comment]
Thanks for fixing it @willmcgugan !
