### ISSUE TITLE
Binary encoding of devtools packets

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#506]
The devtools console is awesome and I use it a lot.

It will tend to slow down when there is a lot of data going through. We should use a binary protocol to avoid some additional work encoding / decoding. `msgpack` would be ideal for this.

Should be a simple change.

**Comment by DrBenton** [comment]
I've heard of msgpack but haven't used it myself yet, however I've used [CBOR](https://cbor.io/) quite a lot (via [this Python library](https://cbor2.readthedocs.io/en/latest/index.html)) and it works well too :slightly_smiling_face: 
Could be worth trying with both, and see what produces the most compact/efficient payload?

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
