### ISSUE TITLE
pop_until_active causes ScreenResume to be posted even though "transitional" screens won't be visible

### ISSUE THREAD

**Issue by mzebrak** [Textualize/textual#5086]
Please consider the following test. ScreenResume should be "logged" just 2 times, but is 4 times, because ScreenResume happens when "dismissing" multiple screens via "pop_until_active".

```python
from __future__ import annotations

from typing import TYPE_CHECKING

from textual import on
from textual.app import App, ComposeResult
from textual.events import ScreenResume
from textual.reactive import var
from textual.screen import Screen
from textual.widgets import Label

if TYPE_CHECKING:
    from textual.pilot import Pilot


async def test_screen_resume() -> None:
    class BaseScreen(Screen):
        def compose(self) -> ComposeResult:
            yield Label("BASE")

    class FooScreen(Screen):
        def compose(self) -> ComposeResult:
            yield Label()

        @on(ScreenResume)
        def log_resume(self) -> None:
            self.app.resumed.append(True)

    class BarScreen(Screen):
        BINDINGS = [("b", "app.make_base_active")]

        def compose(self) -> ComposeResult:
            yield Label()

    class PopApp(App):
        SCREENS = {"base": BaseScreen}
        
        resumed = var([])

        async def on_mount(self) -> None:
            # Push base
            await self.push_screen("base")
            # Push two screens
            await self.push_screen(FooScreen())
            await self.push_screen(FooScreen())
            await self.push_screen(BarScreen())

        def action_make_base_active(self) -> None:
            self.get_screen("base").pop_until_active()

    async with PopApp().run_test() as pilot:
        pilot: Pilot
        await pilot.press("b")
        assert len(pilot.app.resumed) == 2
```

**Comment by willmcgugan** [comment]
The is the correct behavior.

Perhaps you can say why you think it should be otherwise. And please make your MREs runnable.

**Comment by mzebrak** [comment]
Why would notifying the screen that it's active when it's not active for even a fraction of a second be the correct behavior?

If there is a good reason for this, please provide it. In my opinion this is incorrect behavior because this intermediate screen can define some actions for this event and why should they occur when transitioning between screens during that multiple dismiss. Since it will be destroyed in a moment, why should it react?

**Comment by willmcgugan** [comment]
The intermediate screens will briefly be the active screen. Screens can make the assumption that it will receive resume and suspend.

An MRE should run with just python.

@mzebrak We want to help you, but your issues are getting close to time-wasting. I'd suggest you first ask questions on Discord before assuming something is a bug. Additionally, if you explain *why* you want something or expect it to work a certain way, you will get a satisfactory response quicker.

**Comment by mzebrak** [comment]
> An MRE should run with just python.

I don't believe that pytest is a problem here when Textual supports pytest and bases its tests on it as well.
In this case, instead of writing the steps for reproduction, it's probably easier and faster to understand it on the assertion.

I'm sorry you have to say that when I'm trying my best to explain to you what the problem is. I feel like I'm treated in advance here because a good example of that is also closing the https://github.com/Textualize/textual/issues/5064 without a fix or a word despite the "silent crash" that I found.

If your opinion is correct behavior, please close this issue. My opinion is that informing the screen which will be removed in a moment and taking some action on it is an unnecessary performance waste. I think, I have the right to express it, especially since we operate in an open-source environment. I'm not posting here to harm Textual...

**Comment by willmcgugan** [comment]
You haven't explained what problem this is causing for you. And you haven't said why you think it should behave this way. We simply have nothing to work with.

Most of your other issues are like this. I mean you never once asked how to dismiss a number of screens to get back to a desired screen. 

If Textual is important to your work, and I assume it is, you will need to start cooperating with is. Have a look at the 100s of closed issues that go smoothly for inspiration.
