### ISSUE TITLE
Strange widget border in 256-color terminal

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#5101]
I noticed that the `Checkbox` widget now has a strange border in urxvt. I assume this is specific to 256-color terminals, as I couldn't replicate the issue in other modern emulators.

Here's screenshots of the checkbox.py example before and after Textual 0.80.0:

| Before v0.80.0  | After 0.80.0 |
| ------------- | ------------- |
| ![Before v0.80.0](https://github.com/user-attachments/assets/310d4359-0cf0-4cfc-8d89-961829ad76f8)  | ![After 0.80.0](https://github.com/user-attachments/assets/a25239dc-e7dd-4c67-9064-5e5e940035e0) |

**Comment by TomJGooding** [comment]
After some further testing, I found other widgets also have this issue:

| Before v0.80.0  | After 0.80.0 |
| ------------- | ------------- |
| ![Before v0.80.0](https://github.com/user-attachments/assets/846a692c-d539-43cc-afc2-80f24abff256) | ![After 0.80.0](https://github.com/user-attachments/assets/a281231b-01fa-47a7-b141-4df769b077a5) |

**Comment by TomJGooding** [comment]
Reverting commit 17097e6 seems to fix this issue, although I don't understand why as the only change was reversing the foreground and background colors. This also doesn't seem to explain why this strange border only appears on the left.

**Comment by darrenburns** [comment]
I can see similar artifacts in iTerm 2 - but only when the app itself does not have focus:

<img width="236" alt="image" src="https://github.com/user-attachments/assets/d165566f-b24c-48c4-af0d-4b56f0ea76f0">

**Comment by willmcgugan** [comment]
I suspect a bug in urxvt. There was a change in how some borders were rendered recently, but I'm pretty sure urxvt is doing something wrong with the control sequences given.

Will keep the issue open. At some point I'll dig out a linux VM and give it a try.

**Comment by TomJGooding** [comment]
Interesting, apparently trying to reverse the same background/foreground color does produce unexpected results. I wonder if this is specific to urxvt then!

![image](https://github.com/user-attachments/assets/df87fcb8-b1fe-4536-be2d-4d968f8729f7)


```python
from rich.console import Console
from rich.style import Style
from rich.text import Text

red_on_red_style = Style(color="red", bgcolor="red")
reversed_style = red_on_red_style + Style(reverse=True)

console = Console()
console.print(Text("Red on red", style=red_on_red_style))
console.print(Text("Reversed", style=reversed_style))
```

**Comment by willmcgugan** [comment]
Yeah. It looks like it ignores colours when the reverse style is set!

**Comment by TomJGooding** [comment]
After some digging into the urxvt CVS, it looks like this was an intentional design decision. Shame as otherwise Textual works well in urxvt, but maybe time to switch to a more modern emulator! Closing.

> 	- text with background==foreground colour gets displayed with default
> 	  bg/fg now when in reverse video, so it can be seen when selecting.
