### ISSUE TITLE
Doesn't work in VSCode terminal

### ISSUE THREAD

**Issue by o9zs** [Textualize/textual#5142]
Textual doesn't work in the VSCode built-in terminal. It runs, but the buttons aren't clickable and the containers aren't scrollable.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.83.0 |
| Rich    | 13.7.1 |

## Python

| Name           | Value                                                            |
|----------------|------------------------------------------------------------------|
| Version        | 3.11.5                                                           |
| Implementation | CPython                                                          |
| Compiler       | MSC v.1936 64 bit (AMD64)                                        |
| Executable     | C:\Users\opzs\AppData\Local\Programs\Python\Python311\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19045 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | vscode (1.94.2) |
| TERM                 | *Not set*       |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=189, height=48 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 189                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 48                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment]
This is a known issue with VSCode on Windows 10,  I'm afraid.

https://github.com/Textualize/textual/issues/1031
