### ISSUE TITLE
TextArea code editor freezes the app

### ISSUE THREAD

**Issue by Klavionik** [Textualize/textual#5151]
Hey again. :)

Mounting the TextArea code editor with any code other than the comment freezes my terminal. I tried several versions of Textual, I tried running it both on Mac and Linux and using Python 3.10 and 3.12. It freezes every time. I then tried an example from the docs and it freezes too.

An MRE:
```python
from textual.app import App, ComposeResult
from textual.widgets import TextArea

# OK_TEXT = "# OK"
FAIL_TEXT = "x = 1"


class CodeApp(App):
    def compose(self) -> ComposeResult:
        yield TextArea.code_editor(FAIL_TEXT, language="python")


if __name__ == "__main__":
    app = CodeApp()
    app.run()
```

If you replace usage of `FAIL_TEXT` with `OK_TEXT`, it doesn't freeze. Somehow it doesn't freeze with `FAIL_TEXT` too if you set `show_line_numbers=False`.

I tried investigating it a bit myself and I found out that the freeze happens because of the `while True` loop in `rich.segment.Segment._split_cells`: it keeps counting `pos` down and never stops. I'm not sure why, though. And I still don't know why the comment works alright even with the line numbers. 

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.83.0 |
| Rich    | 13.9.2 |

## Python

| Name           | Value                                                  |
|----------------|--------------------------------------------------------|
| Version        | 3.12.3                                                 |
| Implementation | CPython                                                |
| Compiler       | GCC 11.4.0                                             |
| Executable     | /home/jediroman/Desktop/textarea-mre/.venv/bin/python |

## Operating System

| Name    | Value                                        |
|---------|----------------------------------------------|
| System  | Linux                                        |
| Release | 5.15.0-122-generic                           |
| Version | #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 |

## Terminal

| Name                 | Value                              |
|----------------------|------------------------------------|
| Terminal Application | WezTerm (20230712-072601-f4abf8fd) |
| TERM                 | xterm-256color                     |
| COLORTERM            | truecolor                          |
| FORCE_COLOR          | *Not set*                          |
| NO_COLOR             | *Not set*                          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=105, height=25 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 105                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 25                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by darrenburns** [comment]
Hi, thanks for the report. I can't reproduce this.

Could you please share the full error output?

**Comment by TomJGooding** [comment]
@darrenburns This freeze only seems to happen with the latest rich version 13.9.2.

**Comment by darrenburns** [comment]
Yeah, I tried with Rich 13.9.2 and Textual v0.83.0 (and `main`). There must be some specific condition causing the crash. The width of the TextArea maybe? 🤷

**Comment by TomJGooding** [comment]
Bizarre! After testing working through the alphabet, "o" doesn't seem to crash but "p" does...

**Comment by TomJGooding** [comment]
After being nerd sniped by this, I couldn't help trying to dig a bit deeper. I found this line in [rich/rich/cells.py](https://github.com/Textualize/rich/blob/0f2f51b872d14588de3a65968f5cdde6fb5694a3/rich/cells.py#L10):

```python
_is_single_cell_widths = re.compile("^[\u0020-\u006f\u00a0\u02ff\u0370-\u0482]*$").match
```
This might explain why this only seems to occur with certain characters, since this doesn't seem to include lowercase p-z?

**Comment by willmcgugan** [comment]
Bravo, Tom!

**Comment by darrenburns** [comment]
Thank you Tom, I will sleep tonight!!

**Comment by willmcgugan** [comment]
How did you get there so fast @TomJGooding ? We were bamboozled by this.
