### ISSUE TITLE
TreeNode is not "exported" from textual.widgets (or another public module)

### ISSUE THREAD

**Issue by Hnasar** [Textualize/textual#5168]
I want to have type checking but avoid importing `textual.widgets._tree.TreeNode`. Unfortunately `textual.widgets.TreeNode` isn't something that is importable or exported.

This seems like a duplicate of https://github.com/Textualize/textual/issues/992 but I'm not sure if there was a regression, or if the issue was never actually fixed.

Using 0.73.0 

```
$ python -c 'from textual.widgets import TreeNode'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/venvs/versioned/algovenv11-1.0.95/lib/python3.10/site-packages/textual/widgets/__init__.py", line 103, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'TreeNode'


$ python -c 'from textual.widgets._tree import TreeNode'
```

**Comment by willmcgugan** [comment]
You are running on quite an old version of Textual. Although that probably has no bearing the import, which is as follows:

```python
from textual.widgets.tree import TreeNode
```

**Comment by Hnasar** [comment]
Oh thank you! I missed this `tree.py` vs `_tree.py` when looking through.
