### ISSUE TITLE
Running Textual tests opens links in my web browser?

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#5169]
This is a bit of a weird one and might just be some issue in my setup! After pulling the latest changes, I was a bit concerned when links started opening in my web browser! This includes `http://tété/`, `https://test.md/#first` and filepaths like `/textual/#second`

Anyone else experiencing this or have any idea what the issue might be?!

**Comment by willmcgugan** [comment]
I suspect that is because I changed the Markdown widgets to open urls by default. We probably need to set `open_links = False` on the Markdown tests.

**Comment by TomJGooding** [comment]
Oof, thanks Will that explains it! Fix incoming...!

**Comment by TomJGooding** [comment]
Perhaps I should raise a separate issue for this, but I'm wondering if opening links by default is actually a good idea?

Markdown links might not be websites but actually other documents on the disk. For example, now running `examples/markdown.py` and clicking the `example.md` link will try to open this in the browser.

**Comment by willmcgugan** [comment]
It was added recently, because too many users expected it and were opening issues.

The problem is that it is ambigious. is markdown.md a file or https://markdown.md ?

I'm not disagreeing though. The default behavior should be the least astonishing -- whatever that may be. Anything else, the dev can handling the appropriate event.

**Comment by TomJGooding** [comment]
Damned if you do and damned if you don't!

My concern is that internal links are probably more common than external links, so this will just open new issues.

Perhaps there's some compromise, or the documentation can be improved on handling markdown links.

**Comment by TomJGooding** [comment]
Thankfully `test.md` wasn't malicious, but perhaps also worth considering whether potentially opening all `.md` domains by default is a good idea.
