### ISSUE TITLE
Implement synchronised output

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#517]
We use an iTerm extension for this, but there is a new emerging standard.

https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036

The idea is you tell the terminal that an update is about to begin, which defers rendering. You then write some output, and issue the command to end the update. The terminal will then update the screen. This should reduce flickering on terminals where it is supported.

The link above describes how to auto-detect this feature.

Here's the current (deprecated) spec, which we are currently using:

https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec

**Comment by DrBenton** [comment]
Ready for review! :slightly_smiling_face:  #533

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
