### ISSUE TITLE
unofficial support for Python 3. 6 ?

### ISSUE THREAD

**Issue by dirkpetersen** [Textualize/textual#519]
To be added by @willmcgugan

The problem: Python 3.6 is the official python on RHEL8 
https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8-3

On shared environments (e.g. HPC) the users do not have root access but can install their own Python in a shared folder or their home directory which are typically not on the local disk. Launching a big python stack from a network location can add 1-2 seconds of latency at startup and makes many command line and TUI tools less fun to work with. Sysadmins are likely not going to upgrade the system python3 as there are many dependencies. 

Is there any unofficial support for Python 3.6 ?  is there a way to hack this ?

**Comment by willmcgugan** [comment]
Afraid not. It's too much of a burden to support 3.6

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
