### ISSUE TITLE
Linux driver input thread freeze

### ISSUE THREAD

**Issue by daler-rahimov** [Textualize/textual#520]
When there is an error while capturing input from a terminal, current linux driver thread quietly logs the error (with app.log) and exits, meanwhile TUI becomes completely unresponsive. It's very hard to notice what went wrong in this situation. It took me quite a long time to realize that some other peace of code was redirecting stdin (fd 0) for a short time. Maybe it's better to app.panic when this happens 

https://github.com/Textualize/textual/blob/94944f7054fe50cc8ddd86134724c312c71d46f7/src/textual/drivers/linux_driver.py#L207

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
