### ISSUE TITLE
Textual in docker containers

### ISSUE THREAD

**Issue by gabriele-costa** [Textualize/textual#5231]
When running Textual apps in docker containers strange characters appear on screen.

Minimal Dockerfile to reproduce
```
FROM python:3.9-slim

RUN pip install textual textual-dev

COPY main.py main.py

CMD ["python3", "main.py"]
```

Where main.py contains

```
from textual.app import App
from textual.widgets import Button

class Test(App):
    def compose(self):
        yield Button("Hi")

if __name__ == "__main__":
    Test().run()
```

When moving the mouse pointer over the terminal, numbers appear. They seem like screen coordinates.

**Comment by TomJGooding** [comment]
Those strange characters are the ANSI escape sequences that control the terminal.

I'm not super familiar with docker, but how are you running the container? For example, are you using the `i` (interactive) or `t` (tty) flags?

**Comment by gabriele-costa** [comment]
You are right, the -t flag apparently solved the issue (which perfectly makes sense since the terminal type clearly matters). Thank you very much for your kind and prompt answer
