### ISSUE TITLE
string '=2s' shows up in Footer on remote terminals

### ISSUE THREAD

**Issue by rhuygen** [Textualize/textual#526]
This is a report of some strange behaviour in a remote terminal (ssh session to a Linux machine). The video shows that when I press '?' to show the help widget on the right of the terminal [at 13s], the Footer disappears and shows a string '=2s'. When closing the help widget, the Footer doesn't restore, it only restores when I scroll again in the _Records_ panel [at 22s]. The header seems to refresh. The problem does not occur in a local Terminal (on my macOS).

https://user-images.githubusercontent.com/6662864/169052522-e4d1c576-1206-4594-bee8-e859caf65b1e.mp4

Could it be that I have to explicitly refresh the Footer?

**Comment by rhuygen** [comment]
I just checked and the same behaviour shows when running the textual showcase app and press 'b' to toggle the sidebar:
```
python -m textual.app
```

**Comment by Precision-Tech** [comment]
I have experienced this same exact behavior. On the local terminal it works as expected, but on a remote terminal (PuTTY in my case) this '=2s' string appears and the footer disappears until scrolling.

**Comment by willmcgugan** [comment]
This is fixed in the CSS branch.

**Comment by pythonpray** [comment]
> hi, Can you provide the SHA hash or information of the fixed commit?   I can copy it to my local and use it in the 0.1.18 version

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
