### ISSUE TITLE
The themes don't look the same as it is in the docs.

### ISSUE THREAD

**Issue by grvstick** [Textualize/textual#5263]
#### Textual: 0.86.3

The [Link](https://textual.textualize.io/guide/design/#__tabbed_1_4) shows how default theme(textual dark) should look like

After the recent update the default screen looks like this, which is slightly different. It changed all of my previous projects as well, like borderline with $accent CSS would show yellow rather than blue.
![image](https://github.com/user-attachments/assets/ccbcf249-f970-410c-bebf-ec66911416b7)

**Comment by willmcgugan** [comment]
The change to color constants are to be expected. You should be able to fix your app with a search and replace, if you have any problems with that we can help (best to try the Discord server).

The screenshot looks to me like Windows Terminal is using 256 color mode. Which you may be able to fix by upgrading Windows Terminal to the latest version.

If that doesn't fix it, please paste the output of `textual diagnose`
