### ISSUE TITLE
Issue after Bind [ctrl + s]

### ISSUE THREAD

**Issue by yorevs** [Textualize/textual#5271]
Hello everyone,

I used the combination [Ctrl+s] to bind functionality to my footer:

("ctrl+s", "stop", " Stop-GenAi"),

When I hit that inside the Input widget, I got strange behavior. All the TUI gets unresponsive and even Ctrl+c and Ctrl+d no longer work. Instead, I keep getting VT100 escape codes, as demonstrated in the attached GIF.

![ss-ctrl+s-issue](https://github.com/user-attachments/assets/5e41d84d-84f3-4d3c-bf0d-79998468bfa2)

**Comment by willmcgugan** [comment]
What does your `action_stop` message do?

Can you paste the output of the following command:

```
textual diagnose
```

**Comment by yorevs** [comment]
> What does your `action_stop` message do?
> 
> Can you paste the output of the following command:
> 
> ```
> textual diagnose
> ```
```
async def action_stop(self) -> None:
    """Stop generating response."""
    self.askai.abort()
    self.enable_controls()
```

Abort method:
https://github.com/yorevs/askai/blob/d0ea1346878a542333579c48d1cbcf9862d103fe/src/main/askai/core/askai.py#L123

Enable controls:
https://github.com/yorevs/askai/blob/d0ea1346878a542333579c48d1cbcf9862d103fe/src/main/askai/tui/askai_app.py#L212

-bash: textual: command not found

I'm using version 0.86.3

**Comment by willmcgugan** [comment]
You'll need to installed `textual-dev` for the command.

The most likely cause for this is that you are writing ansi escape sequences, which will almost certainly break something.

**Comment by yorevs** [comment]
Removing the Asc fixed the issue. thanks
