### ISSUE TITLE
Select - incorrect width calculation for SelectOverlay

### ISSUE THREAD

**Issue by MorningLightMountain713** [Textualize/textual#5280]
When setting `width: auto` for the SelectOverlay - it miscalculates the width by 2 every time. So the longest item in the select list is always split over 2 lines.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.86.3 |
| Rich    | 13.9.3 |

## Python

| Name           | Value                                                      |
|----------------|------------------------------------------------------------|
| Version        | 3.12.3                                                     |
| Implementation | CPython                                                    |
| Compiler       | Clang 13.0.0 (clang-1300.0.29.30)                          |
| Executable     | /Users/davew/code/flux/flux_iso_installer/.venv/bin/python |

## Operating System

| Name    | Value                                                                                               |
|---------|-----------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                              |
| Release | 24.2.0                                                                                              |
| Version | Darwin Kernel Version 24.2.0: Sun Nov  3 20:54:52 PST 2024; root:xnu-11215.60.405~54/RELEASE_X86_64 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.5.10) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=145, height=38 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 145                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 38                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

Here is an MRE:

```python
from textual.app import App, ComposeResult
from textual.widgets import Select


class TallSelectApp(App[None]):
    CSS = """
        Screen {
            align: center middle;

            & > Select {
                width: 50;

                & > SelectOverlay {
                    max-height: 100vh;
                    width: auto;
                }
            }
        }
    """

    def compose(self) -> ComposeResult:
        yield Select(
            [(f"Option {idx + 1}", idx) for idx in range(100)]
            + [("Extra long option here", 100)],
            value=25,
        )


TallSelectApp().run()
```

Visual:

![Screenshot 2024-11-24 at 4 47 05 PM](https://github.com/user-attachments/assets/767680f3-046e-4ae4-ba7a-cd2265f5b409)

**Comment by Zaloog** [comment]
Hi, @MorningLightMountain713 
This has to do with the padding of the `.option-list--option` [source](https://github.com/Textualize/textual/blob/df8ffb12d204db276ece2f414b364bdad3bd31ac/src/textual/widgets/_select.py#L228-L230)
if you set that to 0 it fits.

![image](https://github.com/user-attachments/assets/a761fb3b-20d2-4a7a-89b2-4c6233d745a7)

**Comment by willmcgugan** [comment]
Try v0.87.1

**Comment by MorningLightMountain713** [comment]
> Try v0.87.1

Amazing. Thank you
