### ISSUE TITLE
Horizontal scroll bar disappeared in 0.87.1

### ISSUE THREAD

**Issue by pablogsal** [Textualize/textual#5284]
We have a bunch of test failures due to textual in the 0.87.1 version. It seems that textual 0.87.1 has some regression that makes the horizontal scroll bar disappear. Here is some screenshots from our 

## BEFORE

![Screenshot 2024-11-25 at 15 56 01](https://github.com/user-attachments/assets/2ccfe97b-0ef9-42bf-8c02-1dd7c638da4b)

## AFTER

![Screenshot 2024-11-25 at 15 56 15](https://github.com/user-attachments/assets/ace9c871-ebad-47c2-81c6-9f34995e2788)

This also happens in the main `memray` app and makes impossible for users to scroll horizontally the table:

![Screenshot 2024-11-25 at 15 57 10](https://github.com/user-attachments/assets/12fb3be9-2535-4aa0-bbe8-8e2d548b6d53)

**Comment by pablogsal** [comment]
One example of the test failing is: https://github.com/bloomberg/memray/blob/12cfcfe7c04280457d05725952b382447dbf4867/tests/unit/test_tui_reporter.py#L794

**Comment by pablogsal** [comment]
After some investigation seems that the horizontals scrollbar only appears when the external scrollbar is at the bottom:
![Screenshot 2024-11-25 at 15 59 19](https://github.com/user-attachments/assets/186e6030-6012-40dc-8d68-7c6fbe610936)

and after scrolling:
![Screenshot 2024-11-25 at 15 59 31](https://github.com/user-attachments/assets/d9223b8d-abe5-45df-947a-a07518d73a81)

Some users have mentioned that this is a bit confusing because unless you scroll the second scrollbar in our app it looks like you can't scroll horizontally.

**Comment by willmcgugan** [comment]
I can't think of anything off the top of my head that would cause this. What was the last known working version?

**Comment by pablogsal** [comment]
I think this happened after https://github.com/Textualize/textual/pull/5000

**Comment by pablogsal** [comment]
> What was the last known working version?

0.81

**Comment by willmcgugan** [comment]
That release did unfortunately break snapshots, but I don't think that is the issue here.

You have the following rule in your TCSS:

```
.narrow AllocationTable {
  height: 100%;
}
```

It looks like `narrow` class is added when the width is less than 80, to make the UI responsive.

The rule makes the table 100% of the container. There are other things in the container, so the total height is greater than 100%, which forces the screen to scroll. If the table also has to scroll, then you would get the confusing double scrollbars.

If you remove that rule, then it works more naturally. Maybe add a keybinding to [maximize](https://textual.textualize.io/api/screen/#textual.screen.Screen.maximize) the table?

**Comment by godlygeek** [comment]
Ah, the change here isn't whether or not the horizontal scrollbar is visible, it's the position of the vertical scrollbar, and how focusing widgets works. The horizontal scrollbar for the grid was never visible when the outermost vertical scrollbar was scrolled up, but we used to wake up with the AllocationTable focused and the outermost vertical scrollbar scrolled to the bottom:

![image](https://github.com/user-attachments/assets/c46e3e9f-94da-47ab-ae2b-80dd75953cc0)

And now we wake up with that vertical scrollbar scrolled to the top instead:

![image](https://github.com/user-attachments/assets/b7db60c7-125d-4f30-af8a-9e507afa54b5)

Bisecting tells me that this change came in e157c6b2b14f57fa825fe1fb3852aebe0b858e3b - you can reproduce for yourself with a `pip install memray` and then
```sh
memray run --live -c "import mmap; mmap.mmap(-1, 4096)"
```
in a 80x24 terminal window.

Moreover, pressing `<Tab>` should toggle between having the AllocationTable focused and having the Header focused. Prior to e157c6b2b14f57fa825fe1fb3852aebe0b858e3b the first time you pressed `<Tab>` the outermost vertical scrollbar would jump to the top (scrolling to the start of the Header widget), and pressing it a second time would cause the outermost vertical scrollbar to jump to the bottom (scrolling to the start of the AllocationTable widget, and returning what was shown when the TUI first started).

After e157c6b2b14f57fa825fe1fb3852aebe0b858e3b the first time you press `<Tab>` has no visual effect whatsoever - the outer vertical scrollbar doesn't move at all. But pressing it a second time causes the AllocationTable to be focused and scrolled to the way we want it to be, and future tabs toggle between the two widgets as we'd expect.

**Comment by godlygeek** [comment]
The `AllocationTable` calls `table.focus()` in its `compose()`, which is the thing that has up until now been successfully causing the `.narrow` styled TUI to wake up with the `AllocationTable` taking up 100% of the screen on wakeup, with the outer vertical scrollbar scrolled to the bottom. But e157c6b seems to have broken that (by delaying the resize, I suppose?)

**Comment by godlygeek** [comment]
That doesn't seem to work. I've added
```
*:focus {
  background: magenta;
}
```
to the TCSS to make it immediately obvious which widget is focused, and putting `AUTO_FOCUS = "DataTable"` into the screen (`DataTable`, not `AllocationTable`, since the `.focus()` we were calling explicitly up until now was on the `DataTable` contained within the `AllocationTable`), I see the exact same behavior as we're getting from calling `.focus()` - the data table widget is focused, but we're not scrolled to it as we should be.

**Comment by godlygeek** [comment]
In fact, `AUTO_FOCUS` doesn't do what we want even in older versions of Textual - it does focus the widget, but doesn't seem to scroll so that the widget takes up 100% of the screen like we want, even before https://github.com/Textualize/textual/commit/e157c6b2b14f57fa825fe1fb3852aebe0b858e3b.

**Comment by godlygeek** [comment]
Any other suggestions, @willmcgugan?

**Comment by godlygeek** [comment]
Prior to e157c6b2b14f57fa825fe1fb3852aebe0b858e3b that seems to work 100% of the time, but after e157c6b2b14f57fa825fe1fb3852aebe0b858e3b that seems to _sometimes_ work, and sometimes not. It seems to be racy... the widget always winds up focused, but it's only scrolled to about 75% of the time in my testing.

Presumably it's still the same issue - the focus() call is sometimes happening before the data table has been resized to the height we want...

**Comment by godlygeek** [comment]
And unfortunately it seems to work 100% of the time if I `textual run --dev`, which reinforces the idea that it's still racy, but makes it harder to confirm...

**Comment by TomJGooding** [comment]
Here's my attempt at creating an MRE in case it helps someone...

```python
from textual import events
from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Static


class Placeholder(Static, can_focus=True):
    DEFAULT_CSS = """
    Placeholder {
        &:focus {
            background: $success;
        }
    }
    """


class ExampleScreen(Screen):
    def compose(self) -> ComposeResult:
        yield Placeholder("Header", id="header")
        yield Placeholder("Table", id="table")

    def on_show(self) -> None:
        self.call_after_refresh(self.query_one("#table").focus)


class ExampleApp(App):
    CSS = """
    #header {
      height: 7;
    }

    .narrow #header {
      height: 11;
    }

    #table {
      height: 1fr;
    }

    .narrow #table {
      height: 100%;
    }
    """

    def on_mount(self) -> None:
        self.push_screen(ExampleScreen())

    def on_resize(self, event: events.Resize) -> None:
        self.set_class(0 <= event.size.width < 81, "narrow")


if __name__ == "__main__":
    app = ExampleApp()
    app.run()

```

**Comment by willmcgugan** [comment]
The App resize event is being sent after the auto focus. I'm working on a fix.

A workaround, which won't require the `call_after_refresh` would be to move the resize handler from App to your Screen. Or you could wait a day or two for a new release.

**Comment by godlygeek** [comment]
I can confirm that #5296 fixes this for us. Thanks for the help!
