### ISSUE TITLE
[textual][bug] Mouse events not managed correctly when a widget has both a horizontal and a vertical scrollbars

### ISSUE THREAD

**Issue by olivierphi** [Textualize/textual#530]
We can tweak the `sandbox/basic.css` to reproduce the bug:
 - change `overflow-y: auto;` to `overflow: auto;` for the _Tweet_ selector
 - change `width: 100%;` to `width: 130%;` for the _TweetBody_ selector

Then playing with both the scrollbars reveals the issue

Quick demo:

https://user-images.githubusercontent.com/722388/169296947-f23106eb-e7f9-464b-b1cf-5a7dc98ceefa.mp4

**Comment by willmcgugan** [comment]
Strange!

**Comment by willmcgugan** [comment]
I think this may be fixed.
