### ISSUE TITLE
Add a way to remove nodes from a TreeController/TreeNode

### ISSUE THREAD

**Issue by PhilipVinc** [Textualize/textual#531]
To be added by @willmcgugan

I have recently been playing with extending the `DirectoryTreeView` and adding live-refresh capabilities with `watchdog`, and I realised that while it's possible to add new nodes, there's no way to easily remove them in the API.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
