### ISSUE TITLE
Feature request / question: Get modifier keys on keyboard event

### ISSUE THREAD

**Issue by novak-services** [Textualize/textual#5318]
To fully support the keyboard in my application, I would need to be able to get the current state of the modifier keys (shift,control,meta).

The key event does not provide that. For example if I press the return key, I see no difference if I press return with or without space key.

Interestingly Mouse events seem to support it, but I do not want to wait for a mouse event to fire -- the interactions should be triggered from the keyboard alone.

It also could be a separate function to get that state, but it really would make my application possible, since I would need to find another way of implementing it, if it is not possible in textual.

Is there a way to do that already (I scanned the documentation and FAQ but found nothing yet)? If not, would it be possible to integrate such a functionality in reasonable time?

Could that be available with "Extended keys" #3411 ? That would also be a possibility for me, to use such a terminal, but I saw no possibility to integrate it into the current Key event structure, so I did not try a terminal with that support yet.

Any response would be appreciated.

**Comment by willmcgugan** [comment]
Modifiers are encoded in the key name, but you will need a terminal that supports the extended key protocol to use them.

<img width="1519" alt="Screenshot 2024-12-02 at 16 38 44" src="https://github.com/user-attachments/assets/196ca475-8b7c-4874-9e93-fde662896fe1">
