### ISSUE TITLE
Double and triple click support

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#5339]
We should support double and triple click events.

This may need to be opt-in, as we'll need to wait after the initial click to determine which type of event to send.

This could be used to unlock extra features in existing widgets, for example, double click to select a "word" in the `TextArea`, and triple click to select a line.

**Comment by darrenburns** [comment]
@willmcgugan Thinking more about this. We could do this in a backwards compatible way without needing it to be opt-in.

We'd have the existing `Click` event fire immediately on mouse up as it does now, and `SingleClick`, `DoubleClick`, and `TripleClick` events which fire after the required time has elapsed for us to know which one to send.

That way, if users don't care about whether it's a single/double/triple click, they can continue to handle `Click`. If they do care, they can listen for the appropriate event.

**Comment by willmcgugan** [comment]
But what if you want to handle both a single and a double click? In that case you don't want the double click event to have been preceded by a click event.

**Comment by darrenburns** [comment]
You'd have a handler for SingleClick and a handler for DoubleClick.

**Comment by willmcgugan** [comment]
But presumably a dev would want to distinguish between the two.

If we send both events, then a double click would produce a Click followed by a DoubleClick after a short delay. At the time the Click handler is invoked, I can not know if it is part of a double click or a single click.

**Comment by darrenburns** [comment]
Yeah, that's why I'm suggesting you'd handle the SingleClick event **not** the Click event.

Every time you click, a Click event is fired immediately.

Click once, the click event is fired immediately then after 50ms if you haven't clicked again a SingleClick is fired.

Click twice in quick succession (less than say 50ms apart) and two Click events are sent immediately on each click as usual, then 50ms later if you haven't clicked again, a DoubleClick event is fired.

**Comment by willmcgugan** [comment]
Ah! Got you now. So a double click would produce `Click`, `Click`, `DoubleClick`, and a single click would produce `Click`, `SingleClick`?

I see how that would negate the need to opt-in.

That does mean that if I decide I need to handle double clicks, I would have to switch my click handlers from `Click` to `SingleClick`.

TBH, that feels like much the same effort as opting in. With this system I would have to replace `def on_click` with `def on_single_click` to handle double clicks. With an opt in system I would set `ENABLED_DOUBLE_CLICK=True`.

But that doesn't feel like a compelling argument for or against. I like this idea.
