### ISSUE TITLE
`.dark` mode breaking change

### ISSUE THREAD

**Issue by JoeZiminski** [Textualize/textual#5341]
Just a small suggestion, I recently saw that dark mode has been [superceeded](https://github.com/Textualize/textual/pull/5087) by [themes](https://textual.textualize.io/guide/design/#__tabbed_1_1) (which look great BTW). I had some tests that did not pick up the breaking change as the `.dark` attribute is still held on `app` vestigially (as far as I can tell). It might be worth either a) setting `.dark` so it still changes to `textual-dark`/'light' theme under the hood, or raise deprecation error if it is accessed so this gets flagged in tests.

**Comment by darrenburns** [comment]
Thanks Joe! We considered this but opted to just get rid of it completely, as the migration is very simple.

We're still at v0 and about to bump to v1, where we'll be stricter about versioning this type of change.
