### ISSUE TITLE
Your lovely docs website https://textual.textualize.io/ is down

### ISSUE THREAD

**Issue by kleer001** [Textualize/textual#5390]
https://www.isitdownrightnow.com/textual.textualize.io.html

I swear I went there a few days ago. Hopefully it's just temporary. 

Great work everyone, I love textual!

**Comment by darrenburns** [comment]
Seems to be up again!

**Comment by kleer001** [comment]
I wish. 
Please check on another machine and/or network.

**Comment by willmcgugan** [comment]
No idea why the DNS has stopped resolving.

In the meantime, the docs are here.

https://textualize.github.io/textual/

**Comment by kleer001** [comment]
Sorry, they're not. Please try again with a different computer and/or network.

**Comment by kleer001** [comment]
Back up. 
https://textual.textualize.io/

We can clear/close this thread. 
Thank you all for your patience and quick responses. Have a great weekend and lovely holidays!
