### ISSUE TITLE
Unknown escape sequences shouldn't cause freeze (e.g. `^[d`, `^[f`, `^[b`)

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#541]
These sequences get sent by iTerm when natural text editing mode is on by default. 

They also get sent by default by Terminal.app, so pressing Option + Left, Option + Right, Option + Delete in that also results in a crash.

They're and to move the cursor back and forward by full words, and delete the next word forward.

Right now, when Textual receives them, the app becomes completely unresponsive.

Perhaps we need some kind of timeout inside the driver which reads input? Right now I'm having to `kill -9` relatively often because of it.

The natural text editing mode is relatively popular in iTerm (

**Comment by willmcgugan** [comment]
At the moment we have no way to recover there is a timeout, which could lead to missing keys or garbage keys.

We should parse the keys more intelligently though. So we can recover from an unknown key.
