### ISSUE TITLE
Ability to capture an 'enter' key press when focus is on a DataTable

### ISSUE THREAD

**Issue by reriley** [Textualize/textual#5423]
I currently seem unable to capture a press of the enter key when focused on the DataTable widget. This would allow for more intuitive selection.

Here's the code I had hoped would work:
```python class PeopleView(Container):

    BINDINGS = [
        Binding('i', 'toggle_id', 'Show/hide ID'),
        Binding('enter', 'select', 'Select/Deselect', show=False)
    ]

    def compose(self):
        yield DataTable(id='people_table')

    def on_mount(self):
        table: DataTable = self.query_one("#people_table")
        table.cursor_type = 'row'
        table.add_columns(*COLS)
        for p in serve_people():
            table.add_row(p.name, p.address_line_1, p.address_line_2, p.first_tax_year, key=p.id, label=p.id)
    
    def on_show(self):
        table: DataTable = self.query_one("#people_table")
        table.show_row_labels = False

    def action_select(self):
        table: DataTable = self.query_one("#people_table")
        cursor_type = table.cursor_type
        match cursor_type:
            case 'row':
                table.cursor_type = 'cell'
            case 'cell':
                pass

    def action_toggle_id(self) -> None:
        table: DataTable = self.query_one("#people_table")
        table.show_row_labels = True if table.show_row_labels is False else False`

**Comment by reriley** [comment]
I searched for hours for some explicit explanation of what to do for this functionality and of course found it just after posting.  [https://textual.textualize.io/guide/input/#keyboard-input](url) provides the answer in the form of Key Methods, namely a method called 'key_enter'.

**Comment by willmcgugan** [comment]
I would advise against using `key_` methods. They should be considered convenient for quick experiments, but bindings are preferred.

I suspect your example doesn't work because the DataTable already binds 'enter'. Which will send a `DataTable.CellSelected` message. If you want to change that behavior, you can extend the DataTable class and add your bindings.
