### ISSUE TITLE
Logging widget

### ISSUE THREAD

**Issue by DecrepitHuman** [Textualize/textual#544]
I'm in need of a widget that can display logs, I've attempted to implement this myself multiple times. However, the widget refuses to update with the new content.

Example:
class LogPanel(Widget):
    logs = Reactive([])
    
    def write(self, message: str) -> None:
        self.logs.append(message)
        self.refresh()

    def render(self) -> Panel:
        return Panel("\n".join(self.logs), title="Logs")

The main app can call the `write` method without anything happening. According to the source refreshing happens when idle, this does not seem to be working!

This isn't difficult, rather simple yet It's not working and I am unable to explain why.

**Comment by iapyeh** [comment]
I found a imperfect workaround, 
```
class Logview(Widget):
    value = Reactive('this is log view')
    def __init__(self,*args):
        super().__init__(*args)
        ## need some placeholder to expand size of this widget
        self.rows = [''] * 60 
    def render(self) -> RenderableType:
        value = '\n'.join(reversed(self.rows))
        #return ScrollView(Panel(value)) ## this does not work
        return Panel(value)
    def write(self,s):
        self.rows.append(s)
        ## just hint the widget to call "render"
        self.value = s
```
In the on_mount of the app, calls
```
await self.dock(ScrollView(Logview()), edge="top", name="body")
```

**Comment by iapyeh** [comment]
Finally I got a working copy inspired from https://github.com/Textualize/textual/issues/125
```
class MyApp(App):
    console_outputs = Text("")
    def write(self,value:str)->None:
        self.console_outputs.append(Text.from_ansi(value+"\n"))
    async def on_mount(self) -> None:
        self.myview = ScrollView()
        await self.view.dock(self.myview)

        loop = asyncio.get_running_loop()
        task = loop.create_task(self.action_console())
        loop.call_soon_threadsafe(task)

    async def action_console(self):
        body = self.myview
        while True:
            pre_y = body.y
            await body.update(self.console_outputs)
            body.y = pre_y
            body.animate("y", body.window.virtual_size.height, duration=1, easing="linear")
            await asyncio.sleep(1)
```

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
