### ISSUE TITLE
Is it possible for any sort of support for graph?

### ISSUE THREAD

**Issue by wey-gu** [Textualize/textual#554]
Like https://observablehq.com/@d3/temporal-force-directed-graph in the browser(but relatively pixelated/in low-resolution), I realized it's not as practical(pixel density) as web browsers and I couldn't even draw that properly in http://asciiflow.com/, but just would like to ask, in case you have more ideas :D.

Great job on textual and rich! Thanks!

**Comment by willmcgugan** [comment]
Not currently, but we would like to support plots. The graph in your URL should be possible with braille "bitmaps" although it obviously wouldn't look as slick.

**Comment by heeplr** [comment]
Using this since I'm also interested in drawing within textual. I want to do a X/Y plot with interactive widgets. So some primitives (line, circle, pixel) would be needed.

Is there maybe a recommended 3rd party library which has proven to integrate nicely with textual?
