### ISSUE TITLE
When you toggle dark mode, the background colour of borders doesn't update unless you hover your cursor over it to trigger repaint

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#572]
Going from light to dark mode via a keybind:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/5740731/173050196-4ecb9293-78a5-404f-9e4d-492125dbe2cf.png">

The light background is retained on the cells representing the border.

**Comment by willmcgugan** [comment]
I have a suspicion that my scroll-view branch may have fixed that. Will defer looking at this until that's merged.

**Comment by willmcgugan** [comment]
@darrenburns Can you confirm if this is still the case once the datatable PR is merged.

**Comment by darrenburns** [comment]
@willmcgugan Fixed with the datatable PR
