### ISSUE TITLE
Wrong CSS styles being applied on hover

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#573]
I noticed this when adding semantic style variants for Button.

When I hover over the warning button, the border is being set to `tall $primary-lighten-3`. I would expect it to be set to `tall $warning-lighten-3` given `Button.-warning` has higher specificity.

Relevant CSS
```
    Button {
        border: tall $primary-lighten-3;
    }
    Button.-warning {
        background: $warning;
        color: $text-warning;
        border: tall $warning-lighten-3;  
    }
    
    Button.-warning :hover {
        background: $warning-darken-1;
        color: $text-warning-darken-1; 
    }
```

**Comment by willmcgugan** [comment]
Could it be because there is a space before the `:hover`? Could you try `Button.-warning:hover` ?

**Comment by darrenburns** [comment]
Removing the space makes no difference

**Comment by willmcgugan** [comment]
Actually, your hover style has no border in the code above. I wouldn't expect the hover to change the border color at all.

**Comment by darrenburns** [comment]
Yep - that's the issue. I wouldn't expect the hover to change the border colour, but it does - it changes it to `tall $primary-lighten-3`. I would expect the hover to have no effect on the border (it should stay as `tall $warning-lighten-3`)

**Comment by willmcgugan** [comment]
Got you. Yeah, I can reproduce that here.

**Comment by willmcgugan** [comment]
@darrenburns Can you check the css in the `Button.CSS` classvar ?

**Comment by willmcgugan** [comment]
BTW you can do `print(app.stylesheet.css)` to see the combined rules.

**Comment by willmcgugan** [comment]
Is that really all the CSS for Button? Nothing else defined in `_buttons.py` ?

**Comment by darrenburns** [comment]
There is more CSS there, I just picked out the relevant stuff to reproduce the issue. Not sure what you're wanting me to check 😄

**Comment by willmcgugan** [comment]
I could use a self contained app that reproduces this. Every appears to conform to my expectations when I take in to account the CSS classvar.
