### ISSUE TITLE
Activated button animations

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#576]
The Button widget should have a visual indicator that it was clicked. Material buttons do this. The reasoning is that if an action doesn't immediately update the UI, the user tends to click again to make sure it works.

I'm thinking a brief pulse animation, or 500ms flash. Something subtly enough to not be irritating, but still convey the active state.

this may be achieved by adding an `-active` class to the Button to allow a dev to define the active animation.

**Comment by darrenburns** [comment]
"Fried pulse animation"? 😄
