### ISSUE TITLE
Config file plan

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#577]
We need a config file to be read by Textual that contains settings, key bindings etc.

YAML, or maybe TOML.

It should be flexible enough that third party packages should be able to read from it.

Discuss with @willmcgugan re requirements, and come up with a proposal before working on this.

**Comment by willmcgugan** [comment]
Mainly developers, but potentially also exposed to users.

**Comment by darrenburns** [comment]
My vote is for [TOML](https://toml.io/en/) as I personally find it significantly easier to read and write. Considering `pyproject.toml` is standard now, TOML support is being added to the Python stdlib in 3.11 (based on @hukkin great package https://github.com/hukkin/tomli), and TOML data structures look similar to Python, it's a format that Python developers are likely to be both familiar and comfortable with.

Every time I write YAML I don't feel certain it's correct, and past experience makes me suspect I'm not alone in this :)

**Comment by DrBenton** [comment]
Since we're targetting people who are already writing Python code, I wonder if [Starlark](https://github.com/bazelbuild/starlark#readme), the Python sandboxed dialect created by Google for their Bazel build tool, couldn't be a good choice?

> Starlark is a language intended for use as a configuration language. It was designed for the [Bazel](https://bazel.build/) build system, but may be useful for other projects as well. 
> Starlark is a dialect of Python.
>
> Design Principles
>
> -    Deterministic evaluation. Executing the same code twice will give the same results.
> -    Hermetic execution. Execution cannot access the file system, network, system clock. It is safe to execute untrusted code.
> -    Parallel evaluation. Modules can be loaded in parallel. To guarantee a thread-safe execution, shared data becomes immutable.
> -    Simplicity. We try to limit the number of concepts needed to understand the code. Users should be able to quickly read and write code, even if they are not expert. The language should avoid pitfalls as much as possible.
> -    Focus on tooling. We recognize that the source code will be read, analyzed, modified, by both humans and tools.
> -    Python-like. Python is a widely used language. Keeping the language similar to Python can reduce the learning curve and make the semantics more obvious to users.

I couldn't find an implementation of Starlark in pure Python (the 3 main implementations are in Go, Java and Rust), but there is a Python extension that wraps the Go version:
https://python-starlark-go.readthedocs.io/en/latest/index.html

```py
from starlark_go import Starlark

s = Starlark()
fibonacci = """
def fibonacci(n=10):
   res = list(range(n))
   for i in res[2:]:
       res[i] = res[i-2] + res[i-1]
   return res
"""
s.exec(fibonacci)
s.eval("fibonacci(5)")  # [0, 1, 1, 2, 3]

s.set(x=5)
s.eval("x") # 5
s.eval("fibonacci(x)")  # [0, 1, 1, 2, 3]
