### ISSUE TITLE
Code viewer becomes unresponsive after a while

### ISSUE THREAD

**Issue by brechtm** [Textualize/textual#580]
I've written a tool starting from `code_viewer.py` and I'm running into an issue that it becomes unresponsive to mouse clicks (and scrolls, IIRC) after several hours. It appears this issue also is present in `code_viewer.py` itself. The 'B' and 'Q' shortcuts still work, however.

To reproduce, start `code_viewer.py`, expand some folders, let it run overnight.

RHEL 7.4, Python 3.10.1 (installed using [Spack](https://spack.readthedocs.io/en/latest/)), Textual 0.1.17, Rich 12.2.0

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
