### ISSUE TITLE
Need layout usage example

### ISSUE THREAD

**Issue by senyai** [Textualize/textual#586]
Hi! I failed at creating a widget with complex content using textual. What would help me is an example of how one do something like this:
![window](https://user-images.githubusercontent.com/76137/175279689-22a5a28b-0e2e-49a4-bda1-3baa05cf195c.png)

My try at it was:
```python
class PlayerWidget(Widget):
    def render(self) -> RenderableType:
        layout = VerticalLayout()
        layout.add(Static(Align.left(Text("FIRST LINE"))))
        layout.add(Static(Align.left(Text("SECOND LINE"))))
        return Panel(
            layout,
            title='Player',
            border_style="green",
            height=10,
        )
```

**Comment by Hakobkhh** [comment]
You may find this useful. I found this when I was looking for examples myself.
The link refers to part 3 of the tutorial but parts 1 and 2 are worth taking a look as well.
https://dev.to/wiseai/textual-the-definitive-guide-part-3-2gl

**Comment by senyai** [comment]
Thanks, I read the tutorial. Unfortunately I still can't get closer to understanding of what should be done in my case.

**Comment by anjakefala** [comment]
Writing on behalf of the devottys =) https://github.com/devottys. I love the terminal, and I really love tools that are going to mean more TUI apps.

When we played with Textual, we liked how much easier it was to build panels, but wanted something akin to a curses-like interface to place things within panels. With the goal of being able to play with the layout.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
