### ISSUE TITLE
User added documentation

### ISSUE THREAD

**Issue by michelececcacci** [Textualize/textual#616]
I really like the project, but i feel like it would benefit a lot from some basic documentation. Do you mind if i add some documentation as i discover how to do things? Maybe other users can chime in and correct me if i write something wrong. I know this is not optimal, but I also understand that you might be busy implementing features, and i feel like this would make the project much more accessible.
To be added by @willmcgugan

**Comment by willmcgugan** [comment]
Documentation is coming for the CSS branch which is landing soon. I'm afraid if you documented master branch, it will soon be out of date.

**Comment by michelececcacci** [comment]
I didn't write any documentation yet, but i was wondering whether it could be useful if i started doing it. Should i refer to css branch for newer documentation? (I'm mainly interested in views)

**Comment by michelececcacci** [comment]
Perfect! Thanks a lot!
