### ISSUE TITLE
Footer() not visible

### ISSUE THREAD

**Issue by heeplr** [Textualize/textual#621]
It seems screen height suffers from some sort of off-by-one bug.
This testcase:
```

from textual.app import App
from textual.widgets import Footer, Placeholder


class MainApp(App):

    async def on_mount(self) -> None:
        await self.view.dock(Placeholder())
        await self.view.dock(Footer(), edge="bottom")

if __name__ == "__main__":
    MainApp.run()
```

produces this output::

![win](https://user-images.githubusercontent.com/32984777/180656791-16934b05-6ea1-4fdf-bed0-0dc6193e3cc2.png)

The bottom line is cut off. Without the Placeholder widget, the Footer displays correctly at the bottom line:

![win2](https://user-images.githubusercontent.com/32984777/180706369-555c229c-f909-440f-be62-7f012990bd88.png)

**Comment by doobeh** [comment]
For what it's worth, applying the elements in reverse order works:

```
from textual.app import App
from textual.widgets import Footer, Placeholder


class MainApp(App):

    async def on_mount(self) -> None:
        await self.view.dock(Footer(), edge="bottom")
        await self.view.dock(Placeholder())

if __name__ == "__main__":
    MainApp.run()
```

You could also apply the widgets at once-- `await self.view.dock(Placeholder(), Footer(), edge="top")` so they can work out a fair arrangement with each other.

The way my mental model interprets this is-- when you placed the `Placeholder()` the 'canvas' was empty, so Placeholder naturally grows to fully encompass everything.  When you then add the `Footer()` the top of the footer has to touch the bottom of the Placeholder, so it therefore 'scrolls' offscreen.  

(my mental model could well be wrong! I'm only new to exploring this project)

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
