### ISSUE TITLE
Include docs and tests on PyPI

### ISSUE THREAD

**Issue by jonathanspw** [Textualize/textual#631]
Hi,

I'm a Fedora packager and I'm working on a package for Fedora and EPEL (RHEL/AlmaLinux/etc.) and I'd like to use the PyPI package since it's easier to use with RPM packaging (ie setup.py) but the archive is missing docs and the test suite so it would be against Fedora policy for me to build packages against it.

Can you please include docs and tests in the PyPI packages?

**Comment by davep** [comment]
Thanks also to @mia-0 for raising this as well in #1349. The documentation is unlikely to be included as part of the distribution as it's fairly large and getting larger. The tests: including them would make sense.

**Comment by willmcgugan** [comment]
@jonathanspw What would you need for docs? Our docs are quite large and there is a custom build process. Is there any particular format you require in order to fulfil the docs requirement?

**Comment by mia-0** [comment]
From the openSUSE side, I’d be okay with anything that can be viewed offline. Even better if it’s usable from a terminal in some form without depending on a full-blown web browser ;)

If the documentation requires a build process, that *must* be able to run without an Internet connection. I think that’s all.

**Comment by willmcgugan** [comment]
Would it be enough to offer a Markdown file containing a getting started guide and direct readers to the [online docs](https://textual.textualize.io/) ?

**Comment by willmcgugan** [comment]
**Update** We are going to look at an offline build step for our docs.

**Comment by jonathanspw** [comment]
Thanks guys!

**Comment by davep** [comment]
> If the documentation requires a build process, that must be able to run without an Internet connection.

Note to self: our docs include, and run and grab the display of, actual Python code. One of these bodies of code is a dictionary-lookup tool which makes calls out to the net. This is used both on the opening page of the docs as an illustrative example of a Textual application, and also used to demonstrate how the event system works.

This example will need replacing with something fully-local.

**Comment by davep** [comment]
Also note to self: there is an issue with building and viewing the HTML locally in that, some links link to a directory, which will contain `index.html`. The problem then is that browsing `file:///path/to/textual/site/getting_started/` results in a listing of that directory, not the auto-loading of `index.html`. If the full docs (minus the parts that don't make sense "locally") are to be made available in some sort of "local" form, that doesn't require a web server, a workaround for that would be needed too.

**Comment by davep** [comment]
@jonathanspw Did you have any input on [Will's question above](https://github.com/Textualize/textual/issues/631#issuecomment-1413819953)? It would be be really helpful to us, in looking to enable and support this, if we could get a good overview of how the documentation would be used, deployed and made available to the users of the packaging systems.

**Comment by RoniJacobson** [comment]
@davep There is an excellent guide on the material for mkdocs website about building the docs offline:
https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/#built-in-offline-plugin
It will involve bumping the mkdocs version, disabling some things and adding the `offline` plugin.
The offline plugin does lots of heavy lifting, including making search work without any server running.

**Comment by davep** [comment]
Thanks. I'll take a look when I'm next at my desk.

**Comment by RoniJacobson** [comment]
You may need to bump the version of mkdocs-material to over 9.0

**Comment by davep** [comment]
@RoniJacobson I was just about to comment that I'd solved it and the cause was YAML. The cause is always YAML. 😝

**Comment by RoniJacobson** [comment]
@davep you should probably bump the version anyway because in the version of mkdocs-material you have the plugin was in preview and only for insiders. It was released publicly in 9.0

**Comment by davep** [comment]
Noted, thanks. :-)

**Comment by davep** [comment]
These last two come from the SVGs that are generated by our "from the code make screenshots" system; and the fonts will fall back to the system's default monospace font if there is no connection; so this looks fine.

**Comment by davep** [comment]
As of #1726 -- which is now release with v0.11.0 -- there is now the ability to build offline documentation.

Thanks again all for your input and feedback.
