### ISSUE TITLE
No display output on Classic Python and ipython Terminal

### ISSUE THREAD

**Issue by AnilJean** [Textualize/textual#632]
This is my first time using Github to report something, thus sorry if I have done something wrong...
I tried various examples with classic and ipython terminal. Checked the log, key inputs are logged; However, nothing was displayed before and after key press. 
Thank you for reading...

P.s Rich works fine

**Comment by alexgarciavila** [comment]
Which SO are you using?

**Comment by AnilJean** [comment]
> Which SO are you using?
If you are meaing SO as shared objects or shared libraries, I have:

**Comment by AnilJean** [comment]
Which SO are you using?
If you are meaing SO as shared objects or shared libraries, I have installed almost every major libraries for my workflow (It's a bit long to post that here...)  . The codes that I have run to test textual was the examples provided by the main page.

**Comment by AnilJean** [comment]
> Which SO are you using?

If you are meaing SO as shared objects or shared libraries, I have installed almost every major libraries for my workflow (It's a bit long to post that here...) . The codes that I have run to test textual was the examples provided by the main page.

**Comment by alexgarciavila** [comment]
Sorry, my mistake.
I want to say OS (Operating System) not SO.

**Comment by spasmsagain** [comment]
Seeing same on Windows 10 - under both CMD.EXE and powershell

Python 3.10.5
Textualize 0.1.18
ipython 8.4.0

python -m textual.app is also showing nothing

**Comment by alexgarciavila** [comment]
Try to download powershell 7.
Under cmd or old versions of powershell black screen appear with Textual.

For me is a problem, because i will develop a TUI for clients using Windows 7 and can't use this awesome framework.

You can try to download "windows terminal" under Microsoft Windows Strore and later, install powershell 7.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
