### ISSUE TITLE
Improve CSS syntax error

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#655]
CSS syntax errors produce somewhat cryptic errors. We should try and improve this.

In particular we should try to produce a helpful error for missing semi-colons, which will be a common issue.

<img width="828" alt="Screenshot 2022-08-07 at 10 41 16" src="https://user-images.githubusercontent.com/554369/183284982-c14d8f99-96b5-4c6f-b8f8-62daa41ac934.png">

**Comment by tusharsadhwani** [comment]
or... make semicolons optional?

**Comment by tusharsadhwani** [comment]
if you need to implement that manually, you can try doing "automatic semicolon insertion", like javascript.

**Comment by willmcgugan** [comment]
They were optinal originally. We changed it to be in line with browser CSS.
