### ISSUE TITLE
Devtools doesn't work in spin-loops

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#661]
If the application code is in a spin-loop and not awaiting, then devtools will not receive any logs.

This makes complete sense due to the nature of cooperative multitasking.

I suspect the fix may be to run the websocket client in a thread so that it can run independently of the async loop.

**Comment by darrenburns** [comment]
> I suspect the fix may be to run the websocket client in a thread so that it can run independently of the async loop.

The better fix is to never write any infinite loops 😜

**Comment by willmcgugan** [comment]
This doesn't seem much of a problem in practice. Closing for now.
