### ISSUE TITLE
Can TextInput support GNU Readline Library?

### ISSUE THREAD

**Issue by codefell** [Textualize/textual#666]
Hi team, this project is really cool! I just tried the TextInput widget, and came up a thought, is it possible that TextInput can integrate with GNU Readline? Because it will make editing long text much easier.

**Comment by willmcgugan** [comment]
I doubt it. But we will be able to replicated readlines features.

**Comment by codefell** [comment]
That's all right, some simulation will also be fine, after all it's not expected to be a full-featured editor. Any way, textual is excellent.
