### ISSUE TITLE
An option to allow loading a stylesheet in non-strict mode

### ISSUE THREAD

**Issue by davep** [Textualize/textual#671]
Currently stylesheets are loaded such that unknown properties cause an actual error. Mostly I'd say this makes a lot of sense. However, I feel it could be useful to have some sort of switch that tells the stylesheet loader to forgive unknown properties. This is mainly motived by something I often do when tweaking the style on something when doing web development. If I want to very quickly disable, say, a `border`, I'll just change it to `-border` and save. In the browser this obviously isn't an error so it's a handy way of quickly "commenting" out a property.

If implemented I think it would make sense that it is only provided as a development/debug facility.

**Comment by willmcgugan** [comment]
I don't think this is wise to have a mode for this. Folk would be tempted to run it all the time.

Textual CSS is stricter than the browser intentionally. We don't need to worry about backwards compatibility.

I would consider adding a hash for comment, like Python.

**Comment by davep** [comment]
> I would consider adding a hash for comment, like Python.

Works for me!
