### ISSUE TITLE
Invisible widgets can still be clicked

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#697]
It looks like widgets with "visibility: hidden" can still be clicked. They should also be invisible to the mouse cursor as well.

**Comment by tusharsadhwani** [comment]
iirc visibility hidden means exactly that: hidden, but interactive, with say, the tab key to select stuff.

display: none makes it non interactive.

**Comment by davep** [comment]
> iirc visibility hidden means exactly that: hidden, but interactive, with say, the tab key to select stuff.

If you mean as you'd expect on the web, [that wouldn't be the case](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#values).

Try it with a little example:

```html
<html>

  <head>
    <title>Visible/display test</title>
  </head>

  <body>
    <button style="cursor: hand; visibility: visible; display: inline;">This is visible and has display</button>Visible, display<br />
    <button style="cursor: hand; visibility: hidden; display: inline;">This is not visible and has display</button>Invisible, display<br />
    <button style="cursor: hand; visibility: visible; display: none;">This is visible and has no display</button>Visible, no display<br />
    <button style="cursor: hand; visibility: hidden; display: none;">This is not visible and has no display</button>Invisible, no display<br />
  </body>

</html>
```
