### ISSUE TITLE
GridView rendering issue on windows

### ISSUE THREAD

**Issue by vyalovvldmr** [Textualize/textual#710]
Environment:
1. Windows 10
2. Powershell 7

Steps to reproduce:
1. `pip install onx`
2. Run `onx` in powershell

Result:
![gridview_windows](https://user-images.githubusercontent.com/1394685/187091406-f3fd1e49-6123-4480-abd3-075d8686918d.png)

Source code: https://github.com/vyalovvldmr/onx/blob/c8b477cf4d552dfca38ee169cd973ae0971ccdfc/run.py

I will be grateful for any advice of better code implementation with textual. Which will let me avoid the rendering problem or reduce the impact.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
