### ISSUE TITLE
GridView rendering issue on mac os

### ISSUE THREAD

**Issue by vyalovvldmr** [Textualize/textual#711]
Environment:
1. Mac OS 11.6.3
2. Standart terminal
3. fish shell

Steps to reproduce:

1. `pip install onx`
2. open terminal in a small window size
3. Run `onx -g14`

Result:
<img width="1130" alt="gridview_maxos" src="https://user-images.githubusercontent.com/1394685/187091773-e74194c1-faf5-4bc7-99ec-f505086448bd.png">

Source code:
https://github.com/vyalovvldmr/onx/blob/c8b477cf4d552dfca38ee169cd973ae0971ccdfc/run.py

I will be grateful for any advice of better code implementation with textual. Which will let me avoid the rendering problem or reduce the impact.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
