### ISSUE TITLE
README and Docs improvements

### ISSUE THREAD

**Issue by alex-astronomer** [Textualize/textual#761]
Let me start by saying, this thing is sweet!  A TUI library that is *SO CLOSE* to perfection.  I have one gripe that is making it super hard to use and learn Textual.

I know that this is probably a common ask and most likely something in progress on the CSS branch, but I'm really struggling to learn this library with the lack of documentation.  Just spend around 3 hours trying to figure out how to pass focus and key events to a child Widget, from a parent that is composed of the children.  Not even sure that I'm doing this the right way.  Would this make more sense with views?  No clue because there's no examples (that I can find) of views, and very, very limited documentation.

I hacked it together by calling a register event manually in the App for the children of the Widget that I'm docking.

I'd rather have documentation for existing features than CSS, and I believe that's the focus right now.  I mean this thing is so sweet and I feel like if I knew how to use the tool effectively, I would never look to another TUI library again.

Thoughts?  I would be happy to write up some docs if I knew that what I was doing could be considered best practices, but because I don't have a ton of underlying knowledge about implementation details I'm not sure that I'm the best one for the job.

**Comment by yoann9344** [comment]
Can you share how you passed the focus with the register please ?

**Comment by willmcgugan** [comment]
New version and docs will land on 10/24
