### ISSUE TITLE
CSS Branch, text-style:italic is reversing text

### ISSUE THREAD

**Issue by rogerlew** [Textualize/textual#786]
Hi textualize.io,

I've been playing with your CSS branch. It is really cool. 

I'm not sure if you are aware but `text-style:italic` is doing the same thing as `text-style:reverse`

`textual/docs/examples/styles/text_style.py` yields:

![image](https://user-images.githubusercontent.com/3652906/190827540-9a532b65-d0c2-45c1-b3c9-3d542db8627c.png)

![image](https://user-images.githubusercontent.com/3652906/190827705-b6366718-e1c5-4535-9db2-2fe788cc1adb.png)

Cheers!

Roger

**Comment by willmcgugan** [comment]
Are you using tmux?

**Comment by rogerlew** [comment]
Yes, that was observed while using Byobu on Ubuntu 20.04 with miniconda 3.9.12.

I just tested it without byobu and it does seem to render as expected. 

~Sorry not mentioning that, I didn't think as relevant at the time.

**Comment by rogerlew** [comment]
I was able to enable italic text by following the guidance here:
https://askubuntu.com/a/1004253/922793

**Comment by willmcgugan** [comment]
Great. Tmux is known to do that. No idea why.
