### ISSUE TITLE
Investigate disabled button state

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#790]
Disabled buttons still have a hover state, even with a hack to `watch_mouse_hover`.

Investigate why this occurs, and fix or implement a better solution.

**Comment by rogerlew** [comment]
overriding `get_pseudo_classes` in the ```Button``` class seems to work

```python    
    def get_pseudo_classes(self) -> Iterable[str]:
        """Pseudo classes for a widget.

        Returns:
            Iterable[str]: Names of the pseudo classes.

        """
        for cls in super().get_pseudo_classes():
            if cls == 'hover' and self.disabled:
                continue
            yield cls

```

**Comment by darrenburns** [comment]
It doesn't seem to be the case anymore @willmcgugan.

Running `textual run docs/examples/widgets/button.py --dev` and hovering over the buttons - nothing happens.
