### ISSUE TITLE
Textual Issues on Windows

### ISSUE THREAD

**Issue by hucker** [Textualize/textual#791]
The latest pip install does not appear to work on windows (I just downloaded last Friday) version 0.1.18, and am running on python 3.10.

Rich seems to work fine, the colorized text output works in the line-based stdio ouptut use cases I have.

1. When I run textual on cmd or ps I get a blank screen...until I resize the window, at which point I get what looks to be a (very) nice windowed screen. (I'm running the placeholder sample with 3 rows with a 1 span, 3 span and 1 span footer).
2. When I move the mouse around, the windows jump around and don't refresh properly. When I float over the sub-window in the second row, the color-changing border is redrawn starting from the first row. The same thing with the footer, the clicked on footer appears in the top row. It looks like the redraw code doesn't have a top offset.
3. I see no output in the pycharm or vscode terminals (I don't expect it to work there) no matter what I do.
4. If I slowly drag the bottom right corner of the screen I can watch it do the redraws.  It doesn't get them right fairly often.

I've attached a video that shows the behavior under cmd.  It does the same thing on power shell.

Is there more to running textual on windows than the PIP install?

https://user-images.githubusercontent.com/168343/191092460-0e00d0e3-acb1-49d5-9cf2-73974493d34f.mp4

**Comment by AyushSehrawat** [comment]
Yeah, i am facing the same issue...

Python Version : 
```sh
(venv) D:\Projects\tui>python --version   
Python 3.9.13
```
The same issue occurs as described in the issue.

Also, when i run this in pycharm ( after opening terminal and running `python main.py`. Name of file is main.py and code is code_browser.py example) ,, it loads but it ruins the look, so not gonna use it...

Any fix for it ?

**Comment by AyushSehrawat** [comment]
Update :
Tried with `python3.8 main.py` , and it works fine with it. The issue seems to be with python version 3.9+

@willmcgugan Please look into this... For the time being i am going back to v3.8.x

**Comment by PyTsun** [comment]
I tried other terminal clients and it looks like Windows Terminal works perfectly with textual TUIs on windows.

**Comment by AyushSehrawat** [comment]
> I tried other terminal clients and it looks like Windows Terminal works perfectly with textual TUIs on windows.

I will try that

**Comment by hucker** [comment]
I can confirm that running on python 3.8 in power shell and cmd does work from a "normal" user perspective.  The  only issue I can cause is resizing the window slowly and catching what looks to be a modulus arithmetic issue.  Once I mouse over the screen the redraw fixes it...which seems to be a clue that the full screen refresh does something different than the mouse over refresh.  

This rev is helpful for me for test purposes, but we are going to roll to 3.11 (or 3.10 if there are issues).   Is there an understanding of what is causing this problem?

**Comment by hucker** [comment]
> I tried other terminal clients and it looks like Windows Terminal works perfectly with textual TUIs on windows.

What Python version?  It appears that there might be an issue that allows textual to run under python 3.8 but no under 3.9/3.11.  Do you see it working correctly with versions after 3.8?

**Comment by PyTsun** [comment]
> What Python version?
My python version is 1.10

> Do you see it working correctly with versions after 3.8?
Yep, everything works fine on Windows Terminal above python 3.8

Here's a screenshot of me using it
![image](https://user-images.githubusercontent.com/53323309/194483985-223e6e61-bc75-4ae0-b30e-dc85b15a5c2c.png)

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
