### ISSUE TITLE
'tab' key doesn't work

### ISSUE THREAD

**Issue by Beafantles** [Textualize/textual#803]
Hello,

I've been using *textual* a bit and I faced recently what seems like a bug. Indeed, whenever I try to bind the **tab** key to any action, the application won't react to it. I bound several keys and it seems like this problem only occurs for the **tab** key (I haven't tested all keys though).

Here's a sample code to reproduce the bug:

```python
from textual.app import App
from textual.keys import Keys


class Application(App):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    async def on_load(self) -> None:
        await self.bind(Keys.Tab, "quit")
        # await self.bind("tab", "quit") doesn't work either
        # await self.bind("a", "quit") works fine


Application.run()
```

If I bind the `quit` action to another key, let's say `'a'`, I can quit the application just fine using the A key but it won't work if I use the **tab** key.

I'm using *textual* on Windows 11 and encountered this problem with all terminals I've been testing this on (command prompt, Powershell, [Hyper](https://github.com/vercel/hyper)).

**Comment by mathman1618** [comment]
I encountered the same thing.  As a workaround, try

```python
await self.bind("ctrl+i", "quit", key_display="Tab")
```

**Comment by Beafantles** [comment]
Alright, thank you, that's indeed a workaround. It's not ideal since it also binds ctrl+i to the action but at least, I can use tab with that.

**Comment by willmcgugan** [comment]
I'm afraid there is no way to distinguish ctrl+i from tab in a terminal. What we probably need is aliases, so you can use "tab" as well.
