### ISSUE TITLE
Better Documentation?

### ISSUE THREAD

**Issue by OhadRubin** [Textualize/textual#805]
I mostly want to do really simple things and streamlit really fills that role, but I don't want to be bound to a browser...
I know you are a small team, but I had my eye on this package for a while and i've been waiting for the documentation to improve so I could start experimenting with it, but it looks like there hasn't been any improvement w.r.t documentation for a while now.
When should I expect significant improvement to documentation?
Thanks!

**Comment by davep** [comment]
Have a bit of a scroll back through Will's Twitter (https://twitter.com/willmcgugan) -- way more documentation is coming.

**Comment by willmcgugan** [comment]
New version with docs will land on the 24 of October.
