### ISSUE TITLE
Strange behaviour with cursor blink in `Input`

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#818]
I can't work out how to reproduce this. This happened when the cursor was over certain characters - I think only the double width ones. The length of the text exceeded the width of the content area. It may have been triggered by scrolling to the left, but I'm really not sure.

https://user-images.githubusercontent.com/5740731/193867129-9dd15418-ead3-474c-a0b3-507c745d0edf.mov

**Comment by willmcgugan** [comment]
@darrenburns I think this is fixed now? I haven't seen any issues with text input lately.

**Comment by willmcgugan** [comment]
Assuming fixed

**Comment by darrenburns** [comment]
@willmcgugan I doubt it - you managed to reproduce it in the office after your previous comment a month ago.
