### ISSUE TITLE
Any way to update the Widget content

### ISSUE THREAD

**Issue by mlafois** [Textualize/textual#823]
Hello, 

First of all for this great work.

I'm trying to play with the css branch and I'm wondering if it is possible to a widget to self update (not adding) its content ?

So far I manage (I'm not a powered python user), to triggereed an action based on a click on an another widget's button. And I'm I don't know if it is possible to change the full  content a the current widget based on this action. Hereunder piece of the code.

```py
class Body(Widget):
    DEFAULT_CSS = CSS
    content = 'welcome'

    def action_test(self, msg: str) -> None:
        self.content = msg #Here I receive the msg
        print('Content', self.content)
        self.compose()
        self.refresh(layout= True)

    def compose(self) -> ComposeResult:
        print('test mount') #Apper only once so only triggered on mount I suppose
        if self.content == 'welcome':
            yield Widget(
                Container(
                    Static("Welcome"),
                id="body",
                ),
            )
        elif self.content == 'stack':
            yield Widget(
                Container(
                    Static("Stack"),
                    id="body",
                ),
            )
        else:
            yield Widget(
                Container(
                    Static("Null"),
                    id="body",
                ),
            )
```

I was naively thinkink that calling compose method will "rerender" the widget, but it does not seem to be the case.

So far I have tried to use mount(). It's working but it is only updating ("push") new content.

I have seen some exemple but, in my understanding, they are all handling this issue at the level of the app and reredender everything.

Any Idea, or solution if it is a noob question ?

Regards,

Mickael

**Comment by davep** [comment]
@mlafois I might be misunderstanding what it is you're trying to do based on the snippet above, but it seems you're waiting to update the text contained within the `Static`, is that right? If that's the case you'd update the content of the existing `Static` using the `update` method. Based on what you're showing above, I imagine you want to be doing something more like this in your app code somewhere (taking into account you gave your `Static` the `id` of `body`):

```python
self.query( "#body" ).first().update( "This is the new text" )
```

The code is likely a bit out of date now, as the CSS branch has moved on a little, but if you [look here at a sample app I was writing](https://github.com/davep/textual/blob/5078e9adb649335b4edd9e395da6c0eca1e030c6/sandbox/davep/five_by_five.py#L41) you'll see I set up some `Static` widgets to show game progress, then later on [you'll see the code that updates those `Static`s](https://github.com/davep/textual/blob/5078e9adb649335b4edd9e395da6c0eca1e030c6/sandbox/davep/five_by_five.py#L91).

Is that the sort of thing you were looking to do?

**Comment by mlafois** [comment]
Hi @davep,

it seems that my snipet made my question a little bit unclear.

In fact I.m using text only for dummies tests. 

I want to be able to update this widget (which is the body of my testing app) an md update its content based on a menu sélection (new widget, layout, ...). 

Sorry if it is a little unclear English still a foreign language to me.

Any way thanks for your reply and links I look at them tomorrow and give you a feedback.

Mickaël

**Comment by davep** [comment]
@mlafois Is this something you still need input on? It's been a while since you said you were going to do a bit of reading and come back. Not a problem either way but I'm just checking some older issues to see if they still need some help or just need closing.

@iapyeh It looks like your question may have got missed, likely because you tacked it onto someone else's issue that doesn't look very related. If you still need help would you please ask your full question as [a "Q&A" over in the discussions](https://github.com/Textualize/textual/discussions/categories/q-a)?
