### ISSUE TITLE
Polish geometry.py

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#83]
geometry.py is fairly unique in that it has stabilized quickly. It is also fairly easy to comprehend on its own.

There are a few missing docstrings (args and return types) etc. There are probably also a few edge cases that could used tests for. Finally, there may be optimizations that could be done. If you want to do optimization, I would expect a serious attempt at profiling, but bear in mind that I don't want to sacrifice readability.

**Comment by AlexWaygood** [comment]
I'd be interested in helping out with this. Would you prefer one pull request, or several small, focused ones (one regarding docstrings, one regarding tests, etc)?

**Comment by willmcgugan** [comment]
Great! Feels like a single PR thing.
