### ISSUE TITLE
Test everything on Windows

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#861]
Windows tends to be the most problematic platform, but the least tested.

We should test test all the examples / documentation examples on Windows, looking for bugs and inconsistencies.

We should also test the devtools on Windows. And the live-editing.

Windows users may be nearly 50% of our audience so we should be thorough with it.

**Comment by dlasusa** [comment]
My primary system is Windows though I've never done any sort of "official" testing, are there any guides or instructions on the types of things this entails?  Happy to help if I'm able to.

**Comment by davep** [comment]
Hey @dlasusa, thanks. As Will says above, a great place to start would be to work through [the examples](https://github.com/Textualize/textual/tree/main/examples) and also follow [the tutorial](https://textual.textualize.io/tutorial/) from start to end, testing stuff as you go. If anything seems wrong a heads-up here would be really appreciated.

**Comment by dlasusa** [comment]
Gotcha. @davep Thanks!  I actually started doing some of that just to learn, I totally missed that was actually part of the testing.  I'll spend some time and actually make notes now for anything that pops up.

**Comment by davep** [comment]
Awesome, thanks. Please don't hesitate to ask anything.

**Comment by dlasusa** [comment]
Before I get too far down the path of testing the other examples, wanted to see if this is the sort of things we're after?

Windows 10 (64bit)

Python Env:
Using a virtual python environment (venv)
Python 3.10.8
commonmark==0.9.1
importlib-metadata==4.13.0
nanoid==2.0.0
Pygments==2.13.0
rich==12.6.0
textual==0.2.1
zipp==3.9.0

Downloaded repo as zip, copied the examples into a folder called "samples"
```
Project_Dir/
    samples/
    venv/
    testing_notes.txt
    textual.log
```
Tests:

Windows Terminal (Powershell): python.exe .\calculator.py --> Works
Windows Terminal (Command): python calculator.py --> Works
Standard command prompt: python calculator.py --> Works, but has visual artifacts (see image)
![calc_cmd](https://user-images.githubusercontent.com/36902797/197664422-5cd0e05e-4b72-4ae2-9689-e05598be9d58.jpg)

Can move all terminals between monitors (different resolutions) - no issues

After resizing the calculator...
All work, but...
Windows Terminal (powershell) doesn't resize quite right, but provides a scrollbar if resize smaller. (see image)
Windows Terminal (command) - works best.  No noticed issues.
Standard command prompt has resize artifacts (see image)
![calc_cmd_after_resize](https://user-images.githubusercontent.com/36902797/197664459-7b1928a3-9de5-47f1-9cfb-da0a5768ef24.jpg)

Powershell Scroll bar after resize:
![PS_scrollbar](https://user-images.githubusercontent.com/36902797/197664468-58ae4448-902e-4c52-a5c0-865b437b04e0.jpg)

**Comment by willmcgugan** [comment]
Windows compatibility is getting better and we are more regularly testing on Windows now.

I have a feeling Windows 10 is more glitchy than Windows 11, but there likely isn't much we can do about that.

Feel free to open individual issues regarding Windows compatibility.
