### ISSUE TITLE
Initial focus

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#878]
Maybe we already have this somewhere, but I can't find it.

When you launch a Textual app or push a Screen, it'd be nice to have a widget focused by default. For example, when you run the dictionary example, you need to press `tab` to focus the text input.

Perhaps App/Screen can grow a class var which points to the ID of the widget to be focused, or we could make `.focus()` work inside `compose`.

**Comment by willmcgugan** [comment]
The `focus()` method should work in `compose` / `on_mount` now. Would that be enough?

**Comment by darrenburns** [comment]
Yep, this issue is no longer relevant
