### ISSUE TITLE
Look at the idea of adding an API for reverse-lookup of key bindings

### ISSUE THREAD

**Issue by davep** [Textualize/textual#884]
There may be times where a developer, knowing an action, wants to get the currently-known key bindings (if any exist); an example of wanting to do such a thing could be if they were going to provide the user of their application with a full help screen.

Because of the nature of actions, which can have parameters, it'll likely be necessary to have the developer provide an action ID -- by default this could be a slugged version of the action itself.

**Comment by willmcgugan** [comment]
Closing for now. Will wait for a request for this functionality.
