### ISSUE TITLE
Can't disable the default highlighter

### ISSUE THREAD

**Issue by ikapelyukhin** [Textualize/textual#909]
Hello,

I'm trying to disable the default highlighter which is highlighting numbers. I'm trying to pass an instance of `Console(highlight=False)` to the application, however:

1. `App.run` method seems to accept the console option, but doesn't seem to do anything to do with it (i.e., an instance of `Console()` created with default options is being used regardless of the `console=` value):
    https://github.com/Textualize/textual/blob/c9261f9e620cdda5484acad8680b49b496e067e3/src/textual/app.py#L186-L206
    As the result, the application ends up with an instance of the default `Console` class.
2. Even if `console` property is set on the instance of `App` class, it seems it's being overwritten with a new `Console` instance every time `process_message` is called:
    https://github.com/Textualize/textual/blob/eec8398fc5577b5f28c89a8b5a8879be0502b139/src/textual/app.py#L305

I suspect this is a bug :thinking:

If that is not so, please let me know what would the proper way of disabling the default highlighter be :slightly_smiling_face: 

Thanks, Ivan.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
