### ISSUE TITLE
[Documentation] Supported OS?

### ISSUE THREAD

**Issue by rubyFeedback** [Textualize/textual#919]
Could the readme specify which OS are supported? Linux? Windows?

I'd like to know beforehand if possible due to the current hype textual generated (well at the least on reddit).

My main OS is linux, and although I use ruby, I also use python. I'd love to try it but ... on windows. (On
Linux I am fine with KDE konsole as-is, and RGB colourized emoji/unicode output. It's not the same as
what textual does, but I keep things simple on Linux)

**Comment by davep** [comment]
The current README says:

> Textual currently runs on MacOS / Linux / Windows.

**Comment by erdurano** [comment]
For Windows: In the main branch examples works as-is in Terminal app in both powershell and command prompt.

**Comment by darrenburns** [comment]
Closing as the README does specify the supported OS
