### ISSUE TITLE
Don't use bell in examples so much

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#955]

**Comment by davep** [comment]
Example and documentation code and documents where `App.bell` is currently used and which should be allowed or removed:

- [ ] `docs/examples/guide/actions/actions01.py`
- [ ] `docs/examples/guide/actions/actions02.py`
- [ ] `docs/examples/guide/actions/actions03.py`
- [ ] `docs/examples/guide/actions/actions04.py`
- [ ] `docs/examples/guide/actions/actions05.py`
- [ ] `docs/examples/guide/input/key01.py`
- [ ] `docs/examples/guide/input/key02.py`
- [ ] `docs/examples/guide/reactivity/computed01.py`
- [ ] `docs/examples/styles/links.py`
- [ ] `docs/examples/tutorial/intro02.py`
- [ ] `docs/examples/widgets/button.py`
- [ ] `docs/guide/actions.md`
- [ ] `docs/guide/events.md`
- [ ] `docs/guide/input.md`
- [ ] `docs/guide/widgets.md`
- [ ] `docs/widgets/button.md`
- [ ] `examples/calculator.py`
- [ ] `sandbox/darren/basic.py`
- [ ] `sandbox/darren/buttons.py`
- [ ] `sandbox/will/add_remove.py`
- [ ] `sandbox/will/basic.py`
- [ ] `sandbox/will/bindings.py`
- [ ] `sandbox/will/calculator.py`
- [ ] `sandbox/will/footer.py`
- [ ] `sandbox/will/spacing.py`
- [ ] `src/textual/_doc.py`
- [ ] `src/textual/_event_broker.py`
- [ ] `src/textual/app.py`
- [ ] `src/textual/cli/previews/borders.py`
