### ISSUE TITLE
Look into creating Textual-provided CSS utility classes

### ISSUE THREAD

**Issue by davep** [Textualize/textual#966]
Textual currently has a whole set of CSS "variables" that provide themed colours, and these are handy when writing stylesheets. However, to make use of these the user would need to write their own CSS rules. While this is normally useful, there is an argument in favour of providing a full set of CSS utility classes, which make use of these CSS variables, so a user of Textual can create items in the DOM that are styled using just classes alone.

By way of example, consider Bootstrap and its classes such as `text-primary`, `text-secondary`, `text-danger`, `btn-primary`, `btn-secondary`, and so on.

**Comment by willmcgugan** [comment]
I'm ambivalent about this one. It makes it a little to explicit and no longer semantic. Going to sit on this for a while until we start building larger apps.

**Comment by davep** [comment]
I also feel it's less necessary for us to do this now given that we've already seen one "third party" project spring up to provide this as a Textual-supporting library, and I imagine more may come.

**Comment by davep** [comment]
This feels less and less necessary now so closing.
