### ISSUE TITLE
TreeNode is not "exported"

### ISSUE THREAD

**Issue by Midnighter** [Textualize/textual#992]
To be added by @willmcgugan

I'm adapting the `DirectoryTree` class for my own purposes and I noticed that I needed the `TreeNode` class to provide the right type hints. This class is currently considered "private" rather than public to `textual.widgets`. I don't see why it shouldn't be made public for purposes of subclassing `TreeControl`.

Thank you for considering it.

**Comment by davep** [comment]
Now that [`Tree` has had a complete rewrite](https://textual.textualize.io/blog/2022/12/11/version-060/#textual-060-adds-a-treemendous-new-widget), `TreeNode` is "public" and can be imported from `textual.widgets`.
