### ISSUE TITLE
Invalid default screenshot file name in Windows.

### ISSUE THREAD

**Issue by kmonson** [Textualize/textual#993]
Default screenshot filename format in App.save_screenshot (specifically time_format) results in colons in the default file name. This is invalid in Windows. 

`OSError: [Errno 22] Invalid argument: './textual demo 2022-10-23 16:00:23 341765.svg'`

An additional replace call here is probably needed: https://github.com/Textualize/textual/blob/main/src/textual/app.py#L538

**Comment by davep** [comment]
Good catch, thanks.
