### ISSUE TITLE
TailwindCSS support experimental

### ISSUE THREAD

**Issue by ahmetkca** [Textualize/textual#996]
I don't know if it make sense but can we somehow support tailwindcss for styling. I just thought if we can reference to a css file then why not use tailwindcss. I could also try to experiment how to achieve this. 

To be added by @willmcgugan

**Comment by willmcgugan** [comment]
I'm afraid that Textual CSS is different enough from the browser that it is unlikely to work.

But there could be tailwind-like CSS frameworks for Textual.

**Comment by willmcgugan** [comment]
I spoke too soon!

https://github.com/koaning/tuilwindcss/

**Comment by willmcgugan** [comment]
It's not *exactly* tailwindcss, but it works in a very similar way.
